### ISSUE TITLE
pgfparse of deg function in a TikZ picture

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1002]
TikZ and PGF provide the `deg` function, which converts radians into degrees.  It is equivalent to having a suffix of `r`.  It appears that we have defined `deg` in an axis environment, but not just within a TikZ picture.

```TeX
\documentclass{article}

\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.13}

\begin{document}

\begin{tikzpicture}
\draw(0,1)--(5,5r/60); % works
\end{tikzpicture}

\begin{tikzpicture}
\begin{axis}[xmax=6,ymax=6]
\addplot(0,1)--(5,{deg(5/60)}); % works
\end{axis}
\end{tikzpicture}

\begin{tikzpicture}
\draw(0,1)--(5,{deg(5/60)}); % doesn't work
\end{tikzpicture}

\end{document}

```

This causes `Error:pgfparse:pgfparse Parse of 'deg(5/60)' failed`

**Comment by teepeemm** [comment]
I've also uncovered a possibly similar issue with exponents:

`\draw(4,0)--(5,{(1)^2});`

**Comment by dginev** [comment]
Just a quick note that I can reproduce - thanks for the reports!

**Comment by brucemiller** [comment]
Yes, some more syntax that got overlooked. Should work now. Thanks for the report!
