### ISSUE TITLE
Disappearing parent with context toc

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1003]
I'm compiling the following tex file via `latexml` and then `latexmlpost --split`.

```TeX
\documentclass{book}

\usepackage{latexml}
\lxDocumentID{DocID}

\begin{lxNavbar}
\lxContextTOC
\end{lxNavbar}

\begin{document}

\chapter{Title One}

\section{Title One One}

\chapter{Title Two}

\end{document}
```
The file DocID.Ch1.html has the local context toc that I would expect:

> 1 Title One
> ` ` ` ` ` ` ` `1.1 Title One One
> 2 Title Two
> 

The file DocID.Ch1.S1.html, on the other hand, has a different local context toc:

> 1.1 Title One One
> 2 Title Two
> 

Here, the entry for Chapter 1 has disappeared, and the entry for the section is no longer indented.  Shouldn't I have the same local toc, only with a different entry no longer hyperlinked?  Or am I overlooking something?

**Comment by brucemiller** [comment]
Indeed, a leftover from previous changes. Should work now. Thanks for the report!
