### ISSUE TITLE
Incorrect newline command in parbox and minipage

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1004]
Normally, LaTeXML discards the optional vertical skip argument to the newline command `\\`.  I suppose this makes sense for separating style and content.  I've found, however, that in parbox and minipage, `\\` no longer takes an optional argument and prematurely ends the container.  This means that the optional `[Dimension]` becomes output in the document.

I think this is because `LaTeX.pool.ltxml` has `Let('\\\\', '\par');` in its definitions for `parbox` and `minipage`, and `\par` doesn't accept an optional argument.  I can't decipher how LaTeX does the redefinitions that it does.

Here's a minimal example.

```TeX
\documentclass{article}

\begin{document}

Line 1\\[1in]
Line 2 ok

\begin{minipage}{100pt}
Line 3\\[1in]
Line 4 not ok. It has the dimension, and doesn't follow the defined width.
\end{minipage}

\parbox{100pt}{Line 5\\[1in]
Line 6 not ok. It has the dimension, and doesn't follow the defined width.}

\end{document}
```

resulting in the xml:

```xml
  <para xml:id="p1">
    <p>Line 1<break/>
Line 2 ok</p>
  </para>
  <para xml:id="p2">
    <p class="ltx_minipage" vattach="middle" width="100.0pt">Line 3</p>
  </para>
  <para xml:id="p3">
    <p>[1in]
Line 4 not ok. It has the dimension, and doesn’t follow the defined width.</p>
  </para>
  <para xml:id="p4">
    <p class="ltx_parbox" vattach="middle" width="100.0pt">Line 5</p>
  </para>
  <para xml:id="p5">
    <p>[1in]
Line 6 not ok. It has the dimension, and doesn’t follow the defined width.</p>
  </para>
```

Specifically, the latter two `[1in]` have appeared in the xml, and show up in the resulting html.  The `\\` has also caused the next paragraph to no longer be part of the fixed width `p` tag.

**Comment by brucemiller** [comment]
Slightly related to a couple of previous issues here, but mainly the wrong local redefinition of `\\`. Should work better now. Thanks for the report!
