### ISSUE TITLE
(How) can I use rawhtml?

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1007]
I'm trying to have an iframe in my html.  From reading https://dlmf.nist.gov/LaTeXML/manual/schema/schema.module.LaTeXML-misc.html#schema.element.rawhtml, I assumed that I could put any valid xml inside a rawhtml tag.  My first attempt was

```perl
DefConstructor('\myiframeA',
	       '<ltx:rawhtml>'.
	       '<iframe src="no_attributes_A.html" class="self closes">'.
	       '</iframe>'.
	       '</ltx:rawhtml>');
```
This leads to the xml: `<rawhtml><iframe/></rawhtml>`.  The iframe becomes a self closing tag, and loses its attributes.  My next attempt was to try to trick latexml into keeping the closing tag by including content:

```perl
DefConstructor('\myiframeB',
	       '<ltx:rawhtml>'.
	       '<iframe src="no_attributes_B.html">'.
	       'PCDATA isn t allowed B'.
	       '</iframe>'.
	       '</ltx:rawhtml>');
```
I still lose the attributes.  This also gives the error `#PCDATA isn't allowed in <iframe>` (even though the allowed content of an iframe tag is the html for non-iframe browsers to display), and the xml `<rawhtml><iframe>PCDATA isn t allowed B</iframe></rawhtml>` becomes the html `<div id="p2" class="ltx_para">PCDATA isn t allowed B</div>`.  In fact this error persists even with something other than iframes:

```perl
DefConstructor('\myiframeC',
	       '<ltx:rawhtml>'.
	       '<h1 class="no_attributes_C not_h1_C">'.
	       'PCDATA isn t allowed C'.
	       '</h1>'.
	       '</ltx:rawhtml>');
```
still loses attributes, claims that `#PCDATA isn't allowed in <h1>`, and results in the identical html. 
(I also discovered that using `"PCDATA isn't allowed C"` causes a different error because of the apostrophe.)  I can get my iframe to appear by using rawliteral:

```perl
DefConstructor('\myiframeD',
	       '<ltx:rawliteral open="iframe" close="">'.
	       ' src="attributes.html"'. # must have leading space
	       ' class="Odd number of elements in hash assignment"'.
	       '</ltx:rawliteral>'.
	       '<ltx:rawliteral open="/iframe" close="">'.
	       '</ltx:rawliteral>');
```
But this feels like I'm abusing rawliteral.  (It also causes a warning about an odd number of elements in a hash assignment.)

Is there a way that I can get rawhtml to work?  Am I completely misusing it?  How should rawhtml be used?

**Comment by brucemiller** [comment]
Have you tried putting the html in the xhtml namespace?
Such as: <ltx:rawhtml><xhtml:iframe ...

**Comment by teepeemm** [comment]
I hadn't tried using the xhtml namespace, but that results in

```
Warning:malformed:http://www.w3.org/1999/xhtml No prefix has been registered for namespace 'http://www.w3.org/1999/xhtml' (in document)
	at /Users/tprescott/Documents/programming/latexml/rawhtml/minimal.tex; line 7 col 11
	Using 'namespace1' instead
	In Core::Document[@0x7fde372dd428] at /Users/tprescott/Documents/programming/latexml/rawhtml/minimal.tex; line 7 col 11
	 <= Core::Definition::Constructor[\myifra... <= Whatsit[\myiframe] <= Core::Document[@0x7fde372dd428] <= ...
```
The same errors still happen, but now the tags are `<namespace1:iframe/>` etc.  I find this all strange.  The namespace is registered, since latexml realizes the proper url for the namespace. 
 (This also happens if I start the ltx.html with  
`RegisterNamespace(xhtml => "http://www.w3.org/1999/xhtml");`,  
but since `TeX.pool.ltxml` does that already, I don't think that should affect anything.)

**Comment by brucemiller** [comment]
Seems that this was a bit of unfinished code; and also the simplification of the relaxng wasn't dealing well with things like `xhtml:*`.  So, anyway, I've fixed up the schema processing and now rawhtml should accept any markup in the `xhtml` namespace.  I thing your example should work out fine now. Thanks for the report!
