### ISSUE TITLE
Portions of lstlisting truncated

### ISSUE THREAD

**Issue by MikePetullo** [brucemiller/LaTeXML#1010]
I have a LaTeX document which makes use of the lstlisting environment, and I am processing the document using latexml. I have found in some cases that latexml truncates the contents of a lstlisting environment. This appears in the HTML I subsequently produce using latexmlpost.

For example,

```
\begin{lstlisting}
config dropbear
        option PasswordAuth 'off'
        option RootPasswordAuth 'off'
        option Port         '22'
\end{lstlisting}
```

becomes

```
config dropbear
        option PasswordAuth 'off'
        option RootPasswordAuth 'off'
        option Port         '
```

Note the absence of "22'".

**Comment by MikePetullo** [comment]
[index.txt](https://github.com/brucemiller/LaTeXML/files/2147135/index.txt)

**Comment by brucemiller** [comment]
That happens with 0.8.2? Have you tried the development version?  It's working OK for me here.

**Comment by MikePetullo** [comment]
Yes, this issue is present in 0.8.2. I just tried master from GitHub, and it does indeed seem to fix the problem.

I am now the LaTeXML packager for Fedora. Do you know when we might see another release?

**Comment by dginev** [comment]
> Do you know when we might see another release?

Excellent question! In all seriousness, we have ~1 week of work to merge and test the last features we wanted in the 0.8.3 release, so I think we are unofficially aiming for "end of July". Bruce has the final say of course, but *definitely* by end of summer.

**Comment by MikePetullo** [comment]
This is fixed in Git master as indicated above. Looking forward to the next release.

**Comment by dginev** [comment]
Thanks for confirming!

**Comment by brucemiller** [comment]
Before this got closed, I wanted to give a huge thanks for looking into creating a redhat rpm! Welcome, and if there's anything we can do to help, let us know.
