### ISSUE TITLE
Blank lines are not preserved in {alltt} environment

### ISSUE THREAD

**Issue by siegfriedzoetzsche** [brucemiller/LaTeXML#1017]
The `{alltt}` environment should preserve blank lines but `alltt.tex`:

```tex
    \documentclass{article}
    \usepackage{alltt}
    \begin{document}
    \begin{alltt}
    #!/usr/bin/env bash
    
    echo 'Hello'
    \end{alltt}
    \end{document}
```

converted with

```bash
    latexml --strict --destination alltt.xml alltt.tex
```

results in

```xml
    [...]
        <verbatim font="typewriter">
    #!/usr/bin/env bash
    echo ’Hello’
    </verbatim>
    [...]
```

**Comment by dginev** [comment]
Thank you for the report! There is already a test file for alltt that we should add this test into to ensure parity.

**Comment by brucemiller** [comment]
Hmm, thought that was handed, but needs to be a bit more clever.  Should work now. Thanks for the report!
