### ISSUE TITLE
False error on underscore in included file names

### ISSUE THREAD

**Issue by altavir** [brucemiller/LaTeXML#1019]
Latexml reports errors like this:
```
Error:unexpected:_ Script _ can only appear in math mode
        at ./Chapter_1/lab_3_1_2.tex; line 60 col 27
        In _ from TeX.pool.ltxml line 3375
         <= Core::Stomach[@0x3d64840] <= { <= Core::Stomach[@0x3d64840] <= ...
```
when including file names that contain underscores (with `\input` command). It works fine after the error, but if there are many imports, it could fail by exceeding error limit.

**Comment by brucemiller** [comment]
This is working fine for me in the development version (and even in 0.8.2).  Do you have a minimal sample file that demonstrates the problem?

**Comment by altavir** [comment]
Can't reproduce it in a simple example. I will try to find the problem myself and report back.

**Comment by altavir** [comment]
OK, I found the problem. The message was confusing me. The error appeared not in the place where file was attached, but inside the file itself. I have a custom command that attaches ancient TexCad drawings and it contained `_` in file name. Pdflatex and lualatex work fin with it, but latexml throws a error.

The issue still stands for custom commands with parameters with underscores, but it is quite rare case, I believe.
