### ISSUE TITLE
[question] Attach a style class to environment

### ISSUE THREAD

**Issue by altavir** [brucemiller/LaTeXML#1021]
Probably there is an easy answer to this question, but I have not found it.
I've got an environment like this:
```latex
	\newenvironment{lab:warning}{
		\begin{tabular}{|p{0.9\textwidth}|}
		\hline\\
		\hfil\textbf{Внимание!}\par
		\begin{center}
	}{
		\end{center}\\ \hline
		\end{tabular}%
	}
```

And in my html I want it to be just like:
```
<div class="lab_warning">
  ...
</div>
```
Then I can control everything else by custom CSS.
I can use conditional compilation flags from `xmlatex.sty` (by the way, had to build package from source since it is not included in prebuilt versions), but I do not understand how to do it from within latex.

I do understand how it could be done by custom style definition, but creating definition for my style requires tremendous amount of work and I do not want to do it for single command (maybe there is a way to define single command?).

**Comment by dginev** [comment]
Hi @altavir , indeed there is a simple way to define a single command for your package, while using the raw TeX interpretation for the rest. If your package is named "lab", you would make a file `lab.sty.ltxml` in the root directory of your manuscript (you can also just put it anywhere and add a `--path` option to detect it), and add to it:

```perl
package LaTeXML::Package::Pool;
use strict;
use warnings;
use LaTeXML::Package;

InputDefinitions('lab',type=>'sty',noltxml=>1); 

# Here you define your own custom definitions, such as:
DefEnvironment('{lab:warning}',
  '<ltx:rawhtml><div class="lab_warning">#body</div></ltx:rawhtml>');

1;
```

Note the special `<rawhtml>` tag which is needed to directly encode raw HTML directly in a binding - as the main binding target is LaTeXML's custom XML target. I believe you could also emulate this by using the logical paragraph of latexml as:

```perl
DefEnvironment('{lab:warning}',
  '<ltx:para> class="lab_warning">#body</ltx:para>');
```

**Comment by altavir** [comment]
Super. Thanks a lot! It works, and I probably could add custom definitions for other environments without rewriting the whole style. The second approach is probably better, since it allows to preserve the universality of XML representation, but it is good to know, that I can introduce a direct hack to HTML if needed.

I could not find `InputDefinitions` in the documentation. Such a useful function deserves to be placed there. Also, as I already told, it would be good to update binary versions for Debian and other distributions. I tried all available ways to convert latex to html (I need to do it for a laboratory practice book for our university) and so far `latexml` is the best way. Perl requirement for windows is hard, but i managed to do everything with Windows Subsystem for Linux, which runs on Ubuntu. So Debian package covers it as well.

**Comment by altavir** [comment]
For people completely unfamiliar with Perl (like me) it is even harder. 

Using WSL is in fact simpler than managing Perl on Windows. There was a problem with texlive, which is very inconvenient after Miktex, but nothing I could not solve in the end.

**Comment by brucemiller** [comment]
hmm, I can't check rightnow, but I thought that environments already put a
class attribute on the result. Or maybe not from `\newenvironment`?

**Comment by altavir** [comment]
Just checked, It does not. `newenvironment` is just transformed to its contents.
