### ISSUE TITLE
How to provide alternative path to svg?

### ISSUE THREAD

**Issue by altavir** [brucemiller/LaTeXML#1032]
I have svg images which are converted to tex/pdf format by inkscape and included in latex version via `input` command. Obviously, when I am converting latex to xml/html, I want to use this svg file directly without converting it to pdf first.

I made a command called `svg` which loads svg converted to tex/pdf from specific directory and now I need to somehow redefine it in `.sty.ltxml` to load svg-s with the same name instead. It should be doable with preprocessor as is, but it is very hard to non-perl people to figure out how. Could you write an example of such code? It should be quite common problem.

**Comment by dginev** [comment]
So you want `\input` to check if an SVG file of the same name exists, and prioritize it over the TeX file? 

Here is one example how to achieve that:

In `mysvg.sty.ltxml` I added:

```perl
package LaTeXML::Package::Pool;
use strict;
use LaTeXML::Package;

#**********************************************************************

RequirePackage('graphicx');

Let('\saved@input','\input');
DefMacro('\input {}', sub {
  my ($gullet, $arg) = @_;
  my $svg_file = ToString($arg);
  $svg_file =~ s/\.tex$//;
  $svg_file .= ".svg";
  if (-e $svg_file) {
    return Invocation(T_CS('\includegraphics'), T_OTHER($svg_file)); }
  else {
    return Invocation(T_CS('\saved@input'), $arg); }
});

#**********************************************************************

1;
```

then I created two files `foo.tex` and `foo.svg` and the following main test file:

```
\documentclass{article}
  \usepackage{mysvg}
\begin{document}
\input{foo}
\end{document}
```

Then running `latexmlc test.tex --destination=test.html` gets the SVG incldued, while running pdflatex uses the `foo.tex` instead.

**Comment by altavir** [comment]
This one juts turned off all imports. What I meant is actually simpler. I define additional command:
```latex
\newcommand{\svg}[2]{
  \def\svgwidth{#1}
  \input {\detokenize{Images/#2.pdf_tex}}	
}
```
And then just redefine it in `ltxml` to generate xml responsible to image loading directly, avoiding `input`. 
Could you explain which part of this code actually loads svg? Maybe I can figure it out myself. As far as I can understand this line: `Invocation(T_CS('\includegraphics'), T_OTHER($svg_file));` should do the trick, but what does it do? Latex `includegraphics` does not work on svg.

**Comment by dginev** [comment]
> Latex includegraphics does not work on svg.

Right, but this is not latex, it is latexml-only. And latexml's includegraphics has no problem at all with including SVG images in the document. So it should work for your use case.

**Comment by altavir** [comment]
I think that we figured this out. The problem is that `pdflatex` does not allow svg as image and `html` does not render pdf as image. So in general, if you want to have vector graphics for both formats, you will need to provide two image files, one in pdf or tex encapsulating pdf for latex and the second one in svg for html.

My current solution looks like this:
```
\newcommand{\pic}[2]{
  \def\svgwidth{#1}
  \input {\detokenize{Images/#2.pdf_tex}}	
}
```
in `sty` (tex wrapper is generated by inkscape) and
```
DefMacro('\pic{}{}','\includegraphics[width=#1]{#2.svg}');
``` 
in `sty.ltxml`

**Comment by brucemiller** [comment]
I'm not sure that @altavir has caught on that `\includegraphics` does *not* need the extension, and it's generally best not to use it --- it will find the "best" extension for the given processor.  At least to me, creating foo.svg and foo.pdf and then simply using `\includegraphics{foo}` is much simpler;  But if you've got something that works the way you want, that's good.
