### ISSUE TITLE
"\uppercase{äöü}" results in "äöü" instead of "ÄÖÜ"

### ISSUE THREAD

**Issue by siegfriedzoetzsche** [brucemiller/LaTeXML#1035]
It seems like `lookupUCcode()` in Core/State.pm does not return a code for "ä", "ö" or "ü" and so `ucToken()` in Package/TeX.pool.ltxml just maps "ä", "ö" and "ü" to "ä", "ö" and "ü" respectively.

#### `example.tex`
```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\begin{document}
\uppercase{(äöü)(ÄÖÜ)}
\end{document}
```

#### output of `latexml --strict --nocomments --destination latexml.xml example.tex`
```xml
[...]
<p>(äöü)(ÄÖÜ)</p>
[...]
```

**Comment by dginev** [comment]
This is simply missing from the `utf8.def.ltxml` binding. Looking into it.
