### ISSUE TITLE
\lx@ignorehardspaces question

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1038]
Hi!

We have a definition in TeX.pool.ltxml:
```perl
DefPrimitiveI('\lx@ignorehardspaces', undef, sub {
    my ($stomach) = @_;
    my $gullet = $stomach->getGullet;
    my ($token, @boxes);
    while (($token = $gullet->readXToken) && (@boxes = $stomach->invokeToken($token))) {
      while (@boxes && $boxes[0]->getProperty('isSpace')) {
        pop(@boxes); }
      last if @boxes; }
    return @boxes; });
```

which (among assumed other uses) is used internally when typesetting the typerefnum tag:
```xml
<tag role="typerefnum">§1</tag>
```

My question is about the logic of the innermost loop in the definition. It seems to:
 - loop while
  - the next expandable token's invocation has boxes and
  - the leftmost box is marked as `isSpace`
  - in which case remove/pop the _rightmost/last_ box from the array of boxes

If I am not hopelessly confused here, doesn't this effectively remove *all* boxes from `@boxes` when the first one is marked with `isSpace`? The check will continue testing the first box, while the boxes at the end are removed one by one.

Just wondering if this is an oversight bug for `shift(@boxes)`, or I am misunderstanding the intent.

**Comment by brucemiller** [comment]
Can't think of a better explanation! Fixed, Thanks! :>

**Comment by dginev** [comment]
Hey, don't say my secret side-experiments didn't have *any* benefit :joy: Spotted this while adapting it...
