### ISSUE TITLE
TeX macro \bordermatrix omits brackets

### ISSUE THREAD

**Issue by evoludolab** [brucemiller/LaTeXML#1041]
The code
```
\[
\bordermatrix{
& C & D \cr
C & a & b \cr
D & c & d \cr} .
\]
```
renders as 
![image](https://user-images.githubusercontent.com/21139511/44178530-9b487600-a0a7-11e8-823b-c48e3668fadc.png)
using `pdflatex` but when converted to (X)HTML with `LaTeXML` the displays is missing the brackets:
![image](https://user-images.githubusercontent.com/21139511/44178607-f8442c00-a0a7-11e8-9b9a-dcd6a6f23509.png)

**Comment by brucemiller** [comment]
Hmm,yeah. I'd left that case dangling a long time ago.  I haven't quite figured out how to get that to work cleanly in MathML, let alone a "semantic" internal representation of it.  I'm looking into it, though.

**Comment by evoludolab** [comment]
Turns out this is an open issue in MathJax too... \bordermatrix and MathML resulted in some discussion on the web but nothing substantial surfaced so far. Will post here if I come across some leads. Thanks.

**Comment by brucemiller** [comment]
I don't know what the semantics of such a thing should be, but this patch (64016e810c4a005dc712b859a8141f4a34f93f01) ought to get the presentation right (at least on Firefox, which deals with row/column spans correctly).  Thanks for the report!
