### ISSUE TITLE
order of subplus

### ISSUE THREAD

**Issue by physikerwelt** [brucemiller/LaTeXML#1045]
On the [LaTeXML web-editor](https://latexml.mathweb.org/editor) I see
![screenshot from 2018-08-26 16-14-40](https://user-images.githubusercontent.com/2777736/44632585-64961980-a94b-11e8-91a6-b2e7dee5eaf9.png)
However, if I compile
```latex
\documentclass{article}
\usepackage{amsmath}
\newcommand{\subplus}{\mathbin{\genfrac{}{}{0pt}{}{}{+}}}
\begin{document}
\[
1+\frac12\subplus\dots
\]
\end{document}
```
with pdflatex I get the output in the [expected order](https://github.com/brucemiller/LaTeXML/files/2321880/subplus.pdf).
@Howardcohl can you think of another way to define `\subplus`, so that the + symbols appear in the intended order?

**Comment by brucemiller** [comment]
Hmm, binop. I guess the MathML conversion has to support it, w/o knowing whether it's add or mul.  Fixed now!

BTW: I hope this isn't for continued fractions; it's pretty poor layout/semantics. See amsmath's `\cfrac`, or my variation of it.
