### ISSUE TITLE
longtable tables don't get LOT entries

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1054]
I have just started testing of my document collection with LaTeXML 0.8.3. Thanks for the fixes ofr bugs reported by me. Unfortunately I have just discovered that tables marked up in LaTeX as `longtable`s no longer get entries in List of Tables.
I have used the conversion route: 

- LaTeX  to XML with `latexml`: `latexml --dest=longtable-min.xml longtable-min.tex` 
- followed by XML -> HTML5 with `latexmlpost`: `latexmlpost --dest=test-longtable-min/index.html --urlstyle=server  --format=html5 longtable-min.xml`.

I can see that in XML file `table` tag generated for `longtable` does not have `inlist` attribute, which is present (`inlist="lot"`) in `table` tags of ordinary tables (i.e. marked up in LaTeX as `table` environments).
I attach LaTeX file I used for this test and generated XML and HTML files.

[longtable-min.zip](https://github.com/brucemiller/LaTeXML/files/2356709/longtable-min.zip)

**Comment by brucemiller** [comment]
Good catch! And alas there were several other tables/figures that hadn't gotten the updated inlist attribute. Thanks for the clear report & test case; should be good now!

**Comment by goska** [comment]
Thanks!
