### ISSUE TITLE
\emph regression?

### ISSUE THREAD

**Issue by molke-productions** [brucemiller/LaTeXML#1056]
Recently, I started upgrading an existing converter from LaTeXML 0.8.2 to 0.8.3. There seems to be a regression with the new way of handling `\emph` ( #874 ).
Input:

    \documentclass{article}
    \begin{document}
    \emph{Emphasized} text.
    
    \emph{\emph{Emphasized} text in emphasized text} not emphasized.
    \end{document}
Output of `latexml --destination=test.xml test.tex`:
   
    <para xml:id="p1">
      <p><text class="ltx_emph" font="italic">Emphasized</text> text.</p>
    </para>
    <para xml:id="p2">
      <p class="ltx_emph">Emphasized<text class="ltx_emph" font="italic"> text in emphasized text</text> not emphasized.</p>
    </para>

Since I am using (customized) JATS output, I would actually prefer `<ltx:emph>`. This easily maps to `<italic>` (although the name might be misleading) which has `@toggle` (default value `yes`). Can the old behavior be restored by using the previous constructor of `\emph` (from the manual)?

The JATS XSL apparently still matches `ltx:emph` by the way.

**Comment by brucemiller** [comment]
I made the change because I was encountering peculiar markup that had the ```\emph``` containing arbitrary higher level stuff like equations or tables. That was messing up the schema when using ```ltx:emph```.  It was cleaner to leverage the font tracking mechanism to deal with emphasis as well, but the obvious end result was simply ```ltx:text``` with an appropriate class, and I'd kinda hate to special case it there.

OTOH, maybe it's not too hard to customize the JATS stylesheet to recognize the font, and generate italic instead?  I can help...

**Comment by molke-productions** [comment]
Thank you for the comment. Maybe I misunderstood something. I don’t mind mapping some ``@class`` attribute (preferrably on ``ltx:text``) instead of ``ltx:emph``. Then the second paragraph in the above example should still be something like
```xml
<p><text class="ltx_emph">Emphasized <text class="ltx_emph" font="italic">text in emphasized text</text></text> not emphasized.</p>
```
Otherwise, “not emphasized” ends up being emphasized.

**Comment by brucemiller** [comment]
Doh! Yeah, definitely a bug there.  Figuring a way around it sent me back to the drawing board and I think gets the right behaviour while still using ```ltx:emph```.  It usually wrap the appropriate number of ```ltx:emph```'s around, as well.  Not sure if it's a kludge or a brilliant conceptual framework.  Maybe a bit of both. (a44cad30)
