### ISSUE TITLE
\noindent only works on first paragraph

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#1061]
When `\noindent` is applied to two paragraphs in a row, it only seems to work on the first paragraph.

### Steps to reproduce

[Here is the full source of an article that I found the issue in.](https://github.com/arxiv-vanity/engrafo/blob/6a4dfe408c4f71dc5b10746d3aae040b041a4a13/tests/integration/papers/1707.08043/main.tex) The code in question:

```
\noindent Mathematical Subject Classification (2010): 03C20, 03C98, 13B99, 11D72

\smallskip

\noindent Keywords: Lefschetz's principle, hight, complexity, lifting, prime characteristic, radical 
```

### Expected behaviour

Both paragraphs would have the class `ltx_noindent`.

### Actual behaviour

HTML:

<img width="706" alt="screenshot 2018-09-22 16 59 01" src="https://user-images.githubusercontent.com/40906/45917041-d9943a80-be88-11e8-8342-2879b276ce69.png">

What it looks like:

<img width="720" alt="screenshot 2018-09-22 17 01 10" src="https://user-images.githubusercontent.com/40906/45917055-21b35d00-be89-11e8-96ad-9d6f0f5e026c.png">

**Comment by brucemiller** [comment]
The interesting thing is that it's not that it's the 2nd paragraph, but rather how it ends! It's missing a `\par` (or blank line); LaTeX's has the `\par` built into `\section` (& friends), so now LaTeXML does too!  Thanks for the report!

**Comment by bfirsh** [comment]
Nice, thanks!
