### ISSUE TITLE
Issues with baseurl and hyperbaseurl

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1062]
There appear to be issues with LaTeXML 0.8.3 handling of `baseurl` and `hyperbaseurl`. Attempts at setting base URL (which we use to link to file downloads from PDF; I used `baseurl` method with LaTeXML 0.8.2) no longer work. In the following tests I used `hyperlinks.tex` in which I, in turn, specified no base URL (for comparison), used `\hypersetup{baseurl}` in the preamble to set `baseurl` property and used `\hyperbaseurl` in the preamble to set base URL. The file contains one hyperlink to external website (`(https://google.co.uk`) coded using absolute URL and one hyperlink to an image file using relative URL. Both hyperlinks are coded using `\href`.
I have used the conversion route:

- LaTeX  to XML with `latexml`:

-  no baseurl and hyperbaseurl (both commented out) – for comparison only: `latexml --dest=hyperlinks_none.xml hyperlinks.tex`
- `baseurl` set:` latexml --dest=hyperlinks_baseurl.xml hyperlinks.tex`
- `hyperbaseurl` set: `latexml --dest=hyperlinks_hyperbaseurl.xml hyperlinks.tex`

- followed by XML -> HTML5 with `latexmlpost`: 

- `latexmlpost --dest=hyper/hyperlinks_none.html --urlstyle=server  --navigationtoc=context --css=LaTeXML-navbar-left.css --format=html5 hyperlinks_none.xml`
- `latexmlpost --dest=hyper/hyperlinks_baseurl.html --urlstyle=server  --navigationtoc=context --css=LaTeXML-navbar-left.css --format=html5 hyperlinks_baseurl.xml`
- `latexmlpost --dest=hyper/hyperlinks_hyperbaseurl.html --urlstyle=server  --navigationtoc=context --css=LaTeXML-navbar-left.css --format=html5 hyperlinks_hyperbaseurl.xml`

In both attempts to set base URL (using` \hyperbaseurl` and `hypersetup`; `https://gea.esac.esa.int` used as the base URL string) LaTeXML prepends strings to both, absolute and relative URLs.
When `\hypersetup{baseurl}` is used LaTeXML prepends its internal reference instead of the actual string specified, e.g. in this case `latexml::Core::List=HASH(0x7fc75fc34ae8)`.
When base URL is set with `\hyperbaseurl` LaTeXML prepends the specified URL . In this case the `href` attribute of the link to Google website became  `https://gea.esac.esa.inthttps://google.co.uk`.

I attach LaTeX file I used for this test and generated XML and HTML files.

[hyperlinks.zip](https://github.com/brucemiller/LaTeXML/files/2437463/hyperlinks.zip)

**Comment by brucemiller** [comment]
So, that worked in 0.8.2? Not sure what we did to break it, but it's more properly fixed now.  Thanks for the report!

**Comment by goska** [comment]
I used `baseurl` with LaTeXML 0.8.2. It sort of worked: LaTeXML did nothing (except for throwing errors for `baseurl` containing underscores, issue #950), so relative URLs to the resources on the same server worked.
