### ISSUE TITLE
Non-Standard Installation Path Bug

### ISSUE THREAD

**Issue by AndreG-P** [brucemiller/LaTeXML#1063]
I tried to install the latest LaTeXML (v.0.8.3) on a server where LaTeXML v.0.8.1 was already installed. I followed the guide on [https://dlmf.nist.gov/LaTeXML/get.html](https://dlmf.nist.gov/LaTeXML/get.html) under "Installing Tarball" and "Building" and used
``` shell
 perl Makefile.PL PREFIX=/my/path/perl TEXMF=/my/path/tex 
```
The installation works fine but when I ask for the version number after the custom installation it responds version 0.8.1 instead of the new installed version 0.8.3.

I checked the generated files under `/my/path/perl/bin/latexml` and in line 16 the path was:
``` perl
use lib "$FindBin::RealBin/../lib";
```
However, this seemed to be the path for the general installation which accidentally called the old installation library of LaTeXML. I changed this line manually to
``` perl
use lib "$FindBin::RealBin/../share/perl/5.20.2";
```
and now it works fine.

**Comment by brucemiller** [comment]
I'm confused about where things actually got installed. If you've given prefix as `/my/path/perl`, then latexml should have been installed in `/my/path/perl/bin` and LaTeXML's perl modules (say `LaTeXML.pm`) should have been installed in `/my/path/perl/lib/LaTeXML.pm`.  But your "fix" implies that it got installed in `/my/path/perl/share/perl/5.20.2/LaTeXML.pm`, but I don't see why that would be the case. There must be something subtle going on.

**Comment by brucemiller** [comment]
Hmm, I run a pretty similar situation on some workstations, and I can't reproduce the problem. Probably need more details.

**Comment by brucemiller** [comment]
Seems not reproducible.
