### ISSUE TITLE
\noalign used in table affects equation numbering

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1065]
I had `\noalign{\smallskip}` used in a table in one of the LaTeX files, which worked OK when converting to HTML with LaTeXML 0.8.2  (`latexml` -> XML, `latexmpost` -> HTML). When the same file is converted with LaTeXML 0.8.3, the counter of the equation following the table does not get incremented, resulting in a `malformed:id Duplicated attribute xml:id` and a duplicated equation number. 
I attach a simple LaTeX and the corresponding XML files.
[math_simple_min.zip](https://github.com/brucemiller/LaTeXML/files/2482497/math_simple_min.zip)

**Comment by brucemiller** [comment]
What a weird & silly bug.  Should be fixed now. Thanks for the report
