### ISSUE TITLE
\pgfmathparse fails with 0.8.3 (worked with 0.8.2)

### ISSUE THREAD

**Issue by Red-Quill** [brucemiller/LaTeXML#1071]
Hi everyone! I have been experimenting with LaTeXML for couple of weeks and it is a great program. I just updated from 0.8.2 to 0.8.3. Following simple pgfmath calculation worked with 0.8.2 but fails now with 0.8.3

mwe.tex:
```
\documentclass{article}

\usepackage{tikz}

\begin{document}
\pgfmathparse{int(5/2)}\edef\MyResult{\pgfmathresult}\MyResult
\end{document}

```

When converted with:
`latexml --inputencoding=utf8 mwe.tex`

It produces an error message:

> Error:pgfparse:pgfparse Parse of 'int(5/2)' failed
> 	at mwe.tex; line 5 col 39 - line 6 col 23
> 	LTX: '0'
> 	Left: int(5/2)
> 	Next token is T_CS[\edef]
> 	In Core::Definition::Expandable[\lx@pgfm... /usr/share/perl5/vendor_perl/LaTeXML/Package/pgfmath.code.tex.ltxml; line 320
> 	 <= Core::Gullet[@0x5555cc071ab0] <= Core::Stomach[@0x5555ce84e5a8] <= ...

**Comment by dginev** [comment]
Thank you for reporting the regression!

**Comment by brucemiller** [comment]
Argh! Stupid typo; worse even, just an inadvertent likebreak introduced within a regexp...

Fixed now! Thanks for the report!!
