### ISSUE TITLE
Document the LaTeXML Daemon at top-level of LaTeXML manual

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#1073]
The LaTeXML manual only talks about `latexml` and `latexmlpost` in Section/Chapter 2 "Using LaTeXML". This should really have a top-level section about the motivation and practicalities of `latexmls` and `latexmlc`. Nothing like this seems to exist at the moment.

**Comment by dginev** [comment]
Counter take to this issue is that while we've talked on numerous occasions that `latexmlc` may become `latexml`-proper, we're not really making any moves in that direction. So it may be best to document `latexmlc` and keep the organization as-is.
