### ISSUE TITLE
Duplicate author institutions in elsarticle.cls

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#1080]
https://arxiv.org/abs/1803.07574 has some latex like this:

```latex
   %% Group authors per affiliation:
    \author{Alina G. Meresescu\fnref{fn1,fn2}}\ead{alina-georgiana.meresescu@u-psud.fr}
    \author{Matthieu Kowalski\fnref{fn2}}
    \author{Fr\'{e}d\'{e}ric Schmidt\fnref{fn1}}
    \author{Fran\c{c}ois Landais\fnref{fn1}}
    
    %\address{Radarweg 29, Amsterdam}
    \fntext[fn1]{GEOPS, Univ. Paris-Sud, CNRS, Universite Paris-Saclay, Rue du Belvedere, Bat. 504-509, 91405 Orsay, France}
    \fntext[fn2]{L2S, Univ. Paris-Sud, Supelec, CNRS, Universite Paris-Saclay, 3 rue Joliot Curie, 91192 Gif-sur-Yvette, France}
```

It should only produce 2 footnotes (see PDF) but instead produces 5, one for each `\fnref`.

**Comment by brucemiller** [comment]
But the "footnotes" are pop-up boxes attached to each of the authors (at least by default latexml).  Isn't that the right thing to do here? Or have I built in too much assumption about how the resulting html will be displayed?

**Comment by bfirsh** [comment]
Ah! Of course, that makes sense. I’m being a bit stupid.

In the Engrafo stylesheet we display footnotes inline, like would be done in a PDF. Because that is non-default behaviour, I shall use a bit of JS or a plug-in to deduplicate.

There is perhaps a bigger discussion about the best way to semantically represent footnotes so they can be displayed as pop ups and inline, like we do. In the meantime you’re right this isn’t a bug. :)
