### ISSUE TITLE
elsarticle.cls binding is missing \biboptions

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#1085]
It is used to pass options to `natbib`.

I was thinking of implementing this, but didn't know the best way to do it. The easy solution is something like `DefMacro('\biboptions{}', '\usepackage[#1]{natbib}');`, but `natbib` still needs to be loaded if `\biboptions` isn't set.

Example paper: https://arxiv.org/abs/1803.07574

**Comment by brucemiller** [comment]
Turns out there's ```\setcitestyle``` in natbib which is for the same purpose (I think); This (00e8e78) should fix it.  Thanks for the report!
