### ISSUE TITLE
Package "subfiles" not supported

### ISSUE THREAD

**Issue by dietmarw** [brucemiller/LaTeXML#1087]
It looks like latexml currently does not support subfiles. Is there some workaround that I could apply until support might eventually be included?

**Comment by dginev** [comment]
Indeed, not yet available. Looking at [the documentation](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/subfiles/subfiles.pdf) it looks like a pretty easy package to add support for.

**Comment by brucemiller** [comment]
Some parts are easy, but others not so much. Handling the subfiles package and ```\subfile``` is pretty trivial; the latter would be equivalent to ```\input```. But I gather the whole objective is to process just the subfile quickly,which is considerably trickier.  The LaTeX implementation would be relying heavily upon the aux file (which we don't have) for it's info.  In our case, to create the initial XML, we've got class "subfiles", but we need to sniff out what the effective class file, and other bindings, are.  Generating the final html (or whatever) will be missing all the links, counters, etc, that would have been found in the aux file; presumably that could be extracted from the XML of a previous full run (eg. Scan it), but still needs some thinking through about redefined ID's and other such stuff.

**Comment by brucemiller** [comment]
I guess reasonable thing to do is support the subfiles *package*, but have the subfiles *class* generate an error (and then punt). And in fact, when handled that way the implementation is trivial (f302c18a).  Thanks for the request!

**Comment by dietmarw** [comment]
Thanks. That works for me nicely!
