### ISSUE TITLE
csquotes.sty: Error from \enquote inside \emph

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1089]
Working with csquots.sty (cf. issue 1088), I found another problem:
```
\documentclass{article}
\usepackage{csquotes}
\begin{document}
\emph{Hello \enquote{World}}
\end{document}
```
`latexml (LaTeXML version 0.8.3; revision 22db863)` throws
```
Fatal:expected:Token Missing argument Token for Core::Definition::Expandable[\expandafter Token Token]
```

**Comment by giovanni111** [comment]
Note that `\emph{Hello \enquote{World}\relax}` works fine.
And note that the same happens with `\footnote` instead of `\emph`.

**Comment by brucemiller** [comment]
Interesting: it's because when closing quotes, csquotes is peeking past the end of the quote to be tricky about kerning and such. But that fails when we've pre-parsed the args.  Hopefully 4f279b27 will fix it.
