### ISSUE TITLE
array.sty.ltxml: tabular preamble option "!"

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1090]
array.sty provides for tabular preambles the "!" option. It is similar to the "@" option from the LaTeX kernel.
```
\documentclass{article}
\usepackage{array}
\begin{document}
\begin{tabular}{l!{--}l}
  a & b \\
\end{tabular}
\end{document}
```
This document produces warnings with `latexml (LaTeXML version 0.8.3; revision 22db863)`. I guess in array.sty.ltxml a `DefColumnType('!{}'` is missing, probably similar to the `DefColumnType('@{}'` in TeX.pool.ltxml.

**Comment by brucemiller** [comment]
Should work now (I also added tentative w and W formats, although I don't have current array.sty to test). Commit 673f0919.  Thanks!
