### ISSUE TITLE
\ref* breaks when the babel package ist loaded 

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1095]
Passing 
```
\documentclass{article}
\usepackage[USenglish]{babel}
\usepackage{hyperref}
\begin{document}

\section{1}\label{sec1}

\ref{sec1}

\ref*{sec1}

\end{document}
```
through `latexml` (LaTeXML version 0.8.3; revision 22db863) results in a broken `<ref>`:
```
    <para xml:id="S1.p1">
      <p><ref labelref="LABEL:sec1"/></p>
    </para>
    <para xml:id="S1.p2">
      <p><ref labelref="LABEL:*"/>sec1</p>
    </para>
```
But the result is fine with the babel option `safe=none`.
So, one solution might be to add
```
RawTeX('\let\bbl@opt@safe\@empty');
```
to `babel.sty.ltxml`. Or perhaps it is wiser to (re)define `\ref*` in hyperref.sty.ltxml?

**Comment by brucemiller** [comment]
yuck. package loading order issue, in part. Both hyperref and babel redefine ```\ref```.  I've defined it the hyperref way in LaTeX.pool, so babel is redefining it not-quite the right way(?)  Setting the safe flag seems to work (nice debugging, btw!), but I wonder if it has other side effects by inhibiting too many redefinitions?

**Comment by brucemiller** [comment]
Ok, well at least the test cases run fine with this (8cf6f703), so let's give it a try.  Thanks for the report & suggested fix!
