### ISSUE TITLE
New optional argument for \multirow

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1096]
In version 2.0 the multirow package has introduced a new first optional parameter. (It is used for vertical alignment.) I'd like to ask for a suitable adjustment in multirow.sty.ltxml, like:
```
diff --git a/lib/LaTeXML/Package/multirow.sty.ltxml b/lib/LaTeXML/Package/multirow.sty.ltxml
index aacea12..59d5515 100644
--- a/lib/LaTeXML/Package/multirow.sty.ltxml
+++ b/lib/LaTeXML/Package/multirow.sty.ltxml
@@ -16,8 +16,8 @@ use warnings;
 use LaTeXML::Package;

 DefPrimitive('\multirowsetup', undef);
-DefPrimitive('\multirow{Number}[Number]{}[Dimension]{}', sub {
-    my ($stomach, $nrows, $bigstruts, $width, $fixup, $content) = @_;
+DefPrimitive('\multirow[]{Number}[Number]{}[Dimension]{}', sub {
+    my ($stomach, $attachment, $nrows, $bigstruts, $width, $fixup, $content) = @_;
     if (my $alignment = LookupValue('Alignment')) {
         my $colspec = $alignment->currentColumn;
         $$colspec{rowspan} = $nrows->valueOf; }
```

**Comment by brucemiller** [comment]
Seems harmless, since optional and ignored (fix in 84100afd).  And if you have a simple example where the parameter is useful, please post it.  Thanks!

**Comment by giovanni111** [comment]
Thanks for the fix and for the remark! Now I understand that the vertical position can indeed be passed to XML, because you provide the vattach attribute for the td element! So, a minimal example is:
```
\documentclass{article}
\usepackage{array}
\usepackage{multirow}
\begin{document}
\begin{tabular}{lm{2em}}
  a & \multirow[b]{2}{2em}{b} \\
  c \\
  e & f \\
\end{tabular}
\end{document}
```
where LaTeX aligns the `\multirow` cell bottom, but LaTeXML writes
```
<td align="justify" rowspan="2" vattach="middle" width="20.0pt">b</td>
```
So I would appreciate it if you can pass the vertical alignment information to the `<td>`!

**Comment by brucemiller** [comment]
Doh! indeed, I should have known that!  Thanks for the tip; now in c46c2312
