### ISSUE TITLE
\counterwithin and \counterwithout

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1097]
Since April 2018, the LaTeX kernel provides new user level commands `\counterwithin` and `\counterwithout`. I'd like to ask for a corresponding LaTeX.pool.ltxml upgrade. (Note that in the meantime the remreset package is obsolete and `\@removefromreset` is new to the LaTeX kernel, too.)

**Comment by brucemiller** [comment]
Whoops, I forgot ```\@removefromreset` in the previous commit. This (7d08dcc8) should fix this issue, as well as #1106.  Thanks for the report!
