### ISSUE TITLE
marginpars are hidden

### ISSUE THREAD

**Issue by raffam** [brucemiller/LaTeXML#1099]
Because I want marginpar to actually be displayed on the left of the page, I [have read here](http://lists.informatik.uni-erlangen.de/pipermail/latexml/2011-July/000501.html) that I can use the `marginpar.css` to achieve that. First I think it has been renamed to `LaTeXML-marginpar.css`, but teven that doesn't work. The command which I run is:
`latexmlc --dest=rules.html --css=LaTeXML-marginpar.css rules.tex`
but this completely hides any marginpar from the page.

**Comment by brucemiller** [comment]
Works for me in the development version; what version of LaTeXML are you using?

**Comment by raffam** [comment]
Uhm ... I cannot reproduce it anymore ...
