### ISSUE TITLE
\titleformat of the "titlesec" package is not supported

### ISSUE THREAD

**Issue by ghost** [brucemiller/LaTeXML#1104]
This should put the Chapter number and title in the same line
```
\documentclass[12pt,a4paper]{book}
\usepackage[utf8x]{inputenc}
\usepackage{titlesec}
\titleformat{\chapter}[hang] 
{\normalfont\huge\bfseries}{\chaptertitlename\ \thechapter:}{1em}{} 
\begin{document}
\chapter{Hi}
\end{document}
```

As per [this stackoverflow question.](https://tex.stackexchange.com/questions/25030/chapter-number-and-chapter-title-in-one-line)

Compiling it with:

> latexmlc text.tex --dest=text.html

returns and HTML file in which the chapter number and title are on separate lines.

I have LaTeXML version 0.8.3

**Comment by brucemiller** [comment]
You can easily get this effect with a bit of custom CSS, like this:
```
.ltx_tag.ltx_tag_chapter {
    display: inline;
}
```
but I don't know if that fulfulls all your objectives (eg. having all documents look "just like" the pdf)

**Comment by dginev** [comment]
Two notes:
 1. You probably want to make the rule Bruce gave even more specific to ensure it overrides the latexml css, e.g.
```css
span.ltx_tag.ltx_tag_chapter {
    display: inline;
}
```

 2. In the `titlesec.sty.ltxml` binding we do have a TODO note:
```
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# TODO: No styling has been implemented,
# this is just a stub to avoid errors
```

So this may be a valid enhancement request in the long run. I'll change some of the issue labels.

**Comment by brucemiller** [comment]
Should work better with f6498df6; not everything that titlesec does is preserved (mostly spacing), but it uses the most interesting stuff.  Thanks for the report!
