### ISSUE TITLE
Remove "Generated by LateXML"

### ISSUE THREAD

**Issue by raffam** [brucemiller/LaTeXML#1105]
How can I make latexml not output "Generated by LateXML at the end of the file?
I tried with the `--nocomments` options but without success.

**Comment by dginev** [comment]
There may be a magical `--xsltparam` that achives this, but I couldn't find it quickly. Chances are if there isn't one you'd need to either make a derived XSLT or hide the footer via CSS. 

A workaround I remember having used is adding `--mode=fragment` to the output, which always omits the footer, but becomes embeddable and you'll need to rewrap it, e.g. 
```
 latexmlc 'literal:test' --format=html5 --mode=fragment
```

Even if Bruce remembers the "easy way" to disable the footer, we should document it better. The `--xsltparam` doc entry says `See the manual or the stylesheet itself for available parameters. `, but we don't really have any easy-to-find list of the parameters already offered for public use.

**Comment by brucemiller** [comment]
The easiest way would be to create a css file with ```.ltx_page_logo { display:none;}```.  Excluding it completely would require some custom xslt (or new switches).

While I hardly want to force folks to keep the logo, I wonder how easy I should make it :>

**Comment by brucemiller** [comment]
Hopefullly the CSS suggestion is sufficient; if not, please reopen.
