### ISSUE TITLE
Support for `chngcntr` package

### ISSUE THREAD

**Issue by raffam** [brucemiller/LaTeXML#1106]
The `chngcntr` latex package is very useful in chaging the way in which table and figures get numbered. Unfortunately LateXML seems to don't support it:

> Warning:missing_file:chngcntr Can't find binding for package chngcntr

**Comment by brucemiller** [comment]
Is this the same basic functionality that's referred to in #1097?  According to that issue, those commands have been moved into the latex kernel (but still have to be implemented in LaTeXML)

**Comment by raffam** [comment]
Yes it is. In fact, [here](https://ctan.org/tex-archive/macros/latex/contrib/chngcntr) there is written that

`This pack­age is ob­se­lete af­ter the 2018 LATEX re­lase as the com­mands are pre-de­fined in the for­mat.`

Thanks for looking into this

**Comment by brucemiller** [comment]
Thanks; See #1097 for resolution.
