### ISSUE TITLE
\stackrel is missing an alias

### ISSUE THREAD

**Issue by siegfriedzoetzsche** [brucemiller/LaTeXML#1117]
The following `example.tex`
```tex
\documentclass{article}
\begin{document}
$a + b \stackrel{x}{=} c$
\end{document}
```
fails during image generation with `latexmlpost` with
```sh
$ latexml --strict --nocomments --destination latexml.xml example.tex
[...]
$ latexmlpost --verbose --pmml --mathtex --mathimages --destination=latexmlpost.xml latexml.xml
[...]
Couldn't find image for 'LaTeXML::Post::MathImages:png:\beginINLINE a+b\lx@stackrel{{\scriptstyle x}}{{=}}c\endINLINE'
[...]
```

My fix is to add `alias => '\stackrel'` to the constructor of `\lx@stackrel` in `LaTeX.pool.ltxml`
```XML
DefConstructor('\lx@stackrel{}{}',
  "<ltx:XMApp role='RELOP'>"
    . "<ltx:XMTok role='SUPERSCRIPTOP' scriptpos='#scriptpos'/>"
    . "<ltx:XMArg>#2</ltx:XMArg>"
    . "<ltx:XMArg>#1</ltx:XMArg>"
    . "</ltx:XMApp>",
  alias => '\stackrel',
  properties => { scriptpos => sub { "mid" . $_[0]->getScriptLevel; } }
);
```

**Comment by dginev** [comment]
Nice catch! A more targeted fix would be setting the `reversion` attribute, which is chiefly responsible for the way `\lx@stackrel` is represented in the math image latex. I opened a single-line PR with that at  #1118

**Comment by brucemiller** [comment]
Actually, ```alias``` is just as targetted and does essentially the same thing.  Thanks for the report & fix!!!
