### ISSUE TITLE
Extended units: reading API and customization

### ISSUE THREAD

**Issue by wtsnjp** [brucemiller/LaTeXML#1120]
I am processing Japanese LaTeX documents with LaTeXML. There are some differences between the Europian TeX family (e.g., (e-)TeX, pdfTeX, XeTeX, and LuaTeX) and Japanese TeX (e.g., (e-)pTeX and (e-)upTeX).

Fortunately, most of the differences can be solved within TeX macro language and some LaTeXML features. For now, the only thing I cannot solve without modifying LaTeXML itself is the "unit".

In pTeX and its variants, some extra units such as `zw` and `zh` are available as well as `pt`, `cm`, etc. So, for example, the following code is valid in pTeX:

```tex
\hskip 2zw\relax
```

To nobody's surprise, this code causes a warning in LaTeXML and leave unexpected tokens `zw` to the input stream (and final XML output).

```
Warning:expected:<unit> Illegal unit of measure (pt inserted).
```

I checked the source of LaTeXML and find that it seems the acceptable units are hard-coded.

https://github.com/brucemiller/LaTeXML/blob/2e18363faaa4021dbd90ad5bb05f65ce3667c0aa/lib/LaTeXML/Core/Gullet.pm#L699

I am very happy if you could add an API which allows users to add new units. Is there any possibility to go for it? Or is there any other good way to solve this?

**Comment by dginev** [comment]
Hi @wtsnjp your request is rather easy to implement, so yes - definitely possible to do in LaTeXML, and it's somewhat direct to see how you would allow for something akin to a `DeclareUnit` declaration to use in binding files.

Then the hardcoded list you mention would upgrade to a variable maintained in the conversion state, which can be updated through the bindings via a new extension to the declaration API.

I am curious how you are implementing this on the TeX side of things, we could also consider extending latexml's support for the low-level tex mechanism you are relying on to introduce the units natively. It would still require refactoring that hardcoded bit of code of course.

**Comment by wtsnjp** [comment]
I am not familiar with the implementation, but according to a friend from TeX Japanese TeX Development Community (texjporg), it is just an easy modification of the tex\.web.

JFYR, here's the specification of the extended units in pTeX:

* `Q` and `H` are always equal to 0.25mm (7227/10160sp)
* `zw` (resp. `zh`) is standard width (resp. height) of the current Japanese font
    * the values dependent on characters which have "character type 0" in Japanese Font Metric (JFM)
    * unlike `ex` and `em`, those are nothing to do with parameters of JFM

**Comment by brucemiller** [comment]
Usually (but not always?) TeX will give an error if there's an invalid unit, so it would (almost?) be safe to just add the units to the list.  But I'm not 100% sure that no valid TeX that had "123zw" in some tricky spot might be interpretted differently by tex vs ptex.

So, I moved the list of units & values into the State, where it can be customized if needed. But at this stage I don't want to be adding new command-line options, so the way you can customize it is adding the following to some "binding" file:
```
use LaTeXML::Package;

AssignMapping('UNITS', q => 0.25 * (72.27 / 25.4) * 65536);    # 0.25mm
AssignMapping('UNITS', h => 0.25 * (72.27 / 25.4) * 65536);    # 0.25mm
AssignMapping('UNITS', zw => 10 * 65536);                      # width of JFM; 10pts?
AssignMapping('UNITS', zh => 5 * 65536);                       # height of JFM; 5pts?
```
You'll probably want to correct the numbers.  A file ```ptex.sty.ltxml``` might be appropriate, particular if there are further ptex-specific adjustments that you'd want. Then you can use the ```--preload=ptex.sty``` option to get it loaded even if the document file doesn't load it.

**Comment by dginev** [comment]
It would be great if that `ptex.sty.ltxml` becomes a part of the master distribution, so that it is available by default, maybe @wtsnjp could contribute it back to us after testing?

**Comment by brucemiller** [comment]
hmm, yeah, indeed. In which case, probably "ptex.pool.ltxml" makes more sense?

**Comment by brucemiller** [comment]
In fact, if you could check the correctness of the scaling factors for the units, and supply a simple ptex example document, we could include that in the next (or a future) release.

**Comment by wtsnjp** [comment]
First of all, thank you for making it possible to extend the units.

Including general pTeX support (`ptex.pool.ltxml`) to LaTeXML is a great idea, for sure. However, I'm afraid that would be tough work and will take a long time. Current my solution only supports a single pLaTeX class, but to develop general support for pTeX is not that much easy.

I can continue the discussion, but I would be happy if it can be done separately from this issue.

**Comment by brucemiller** [comment]
I suppose I was a victim of Wishful Thinking, hoping that fixing a couple of units would constitute a full (enough) ptex binding!  We'd certainly be interested in exploring further improvements though.  But as you say, perhaps that's too open-ended to tack onto this issue.

Please feel free to open other issues, or open discussions on the LaTeXML mailing list (or even direct mail), all the better with sample documents.  Thanks for the report!
