### ISSUE TITLE
add support for \theendnotes to endnotes binding

### ISSUE THREAD

**Issue by swalter62** [brucemiller/LaTeXML#1125]
The current endnotes binding does not support \theendnotes. Providing support for this command would be useful for a large set of documents.

**Comment by brucemiller** [comment]
This just prints the endnotes, right? I had defined ```\printendnotes``` (perhaps I was coding by analogy, since that's the common idiom), but it looks like there's no such command in endnotes; it should be ```\theendnotes```.... or?

**Comment by swalter62** [comment]
Right. If you change ```\printendnotes``` to ```\theendnotes``` in your binding for endnotes, then all is well. Thanks for the fix, Bruce!

**Comment by brucemiller** [comment]
(Doh!) Should be fixed now (4c982fcc); Thanks for the report!
