### ISSUE TITLE
Optional arg for \citeyear under natbib

### ISSUE THREAD

**Issue by swalter62** [brucemiller/LaTeXML#1127]
The optional argument to ```\cite``` works fine under natbib, but fails for the command ```\citeyear```. Here is a minimal test case:
```
\documentclass{article}
\usepackage{natbib}
\begin{document}
\bibliographystyle{astron}
\section{Test}
Let's cite \citeyear[87]{NagE1961}.
\begin{thebibliography}{}
\bibitem[\protect\astroncite{Nagel}{1961}]{NagE1961}
Nagel, E.: 1961,
\newblock {\em The Structure of Science},
\newblock Harcourt, Brace, New York
\end{thebibliography}
\end{document}
```
latexmlpost complains about a missing item:
```
latexmlpost --verbose --dest=myciteyear.html myciteyear.xml
latexmlpost (LaTeXML version 0.8.3; revision 874fa6a3)
processing started Mon May  6 00:26:27 2019
(post-processing...
(Scan myciteyear.html processing... [DBStatus: 7/0 objects] 0.00 sec)
(MakeBibliography myciteyear.html processing... 0.00 sec)
(CrossRef myciteyear.html processing... [Filled in 0 glossaryrefs] [Filled in 0 TOCs] [Filled in fragment 4 ids] [Filled in 0 refs] [Filled in 0 RDFa refs] [Filled in 1 bibrefs]
Warning:expected:ids Missing items:
	  Entry for citation: [
	In Post::CrossRef[@0x5619ed6e7f08] ->process
 0.00 sec)
(XSLT[using LaTeXML-html5.xsl] myciteyear.html processing... 0.00 sec)
(Writer myciteyear.html processing... 0.00 sec) 0.01 sec)
Postprocessing complete: 1 warning
processing finished Mon May  6 00:26:28 2019
```

The bibliography is correctly rendered, just the citation is boshed: ```[87]NagE1961``` instead of ```1961, 87```. I have many files that employ an optional argument to ```\citeyear```. Perhaps there is an easy fix for the natbib binding?

**Comment by brucemiller** [comment]
Whoops, I missed the part "all \cite commands have the same syntax". Should be fixed now (0151dbca).  Thanks for the report!

**Comment by swalter62** [comment]
Thanks for the quick action! With the new commit, the warning has disappeared, but the optional argument to ```\citeyear``` is improperly rendered. For the MWE above, we should have:
```Let's cite 1961, 87.```
But instead, your commit renders the MWE as follows:
```Let's cite 87 1961.```
In other words, the optional argument [87] should follow the year, a comma, and a space. Your latest commit correctly links the year to the bibliography entry, so it is just a matter of transposing the year and the optional argument, and inserting a comma.

**Comment by brucemiller** [comment]
Oh, yeah, well, forgot about the phrase swapping. And had some *'d forms mangled. Hopefully I've got it mostly right now (436c034a)  And added a test case, since it's all so confusing :>  Thanks again!

**Comment by swalter62** [comment]
This looks good to me, Bruce. Well done, and thanks a million!
