### ISSUE TITLE
\chapter after \appendix is now a child of the previous \chapter

### ISSUE THREAD

**Issue by siegfriedzoetzsche** [brucemiller/LaTeXML#1144]
The behaviour of `\appendix` seems to be broken.
In a document using the book class a `\chapter` following `\appendix` is now a child of the previous `\chapter`.

The example:
```latex
\documentclass{book}
\usepackage[utf8]{inputenc}
\begin{document}
\chapter{}
\appendix
\chapter{}
\end{document}
```

In an older latexml (LaTeXML version 0.8.3; revision 972b290)
```sh
$ latexml example.tex
```
gives
```xml
<?xml version="1.0" encoding="UTF-8"?>
[...]
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  [...]
  <chapter inlist="toc" xml:id="Ch1">
    <tags>
      <tag>Chapter 1</tag>
      <tag role="refnum">1</tag>
      <tag role="typerefnum">Chapter 1</tag>
    </tags>
    <title><tag close=" ">Chapter 1</tag></title>
    <toctitle><tag close=" ">1</tag></toctitle>
  </chapter>
  <appendix inlist="toc" xml:id="A1">
    <tags>
      <tag>Appendix A</tag>
      <tag role="refnum">A</tag>
      <tag role="typerefnum">Appendix A</tag>
    </tags>
    <title><tag close=" ">Appendix A</tag></title>
    <toctitle><tag close=" ">A</tag></toctitle>
  </appendix>
</document>
```
while the current latexml (LaTeXML version 0.8.3; revision 2be9933) gives
```xml
<?xml version="1.0" encoding="UTF-8"?>
[...]
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  [...]
  <chapter inlist="toc" xml:id="Ch1">
    <tags>
      <tag>Chapter 1</tag>
      <tag role="refnum">1</tag>
      <tag role="typerefnum">Chapter 1</tag>
    </tags>
    <title><tag close=" ">Chapter 1</tag></title>
    <toctitle><tag close=" ">1</tag></toctitle>
    <appendix inlist="toc" xml:id="A1">
      <tags>
        <tag>Appendix A</tag>
        <tag role="refnum">A</tag>
        <tag role="typerefnum">Appendix A</tag>
      </tags>
      <title><tag close=" ">Appendix A</tag></title>
      <toctitle><tag close=" ">A</tag></toctitle>
    </appendix>
  </chapter>
</document>
```

This seems to be related to the commit [Extend the lists/inlist mechanism to collections like index, glossary…](https://github.com/brucemiller/LaTeXML/commit/2ca25f32157f2fe025c9fa419852eda2a5bd0538) which added `ltx:appenix` to line [145 of LaTeXML.model](https://github.com/brucemiller/LaTeXML/blob/ab6d4cdde63abd2ded509bdf4852fc3c2a481042/lib/LaTeXML/resources/RelaxNG/LaTeXML.model#L145)

If I remove this `ltx:appenix` I can reproduce the old behaviour.

**Comment by dginev** [comment]
Thanks for the extremely fast testing of the new feature @siegfriedzoetzsche !

**Comment by brucemiller** [comment]
How humiliating! All that testing and didn't realize there were no appendix tests in the test suite!  Thanks for catching that so quickly.  It should work now.  I also went ahead and fixed up appendix.sty so that it now supports appendices on multiple levels (as it should).  Thanks for the report!
