### ISSUE TITLE
Is it possiable to transform LaTeXML from perl to javascript?

### ISSUE THREAD

**Issue by seuliang** [brucemiller/LaTeXML#1149]
Is it possiable to transform LaTeXML from perl to javascript, so that we can rander latex to html in browser?

**Comment by dginev** [comment]
Hi @seuliang .

No, not directly. If you need latexml's functionality from the context of a web application you have to deploy it as a service. There are several plugins around that allow for such use cases:
 - The showcase service for https://latexml.mathweb.org/editor, is available as [LaTeXML::Plugin::Mojolicious](https://github.com/dginev/LaTeXML-Plugin-ltxmojo)
 - There is a more minimal (and hence closer to a microservice) socket server available as [LaTeXML::Plugin::latexmls](https://github.com/dginev/LaTeXML-Plugin-latexmls)
 - There is also a ruby plugin I developed some time ago [latexml-ruby](https://rubygems.org/gems/latexml-ruby/versions/0.0.2) if you're working from e.g. a Ruby on Rails application.

But it wouldn't be possible to directly transform latexml away from Perl without a major rewrite effort. Such efforts may be going on behind the scenes, mostly for reasons of performance, but we are nowhere near any major switchovers in the mid-term future. Thanks for the question!
