### ISSUE TITLE
revtex4 empty citations regression

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1150]
Would love us to re-patch this before the next major rerun.

Example:
https://corpora.mathweb.org/preview/arxiv_testbench/tex_to_html/0704.3193?style=simple

snippet - notice the empty parentheses :
```
between the first and third atoms CHARMM22 ().
```

Also, the previews conveniently include the conversion logs at the end of the document, so feel free to scroll to the bottom for the bit that loads revtex4. I recall the last time Michael reported this same issue for revtex articles, but I can't immediately remember where the patch landed.

**Comment by dginev** [comment]
For the record, when I generate the PDF of that article locally The citation comes out as numeric style `[20]`.

![image](https://user-images.githubusercontent.com/348975/58636652-cb6fa700-82be-11e9-8e10-dc835e111531.png)

**Comment by dginev** [comment]
In turn typeset in the bibliography as:

![image](https://user-images.githubusercontent.com/348975/58636735-f659fb00-82be-11e9-9e90-2c94f1e149ce.png)

**Comment by dginev** [comment]
A minimal example waiting to become a test can be seen at my working branch here:
https://github.com/dginev/LaTeXML/commit/714b4a68a067c363bc7c4b2f9604efc1c8de2823

**Comment by brucemiller** [comment]
Probably the most correct solution would be to defer setting the style till the end, but it's going to be pretty messy to unravel the current setup.  However, it's easy to recognize the case after the fact, and avoid adding the parens (d1fd81271156588356672fd092f42df949f047d6); this should work for now.  Thanks!
