### ISSUE TITLE
Issue with installation on MacOS mojave

### ISSUE THREAD

**Issue by gpykhanna1** [brucemiller/LaTeXML#1151]
Hello -- I just followed the steps to install LaTeXML on MacOS 10.14.5.  I have MacPorts installed and followed the steps and LaTeXML seems to install fine. 

However, when I try to convert a file, I get the output shown below.  Please advise what is missing or if this is a bug/issue.

thanks

Gaurav Khanna

```
GKHANNA-M-26ZK:TestingwithLaTexMl gkhanna$ latexml --dest=foundations2.xml foundations2
Can't locate LaTeXML/Core.pm in @INC (you may need to install the LaTeXML::Core module) (@INC contains: /opt/local/libexec/perl5.26/../lib /opt/local/lib/perl5/site_perl/5.28/darwin-thread-multi-2level /opt/local/lib/perl5/site_perl/5.28 /opt/local/lib/perl5/vendor_perl/5.28/darwin-thread-multi-2level /opt/local/lib/perl5/vendor_perl/5.28 /opt/local/lib/perl5/5.28/darwin-thread-multi-2level /opt/local/lib/perl5/5.28) at /opt/local/bin/latexml line 19.
BEGIN failed--compilation aborted at /opt/local/bin/latexml line 19.
GKHANNA-M-26ZK:TestingwithLaTexMl gkhanna$ latexml --dest=foundations2.xml foundations2.tex
Can't locate LaTeXML/Core.pm in @INC (you may need to install the LaTeXML::Core module) (@INC contains: /opt/local/libexec/perl5.26/../lib /opt/local/lib/perl5/site_perl/5.28/darwin-thread-multi-2level /opt/local/lib/perl5/site_perl/5.28 /opt/local/lib/perl5/vendor_perl/5.28/darwin-thread-multi-2level /opt/local/lib/perl5/vendor_perl/5.28 /opt/local/lib/perl5/5.28/darwin-thread-multi-2level /opt/local/lib/perl5/5.28) at /opt/local/bin/latexml line 19.
BEGIN failed--compilation aborted at /opt/local/bin/latexml line 19.
```

**Comment by brucemiller** [comment]
Yeah, I just installed on a fresh Mojave, and am seeing the same curious thing... will dig into it

**Comment by gpykhanna1** [comment]
Thanks Bruce – appreciate your reply.  I’ll look for an update om the LaTeXML site.

 

Thanks for your work on this project.  Really looking forward to it.

 

Regards

 

Gaurav

**Comment by brucemiller** [comment]
FWIW, there's a PR on macports https://github.com/macports/macports-ports/pull/4692, that should fix this, but which (inexplicably?) fails on Travis. Will update with progress.

**Comment by brucemiller** [comment]
OK, my PR got merged, so hopefully you should be able to install using port and get a working latexml!
(BTW: it will use perl 5.28, which probably was already installed, but likely will upgrade the perl dependencies.  However, you'll then be ready for LaTeXML 0.8.4, which hopefully will come out in a week or two)
