### ISSUE TITLE
Producing plain text with latexmlpost

### ISSUE THREAD

**Issue by paolobrasolin** [brucemiller/LaTeXML#1153]
I'm trying to produce a plain text format from a TeX file.

This is my TeX file:
```tex
% main.tex
\documentclass{article}

\begin{document}
  Foobar.
\end{document}
```

`latexml main.tex` produces
```xml
<!-- main.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/Users/paolobrasolin/rb/tex2xml/repro"?>
<?latexml class="article"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-article.css" type="text/css"/>
  <para xml:id="p1">
    <p>Foobar.</p>
  </para>
</document>
```

I wrote this XSL stylesheet to process it:
```xsl
<!-- main.xsl -->
<?xml version="1.0" encoding="utf-8"?>

<xsl:stylesheet
  version   = "1.0"
  xmlns:xsl = "http://www.w3.org/1999/XSL/Transform"
  xmlns:ltx = "http://dlmf.nist.gov/LaTeXML"
  exclude-result-prefixes = "ltx">

  <xsl:output method="text" omit-xml-declaration="yes" indent="no"/>

  <xsl:template match="/processing-instruction('latexml')"/>

  <xsl:template match="@*|node()">
    <xsl:copy><xsl:apply-templates select="@*|node()"/></xsl:copy>
  </xsl:template> 

</xsl:stylesheet>
```

However when I try `latexmlpost main.xml --stylesheet=test.xsl --nodefaultresources` the result is
```xml
<?xml version="1.0"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML" xml:id="Document">


  <para xml:id="p1" fragid="p1">
    <p>Foobar.</p>
  </para>
</document>
```

I think I might be doing something substantially wrong, beacuse:
* `xsl:output` seems to be ignored;
* If my XSL produces no root element then `latexmlpost` crashes;
* the expected output is a few blank lines w/ `Foobar.` in the middle.

Am I misconfiguring `latexmlpost`? It it possible to achieve what I'm trying to do?

**Comment by dginev** [comment]
Hi @paolobrasolin !

The current latexml postprocessor assumes that the XSLT will return back an XML file. You'd need ot modify it further to convince it that non-XML outputs are viable, as well as to prepare a custom writer separate from the main XML flow.

For an example, see my work-in-progress PR, which tries to emit JSON via XSLT, as one stab towards interoperability with pandoc. Quite incomplete, but the Perl parts are likely what you need to make plain-text output work well.

https://github.com/brucemiller/LaTeXML/pull/1113

**Comment by paolobrasolin** [comment]
Thanks @dginev. I'll look into #1113!

**Comment by dginev** [comment]
Let me know if this helped @paolobrasolin , and whether you think we should keep this issue open until we have "plain post-processing targets" available in the master branch. It's certainly a sensible request for non-XML data models.

**Comment by ronaldtse** [comment]
@dginev thanks for the advice. @paolobrasolin in fact is trying to generate metanorma from LaTeXML (as adoc), as @brucemiller knows about.

Would you recommend using latexmlpost or another XSLT engine to achieve this?

**Comment by dginev** [comment]
Cool! I would definitely prefer an outcome where you can use latexml's post-processing as-is, and just add your plain-oriented stylesheet as the customization. We don't need much more infrastructure to make that possible, I could factor out a generic PR that simply creates a mock JSON target and gives the necessary hooks for others to add plugins.

**Comment by paolobrasolin** [comment]
That sounds great!

@dginev, if you could factor out such a PR that would help immensely!

**Comment by dginev** [comment]
@brucemiller would you be OK with me adding a `--format=plaintext` option value, which would act as a demonstration for this mini featureset? 

The idea being that I will make a `LaTeXML-plaintext.xsl` stylesheet, which discards all non-textual bits, and outputs a very bare version of the document's content. That will be a near-trivial stylesheet (I hope), with a test or two, the more important bits being the perl necessary for the post-processing pipeline to handle a non-XML result.

Also, as simple as this looks conceptually, it would ideally land after 0.8.4 is released, as there will almost certainly be some wrinkles to iron out in my refactor.

**Comment by brucemiller** [comment]
One of my sticking points on an eventual more configurable latexml was managing the pipeline of "Document objects" of varying types: eg. TeX string/file, boxes, xml, (x)html,... and plain text!; along with the ultimate output being a file, or collection of files, directory, zip, epub,... So, let's keep that in mind avoiding coding ourselves into any new corners. :>

That said, we may not need a new option and it may ultimately better fit in the scheme that the XSLT postprocessor (via the XSLT stylesheet) *should* know what it is producing.  Is it possible to get ahold of the output method from the stylesheet object?

**Comment by paolobrasolin** [comment]
@brucemiller in theory that's what `xsl:output` is for, as documented in the [recommendation](https://www.w3.org/TR/xslt-10/#output). I _think_ `latexmlpost` is just ignoring it right now.

**Comment by brucemiller** [comment]
Yeah, that's in all the current stylesheets, but at present the XSLT postprocessor doesn't inspect the stylesheet, it merely applies it to the LaTeXML XML and expects to get some sort of XSLT dom object back.  The postprocessors that follow the XSLT one need to adapt to the different object that the plain text would be returning (I assume; I haven't yet started reexamining the code path yet)

**Comment by paolobrasolin** [comment]
Hi @dginev, I'm back to working on this -- I'll try to fiddle with #1113.
Were you able to make any progress factoring out the generic PR in the meantime?

**Comment by brucemiller** [comment]
LaTeXML doesn't directly use the xsl:output info, but the xsl stylesheet does. The first problem is that your stylesheet uses xsl:copy, so that it's really just copying the xml, rather than converting it to plain text. You'd need to omit the copy, and also presumably add templates for text(). 

Once you do that, you start getting errors from LaTeXML's postprocessing since it's assuming that the result of the XSLT is "xml", ie. has a root element and such.  I'll need to handle the case where the document is simple plain text.

**Comment by brucemiller** [comment]
I've just pushed a patch to let plain text target documents (as XML documents containing only plain text) work in postprocessing. It's not really a proper formal "text" target type, but seems to work for the moment.  This should allow you to experiment further with your stylesheet.  Hope that helps!

**Comment by paolobrasolin** [comment]
That helps a lot @brucemiller! It works perfectly.
Also, removing `xsl:copy` I'm able to produce identical outputs with `latexmlpost` and `saxon` (which I'm using as a double check). Thanks for both the tip and the patch!

**Comment by ronaldtse** [comment]
Thank you @brucemiller !! We will put your work into good use :wink: I ought to thank you again in person...
