### ISSUE TITLE
lstset{language=..} accumulates keywords/comments rather than replacing

### ISSUE THREAD

**Issue by adhilton** [brucemiller/LaTeXML#1155]
If you try to change languages with \lstset{language=...}  you end up with the union of language settings (at least keywords + comments) for languages that you have used so far in the document.   Enclosed example starts in C, sets the language to ML (where "return" is incorrectly shown as a keyword and // incorrectly shows a comment).  Changing back to C shows val as a keyword and (* as comment syntax (and helpfully appends two "close comments" to the end of the function).

This behavior was observed in c3d9a7bc63a6be213b791ac87ae5c555efedd187 .
[test.txt](https://github.com/brucemiller/LaTeXML/files/3312549/test.txt)

**Comment by brucemiller** [comment]
Hah; turns out setting language resets a bunch of keywords' values. Should work now. Thanks for the report!
