### ISSUE TITLE
Major Memory Leak with lstinline[...frame=none]

### ISSUE THREAD

**Issue by adhilton** [brucemiller/LaTeXML#1156]
The enclosed bad.txt and good.txt (really .tex, but github wont take those) demonstrate a major memory leak when trying to use frame=none on lstinline.   The only difference between the two files is whether or not frame=none appears in the lstinline options in the codeinline macro definition.   However, compiling "bad" uses ~13GB of memory before timing out after 10 minutes.  Good, on the other hand uses ~800 MB of memory to complete the entire latexmlc process in a reasonable time.  (I'll note that the document I was working from has ~5000 uses of \codeinline and exceeded 30GB after about half an hour before finishing when I set the timeout incredibly high).  

This was compiled on Mac with perl5.28 on commit c3d9a7bc63a6be213b791ac87ae5c555efedd187 .

[good.txt](https://github.com/brucemiller/LaTeXML/files/3312671/good.txt)
[bad.txt](https://github.com/brucemiller/LaTeXML/files/3312673/bad.txt)

**Comment by dginev** [comment]
Thanks for tracing this issue and reporting it @adhilton ! We'll take a look.

**Comment by brucemiller** [comment]
Well, one less leak. Came from not respecting groups. Should be fixed now. Thanks for the report!
