### ISSUE TITLE
\write does not evaluate its argument before writing

### ISSUE THREAD

**Issue by adhilton** [brucemiller/LaTeXML#1158]
In pdflatex \write{} expands its argument before writing it to a file.   This is important if, e.g., the argument references counters with the intent of using their current value later, rather than their value at the point where the input file is read again (example: macro for question + answer to put answer in back of book, writing answers to a file to read later).

To see this behavior, see the enclosed small example.  With LaTeXML, it prints 
This stuff came from chapter 2
However, pdflatex says
This stuff came from chapter 1

This was done with c3d9a7bc63a6be213b791ac87ae5c555efedd187.
Workaround: compile once with pdflatex to produce any temporary files, comment out the file opening, and then compile again with LaTeXML, so that you use the ones produced by pdflatex.

[test.txt](https://github.com/brucemiller/LaTeXML/files/3318586/test.txt)

**Comment by brucemiller** [comment]
Bah! looks like I expanded it in one case but not the other. Fixed now (41ff0d74).  Thanks!
