### ISSUE TITLE
float.sty loses caption text

### ISSUE THREAD

**Issue by evoludolab** [brucemiller/LaTeXML#1161]
Consider a minimal example ``float.tex``:
```
\documentclass{article}
\usepackage{float}
\floatstyle{plain}
\newfloat{customfloat}{ht}{loc}[section]
\floatname{customfloat}{Custom float}

\begin{document}
\begin{customfloat}
\centerline{\textbf{Some floating text}}
\caption{Caption of floating text}
\end{customfloat}
\end{document}
```
converted to (x)html using
```
latexml --dest=float.xml float.tex ; latexmlpost --dest=float.html float.xml
```
correctly displays the floating text but only "Custom float 0.1:" as the caption, i.e. drops the actual caption text.

This can be fixed by changing `#2` to `#1` at the end of line 52 of `float.sty.ltxml` (definition of macro `\format@title@`). However, since I don't speak `perl` (or `latexml`) I don't really know the implications of this change...

**Comment by dginev** [comment]
@evoludolab you diagnosed this perfectly, and it is indeed a 1 character change to reproduce the correct behaviour seen by running pdflatex. It looks to have been a simple oversight / artefact from refactoring.

Thanks, this is the type of issue maintainers dream of - perfect diagnostics and patch. Feel invited to also make a pull request next time, our continuous integration will make sure you're on track with all tests passing, and we'll be happy to help!
