### ISSUE TITLE
Request: make the content model for \part less restrictive

### ISSUE THREAD

**Issue by siegfriedzoetzsche** [brucemiller/LaTeXML#1165]
First of all: thank you very much for the improvements regarding the handling of bibliographies following https://github.com/brucemiller/LaTeXML/issues/976 !

For my use cases the old handling of bibliographies made it necessary to have a transformation as part of the work flow to fix the document structure, i.e. collect bibliographies and other content that has slipped out of parts or chapters or what have you.

While testing whether I could get rid of this clean-up transformation step I stumbled upon the following:

`example.tex`:
```tex
\documentclass{book}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\begin{document}
\part{P}
Abc
\section*{S}
Def
\chapter{C}
Ghi
\end{document}
```
The `\section*`  would be some introduction to the part.
Converting with LaTeXML version 0.8.4; revision 1b8ad29:
```sh
$ latexml --strict --nocomments example.tex
```
gives me
```xml
<?xml version="1.0" encoding="UTF-8"?>
[...]
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  [...]
  <part inlist="toc" xml:id="Pt1">
    <tags>[...]</tags>
    <title><tag close=" ">Part I</tag>P</title>
    <toctitle><tag close=" ">I</tag>P</toctitle>
    <para xml:id="Pt1.p1">
      <p>Abc</p>
    </para>
  </part>
  <section xml:id="Ch0.Sx1">
    <title>S</title>
    <para xml:id="Ch0.Sx1.p1">
      <p>Def</p>
    </para>
  </section>
  <chapter inlist="toc" xml:id="Ch1">
    [...]
  </chapter>
</document>
```
Note that the section forces the part to be closed to early.

I have not done a thorough analysis of what works and what does not but of the stuff I tested only section macros (section, subsection, etc.) show this problem, while figures, tables, itemize and bibliographies work.

My first thought would be to allow everything inside of part that is allowed inside of chapter, but maybe there is something that should not be allowed as a direct child of part which would be ok as direct child of chapter (but nothing comes to mind).

**Comment by brucemiller** [comment]
Indeed; I had the model that only chapters can be in parts.  Which mostly makes sense, but isn't flexible.  I've fixed it now (5d1197f77512e7b15c1cf691555b97d1efb4b8a6). Of course, it wont show up in a release till 0.8.5; Thanks for the report!
