### ISSUE TITLE
Table of contents for interconnected website

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1167]
I'm staring down a long (8+ hour) latexml run that I would like to speed up if possible.

Since I'm going to be calling `latexmlpost --split` on the result, one option would be if I could split the tex going into latexml.  Then I could have latexml compile one file at a time, instead of everything at once.  I tried to mimic https://dlmf.nist.gov/LaTeXML/manual/usage/ with the test document

```LaTeX
\documentclass[openany]{book}
\usepackage{latexml}
\lxDocumentID{chx1}
\begin{document}
\tableofcontents
\chapter*{Preface}
Chapter \ref{ch1}.  Chapter \ref{ch2}.
\end{document}
```
(and similar documents for Ch1.tex and Ch2.tex), and commands
```
latexml --dest=Chx1.xml Chx1
latexml --dest=Ch1.xml Ch1
latexml --dest=Ch2.xml Ch2
latexmlpost --prescan --db=my.db --dest=Chx1.html Chx1
latexmlpost --prescan --db=my.db --dest=Ch1.html Ch1
latexmlpost --prescan --db=my.db --dest=Ch2.html Ch2
latexmlpost --noscan --db=my.db --dest=Chx1.html Chx1
latexmlpost --noscan --db=my.db --dest=Ch1.html Ch1
latexmlpost --noscan --db=my.db --dest=Ch2.html Ch2
```
Everything looks to be working correctly, except that the table of contents doesn't show up.  Am I missing something that I need to do for my table of contents?  Or do I need to manually process the TOC file for my book?  Or did you have some trickery to get the table of contents of the DLMF?

PS As long as we're looking at the usage page, am I correct that
`latexmlpost --prescan --db=my.db --dest=1.html 1`
should be
`latexmlpost --prescan --db=my.db --dest=1.html ch1`
etc?

**Comment by brucemiller** [comment]
Hmm, it can certainly be made to happen (perhaps w/special code as in DLMF) and should. But here it's missing the parent/child relation between your main and chapter documents, and it isn't clear offhand whether the generic latexmlpost has the options to inform it.  I'll take a look into it, but wont get far till I get back from a conference in a couple of weeks.

**Comment by brucemiller** [comment]
Working...  but on your last question, the "1" is correct, because latexml converted `ch1.tex` to `1.xml`.
