### ISSUE TITLE
[texlive 2020] TikZ "left color" leads to Fatal error

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1168]
I'm having some trouble with TikZ's shadedraw.  I think I've narrowed it down to the option `left color` causing a fatal division by zero.
```TeX
\documentclass{article}
\usepackage{tikz}
\begin{document}
\tikz{\shadedraw[color=brown](0,0)--++(0,20pt)--++(20pt,0)--++(0,-20pt)--cycle;} % recursion error and 3 undefined macros
\tikz{\shadedraw[{left color}=brown](0,0)--++(0,20pt)--++(20pt,0)--++(0,-20pt)--cycle;} % causes Fatal Illegal division by zero
\end{document}
```

**Comment by teepeemm** [comment]
It turns out that the fatal error also happens for `\draw[left color=brown]`, not just `\shadedraw`.  I think `--verbose` shows that LaTeXML is trying to call `\pgfmathdivide@{.01992528}{0.000000}`.  TeX's version throws a `\pgfmath@error` in this case.  Since that doesn't happen in TeX, the bug is further back in the stack trace.  But the rest of the stack trace is a stream of memory references (`@0x7fe292114298`), and I can't make sense of them.

**Comment by dginev** [comment]
Hi @teepeemm , could you let me know of the version of texlive that you are using locally? And whether the error is still reproducible with all components updated. I just tested, and got:

The latest latexml master under texlive 2018:
```
latexmlc test.tex --dest=test.html
```
![image](https://user-images.githubusercontent.com/348975/62000228-8a69f800-b09f-11e9-9e1b-e3bba5464bfe.png)

PDF:
![image](https://user-images.githubusercontent.com/348975/62000236-a8375d00-b09f-11e9-9628-06462c374e82.png)

**Comment by dginev** [comment]
I will close here since this example now consistently works in my tests. Please let me know if you are still encountering this problem after updating to the latest master @teepeemm , and I'll try to find a better way to reproduce.

**Comment by teepeemm** [comment]
Unfortunately, I'm still getting the same error.  Version information:
TeXLive 2020
pdfTeX, Version 3.14159265-2.6-1.40.21
LaTeXML version 0.8.4; revision dad33acc (pulled earlier today)
(sorry for being a year later)

**Comment by dginev** [comment]
Thanks for following up @teepeemm ! I will reopen with a "texlive 2020" tag, and will have to recheck carefully after we resolve the most pressing 2020 regression at #1278

**Comment by dginev** [comment]
I have also reproduced the Fatal under texlive 2019 today, adding that label. Still some digging to do...
