### ISSUE TITLE
Issues with navigation and TOC entries for bibliography and appendix when parts are used

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1185]
Related to #954.
I have repeated TeX to XML to HTML conversion using the same as in #954 input TeX file (minimal_test.tex) and nearly the same conversion procedure (omitting navigation.js script and using default XSLT) with LaTeXMl 0.8.4:
`latexml --dest=minimal_test_8_4.xml minimal_test.tex`
`latexmlpost --dest=minimal_test_8_4/index.html --urlstyle=server --navigationtoc=context --javascript=https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=MML_HTMLorMML  --splitat=subsection --splitnaming=labelrelative --css=LaTeXML-navbar-left.css --format=html5 minimal_test_8_4.xml`
TeX file is using report document class, and chapters are grouped into parts.
The main TOC on the main index page does not contain entry for bibliography. Entries for bibliography are missing from navigation bar on all pages, except the pages corresponding to chapters and sections in the last part and the appendix. Links to bibliography in the navigation at the bottom of the page are also only present on pages in the last part (see part-two-index.jpg). 
The entry for a chapter in appendix ("Miscellaneous"; appendix tagged as `\appendix`) in TOC on the main index page (index.jpg) looks like an entry for another chapter in the part preceding the appendix, and navigation bar contains entries for Miscellaneous only on pages within the last part.
All files are in the attached zip archive.
[minimal_test_8_4.zip](https://github.com/brucemiller/LaTeXML/files/3481542/minimal_test_8_4.zip)

The issues affecting the appendix with could probably be avoided by tagging appendix as a part, but this would not fix the problems with bibliography.
Is there a way I could tweak TOC and other navigation, either by modifying the intermediate XML file  (I tried without a success) or XSLT?
Thanks,
Goska

![index](https://user-images.githubusercontent.com/4363602/62698112-40a0dc00-b9d4-11e9-9fdf-1964d981d297.jpg)

![part-two-index](https://user-images.githubusercontent.com/4363602/62698136-4991ad80-b9d4-11e9-8ec3-0cf4af501616.jpg)

**Comment by goska** [comment]
Related to #954.
I have repeated TeX to XML to HTML conversion using the same as in #954 input TeX file (minimal_test.tex) and nearly the same conversion procedure (omitting navigation.js script and using default XSLT) with LaTeXMl 0.8.4:
`latexml --dest=minimal_test_8_4.xml minimal_test.tex`
`latexmlpost --dest=minimal_test_8_4/index.html --urlstyle=server --navigationtoc=context --javascript=https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=MML_HTMLorMML  --splitat=subsection --splitnaming=labelrelative --css=LaTeXML-navbar-left.css --format=html5 minimal_test_8_4.xml`
TeX file is using report document class, and chapters are grouped into parts.
The main TOC on the main index page does not contain entry for bibliography. Entries for bibliography are missing from navigation bar on all pages, except the pages corresponding to chapters and sections in the last part and the appendix. Links to bibliography in the navigation at the bottom of the page are also only present on pages in the last part (see part-two-index.jpg). 
The entry for a chapter in appendix ("Miscellaneous"; appendix tagged as `\appendix`) in TOC on the main index page (index.jpg) looks like an entry for another chapter in the part preceding the appendix, and navigation bar contains entries for Miscellaneous only on pages within the last part.
All files are in the attached zip archive.
[minimal_test_8_4.zip](https://github.com/brucemiller/LaTeXML/files/3481366/minimal_test_8_4.zip)

The issues affecting the appendix with could probably be avoided by tagging appendix as a part, but this would not fix the problems with bibliography.
Is there a way I could tweak TOC and other navigation, either by modifying the intermediate XML file  (I tried without a success) or XSLT?
Thanks,
Goska

![index](https://user-images.githubusercontent.com/4363602/62698112-40a0dc00-b9d4-11e9-9fdf-1964d981d297.jpg)

![part-two-index](https://user-images.githubusercontent.com/4363602/62698136-4991ad80-b9d4-11e9-8ec3-0cf4af501616.jpg)

**Comment by brucemiller** [comment]
Ha; I have ```\addtocontentsline``` mark the previous element, but didn't look for empty/closed elements like bibliography, so it got overlooked. Should work now (although Bibliography doesn't appear in the home page navbar; but it shouldn't since it's essentially a chapter). Thanks for the report!
