### ISSUE TITLE
Windows directory separator

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1187]
In Windows, `\includegraphics{directory/file}` leads to the xml `<graphics candidates="directory\file.png" graphic="directory/file"/>`,
(possibly from lib/LaTeXML/Package/graphicx.sty.ltxml)
which leads to the html `<img src="directory%5Cfile.png">`.
(possibly from lib/LaTeXML/resources/XSLT/LaTeXML-misc-xhtml.xsl via `f:url(@imagesrc)`).
%5C is the url encoding for \\, but the html needs / if it is going to find the image.  It turns out that a literal \\ also works (at least for local html files), but I'm skeptical that would make for a portable website when I copy everything over to a server.

With
```tex
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{directory/by-nc}
\end{document}
```

`latexmlpost --verbose --verbose` does mention
```
(Graphics windowsPath.html processing... [Using graphicspaths: C:\Users\username\Documents\GitHub\project\lab\windowsPath, C:\Users\username\Documents\GitHub\project\lab\windowsPath]
[Processing C:\Users\username\Documents\GitHub\project\lab\windowsPath\directory/by-nc.png as key=LaTeXML::Post::Graphics:directoryby-nc.png.png] [Destination C:\Users\username\Documents\GitHub\project\lab\windowsPath\directory\by-nc.png] [Copied to directory\by-nc.png @ 403 x 141] [done with LaTeXML::Post::Graphics:directoryby-nc.png.png] 0.11 sec)
```

**Comment by dginev** [comment]
So if I am reading this right, the question is whether running a latexml conversion on Windows that includes one of the `--split` postprocessor directives can be directly copied over to a Linux server?

That's something I don't really have an answer to, you'd have to try it out and tell us. But I would expect if the relative paths work locally on Windows, copying the directory structure over to a Windows server should remain operational? Again, not something we have any experience with ourselves.

**Comment by dginev** [comment]
Enhancing the bit of logic around `f:url(@imagesrc)` to convert the backslash to a slash sounds reasonable to me, but I worry about some weird unintended edge cases (e.g. a linux image that has backslashes in its filename, as rare and odd as that sounds).

**Comment by teepeemm** [comment]
It turns out that it is a Windows server that I will be copying everything over to, so `src="directory\file.png"` would work.  I don't know if that would work on a Linux server.  But at the moment, I'm getting `src="directory%5Cfile.png"`, which isn't working.

Is it indeed `f:url` that is converting the backslash to %5C?  At the least, we can't have that happening on Windows.  I suppose we could leave all slashes and backslashes in place, and make the claim that filenames shouldn't have those characters.

(And there is no `--split` involved in this conversion.)

**Comment by brucemiller** [comment]
f:url is part of the XSLT stylesheet, and kinda late to be guessing what kind of OS. I suspect that it would be better to matintain paths in a "universal" format; or at least paths in xml attributes in an (at worst, relative) url form.

**Comment by brucemiller** [comment]
Following up (finally) on that last point, it would seem best to get paths into a more standard format as early as possible (ie. the XL would use "/"), but then hopefully insure that whenever a file is accessed it is converted to local OS format.

Since I don't have a windows machine available (other than a VM, which I forgot how to use), I could make an attempt at that in a branch.  Would you have the possibility of testing that branch to help git it working consistently?

**Comment by dginev** [comment]
I have to double-check the latest latexml build correctly on Windows for the release, so I can also help test/develop any path upgrades at the same time.

**Comment by teepeemm** [comment]
This is working correctly on my Windows laptop as well.  I should also be able to test branches in the future to make sure it's properly working.

**Comment by dginev** [comment]
Cool, thank you for checking!
