### ISSUE TITLE
Warning:missing_file:babel Can't find package babel 	at babel.sty.ltxml; 

### ISSUE THREAD

**Issue by azverin-sb** [brucemiller/LaTeXML#1211]
Hello, I installed the latexml package on a server with ubuntu and when compiling the file, I see the warings in the log:

`Warning:missing_file:babel Can't find package babel
	at babel.sty.ltxml; line 26
	Anticipate undefined macros or environments
	search paths are /var/www/_default/www/uploads/lectures/lec_56/latex, /var/www/_default/www/uploads/lectures/lec_56/latex
	In Core::Gullet[@0x558e63aeaca8] /usr/share/perl5/LaTeXML/Package/babel.sty.ltxml; line 26

Conversion complete: 1 warning; 1 missing file[babel.sty].

Post-processing complete: No obvious problems
Status:conversion:1 
Wide character in print at /usr/bin/latexmlc line 168.
1 warning; 1 missing file[babel.sty]
No obvious problems
Wrote /var/www/_default/www/uploads/lectures/lec_56/result/lecture.html`

I use the command, launch through proc_open: **latexmlc lecture.tex --dest=lecture.html --whatsout=fragment --noparse --nocomments --quiet**
If I use this command locally on my computer with ubuntu, then everything goes without warning
latexml version 0.8.3

attached lecture file
[kink.zip](https://github.com/brucemiller/LaTeXML/files/3767485/kink.zip)

What could be the problem?

**Comment by dginev** [comment]
Hi @azverin-sb !

It sounds like you don't have a texlive installation that is visible to latexml. A good way to check that is to run one of the toolchain executables called `kpsewhich` which locates various pieces of the TeX/LaTeX ecosystems, also in latexml. If babel.sty is available, you should see something on the lines of:

```
$ kpsewhich babel.sty
/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
```

Chances are your server needs the texlive package installed, to get everything running smoothly.

**Comment by azverin-sb** [comment]
Thank you, I could figure it out thanks to your answer. The reason was proc_open, the $ env parameter was not null. Thank.

**Comment by dginev** [comment]
Great to hear, and let us know if anything else comes up.
