### ISSUE TITLE
Modernize and streamline documentation flows

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1213]
One of the reasons I haven't personally "spurred into action" on the documentation issues (#896 , #1073 ) front is  that I do not necessarily feel comfortable with latexml's current documentation infrastructure, in particular when it comes to "technical appendixes" - be it describing schemas or APIs. Bruce and I recently discussed the need for general improvement on that front, and I have been doing some thinking. 

This issue is not meant to bash on the manual's or perldoc's organization, rather to provide some positive examples+ideas on what would be an upgrade in usability, both in contributing as well as consuming/learning from the docs.

As a best practice example, I have been enjoying the API documentation of mathpix recently:
https://docs.mathpix.com

They have a simple/elegant form factor, generated via the open source slate generator:
https://github.com/slatedocs/slate

That approach uses a responsive three-column documentation layout:
 - the left ToC panel allows for intuitive navigation for new learners of the system
 - the central panel contains the actual technical spec, often using tables for itemizing the parameter details
 - the right column allows for adding examples of usage alongside, with an open-ended set of named tabs for e.g. different programming languages

The main upgrade from the manual being that they keep the examples tightly connected to the documentation for each API route. Having specific examples near the definitions greatly enhances the usability of both API and schema appendixes. E.g. consider having "TeX", "XML" and "HTML" tabs for the schema elements, which could be helpful not only for the schema, but also for binding macros (which can also have a "State" tab that describes side-effects).

I also appreciate that the manual [dogfoods](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) latexml itself, which is a cool commitment. I think it is quite doable to provide a slate HTML dialect for latexml if we chose to - oriented towards technical appendixes - while keeping the TeX syntax for the input. I am definitely not intending to argue for Markdown here.

As to deployment, I wonder if it is possible to keep the latest master's documentation mirrored in a `gh-pages` branch on github, while having the main deployment (https://dlmf.nist.gov/LaTeXML/) lag behind to e.g. major releases. It would both encourage third party contributions to the docs - as they can be previewed on github - while also providing a backup deployment in case one of the two domains experiences downtime. The web manual is still a simple set of static HTML+CSS assets, which keeps things very achievable.

Welcoming any and all comments here, but I think this or similar upgrade could really take latexml's usability to a higher level.

**Comment by dginev** [comment]
Ok, I took the time to make a small demo of just a few items that could live in this "API style" documentation form factor, also to test how easy/hard it is to work with:

https://dginev.github.io/latexml-api-docs

Good sides:
 - Looks great. 
 - Code highlighting, and code tabs - I added `shell`, `perl` and `http` as three separate ways to call into latexml's API, and they live in parallel to each other.
 - Markdown lists are simple to write, and slate's left vs right sidebar separation is automatic based on markup conventions.
 - Auto-folding sections for a single document makes this easier to use than the Wiki pages on github, which are hard to get an overview of. 
 - Easy to mod anything, and to include more advanced versions of ToC, code tabs, other bits.
 - Contributing changes/additions to the docs should be a simple edit of an `.md` file, easy to vet, and auto-deployed on merge.
 - Slate itself has good guides and docs.

Bad sides:
 - Somewhat heavy ruby toolchain. I built locally with their docker recipe, and managed to get the automatic deploy to gh-pages with travis. It's easy-ish to setup, but I can't say it's really "simpler" than doing this with some adaptation of latexml itself. 
 - Some conventions are a little subtle, e.g. the code snippets in the right column align to the level two headings `##`, but not to the level 3 headings `###`.

Take a look, let me know what you think ... Source for the docs in that demo page is here:
https://raw.githubusercontent.com/dginev/latexml-api-docs/master/source/index.html.md

**Comment by teepeemm** [comment]
Here's an attempt at the same document in LaTeX(ML).  Good side:
* dog fooding, so we also get a pdf version, an easier build chain, and can use the existing tex files
* not too much coding is necessary: there's only ~ 50 LOC in the preamble and Javascript file (each)
* it still works reasonably well if Javascript is unavailable
Bad side:
* it doesn't have the nifty folding and searchable TOC (but that would be implementable, I suppose)
* the double hyphens in the shell examples have become en-dashes (see #1399)
* the syntax coloring in the code is a little off (latexml isn't adding  morekeywords?)

A less fixable negative is that the examples come a bit late.  In my mind, we would want the source to have the exposition and then the examples, the pdf to also have this order in one column, but the html to render them starting at the same height in the two columns.  But both this and the markdown have the example after (if it came after in the source) or have the example first in the source (see Converting a single formula To Presentation MathML).  We could work around that with some Javascript and extra syntax in the source, but it'd be some work.  (Or maybe have exposition floating left and examples floating right and headers clearing both, but I can't quite get that to work.)
[srcToGithub.zip](https://github.com/brucemiller/LaTeXML/files/5640066/srcToGithub.zip)

**Comment by dginev** [comment]
I am surprised that you tried that, I wouldn't have :> I could probably write a few essays on just your first sentence about `an easier build chain`, but I'll resist the urge for now. In my experience the markdown toolchains are quite simpler for obvious reasons (markdown is simpler). Of course their "dev documentation" solutions have had significant coding and UX polish time invested in them as well, and we don't even have a prototype. I would wager that is also not something likely to change.

The biggest motivation to do the API docs in TeX would be exactly what you say - to dogfood a hypothetical "our own" API documentation solution, and to develop a full HTML+CSS+JavaScript package for it. That's a sizeable undertaking! I'm not volunteering :>

For now I think the most achievable path forward is to keep adding to the slate markdown documentation (PRs welcome in that repository btw) and see when/where those can be made more official-looking and made adjacent to the latexml manual.

Thanks for finding the issue and trying things out in TeX though, it's curious to see this drew your interest!

**Comment by brucemiller** [comment]
As I'm pondering documentation updates, scouting for entry points, I'm struck by a number of false equivalencies, so have to go all snarky on ya: "what I like" \neq "best practices"; "simple markdown" \neq "simple workflow".

I should point out that our "dogfood" API documentation isn't hypothetical: it already exists, albeit out-of-date and not quite modern.  The solution isn't to add a second set of "more modern" documentation using an inferior language but (potentially) superior infrastructure (js). That will just result in two out-of-date and (gradually) not quite modern sets of documentation that will soon contradict each other (and probably neither correct).

And perhaps Catfood is a more appropriate metaphor, and it seems to me more than just a "cool commitment"; if you won't eat your own catfood, you've pretty much given up.

**Comment by dginev** [comment]
Just to neutralize the perception that I'm arguing best practices from my personal taste:

"Best Practices and Tools for Documenting APIs", 2017
https://www.programmableweb.com/news/best-practices-and-tools-documenting-apis/analysis/2017/09/27

> Slate is an open source, responsive API documentation generator that was originally built by TripIt and later adopted by many leading API providers. Over 9,700 GitHub users have forked the Slate repository, indicating many API providers are reusing this template (not all of them are production use cases, but it is used by notable providers for their APIs such as Travis-CI, Best Buy, and Clearbit). Content for Slate is written in Markdown and documentation is delivered in the industry-standard format where the menu is on the left pane, documentation in the middle pane, and an interactive sandbox in the right pane. While API providers must handcraft the documentation, they can link the sandbox to multiple bindings in an API so that tabbed windows are provided to interact with the API in over 100 programming languages, with programming syntax throughout the documentation automatically highlighted, just like in code editors. Slate automatically creates a GitHub repo with the documentation, which can then be published as GitHub pages, or downloaded as HTML, CSS, and JavaScript and hosted on any server.

There are now over 21,000 forks of the repository, more than double the number since that article was written in 2017.

As I mentioned on the top, I'm definitely open for counter-offers of similar quality. Reinventing everything in latexml departs from the cool "dogfooding" label and enters solipsistic territory. And we haven't really been trying to do that, e.g. we already have (difficult to find) github wiki pages, and - much more successfully - the github issue pages, which are obviously in markdown syntax and serve a useful simple purpose.

**Comment by brucemiller** [comment]
Sure; does solipsistic reinvention only apply to reinventing all the web/js/css machinery (inexplicably avoiding reusing?), or does it also apply to reinventing all the documentation (math, mathml, xml) in markdown trying to fulfill a not-so-simple purpose?

**Comment by dginev** [comment]
We can defer the general sentiment of this issue until a more universally acceptable solution comes to mind.

**Comment by teepeemm** [comment]
Just to muddy the waters a bit, I've been working on a different approach the past few days.

This approach is based on my new claim that if the modules are documented in POD, then the rest of the documentation should also be in POD.  This will have the advantage of consistency of documentation, as well as allowing a bit better documentation of the modules themselves.

`perl convert.pl --txt` (or `--html` or `--tex`) uses a subclass of Pod::Text (or Pod::Simple::HTML or Pod::LaTeX) that also accepts the targets `=begin shell`, `=begin perl`, `=begin http`, `=begin TeX`, `=begin xml`, `=begin tabular`, `=begin example`, and `=begin aside`.  The html version only needs some css to look quite similar to dginev's example; a dog-fooded tex version through latexmlc needs some css and js to start coming close (but I couldn't get a div around the examples, which kept causing trouble).

(Tabular is a pain in all three conversions - taking that out could shorten the code by a third or so.)
[doc-via-pod.zip](https://github.com/brucemiller/LaTeXML/files/9215627/doc-via-pod.zip)
