### ISSUE TITLE
LaTeXML cannot find image processing module

### ISSUE THREAD

**Issue by charlyms** [brucemiller/LaTeXML#1215]
After some updates of perl my image LaTeXML doesn´t work properly.
I have Win 10 with new installed strawberry-perl-5.20.2.1-64bit and ImageMagick-6.8.9-1-Q8-x64-dll, following this  https://www.imagemagick.org/discourse-server/viewtopic.php?t=29426 hint.
Nevertheless I get a problem while image processing, for example:

```
> [1;31mError:imageprocessing:imageclass[0m No image processing module found to convert types
        Skipping C:\Users\Klaus\EIGENE~2\Anne\THESUN~2\MaxCartoon.pdf=>png.
        Please install one of: Graphics::Magick,Image::Magick
        In Post::Graphics[@0x5ee20c0] ->transformGraphic
```

Is there something wrong with the path of ImageMagick?
Can you please give a precise advice?
Is a special or annother version of ImageMagick needed?
Does Ghostscript matter?
Regards from Germany
Charlyms

**Comment by dginev** [comment]
Hi @charlyms ! Judging by the latexml error message, your `Image::Magick` cpan module is not available to the executable. Have you gone through latexml's small doc on Windows installation? It is available at:

https://dlmf.nist.gov/LaTeXML/get.html#windows.strawberry

Sadly I can't provide more specific advice than "try to install Image::Magick again and double-check that it is visible to perl when you are running latexml. A minimal way to check is to run:
```
perl -MImage::Magick -e '1;'
```

which should silently exit when it is installed, and provide a verbose error when the module is missing.

**Comment by charlyms** [comment]
I have to install Image-Magick Perl-modul by: ppm install Image-Magick.
For me it is surprising that this is not done by installing a binary for ImageMagick. I suppose this is only the case for active Perl??
Regards
Charlyms

**Comment by dginev** [comment]
ImageMagick is a special case for a dependency, as it is an independent toolkit for image processing that is external to the Perl ecosystem. So if you are installing manually on Windows (without using a package manager such as `chocolately`) you need to install both the toolkit (.dll) and the perl module wrapping around that toolkit as a perl interface. It's definitely not a pleasant user experience and we are always looking for ways to simplify installation flows. So far package managers are the most convenient answer to that.

So, do i understand correctly that you managed to get your setup to work correctly here? If so I will close the issue.

**Comment by charlyms** [comment]
Thank you.
You are right, I have 2 ohter issues with this complex concerning chocolately (it doesnt work anyway for me; I posted there without an answer till now) and tex4ht, both not your turf I am afraid.
Regards 
Charlyms

**Comment by dginev** [comment]
If it is any consolation, I fully agree with you that this is an installation painpoint. We'll keep thinking of ways to mitigate/automate it away. It's a bit of a stopper that no one on the latexml team uses Windows as their primary OS, so it's always a bit of guesswork to find the workable paths.  

Thanks for reaching out!!

**Comment by larsballieu** [comment]
I'm experiencing the same problem as reported above -- running 

perl -MImage::Magick -e '1;'

generates 

Can't locate Image/Magick.pm in @INC (you may need to install the Image::Magick
module) (@INC contains: C:/Strawberry/perl/site/lib/MSWin32-x86-multi-thread-64i
nt C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/
lib).

Running ppm install Image-Magick 

generates

Version 7.0.10 of 'Image-Magick' is already installed.
Remove it, or use 'verify --upgrade Image-Magick'.

Any suggestions?

**Comment by dginev** [comment]
It appears that your perl isn't picking up the same installation paths that ppm is picking up? This may be a better question for the  Strawberry perl folks, it's more a perl problem than a latexml problem. Image Magick also has known issues on recent linux machines (see #1216 ), so it's a growing pain... 

We recently had some fruitful interactions with the Chocolately team who made a windows package for latexml, see:
https://chocolatey.org/packages/latexml

Maybe that is a more convenient alternative to wrestling directly with strawberry perl?
