### ISSUE TITLE
Improve error-reporting for invalid attributes

### ISSUE THREAD

**Issue by paolobrasolin** [brucemiller/LaTeXML#1220]
Let this be `main.tex`:

```latex
\documentclass{article}
\usepackage{lxRDFa}

\begin{document}
  \section{Due}\lxRDFa{alien=true}
\end{document}
```

`latexml main.tex --output test.xml` produces

```stdout
latexml (LaTeXML version 0.8.4; revision 9a0e7dc5)
processing started Sun Dec  1 17:14:50 2019

(Digesting TeX test...
(Loading /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.00 sec) 0.16 sec)
(Processing content /Users/paolobrasolin/rb/tex2mn/tmp/test.tex...
(Loading /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.21 sec)
(Loading /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/Package/article.cls.ltxml... 0.01 sec)
(Loading /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/Package/lxRDFa.sty.ltxml... 0.00 sec) 0.27 sec) 0.43 sec)
(Building...
(Loading compiled schema /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.03 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.
processing finished Sun Dec  1 17:14:51 2019
```

and

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/Users/paolobrasolin/rb/tex2mn/tmp"?>
<?latexml class="article"?>
<?latexml package="lxRDFa"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-article.css" type="text/css"/>
  <section alien="true" inlist="toc" xml:id="S1">
    <tags>
      <tag>1</tag>
      <tag role="refnum">1</tag>
      <tag role="typerefnum">§1</tag>
    </tags>
    <title><tag close=" ">1</tag>Due</title>
  </section>
</document>
```

If I try to `latexmlpost test.xml` I obtain:

```stdout
latexmlpost (LaTeXML version 0.8.4; revision 9a0e7dc5)
processing started Sun Dec  1 17:17:46 2019Use of uninitialized value in concatenation (.) or string at /Users/paolobrasolin/perl5/lib/perl5/LaTeXML/Post.pm line 891.

Error:malformed:document Document fails RelaxNG validation (LaTeXML)
	Validation reports: test.xml:0: Relax-NG validity error : Element document has extra content: resource
	In Post::Document[] ->validate
```

which is weird since `ltx:resource` is allowed in `lxt:document` to my understanding.

I think the `alien="true"` attribute (which is not allowed on `ltx:section` by the schema) is somehow throwing the validator off: If I remove it the document becomes valid.

**Comment by dginev** [comment]
I didn't comment on the last issue since I thought you're keeping the attributes minimal for example's sake. But for actual use, latexml expects proper namespacing for all XML components, so you would like to provide an explicit declaration for your metadata namespace. An example from my own use in blog posts would be:

```tex
\lxRDFaPrefix{dc}{https://purl.org/dc/elements/1.1}
\def\subject#1{\lxRDF[#1]{property=dc:subject}}
```

Should avoid any warnings from what I remember.

**Comment by paolobrasolin** [comment]
Yes, last time I was just using random attributes for terseness.

My point here is just that `Element document has extra content: resource ` is a bit misleading when in reality the problem is on an attribute of a possibly far away tag.

**Comment by dginev** [comment]
Certainly, something to at least consider improving.

**Comment by brucemiller** [comment]
Yeah, the validation report is coming from libxml2 and is simply passed through by LaTeXML. Unfortunately, I can't do much about the message, other than submitting patches upstream. (I typically use jing, when I really need to know what the error is).

**Comment by brucemiller** [comment]
After contemplation (& procrastination), the best I could come up with was to augment the error message with the suggestion to try Jing! (rather than adding jing & java & .... dependencies) :>  Thanks for the report!
