### ISSUE TITLE
improve parsing \lstset keyvals with multiple grouped parts

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1222]
There was a mailing list report, from which I extracted the following minimal example:
```tex
\documentclass[letterpaper]{article}
\usepackage{listings}
\lstset{
escapeinside={\%*}{*)},
}
\begin{document}
test
\end{document}
```

This example succeeds cleanly with pdflatex, but throws errors in latexml.

It looks like the keyval parsing is assuming too much on latexml's end, and/or recovers worse than tex when the second braced part is spotted. Could be a good extra test for KeyVals in general. bookkeeping here without further diagnostics on my part, for now.

**Comment by brucemiller** [comment]
Ha, this has nothing to do with KeyVals, it was much more fundamental. A ridiculously broken `Tokens->stripBraces`; how did it ever work?  Fixed (5c18c9a5) and even added some unit tests (it was too low-level for regular ones)
