### ISSUE TITLE
Broken link in aa.cls.ltxml and aa_support.sty.ltxml

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1223]
Attempts to follow the URL in references to Astronomy & Astrophysics  given in aa.cls.ltxml and aa_support.sty.ltxml, http://www.aanda.org/content/view/129/173/lang,en/ , result in "404 - Category not found" page being served.

**Comment by dginev** [comment]
Indeed that link seems to have disappeared, thanks @goska . 

@brucemiller should we swap it for https://www.aanda.org/for-authors/latex-issues/texnical-background-information ?

**Comment by brucemiller** [comment]
Yeah, probably, although they'll probably change it again.  Fixed; Thanks!!!
