### ISSUE TITLE
Rendering in Firefox

### ISSUE THREAD

**Issue by linwaytin** [brucemiller/LaTeXML#1224]
Hi,

First, thank you for such a useful tool.

I notice expressions rendered in Firefox always have big parentheses or brackets. 
In Chromium, they are normal.
It seems that Chromium uses MathJax to render the math expressions,
and Firefox uses its MathML implementation, which maybe has some bug leading to the big parentheses.

Is there a way to work around this?

**Comment by dginev** [comment]
Hi @linwaytin, thanks for the report!

Could you make the question a little more specific - an HTML file with an example formula would help a little, but it will be especially helpful to know what the current results you are looking at are. Could it be the DLMF site or some other?

If we can confirm the specifics of the parentheses issue, we can escalate it to the firefox rendering folks, or fix it on latexml's end if it's an issue with the MathML created.

**Comment by linwaytin** [comment]
Sure.
I tried both [DLMF](https://dlmf.nist.gov/) and [the example editor](http://latexml.mathweb.org/editor). 
In Firefox, the parentheses are big and seems not rendered by MathJax.
My system is Manjaro Linux. I am not sure if this is system-dependent.

**Comment by dginev** [comment]
Here's what I see from the example editor, left pane is Firefox 71.0 (64-bit), the right pane is Chrome, indeed via MathJax. My OS is Ubuntu 19.10. Is this comparable to what you're seeing?

![image](https://user-images.githubusercontent.com/348975/70910627-c125b800-2018-11ea-824c-d5864d2cd962.png)

**Comment by linwaytin** [comment]
This is what I get in Firefox.
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/12767902/70911961-8ef46600-1fd8-11ea-9d35-12ec27416f88.png">

Does your Firefox use MathJax?

**Comment by dginev** [comment]
The Firefox screenshot I attached is native rendering of the browser, there is no mathjax on the page. I am wondering if this is related to either the browser version or font availability or ... Unsure if Manjaro linux has some peculiar installation details that we/the firefox team haven't anticipated.

**Comment by linwaytin** [comment]
My Firefox version is also 71.0, so I guess it's due to the font.
Do you know how to fix this?

**Comment by linwaytin** [comment]
I just found that I did not install Latin Modern Math.
After installation, the math is good.
I guess my Chromium used another font which can show math correctly.

Thank you for the help.

**Comment by dginev** [comment]
Excellent news! Next time I'll know to recommend installing Latin Modern Math or similar, good to hear it was a local setup issue. Closing the issue here, and feel free to report any other problems you may encounter.
