### ISSUE TITLE
TikZ output lacks text on Fedora 31

### ISSUE THREAD

**Issue by flyn-org** [brucemiller/LaTeXML#1227]
Something seems to have broken TikZ output on Fedora 31, but I am not yet sure what. When I view LaTeXML's output using a browser, none of the text appears in the SVG diagrams that result from TikZ. Here is an minimal example:

```
\documentclass{article}
\usepackage{fullpage}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
\node {XXX};
\end{tikzpicture}
\end{document}
```

This produces a page containing "XXX" when processed the following commands on Fedora 30:

```
latexml --destination foo.xml foo.tikz
latexmlpost --destination foo.html --format=html5 foo.xml
```

The same commands on Fedora 31 produce an empty page, other than the LaTeXML footer.

I am the maintainer of the Fedora LaTeXML package. I understand that this might be a packaging/distribution issue, but I am not yet sure how to debug it.

**Comment by dginev** [comment]
Thanks @flyn-org ! 

Could you quickly provide the output of `tex --version` on that machine, so that we know what we're debugging against? The tikz bindings rely on the native texlive distribution, and changes to texlive that latexml can not yet handle are the likely culprit here.

**Comment by flyn-org** [comment]
```
# tex --version
TeX 3.14159265 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.
# rpm -q texlive
texlive-2019-13.fc31.noarch
```

[foo.tex.txt](https://github.com/brucemiller/LaTeXML/files/4068356/foo.tex.txt)
[foo.xml.txt](https://github.com/brucemiller/LaTeXML/files/4068357/foo.xml.txt)
[foo.html.txt](https://github.com/brucemiller/LaTeXML/files/4068358/foo.html.txt)
[LaTeXML.css.txt](https://github.com/brucemiller/LaTeXML/files/4068367/LaTeXML.css.txt)
[ltx-article.css.txt](https://github.com/brucemiller/LaTeXML/files/4068368/ltx-article.css.txt)

**Comment by pksweby** [comment]
Hi,
I have a similar problem on windows using MiKTeX:
```
tex --version
MiKTeX-TeX 2.9.7054 (3.14159265) (MiKTeX 2.9.7050 64-bit)
Copyright (C) 1982 by D. E. Knuth; all rights are reserved.
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.61.1; using libcurl/7.61.1 WinSSL
compiled with expat version 2.2.6; using expat_2.2.6
compiled with liblzma version 50020042; using 50020042
compiled with libressl version LibreSSL 2.8.2; using LibreSSL 2.8.2
compiled with MiKTeX Application Framework version 4.6961; using 4.6961
compiled with MiKTeX Core version 14.7079; using 14.7079
compiled with MiKTeX Archive Extractor version 1.6882; using 1.6882
compiled with MiKTeX Package Manager version 6.7100; using 6.7100
compiled with uriparser version 0.9.2
compiled with zlib version 1.2.11; using 1.2.11
```
Using the MWE:
```
\documentclass[12pt]{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
	\node [draw, rectangle]  {Text};
\end{tikzpicture}
\end{document}
```
draws the box, but doesn't show the text within it.

The relevant bit of the html is:

```
<svg id="p1.pic1" class="ltx_picture" style="width:48.6pt;height:20.1pt;" height="27.77" overflow="visible" version="1.1" viewBox="-33.6 -13.88 67.2 27.77" width="67.2"><g transform="matrix(1 0 0 -1 0 0.00999999999999801)"><g><g stroke="#000000"><g fill="#000000"><g color="#000000" stroke-width="0.4pt"><g><g><path d="M -30.56 -10.84 h 61.11 v 21.68 h -61.11 Z" style="fill:none"></path><g><g transform="matrix(1 0 0 1 -25.94 -3.46)"><g class="ltx_svg_fog" transform="matrix(1 0 0 -1 0 12.45)">
<switch>
                <foreignObject color="#000000" height="100%" overflow="visible" width="51.89">
                                <p class="ltx_p"></p>
                </foreignObject>
                <g stroke="#000000">
                                <g fill="#000000">
                                                <switch>
                                                                <foreignObject height="9.0pt" width="7.5pt">Text</foreignObject>
                                                </switch>
                                </g>
                </g>
</switch>
</g></g></g></g></g></g></g></g></g></g></svg>
```

The problem seems to be that the outer switch statement chooses the first foreignObject which does not have any text within the `<p class="ltx_p"></p>`.  Manually placing the text there or reversing the order of statements in the outer switch so that the inner switch comes before the first forgeinObject results (at least for this minimal example) in the text correctly appearing.

**Comment by dginev** [comment]
We have gotten a little closer to the underlying issues in #1255, but not yet there. I am tempted to suggest we upgrade to SVG 2.0 along the way, and minimize the redundant markup - it may be helpful with figuring out the exact interplay with the inner `\hbox` invocations.

**Comment by flyn-org** [comment]
@dginev, have you made any progress on this? Is there anything I could help test?

**Comment by dginev** [comment]
@flyn-org certainly, I had filed #1270 some time back, which is pending feedback/merge from Bruce ( @brucemiller ) when he gets some available time.

I'm currently working on additional core TeX capabilities to try and keep ahead of the texlive 2020 changes, so ideally we get a range of these upgrades for the 0.8.5 release.

**Comment by flyn-org** [comment]
Pull request #1270 does indeed seem to fix this. Thank you! I added the patch to the Fedora package until the patch is merged into LaTeXML master (see https://bodhi.fedoraproject.org/updates/FEDORA-2020-9036827163). Looking forward to seeing this merged!
