### ISSUE TITLE
LaTeXML 0.8.5 release date 

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1234]
Would it be possible to get an update on LaTeXML 0.8.5 release date? According to the information available on Milestones summary page https://github.com/brucemiller/LaTeXML/milestones , 42% of work on 0.8.5 has been completed (and the progress has remained stuck at 42% for a good while). Thanks.

**Comment by dginev** [comment]
Indeed, it looks like an annual release cycle is the natural rhythm at the moment. Ought to be some time mid-2020 I suppose? Will let Bruce chime in.

**Comment by dginev** [comment]
Had a chat with Bruce, and I've pushed the release date to July 2020, mostly in sync with what we've done historically.

It looks like the velocity in the latexml repository has decreased substantially in the recent past, which makes some sense as both Bruce's and my focus are targeting related but separate software projects at the moment. Some of these are explicitly targeting unblocking long-standing limitations with latexml's software stack, so hopefully we can tie those back in already in 2020.

**Comment by dginev** [comment]
The release date ended up November 17, 2020 as latexml 0.8.5 was officially released yesterday. I thought it proper to bookkeep for the ones interested here.
