### ISSUE TITLE
\mathop script position with {array}

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1235]
Thanks to Peter Sweby for reporting this issue.

Minimal example:
```tex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[
  \mathop{
    \begin{array}{c}x\end{array}
  }_{b}
\]
\end{document}
```

PDF rendering:
![image](https://user-images.githubusercontent.com/348975/75467227-5b7b7380-5959-11ea-9830-bc090ebb7b4c.png)

current XMath:
```xml
        <XMath>
          <XMApp>
            <XMTok role="SUBSCRIPTOP" scriptpos="post1"/>
            <XMArray role="BIGOP" vattach="middle">
              <XMRow>
                <XMCell align="center">
                  <XMTok font="italic" role="UNKNOWN">x</XMTok>
                </XMCell>
              </XMRow>
            </XMArray>
            <XMTok font="italic" fontsize="70%" role="UNKNOWN">b</XMTok>
          </XMApp>
        </XMath>
```

I am not fluent in the XMWrap logic, but it looks like the wrap is applied onto the `XMArray` element, which leads to the subscript `XMTok` getting the wrong `post1` position, instead of the `mid` one, as prescribed by `doScriptpos` in TeX.pool

**Comment by dginev** [comment]
One could get the correct rendering (but even more incorrect content tree) by adding some distance between the XMWrap and the XMArray, for instance:

```tex
\mathop{\*\begin{array}...
```

```xml
        <XMath>
          <XMApp scriptpos="mid">
            <XMTok role="SUBSCRIPTOP" scriptpos="mid1"/>
            <XMApp role="BIGOP" scriptpos="mid">
              <XMTok meaning="times" role="MULOP">⁢</XMTok>
              <XMTok meaning="absent"/>
              <XMArray role="ARRAY" vattach="middle">
                <XMRow>
                  <XMCell align="center">
                    <XMTok font="italic" role="UNKNOWN">x</XMTok>
                  </XMCell>
                </XMRow>
              </XMArray>
            </XMApp>
            <XMTok font="italic" fontsize="70%" role="UNKNOWN">b</XMTok>
          </XMApp>
```

**Comment by brucemiller** [comment]
The XMWrap logic was fine: it collapses when it contains a single element, but copies relevant attributes from the XMWrap. The catch was that the "common" XMath  attributes wasn't factored sensibly, so that scriptpos wasn't allowed on an XMArray.  I've refactored and it should be good now. Thanks for noticing!

**Comment by dginev** [comment]
Cool, and thanks for the explanation!

**Comment by pksweby** [comment]
Hi,
I copied the revised files and replaced the originals, whilst it works for Deyan's MWE, it still doesn't work for my original example

\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[
  \mathop{
    \begin{array}{c}x\end{array}
  }_{b}
\]

\[
\mathop{\left(\begin{array}{rrrr} 
                                6&-2&2&4\\
                                12&-8&6&10\\
                                3&-13&9&3\\
                                -6&4&1&-18
                                \end{array}\right) }_{\text{\large $A$}}
\mathop{\left(\begin{array}{r} 
                x_1\\x_2\\x_3\\x_4
\end{array}\right)}_{\text{\large$\mathbf x\vphantom{A}$} }
= \mathop{\left(\begin{array}{r} 
                16\\26\\-19\\-34
\end{array}\right)}_{\text{\large$\mathbf b\vphantom{A}$}}
\]

\end{document}

![below_matrix](https://user-images.githubusercontent.com/60572489/75628680-33974480-5bd3-11ea-8043-be6d62bdcafb.jpg)

**Comment by dginev** [comment]
Thanks for bearing with us @pksweby , and for catching the next-level issue! I'm reopening the issue.

In the case of the fenced array cases, the next markup challenge seems to be with adding Bruce's upgrade also to XMDuals. I am seeing in the XML:
```xml
              <XMApp>
                <XMTok role="SUBSCRIPTOP" scriptpos="post1"/>
                <XMDual role="BIGOP" scriptpos="mid">
                  <XMRef idref="S0.Ex2.m1.1"/>
                  <XMWrap>
                    <XMTok role="OPEN" stretchy="true">(</XMTok>
                    <XMArray role="ARRAY" vattach="middle" xml:id="S0.Ex2.m1.1">
                      <XMRow>
                       ...
```

I guess my initial minimal example only covered one of several possible cases.

**Comment by brucemiller** [comment]
Letting XMDual get more attributes, means you've got to look harder for them!  And MWE should mean NOT working :>  Thanks for the followup; hopefully this should fix your issue!

**Comment by pksweby** [comment]
Many thanks, seems to work fine now.
