### ISSUE TITLE
Wrong grammar in svg

### ISSUE THREAD

**Issue by rurban** [brucemiller/LaTeXML#1237]
The svg schemas that you ship in `resources/RelaxNG/svg/` reference a not-existing `relaxng.dtd`, via
`<!DOCTYPE grammar SYSTEM "../relaxng.dtd">`. This is wrong.
Upstream has this fixed by using `<grammar xmlns="http://relaxng.org/ns/structure/1.0" ns="http://www.w3.org/2000/svg">` instead.

http://yupotan.sppd.ne.jp/relax-ng/svg11/svg11-relaxng-20060604.zip is correct, yours is incorrect.

**Comment by dginev** [comment]
Thank you for reporting this @rurban !

**Comment by brucemiller** [comment]
Curious that the original authors felt compelled to provide a DTD for a RelaxNG schema!
Not sure exactly what "upstream" is, here, since I got the schema from W3C (which still has the DTD, btw).

Other than being less than elegant, I'm curious as to what kind of problem it causes (if any)?
I could simply remove those pointless DTD lines (or upgrade to SVG 1.2(?) or SVG 2, or ... Argh!!)

**Comment by rurban** [comment]
The error it causes is failing SVG validation.
LaTeXML is the only package (at least on Fedora, but most likely debian also), that provides those SVG schemas, and I use jing to validate SVG. With the mentioned upstream zip it passes, with your it fails missing on the local relaxng grammar.

**Comment by dginev** [comment]
Sounds like we can update to an SVG setup that validates with jing, thanks for detailing your setup @rurban !

**Comment by brucemiller** [comment]
Curious: I also use jing to validate LaTeXML (w/SVG included) and it works fine.  I guess you weren't using LaTeXML at all (sniff!), but directly referring to the svg schema. I tried that, and indeed it fails with a completely useless null pointer exception.  Commenting out the offending DOCTYPE's (thanks for debugging that!) seems to solve the problem. 

So, thanks for the report, and happy validating! :>

**Comment by rurban** [comment]
> Curious: I also use jing to validate LaTeXML (w/SVG included) and it works fine. I guess you weren't using LaTeXML at all (sniff!), but directly referring to the svg schema. I tried that, and indeed it fails with a completely useless null pointer exception. Commenting out the offending DOCTYPE's (thanks for debugging that!) seems to solve the problem.

Yes, you are right. I just looked at Fedora which package provides a SVG schema to validate against. There was no proper. dtd
