### ISSUE TITLE
lstlisting line ending in "0"

### ISSUE THREAD

**Issue by pksweby** [brucemiller/LaTeXML#1238]
Hi,

I think that I have discovered a problem with the listings package. 

If a lstlisting line ends with a 0 as the last non-space character then it is missed off when processed. Any other character seems fine.
A work around seems to be to place a space after the 0 but it needs to be escaped:

```tex
\documentclass[12pt]{article}
\usepackage{listings}

\begin{document}

\begin{lstlisting}
If parameter = 1 Then Function1 = 1 Else Function1 = 0   
\end{lstlisting}

\begin{lstlisting}
If parameter = 1 Then Function1 = 1 Else Function1 = 1 
\end{lstlisting}

\begin{lstlisting}[escapechar=\%]
If parameter = 1 Then Function1 = 1 Else Function1 = 0% %
\end{lstlisting}

\end{document}
```

produces

![image](https://user-images.githubusercontent.com/60572489/75796835-219cd980-5d6c-11ea-9255-a60d7c7b26ad.png)

(LaTeXML version 0.8.4 on windows 10, MiKTeX-TeX 2.9.7054 (3.14159265) (MiKTeX 2.9.7050 64-bit))

many thanks
Peter

**Comment by brucemiller** [comment]
Ah, struck by the Perl disease, yet again!  Should be fixed now; Thanks for the report!

**Comment by pksweby** [comment]
Many thanks
Peter
