### ISSUE TITLE
physics.sty support

### ISSUE THREAD

**Issue by cphyc** [brucemiller/LaTeXML#1239]
The physics package is a commonly-used package to write physics paper.

It is mostly made of macros to facilitate the typing of some formulas (e.g. `\pdv{f}{x}` is the partial derivative of `f` w.r.t. `x`) and the typing of vectors, etc.

**Comment by dginev** [comment]
Thanks for the request!

To add some arXiv triage data here, `physics.sty` is used in 0.24% of arXiv sources currently registered in CorTeX (or 3,627 articles, to be exact). It is the 27th most often used "missing" package.

**Comment by brucemiller** [comment]
There's now a binding for physics (in the development version). An interesting package to handle! Kinda perverse in its argument handling, but was a nice motivator for improved infrastructure for preserving semantics. I spot-checked some arXiv docs; hopefully it works out for you.  Thanks for the request!
