### ISSUE TITLE
algorithm2e line number regression

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#1271]
Sometime between 195eadf4b82f361e5b434668f97751145335ead8.. 55cde51cbc635cbdd2be60584f8bb50e41bd0d80 I'm seeing an odd regression in `algorithm2e`, perhaps best explained by this diff in our integration test:

https://github.com/arxiv-vanity/engrafo/pull/973/files#diff-2ec3aacd8f525ebff7df6bf4e51c944e (click "load diff" under `algorithm2e.sty.tex/index.html`)

Seems like the line numbers and line content have been swapped in some cases. We've also got tests for `algorithm` and `listings` and they're unaffected.

**Comment by bfirsh** [comment]
Here's the source of that test, in case it's useful: https://github.com/arxiv-vanity/engrafo/blob/master/tests/integration/packages/algorithm2e.sty.tex

**Comment by dginev** [comment]
The commit that broke the example is the one exactly after the start of the range indicated: https://github.com/brucemiller/LaTeXML/commit/83430bc428a7a41dd9e2324bde7e90e9d7d558b2

Looks like we need to double-check the floating logic.

**Comment by dginev** [comment]
Self-contained comment with issue:
```tex
\documentclass{article}
\usepackage{algorithm2e}
\begin{document}
\begin{algorithm}
  \footnotesize
  \LinesNumbered
  \AlgoDisplayBlockMarkers\SetAlgoBlockMarkers{}{}%
  \SetAlgoNoEnd
  \SetAlgoLined
  \KwIn{int threshold, int stages[], NN\_complexity}
  \KwData{record data[], Model index[][]}
  \KwResult{trained index }
  one\;
  two\;
\end{algorithm}
\end{document}
```

```
$ diff old.xml  new.xml 
14c14
<       <listingline><tags>
---
>       <listingline><text fontsize="80%"> one;</text><tags>
16,17c16,17
<         </tags><text fontsize="80%"> one;</text></listingline>
<       <listingline><tags>
---
>         </tags></listingline>
>       <listingline><text fontsize="80%"> two;</text><tags>
19c19
<         </tags><text fontsize="80%"> two;</text></listingline>
---
>         </tags></listingline>
```

In short, the `<tags>` element that numbers the line appears after the `<text>` of the line, after the floating behaviour was changed.
