### ISSUE TITLE
spurious boldface in tabular environment

### ISSUE THREAD

**Issue by swalter62** [brucemiller/LaTeXML#1273]
I noticed a surprising (contrary to LaTeX) result in the tabular environment, whereby the contents of the first column are displayed in boldface whenever a row has an empty initial element. LaTeXML generates a tabular class ltx_guessed_headers in this case, which appears to be the culprit.
Here's a MWE: the first table has first column in boldface, the second table does not.
```
\documentclass{article}
\begin{document}
\begin{tabular}{lr}
Magnétisme&24\\
Données physiques&124\\
&148
\end{tabular}

\begin{tabular}{lr}
Magnétisme&24\\
Données physiques&124
\end{tabular}
\end{document}
```
I'm using LaTeXML version 0.8.4; revision 1c2de609.

**Comment by dginev** [comment]
Hi @swalter62 ,

I have run into this myself and indeed there is a near-identical issue I once opened for Bruce here:
https://github.com/brucemiller/LaTeXML/issues/591

the `ltx_guessed_headers` that you noticed is in fact the outcome of that discussion -- you may want to share some thoughts on whether we should disable guessing entirely on certain tables, or provide a macro from latexml.sty to do so... It can be very surprising when latexml guesses wrong, even if it is quite neat when it guesses right.

Even without any changes on our end, you can make a small CSS change and request the guessed headers to use the regular font weight:
```css
.ltx_guessed_headers {
  font-weight: normal;
}
```

**Comment by swalter62** [comment]
Thanks @dginev, good to know that this is a not a bug, but a feature. I'll adjust the CSS file, as you suggest.

**Comment by swalter62** [comment]
Upon further examination, @dginev, it is not ```.ltx_guessed_headers``` that is producing boldface for my MWE. The real culprit here is ```.ltx_th```. But I can suppress the boldface via CSS.
