### ISSUE TITLE
Request: An option to disable and/or warn on ligatures.

### ISSUE THREAD

**Issue by krivit** [brucemiller/LaTeXML#1276]
I ran into this when trying to compile an expression like the following:
```
\documentclass{article}
\begin{document}
\[<x,y> =x'y\]
\end{document}
```
`latexml` interprets `>=` as a ligature for `\ge`. As far as I can tell, there is no way to disable ligature parsing without disabling all of maths parsing.

I realise that it is a better practice to use `\langle`/`\rangle`, but based on the principle of least astonishment, I think that the program ought to at least warn the user, particularly where it makes a substitution that potentially changes the substance of the expression. (I.e., whether `>>` is rendered as `>>` or as `\gg`, the difference is purely typographic, whereas replacing `<x,y>=` with `<x,y\ge` creates a nonsensical expression.)

**Comment by dginev** [comment]
Thanks for the very compact example of this guess gone wrong @krivit , it is actually very close to a current stream of work we're undergoing related to ambiguous notations - and in this case the ambiguity is even preempted as a ligature as you mention, which has been mostly off my own radar for now. It's quite a nasty mistake, as even the serialized lexemes for the expression end up wrong, so even our arXiv work is likely to have this error embedded.

While we think about this some more and discuss here, let me first just throw an easy solution for you with the current code. If you are able to edit the formula, adding a minimal "hint" of a space will avoid that ligature match, e.g. via `\!` :
```tex
\[<x,y>\!=x'y\]
```

As to the "principle of least astonishment", that is a great name for a principle, but it is rooted at a subjective perspective to astonish. If you take a perspective of "the most common notations are expected, the advanced are only supported where explicitly encountered", having the ">=" ligature makes some sense. If we want to tackle the worst framing here, we can look at an expression that has two perfectly acceptable separate parses, such as:

1. `2<x,y>=z` meaning "2-times-the-dot-product-of-x-and-y-equals-z"
2. `2<x,y>=z` meaning "x greater than two and y greater-or-equal to z"

Thanks again for raising the issue! We can definitely have latexml do better in terms of user experience / defaults / general enhancements.

**Comment by brucemiller** [comment]
Probably worth rethinking them as ligatures entirely.
TeX doesn't ligature them (is that verbable?).
Need to add a little complexity in grammar, but...

**Comment by dginev** [comment]
Sure. There more steps that need to be taken in the grammar route, e.g. `<x,y>` is currently not grammatical in latexml, and would need to get added in, on top of reworking the ligature as a grammar rule. I'm also curious which of the two parses I mentioned you'd like RecDescent to choose as the preferred case in latexml, as another design question.

Also, if anyone is interested in having a `\DisableMathLigature` macro, I can implement a PR, looks quite direct.

**Comment by krivit** [comment]
Thanks for looking into the issue!

> As to the "principle of least astonishment", that is a great name for a principle, but it is rooted at a subjective perspective to astonish. If you take a perspective of "the most common notations are expected, the advanced are only supported where explicitly encountered", having the ">=" ligature makes some sense. If we want to tackle the worst framing here, we can look at an expression that has two perfectly acceptable separate parses, such as:
> 
>     1. `2<x,y>=z` meaning "2-times-the-dot-product-of-x-and-y-equals-z"
> 
>     2. `2<x,y>=z` meaning "x greater than two and y greater-or-equal to z"

I hadn't thought of this use case. My own sense is that if the user is writing an equation in LaTeX, then they expect the ultimate output to look as if it were rendered in LaTeX (or as close as practical), and so however it's parsed, it should not, by default, risk changing the meaning of an expression.

It may make sense to try to detect `<...>` as angle brackets, but I agree that there is no way to disambiguate the two cases above. Perhaps the parser could warn the user when something looks ambiguous and suggest a semantically meaningful replacement? The warning could be suppressed by, say, wrapping in braces, e.g.,

* `<x,y>`: warning suggesting the use of `\langle`/`\rangle`
* `{<}x,y{>}`: warning suppressed
