### ISSUE TITLE
Help needed for writing LaTeXML binding

### ISSUE THREAD

**Issue by nennigb** [brucemiller/LaTeXML#1285]
Hi,

I would like to create a LaTeXML binding for a part of `fp` latex [package](https://ctan.org/tex-archive/macros/latex/contrib/fp?lang=en) for `amc2moodle`, but I am stuck due to my poor perl level. In particular it is very hard for me to understand the prototype of functions involved in LaTeXML. Could you help me ?

I would like to define a constructor to parse `\FPeval{\out}{Latex things}`. In the original package, `\out` contains the (floating point) results of the expansion of "Latex things". 
The second argument contains computations with basic functions (exp, log, ...), numbers and variables like `\x` or `\out` created by previous calls of the `fp` package (see below). 
I need to conserve **the formal content** and I don't want to get floating point final results since it will be evaluated elsewhere with random parameters. All expressions should be self-content since it is not possible to store intermediate variables.
My idea was to create a Macro, named from the first argument, containing the expanded "Latex things", thus all expressions using `\out` will be recursively expanded by LaTeXML, but I didn't succeed.

Here is a Latex example
```
% assume \x has been defined before and is '2.5' (or a variable 'x' or an expression like 2.5*10)
\FPeval{\out}{exp(2*\x)}
the results is \out
then \FPeval{\y}{log(2*\x)+\out}
```
I expected an XML output like,
```
<ltx:note class='FP_eval'>exp(2*2.5)</ltx:note>
the results is <ltx:note class='FP_eval'>exp(2*2.5)</ltx:note>
then <ltx:note class='FP_eval'> log(2*2.5) + <ltx:note class='FP_eval'>exp(2*2.5)</ltx:note> </ltx:note>
```
Then, this output will be processed with xslt and python...

I start naïvely with :
```
DefConstructor('\FPeval{}{}', "<ltx:note class='FP_eval'>#2</ltx:note>");
```
to avoid to add new name in the LaTeXML schema, then I am stuck and I didn't manage to call the good hook.

Thank in advance for your help,

Benoit

**Comment by dginev** [comment]
I'm a little confused, if you would like to have only the symbolic expansion of the expression in your output, isn't that exactly what you would get in your mini language when you let TeX itself expand for you? For example this self-contained snippet has pdflatex produce an output fitting your explanation:
```tex
\documentclass{article}
\def\FPeval#1#2{\def#1{#2}#1}
\def\x{2.5*10}

\begin{document}
\FPeval{\out}{exp(2*\x)}

the result is \out

then \FPeval{\y}{log(2*\x)+\out}
\end{document}
```

An equivalent binding definition for this version of FPeval is:
```perl
DefMacro('\FPeval{}{}','\def#1{#2}#1');
```
And if you want to add special elements around it, you could add a level of indirection with a constructor, as in:
```perl
DefMacro('\@inner@eval{}{}','\def#1{#2}#1');
DefConstructor('\@wrap@eval{}', '<ltx:note class="FP_eval">#1</ltx:note>');
DefMacro('\FPeval{}{}','\@wrap@eval{\@inner@eval{#1}{#2}}');
```

**Comment by nennigb** [comment]
Thanks a lot, it is almost that.

It work fine as long the substitution is performed in `\FPeval`, but if the variable is used directly like in `the result is \out` in the exemple, you get the full expression outside XML tag and it not possible recover it. Is it possible keep pair of opening-closing XML tags each time a substitution is done ?

If it is too complicated we could use \FPprint{\out}, as a work arround.

Benoit

**Comment by dginev** [comment]
You can rearrange the wrappers in near-arbitrary ways, just the way you can stack any TeX macros together. So if you want a wrapper around every expansion of `\out` you can adapt my previous comment:
```perl
DefMacro('\@inner@eval{}{}','\def#1{\@wrap@eval{#2}}#1');
```

It feels like there may be an even cleaner command set for what you're trying to get at, but as long as you get the hang of writing the binding definitions, it should be a productive time experimenting.

**Comment by nennigb** [comment]
Thanks a lot,

I think I got it.

**Comment by dginev** [comment]
Great!

**Comment by brucemiller** [comment]
Cool!

**Comment by nennigb** [comment]
Hi,

When the substitution are done, everything work fine excepted when it use random number. In this case, I need to track each call to the `fp` internal function `random` which is not prefixed by a backslash...
Here, is an example of the naïve substitution :
```
\PFeval{\x}{2*random}
\FPeval{\y}{3*random}
\FPeval{\z}{\x*\y} # yields {2*random*3*random}
```
And here what I need :
```
\FPeval{\x}{2*random} # create 2*random1
\FPeval{\y}{3*random} # create 3*random2
\FPeval{\z}{\x*\y} # yields {2*random1*3*random2}
```
I have create a counter call `rand`, but I didn't succeed to place the hook to performed the substitution like `replace(#2, 'random', 'random\therand')` and the `\stepcounter{rand}`. The substitution should be realized before all other expansions. 
```
NewCounter('rand', 'document');
DefMacro('\FPeval{}{}','\def#1{#2}');
```
Thanks in advance, 
Benoit

**Comment by dginev** [comment]
It is actually a little difficult to understand if you are having a problem with expansion timing, or with stateful behavior (also since I've now mostly forgotten the previous discussion above).

If you wanted to do things "the TeX way", saying that you'd like `\x` to remember the exact same random value that was generated on its definition, you should switch to an expanded definition style of work. Think `\def` vs `\edef` in TeX. If instead you want to keep the expression symbolic, but a unique id is to be magically generated, that should be an enhancement to how `\FPeval` works with its body when it prepares the definition of `\x`, `\y` etc.

One way to counter-ask is to say, if you are trying to do this in classic TeX, and succeed, would latexml understand that? It might.

A second way to approach it:  If you want to do replacements, are you open to changing the binding of `\FPeval` to allow yourself the replacement capability? Perl can certainly do the work for you with latexml's customization API. The empty backbone would be:

```perl
DefMacro('\FPeval{}{}', sub {
 my ($gullet, $arg1, $arg2) = @_;
 # arbitrary perl goes here, e.g. the 'random' replacement
 DefMacroI($arg1, undef, $arg2);
});
```

**Comment by nennigb** [comment]
Sorry for being unclear. I would like to keep all symbolic expressions to process them externally. What I have in mind correspond to your 'second way'. 
I see how to replace strings, but how to get strings from `LaTeXML::Core::Tokens=ARRAY(...)`. I suppose I have to use `ToString`...

Finally I get something like
```
sub replace {
   # replace($arg, $repl, $by)
   # Replace $repl from $arg by $by+\therand  
   # The input expression is split using $repl and the replacement are performed on   
   # substring to control the way the counter is incremented.   
   my( $arg, $repl, $by) = @_ ;
   my $str = ToString($arg);
   # if the token contains the $repl string
   # Create an array for loop and steping the counter
   my @spl = split('('.$repl.')', $str); 
   foreach my $i (@spl){
     if ($i eq $repl){
   	   StepCounter('rand');
       my $byi = $by . ToString(CounterValue('rand'));         
       $i =~ s/$repl/$byi/g;
     }
   }
   return join('', @spl);
}

NewCounter('rand', 'document');
DefMacro('\FPeval{}{}', sub {
 my ($gullet, $arg1, $arg2) = @_;
 # arbitrary perl goes here, e.g. the 'random' replacement
 my $out = replace($arg2, 'random', 'rand');
 DefMacroI($arg1, undef, $out);
 return;
});
```

It seems to work, but could you confirm that the global approach is correct ? I am a newbee in perl ;-)

Thanks a lot!

Benoit

**Comment by dginev** [comment]
Right, you're almost there @nennigb . Some details are important such as split() never returns the separator, just the parts separated *out*. But also once you decide to use the Perl API, you can do things in a self-contained fashion without ever thinking of TeX counters, as latexml offers you a simple State object in which you can do various forms of assignments and lookup. So this seems workable:

```tex
\documentclass{article}
\usepackage{fpeval}
\begin{document}
\FPeval{\x}{2*random}
\FPeval{\y}{3*random}
\FPeval{\z}{\x*\y}

\x % 2*rand1

\y % 3*rand2

\z % 2*rand1*3*rand2
\end{document}
```

and for `fpeval.sty.ltxml`:
```perl
package LaTeXML::Package::Pool;
use warnings;
use strict;
use LaTeXML::Package;

DefMacro('\FPeval{}{}', sub {
  my ($gullet, $arg1, $arg2) = @_;
  # arbitrary perl goes here, e.g. the 'random' replacement
  my $mark = 'random';
  my $target = 'rand';
  my $fpeval_count = LookupValue('fpeval_rand_index') || 0;

  my $expr_str = ToString($arg2);
  $expr_str =~ s/\Q$mark\E/$target.(++$fpeval_count)/ge;

  AssignValue('fpeval_rand_index', $fpeval_count);
  DefMacroI($arg1, undef, $expr_str);
  return;
});

1;
```

**Comment by nennigb** [comment]
Thanks a lot for your help ! Does `LookupValue` and `AssignValue` also work with an existing counter declared with `NewCounter`   (I just post a part of the bindings and other package commands can step the `rand` counter) ?

Benoit

ps : note that `split` with `(separator)` syntax, returns also the separator in the array.

**Comment by dginev** [comment]
The lookup and assignments are done on a string key, and can take an arbitrary Perl value, so they're quite general.

If you look at the code defining `StepCounter` you're likely to get an intuition of both how we usually use state assignments and how counters are realized internally in latexml:
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package.pm#L680-L693 

Feel free to remix as you see fit :+1:
