### ISSUE TITLE
\mathbin operator is rendered before its arguments

### ISSUE THREAD

**Issue by cpitclaudel** [brucemiller/LaTeXML#1288]
Latexmlmath seems to put mathbin before its arguments, instead of infixing it:

```bash
$ latexmlmath '1 \mathbin{+} 2'
<?xml version="1.0" encoding="UTF-8"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" alttext="1\mathbin{+}2" display="block">
  <mrow>
    <mi mathvariant="normal">+</mi>
    <mo>⁡</mo>
    <mn>1</mn>
    <mn>2</mn>
  </mrow>
</math>
```

Is that expected?

**Comment by dginev** [comment]
Thanks for the report! 

Here is what I am seeing with the latest latexml master:
```
$ latexmlmath '1 \mathbin{+} 2'
<?xml version="1.0" encoding="UTF-8"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" alttext="1\mathbin{+}2" display="block">
  <mrow>
    <mn>1</mn>
    <mo>+</mo>
    <mn>2</mn>
  </mrow>
</math>
```

Could you provide the version you are running? E.g. via:
```
$ latexmlmath -V
latexmlmath (LaTeXML version 0.8.4; revision 395440ac)
```

**Comment by cpitclaudel** [comment]
Looks like I'm 4 years behind the times :/

```
$ latexmlmath -V
latexmlmath (LaTeXML version 0.8.2)
```

Sorry for the false alarm! It works perfectly with the new version. Thanks for the hard work :bow:

**Comment by dginev** [comment]
That is great news! And you are actually the second person this week to bring up a bug report with latexml 0.8.2 (#1286), I am starting to wonder where all of these old latexml installations are coming from... 

We are hoping to see a 0.8.5 release soon, so we'll get even more stability shipped to the official repositories.

**Comment by cpitclaudel** [comment]
>  I am starting to wonder where all of these old latexml installations are coming from...

I'm on Linux Mint 19.3, a derivative of Ubuntu based on 18.04.
