### ISSUE TITLE
latexmlmath fails to handle \text at beginning of input

### ISSUE THREAD

**Issue by worden-lee** [brucemiller/LaTeXML#129]
[Originally Ticket 1453]

This command doesn't work:

 $ echo '\text{and}' | latexmlmath --preload=amsmath.sty --preload=amssymb.sty - --pmml=/tmp/x.xhtml

It outputs this error:

 Undefined namespace prefix

 xmlXPathCompiledEval: evaluation failed at /usr/lib/perl5/site_perl/5.10.0/LaTeXML/Common/XML.pm line 326

But this one works:

 $ echo '~\text{and}' | latexmlmath --preload=amsmath.sty --preload=amssymb.sty - --pmml=/tmp/x.xhtml

That is, when \text is the first thing in the input stream there's a problem.  It's the same when \mbox is in place of \text.

**Comment by dginev** [comment]
I can quickly reproduce the small `\text` conversion by @dorthrithil 

The goal of latexmlmath is to convert a formula, and it appears we are not fully prepared for the case where the formula returns only text-mode content. Should be an easy fix.
