### ISSUE TITLE
Combining \subfloat and \autoref

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#1292]
While there is support for both hyperref.sty and subfig.sty, I can't get them to work together in a simple example like this:
```
\documentclass{article}
\usepackage{subfig}
\usepackage{hyperref}
\newcommand{\subfigureautorefname}{\figureautorefname}
\begin{document}
\begin{figure}
  \subfloat[Subfloat caption.]{Some graphics\label{foo}}
  \caption{Figure caption.}
\end{figure}
See \autoref{foo}.
\end{document}
```

With pdfLaTeX, I get _See Figure 1a._, but with LaTeXML I get _See Figure a._ where the number of the figure is missing.

**Comment by dginev** [comment]
Thank you for the report, I can indeed reproduce the problem. @brucemiller had recently mentioned autoref in a call we had, I am sure he's excited to see an issue related to it :>

**Comment by brucemiller** [comment]
Oh, boy, I'm sure excited! I think I got it right now, defining & using the `\p@<counter>` macros more carefully (9f5c893b);  Should work now. Thanks for the report!

**Comment by henrikt-ma** [comment]
Wonderful to see this closed so quickly!

In case someone stumbles upon this closed issue, I suspect that the subject of the issue is a bit misleading. As far as I can tell (haven't tried building LaTeXML from source myself, so I can't test on master), this issue isn't particularly about
