### ISSUE TITLE
text subscript error

### ISSUE THREAD

**Issue by davpoole** [brucemiller/LaTeXML#1293]
Hi. The following gives an error on the latest development version, but does not give an error on the release version or earlier versions. (But the release version gives other errors for me). It is called test.tex

`\documentclass{book}`
`\newcommand{\tx}[1]{\mbox{\emph{#1}}}  % text in math`
`\begin{document}
$\tx{position}_2$
\end{document}`

`latexml  --destination=artint.xml test.tex`
`latexmlpost --format=html5    artint`

Note that it does not give an error without html5

The error is 
(MathML::Presentation  processing...
Fatal:perl:die Perl died
	Not an ARRAY reference at /Users/poole/LaTeXML/blib/script/../lib/LaTeXML/Post/MathML/Presentation.pm line 73.
	In Post::MathML::Presentation[@0x7f8d4ae... ->associateNodeHook
1 fatal error

**Comment by dginev** [comment]
Can reproduce, thanks! It looks like we have a regression.
