### ISSUE TITLE
Using cleveref.sty with empty \crefname

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#1306]
The `\crefname` command below doesn't work:
```tex
\documentclass{article}
\usepackage{cleveref}
\crefname{equation}{}{}
\begin{document}
\begin{equation}\label{lbl}
  x = y
\end{equation}
See~\cref{lbl}.
\end{document}
```

The purpose is that the reference to the equation should just have the text _(1)_, but instead one gets _creftype 1_, along with this error during the build:
```
(Processing definitions /opt/local/share/texmf-texlive/tex/latex/cleveref/cleveref.sty... 2.94 sec) 3.90 sec)
Error:recursion:\extrasenglish Token T_CS[\extrasenglish] expands into itself!
	at mini.tex; line 4 col 0 - line 4 col 16
	defining as empty
	Next token is T_END[}]
	In Core::Definition::Expandable[\extrase... Anonymous String; from line 0 col 0 to line 0 col 0
	 <= Core::Definition::Expandable[\expanda... <= Core::Gullet[@0x7fb48e836460] <= Core::Definition::Register[\toks@] <= ...
```

**Comment by dginev** [comment]
Thanks for the report! We'll take a look.

**Comment by brucemiller** [comment]
I believe I've come up with the right strategy for cleverref (in 154543a8d95bca21e924aa6e33bc185b29e5caf7).

The babel issue is separate; I think I've seen that before (though I can't find an issue), and probably fixed. If it persists, please open a separate issue, with details of which version of TeX you are using.

Thanks for the report!
