### ISSUE TITLE
Stripped character '0' at end of \lstinline

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#1312]
As illustrated by the document below, the last character of a `\lstinline` gets stripped if it is a zero (`0`):
```
\documentclass{article}
\usepackage{listings}
\begin{document}
Broken: \lstinline!x = 0! (zero at end).

Broken: \lstinline!x = 00! (two zeros at end).

Works: \lstinline!0 = x! (zero at beginning).

Works: \lstinline!x = 1! (one at end).
\end{document}
```

**Comment by dginev** [comment]
Thanks for the report!

**Comment by brucemiller** [comment]
I assume you're using a released version (0.8.4)? I think this was fixed in #1238; your example seems to work for me in the development version, and should in the next release.

**Comment by dginev** [comment]
Indeed, I see @henrikt-ma has suggested as much in their [ModelicaSpecification issue](https://github.com/modelica/ModelicaSpecification/issues/2619#issuecomment-662121269), where he makes the curious suggestion of:

>  Alternatively, we could consider putting more pressure on the LaTeXML people to release more often (the latest version was tagged over a year ago)…

A highly entertaining concept, since we've had internal discussions on the topic :>

**Comment by henrikt-ma** [comment]
Glad to hear that I can at least contribute with some entertainment.  But yes, I am using a released version.  This is because we are several persons from different organizations working on the document, so we need a tool chain that is sufficiently straight-forward to install for any collaborator who wants to make more than just simple content changes to the document.

**Comment by brucemiller** [comment]
I fully understand; you really do want to stick to released software for anything remotely production related.  And in fact, we are gradually sneaking up on a release...
