### ISSUE TITLE
XUntil parameter type: balanced reads?

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1313]
Low-level technical question/issue @brucemiller :

XUntil is documented as:
> Reads tokens until a match to the tokens I<match> is found, returning
> the tokens preceding the match. This corresponds to TeX delimited arguments.
> For C<XUntil>, tokens are expanded as they are matched and accumulated.

But one of the subcases in the implementation of the parameter type, has a clause for reading a balanced argument:
```perl
      elsif ($token->getCatcode == CC_BEGIN) {
        push(@tokens, $token, $gullet->readBalanced); }
```

If this is to be an expanding version of Until, shouldn't this call be `->readBalanced(1)` ? Alternatively, would be nice to document that balanced fragments are not expanded, and ideally record why, for the next time we're reading that code. Thanks!

**Comment by brucemiller** [comment]
Hmm, where did you find that documentation? :>
I *think* it is correct as written. The idea is not so much to *expand*, as it is to read until a matching token is found (which can't be found within braces).  But it is used in cases where the end marker may be hidden within another macro (hence the expand).  So, you don't necessarily want to expand within the braces, and I suspect you don't want to; but I'm not sure what scenario would decide it.

**Comment by dginev** [comment]
Where I found it: in the Package.pm pod, which is [also online](https://dlmf.nist.gov/LaTeXML/manual/modules/LaTeXML_Package.html) of course. Actually the online rendering of this doc entry seems a little broken, I guess the last `>` needs a space just before it to render well?

It may be correctly written, but the confusion of what it intends to do is certainly there. It's a parameter type which expands until it hits `$until`, except if it encounters a `CC_BEGIN` token, in in which case it reads to the matching `CC_END` without expanding. So, I can imagine a scenario where the argument is say `{\foo}` in which case both the `Until` and `XUntil` parameter types will have the same value (`\foo` unexpanded). This may surprise binding authors (or simply "me" in this case), who may expect XUntil to generally be in contrast to Until...

At the least an extra sentence, at best an extra example, would be great in the docs.

**Comment by brucemiller** [comment]
easier to fix than to not fix :>
