### ISSUE TITLE
shortlabels in enumitem ?

### ISSUE THREAD

**Issue by 0-andy-0** [brucemiller/LaTeXML#1314]
Just checking: [shortlabels] is not implemented, so the idiom \begin{enumerate}[A)] will fail silently?
Of course the enumerate package will cover it but then I can't [resume].

_Originally posted by @0-andy-0 in https://github.com/brucemiller/LaTeXML/pull/1302#issuecomment-663344309_

**Comment by brucemiller** [comment]
Since I was mucking about in enumitem, I took a look at this. Was nicely able to leverage enumerate's method.  Should be fixed in 7b6a149c.  Thanks for the report!

**Comment by xworld21** [comment]
I am still affected by this bug, actually, MWE:
```latex
\documentclass{article}
\usepackage[shortlabels]{enumitem}
\begin{document}
  \begin{enumerate}[(a)]
    \item Should be (a).
    \item Should be (b).
  \end{enumerate}
\end{document}
```
outputs 1., 2 instead of (a), (b).

**Comment by brucemiller** [comment]
Whoops, left off an argument... fix coming. Thanks for the report!
