### ISSUE TITLE
enumitem bugs: resume and restartlist

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1316]
I've come across two bugs with enumitem.

1. I don't know if it's intentional, but 
```TeX
\documentclass{article}
\usepackage{enumitem}
\begin{document}
\begin{enumerate}[resume=somelabel]
\item one
\end{enumerate}
\begin{enumerate}[resume=somelabel]
\item two
\end{enumerate}
\end{document}
```
works just fine in LaTeX.  From the documentation, it seems that the author is expecting the first environment to be `[series=somelabel]` and all subsequent environments to be `[resume=somelabel]`.  But only using `[resume=somelabel]` works in LaTeX, but throws
`Fatal:misdefined:LaTeXML::Package::SetCounter Can't call method 'valueOf' on an undefined value` at enumitem.sty.ltxml line 149.

2. enumitem.sty.ltxml doesn't define restartlist, so that
```TeX
\documentclass{article}
\usepackage{enumitem}
\setlist[enumerate]{resume}
\begin{document}
\begin{enumerate}
\item one
\end{enumerate}
\begin{enumerate}
\item two
\end{enumerate}
\restartlist{enumerate}
\begin{enumerate}
\item one
\end{enumerate}
\end{document}
```
ends ups with 1, 2, 3 (and the undefined macro) in LaTeXML; this is 1, 2, 1 in LaTeX.  This item seems more difficult than starting a series with resume.

**Comment by brucemiller** [comment]
This should be fixed with 5a0d2979.  Thanks for the report!
