### ISSUE TITLE
Incorrect figure number when cross-referencing subfigures in subfig package 

### ISSUE THREAD

**Issue by samurdhilbk** [brucemiller/LaTeXML#1320]
I am using the subfig package and defining subfigures like below:

```tex
\begin{figure}[H]
    \centering
    \subfloat[sub caption a \label{fig:q3_1_a}]{{\includegraphics[width=0.45\textwidth]{Plots/density.png} }}%
    \qquad
    \subfloat[sub caption b \label{fig:q3_1_b}]{{\includegraphics[width=0.45\textwidth]{Plots/hist_sample.png}}}%
    \caption{main caption}%
    \label{fig:q3_1}%
\end{figure}
```

When referencing the first subfigure using `\ref{fig:q3_1_a}` I get (a)(a) in the HTML output, and for the second subfigure I get (b)(b). i.e. The main figure number is wrong. However, for figures without any subfloats in them, the cross-referencing works correctly (I would get Fig. 2, Fig. 3, and so forth).

If I use the online converter tool at http://latexml.mathweb.org/editor and use the exact same .tex file this issue does not occur. 

I am not sure whether this is a bug or whether I'm doing something wrong.

**Comment by dginev** [comment]
Thanks for the report! The web editor may have a different (older) version of TeXlive, and may also have more packages loaded than usual. Would need to double-check with the specific binding, should be an easy correction...

**Comment by brucemiller** [comment]
What version of LaTeXML are you using?  I believe this bug has been 
addressed in the development version.

**Comment by samurdhilbk** [comment]
I am using LaTeXML 0.8.4 built from the [source given in the website](https://dlmf.nist.gov/LaTeXML/releases/LaTeXML-0.8.4.tar.gz).

**Comment by samurdhilbk** [comment]
Yes, @brucemiller is right. The issue is revolved in the development version. Thank you.
