### ISSUE TITLE
mathbb mathcal etc sometimes(!!) rendered as bf

### ISSUE THREAD

**Issue by 0-andy-0** [brucemiller/LaTeXML#1321]
We have not got to the bottom of this yet, but on local machines and on the demo server https://latexml.mathweb.org/editor we have the following very odd behaviour.

We tried mathbb inside emph and bold enviroments

1. \emph{$\mathbb R$} 

2. \emph{ $\mathbb R$}

3. \textbf{$\mathbb R$}

4. \textbf{ $\mathbb R$}

Only version 3 renders a blackboard bold R correctly, while 1,2,4 show a standard bold R.

We further tried using \textup{} with or without spaces

1. \emph{\textup{$\mathbb R$}}

2. \emph{ \textup{$\mathbb R$}}

3. \emph{\textup{ $\mathbb R$}}

4. \emph{ \textup{ $\mathbb R$}}

5. \textbf{\textup{$\mathbb R$}}

6. \textbf{ \textup{$\mathbb R$}}

7. \textbf{\textup{ $\mathbb R$}}

8. \textbf{ \textup{ $\mathbb R$}}

Now 3,4 and 5 are correct and 1,2 and 6,7,8 are wrong.

So if you happen to need a mathbb in a theorem environment that might be emphasised, you need \textup{} and the dollar cannot be the first character inside it.  Inside a bold environment the textup is not necessary but the dollar must be the first character?

**Comment by 0-andy-0** [comment]
More tests: while the newer commands  \emph and \textbf fail in different ways, the older commands \em and \bf fail in the same (and fewer) cases - exactly where both of the newer commands fail.  I tried:
```
\def\R{$\mathbb R\mathcal R$}

emph: \emph{\R} \emph{ \R} 

\emph{\textup{\R}} \emph{ \textup{\R}} \emph{\textup{ \R}} \emph{ \textup{ \R}}

textbf: \textbf{\R} \textbf{ \R}

\textbf{\textup{\R}} \textbf{ \textup{\R}} \textbf{\textup{ \R}} \textbf{ \textup{ \R}}

em: {\em \R}{\em\ \R} 

{\em\textup{\R}}{\em\ \textup{\R}}{\em\textup{ \R}}{\em\ \textup{ \R}} 

bf: {\bf\R} {\bf\ \R}

{\bf\textup{\R}} {\bf\ \textup{\R}}{\bf\textup{ \R}} {\bf\ \textup{ \R}}
```
and the result was:

![image](https://user-images.githubusercontent.com/48631703/89567455-fd18c200-d821-11ea-9d4b-82c5ae0aabb7.png)

**Comment by 0-andy-0** [comment]
For anyone else suffering this, one workaround is to "fix" the XML file with
 `sed -iE 's/(blackboard|caligraphic|script|bold) upright/\1/g' xmlfile`

Just to restate the core of the issue (no packages are involved, and no warnings or errors are given): 

The source `\emph{$\mathcal X$}` and `\emph{\upshape{$\mathcal X$}}` both produce the XML: 
```xml
<emph font="italic">
    <Math mode="inline" tex="\mathcal{X}" text="X" xml:id="p1.m1">
        <XMath><XMTok font="caligraphic upright">X</XMTok></XMath>
    </Math>
</emph>
```
latexmlpost then produces html containing `<mi class="ltx_font_mathcaligraphic" mathvariant="normal">X</mi>`
which renders as a plain X.

If I edit the XML by hand or by sed to `<XMTok font="caligraphic">X</XMTok>` (just removing the word upright) then post produces the correct HTML `<mi class="ltx_font_mathcaligraphic">𝒳</mi>`.

Similarly for mathbb, mathscr, mathbf and the XML "blackboard upright", "script upright", "bold upright" (are there others?) 

Should I change the issue title to "caligraphic etc + upright problem" and make another issue for nesting bugs, or better to keep it all together?

**Comment by dginev** [comment]
Depends on preference, but if you can find a single test case for each independent problem, it makes sense to host each example in its own issue.

I really need a "fonts" label for marking such issues, will add that.

**Comment by brucemiller** [comment]
actually, although there may be more than one bug, they're pretty well 
related and probably easier to tackle as a bunch in one issue.

**Comment by 0-andy-0** [comment]
I was beginning to think the same thing, it is not worth separating things as they won't be worked on separately.  

Though the sed script above is naive, assuming that when an XMTok font was described by 2 words (script medium, for example) then taking the first one (script) would produce what was intended, it does cover almost all the cases I have come across.  It assumes that the second word (upright, medium, ...) was incorrectly added wrongly to undo an outer environment.

I still have two (maybe) independent doubts: 
1. is the problem that latex to xml conversion of `\emph{$\mathbb C$}` produces "bold upright" rather than just "upright", or that xml to html conversion of "bold upright" produces just upright and loses the bold?
2. is the non-associative nesting of the xml conversion of `\textsf{$\mathbf C$ C $\mathbf C$}` intended? 
```xml
<Math mode="inline" tex="\mathbf{C}" text="C" xml:id="p11.m1">
	<XMath>
		<XMTok font="bold" role="UNKNOWN">C</XMTok>
	</XMath>
</Math>
<text font="sansserif"> C 
	<Math mode="inline" tex="\mathbf{C}" text="C" xml:id="p11.m2">
		<XMath>
			<XMTok font="serif bold" role="UNKNOWN">C</XMTok>
		</XMath>
	</Math>
</text>
```
 
Wherever the blame lies, 1 and 2 together give `bold-C sansserif-C serif-C` in the resulting html/mathjax!

**Comment by brucemiller** [comment]
The xml tracks fonts relative to the parent, so the font attribute there is correct. The problem was that MathML's fonts don't inherit from the outer HTML, and are typically only on tokens, so there are a bunch of redundant cases to be translated.  I think I've got them right, now (at least the ones you pointed out :> )

Hopefully you're not concerned with the missing leading spaces in some of your examples. I'm finding it difficult to figure out a clear-cut rule for when to trim and when not to. (If that's an issue, please open/reopen).

Thanks for the report!

**Comment by 0-andy-0** [comment]
Looks (nearly) perfect now - thanks!
The "nearly" is because of the { ..... $\boldsymbol{C}$ } colum (the one before mathbb) which I am not sure is quite right either in mathjax or firefox native:
 
![image](https://user-images.githubusercontent.com/48631703/92781382-5f765c80-f3a4-11ea-9dad-5a014ade6d2f.png)

**Comment by brucemiller** [comment]
How was that created? (and thus, what was expected?)

**Comment by 0-andy-0** [comment]
Sorry, pedestrian and by no means complete tex test file attached 
(renamed as .txt as tex attachments aren't supported by github... 
[font-bug-test.tex.txt](https://github.com/brucemiller/LaTeXML/files/5205894/font-bug-test.tex.txt)
:-1:  )

What was expected was that the rendering of the first row is mirrored by all the other rows.
It very nearly passes - just six items in the { ..... $\boldsymbol{C}$ } column seem wrong: some upright and some nonbold appear when inside emph/em/textit/it/textbf/bf. 

Not sure how a "complete" text of all the font combinations could be done...
