### ISSUE TITLE
<emph> node allowed inside XMText inside XMath?

### ISSUE THREAD

**Issue by 0-andy-0** [brucemiller/LaTeXML#1323]
Testing `\emph{$y\mbox{\upshape{ $y$}}$}` on [the demo server](https://latexml.mathweb.org/editor) gives
![image](https://user-images.githubusercontent.com/48631703/89733657-3a19ca00-da57-11ea-8ffd-b2d6945c004b.png)
The corresponding XML file has nested XMath, XMText, text and emph nodes.
```xml
<XMath>
	<XMApp>
		<XMTok meaning="times" role="MULOP">⁢</XMTok>
		<XMTok role="UNKNOWN">y</XMTok>
		<XMText>
			<emph font="upright"> </emph>
			<Math mode="inline" tex="y" text="y" xml:id="p1.m1.m1">
				<XMath>
					<XMTok role="UNKNOWN">y</XMTok>
				</XMath>
			</Math>
		</XMText>
	</XMApp>
</XMath>
```

**Comment by dginev** [comment]
Hi @0-andy-0 , just taking a look here now and I wanted to remark that this is only visible when you're using e.g. Chrome that loads MathJax. The error you're seeing is from MathJax not knowing how to handle an `em` inside an `mtext` element.

If you render the same content with Firefox, which uses native rendering via its Gecko engine, without any javascript polyfills, it will render without any errors.

That said, the XMath you're sharing looks quite ugly, so one wonders whether you can't consider simplifying the TeX input as well... I think styling text has been left largely out of scope in the specification of `mtext`, so you're on a bit of shaky ground there. You could provide a softer indication to latexml and let it be a bit quieter in its lack of capability by e.g.

Probably better to do:
```tex
{\em $y\mbox{\upshape{$y$}}$}
```

**Comment by 0-andy-0** [comment]
OK if it is a mathjax bug then this issue should be closed.
I don't consider Firefox native rendering complete or consistent enough to rely on (I notice different results on the same firefox version on ubuntu and manjaro)
The tex was deliberately ugly and contrived - the question was whether the xmath (that was produced by latexml, not me!!)  was legal.

**Comment by dginev** [comment]
Right, I wouldn't close it before hearing from @brucemiller , since he may have a better intuition how to deal with the `<em>` information in general, and its relationship to MathML in particular. Likely that would imply if the XMath is currently correct as well.

MathML itself seems to indicate [embedding of HTML is intended to be possible](https://www.w3.org/TR/MathML3/chapter3.html#presm.html.insertion) from what I can dig up.

**Comment by brucemiller** [comment]
HTML wouldn't be allowed within `mtext` in *pure* MathML, but within HTML5, it allows what they call "phrasing content elements".  So, yes the html is legal.  OTOH, XMath is always legal, whether or not it's usable :>

**Comment by dginev** [comment]
I guess we can close for now in that case, thanks!

**Comment by 0-andy-0** [comment]
Just for the record (so I can find it again later, and anyone else google might lead here), use the **first** form as the second will not render
```
\[
p_i \text{ {\em distinct} primes}
\]
\[
p_i \text{ \emph{distinct} primes}
\]
```

**Comment by brucemiller** [comment]
And just to clarify the clarification: it will not render under MathJax.  It will however, render in firefox
