### ISSUE TITLE
\! eats characters in equations

### ISSUE THREAD

**Issue by evoludolab** [brucemiller/LaTeXML#1324]
Consider a minimal example ``neghspace.tex``:
```
\documentclass{article}
\begin{document}
\(x^\ast<\rho_B\) versus \(x^\ast\!<\!\rho_B\!\)
\end{document}
```
converted to (x)html using (latest `LaTeXML` version from github)
```
latexml --dest=neghspace.xml neghspace.tex ; latexmlpost --dest=neghspace.html neghspace.xml
```
correctly displays the first inequality but deletes the math symbols _before_ the negative horizontal space ``\!`` (note the inequality sign is not affected, i.e. the second inequality prints as `<` only).

As an aside, this only came up because the spacing between `x^\ast` and `<` is bad in LaTeX but worse in `LaTeXML`...

**Comment by 0-andy-0** [comment]
Works fine for me on version 0.8.4; revision 4fe74e1c (latest? don't know but a version less than a month ago) 
And nothing gets eaten on https://latexml.mathweb.org/editor

**Comment by dginev** [comment]
Indeed, there may be some other setup parameter at play to get the bad output of @evoludolab , since the basic inequality also look reasonable here with the latest latexml master (using Firefox):

![image](https://user-images.githubusercontent.com/348975/90126913-62911500-dd32-11ea-9242-4ace8eb72f02.png)

I also checked .xhtml looks the same, and it does.

**Comment by dginev** [comment]
@evoludolab can you also attach your log full log from running the command, the HTML file in question, and mention which browser you're using to view? That will give us a full picture. It's almost certainly some versioning problem given that we have twice confirmed correct rendering (thanks @0-andy-0 )

**Comment by evoludolab** [comment]
Thanks for checking! It turns out it is indeed a browser issue, or more specifically an issue with WebKit. The characters are missing both in Safari 13.1.2 and in iBooks (when converted to an ePub) but indeed everything displays as expected in Firefox. Chrome is somewhere in the middle - no characters are missing but sub- and superscript shifts are lost (and \\! has no effect).

@0-andy-0 thanks for the link to the mathweb LaTeXML editor! Cool tool and strangely enough when visiting the site using Safari (or Chrome) and translating my inequalities above the output renders correctly - not sure what to make of this...

Anyways, I close this issue and will make sure to check other browsers before opening another one ;-)

**Comment by dginev** [comment]
Good to have it resolved, WebKit is not MathML-ready quite yet (but lots of activity to get it there soon!). The web editor showcase is something I've built and maintain, and you can also directly use its code, based at:
https://github.com/dginev/LaTeXML-Plugin-ltxmojo

The main thing to note is that it is using MathJax - a MathML polyfill, which uses javascript to render beautiful math syntax in browsers that haven't added sufficient native MathML support yet. You can also use Katex as another currently popular solution.

The simplest way to obtain a latexml conversion with mathjax enabled is to use a small built-in javascript script we added some time back via:
```
latexmlpost --javascript=LaTeXML-maybeMathjax.js ...
```
