### ISSUE TITLE
Update mathjax url?

### ISSUE THREAD

**Issue by matthuszagh** [brucemiller/LaTeXML#1331]
I was getting some math processing errors in browsers which don't support mathml and therefore fall back to mathjax. I was able to resolve these issues by updating the mathjax_url specified [here](https://github.com/brucemiller/LaTeXML/blob/fb71c30ff7674fc62441ce6187a98240d19e279a/lib/LaTeXML/resources/javascript/LaTeXML-maybeMathjax.js#L6) to `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js?config=MML_HTMLorMML` which is the recommended cdn in the mathjax documentation mentioned [here](http://docs.mathjax.org/en/latest/web/start.html#using-mathjax-from-a-content-delivery-network-cdn). Should this be updated so that others don't experience the same issues? I'm happy to create the PR if this would be useful.

**Comment by dginev** [comment]
I think that we should keep up to date with the marhjax releases yes, we have updated the CDN link before and we should do so again. Would encourage a PR and thanks already for the report!

**Comment by matthuszagh** [comment]
No problem! PR [here](https://github.com/brucemiller/LaTeXML/pull/1332).

**Comment by brucemiller** [comment]
fixed; thanks!
