### ISSUE TITLE
Use latex comments to pass parameters to a bindings ?

### ISSUE THREAD

**Issue by nennigb** [brucemiller/LaTeXML#1336]
Hi,

I would like to pass parameters to my bindings, that does not exist in the original LaTeX package, without breaking the backward compatibility, ie the same file can be compiled in the standard LaTeX way or with LaTeXML without modification.
To do so, a commonly used method is to use a preprocessor. I was wondering if it is possible to use the LaTeX comments to pass  data to LaTeXML and how to recover them.
For instance, using `%#` 
```
... standard latex code ...
% normal comment
%#\mydata=10
... standard latex code ...
```
Once in LaTeXML, `\mydata=10` is processed as a normal input.

I know I can performed this step _externally_ before invoking LaTeXML, but is there a cleaner way ?
Have you another idea to ensure such backward compatibility ?

Thank a lot,

Benoit

**Comment by dginev** [comment]
Hi @nennigb ,

A commonly used technique in latexml is to pass additional options via preload options, such as:
```
latexml --preload=[ids,mathlexemes,localrawstyles]latexml.sty
```

Which are only relevant to the special perl code in `latexml.sty.ltxml` and have no effect in the PDF files themselves.
A different technique that has been used is to have a latexml-only block of declarations, via the `\iflatexml` conditional. So for your case you could do:
```tex
\iflatexml
% this only executes in latexml processing
\mydata=10
\else
% this only executes in pdflatex processing, not in latexml
\fi
```

That conditional is defined in latexml.sty, so you also would need a `\usepackage{latexml}` at the top of the document.

As to the templating direction, it may "look" more internal, but it still requires some templating engine to exist and do the rewrites for you. It's just a matter of whether latexml will offer one itself (it doesn't, and I would guess it won't - out of scope for us for now), or whether you would need to resort to some of the existing external templating engines.

You could always write `doc.tex.hbs` or `doc.tex.erb` and have Handlebars or ERB do the work from the outside as a preprocessor for you. Or any of the other myriad of templating engines out there...

**Comment by nennigb** [comment]
Thank you for your complete response. Do you know if the perl code called by `--preload` is natively aware of the input tex file and can be used to patch it (easily)? 
Since my workflow already involved several other steps after latexml processing, I think I will choose an external preprocessor.
It seems to be the only working solution without adding a custom `\usepackage` and their associated path problem for our application.

**Comment by dginev** [comment]
Sure, feel free to play around and let us know what you ended up liking/disliking with the various approaches.

`--preload` is best thought of as doing a `\usepackage` from the outside of a TeX input file, so if you don't want to add a custom package, it's just as bad an option for you.
