### ISSUE TITLE
Center align environment and display tags at right

### ISSUE THREAD

**Issue by matthuszagh** [brucemiller/LaTeXML#1337]
Hello, I'm having some trouble converting some math environments to mathml. Here's the command I'm currently running:

```
$ latexmlc 'literal:\\begin{equation}\\label{eq:distance_time_diff}\\tag{4.1.1}
                           d = \\frac{c\\Delta t}{2},
                         \\end{equation}' --profile=math --preload=siunitx.sty 2>/dev/null
```

This produces
```html
<math xmlns="http://www.w3.org/1998/Math/MathML" id="S0.Ex1.m1.1" class="ltx_Math" alttext="d=\frac{c\Delta t}{2}," display="block">
  <semantics id="S0.Ex1.m1.1a">
    <mrow id="S0.Ex1.m1.1.5" xref="S0.Ex1.m1.1.5.2.cmml">
      <mrow id="S0.Ex1.m1.1.5.2" xref="S0.Ex1.m1.1.5.2.cmml">
        <mi id="S0.Ex1.m1.1.1" xref="S0.Ex1.m1.1.1.cmml">d</mi>
        <mo id="S0.Ex1.m1.1.2" xref="S0.Ex1.m1.1.2.cmml">=</mo>
        <mfrac id="S0.Ex1.m1.1.3" xref="S0.Ex1.m1.1.3.cmml">
          <mrow id="S0.Ex1.m1.1.3.2" xref="S0.Ex1.m1.1.3.2.cmml">
            <mi id="S0.Ex1.m1.1.3.2.1" xref="S0.Ex1.m1.1.3.2.1.cmml">c</mi>
            <mo id="S0.Ex1.m1.1.3.2.4" xref="S0.Ex1.m1.1.3.2.4.cmml">⁢</mo>
            <mi mathvariant="normal" id="S0.Ex1.m1.1.3.2.2" xref="S0.Ex1.m1.1.3.2.2.cmml">Δ</mi>
            <mo id="S0.Ex1.m1.1.3.2.4a" xref="S0.Ex1.m1.1.3.2.4.cmml">⁢</mo>
            <mi id="S0.Ex1.m1.1.3.2.3" xref="S0.Ex1.m1.1.3.2.3.cmml">t</mi>
          </mrow>
          <mn id="S0.Ex1.m1.1.3.3" xref="S0.Ex1.m1.1.3.3.cmml">2</mn>
        </mfrac>
      </mrow>
      <mo id="S0.Ex1.m1.1.4" xref="S0.Ex1.m1.1.5.2.cmml">,</mo>
    </mrow>
    <annotation-xml encoding="MathML-Content" id="S0.Ex1.m1.1b">
      <apply id="S0.Ex1.m1.1.5.2.cmml" xref="S0.Ex1.m1.1.5">
        <eq id="S0.Ex1.m1.1.2.cmml" xref="S0.Ex1.m1.1.2"/>
        <ci id="S0.Ex1.m1.1.1.cmml" xref="S0.Ex1.m1.1.1">𝑑</ci>
        <apply id="S0.Ex1.m1.1.3.cmml" xref="S0.Ex1.m1.1.3">
          <divide id="S0.Ex1.m1.1.3.1.cmml" xref="S0.Ex1.m1.1.3"/>
          <apply id="S0.Ex1.m1.1.3.2.cmml" xref="S0.Ex1.m1.1.3.2">
            <times id="S0.Ex1.m1.1.3.2.4.cmml" xref="S0.Ex1.m1.1.3.2.4"/>
            <ci id="S0.Ex1.m1.1.3.2.1.cmml" xref="S0.Ex1.m1.1.3.2.1">𝑐</ci>
            <ci id="S0.Ex1.m1.1.3.2.2.cmml" xref="S0.Ex1.m1.1.3.2.2">Δ</ci>
            <ci id="S0.Ex1.m1.1.3.2.3.cmml" xref="S0.Ex1.m1.1.3.2.3">𝑡</ci>
          </apply>
          <cn type="integer" id="S0.Ex1.m1.1.3.3.cmml" xref="S0.Ex1.m1.1.3.3">2</cn>
        </apply>
      </apply>
    </annotation-xml>
    <annotation encoding="application/x-tex" id="S0.Ex1.m1.1c">d=\frac{c\Delta t}{2},</annotation>
  </semantics>
</math>
```

which renders in a browser as:

![center](https://user-images.githubusercontent.com/7377393/92044304-cce61580-ed32-11ea-93b4-0c89f57e33f3.png)

So, it's centered (which I want), but the tag is removed.

If I use an `align` environment, e.g.
```
$ latexmlc 'literal:\\begin{align}\\label{eq:switching_converter_ion}
                           -V_{\\mathit{in}} + V_L + V_{\\mathit{out}} &= 0,\\tag{5.4.2.1a}\\\\
                           L \\frac{\\Delta I_{\\mathit{on}}}{\\Delta t_{\\mathit{on}}} &=
                                                                                     V_{\\mathit{in}}
                                                                                     -V_{\\mathit{out}},\\tag{5.4.2.1b}\\\\
                           \\Delta t_{\\mathit{on}} &= DT,\\tag{5.4.2.1c}\\\\
                           \\Delta I_{\\mathit{on}} &= \\frac{DT}{L}
                                                    \\left(V_{\\mathit{in}}-V_{\\mathit{out}}\\right).\\tag{5.4.2.1d}
                         \\end{align}' --profile=math --preload=siunitx.sty 2>/dev/null > file.html
```

I get the tags but all of the equations are shifted to the left of the page. Here's how it renders:

![align_math](https://user-images.githubusercontent.com/7377393/92044558-5f86b480-ed33-11ea-835a-a28f4cb16ede.png)

Moreover, the left-hand side of each equation is also shifted to the left. I'd prefer this end just to the left of the equals sign as it does in LaTeX.

I've also tried using `--profile=fragment`, which has the effect of giving me tags for `equation` environments but left-shifting it also. It seems to have roughly the same result for `align` environments as `equation`. I also tried the other profiles but didn't have any luck.

I'm using
```
latexmlc (LaTeXML version 0.8.4)
```

Is there a way to achieve the effect I want here? Thanks!

**Comment by dginev** [comment]
Hi @matthuszagh ,

Luckily, there are ways to calibrate latexml to get exactly what you want on the output. First note is that the math `--profile` is intended for extracting out a single `<math>` element. So naturally the tag you seek will not be included, as the equation tags live in regular HTML, rather than MathML itself. What you can use instead is the fragment profile, as in:

```
latexmlc --profile=fragment --preload=siunitx.sty \
'literal:\begin{equation}\label{eq:distance_time_diff}\tag{4.1.1} d = \frac{c\Delta t}{2},\end{equation}'
```

Which will produce a `<div>` element meant to be embedded in any HTML document. Here is a screenshot of that div rendered by firefox:
![image](https://user-images.githubusercontent.com/348975/92056550-adfc7900-ed5c-11ea-98b0-b68c5f98e82d.png)

If you want the centering to work you should also include the default css files, which you would get if you were creating a full HTML document with `--preload=article.cls`. They are namely:
```html
<link rel="stylesheet" href="LaTeXML.css" type="text/css">
<link rel="stylesheet" href="ltx-article.css" type="text/css">
```

You should then see:
![image](https://user-images.githubusercontent.com/348975/92058332-44309f00-ed5d-11ea-920c-5d202e7a767e.png)

Let us know if this helps, and thanks for investigating!

**Comment by matthuszagh** [comment]
`fragment` plus the stylesheets achieved exactly what I wanted. Thanks for such a prompt response @dginev!
