### ISSUE TITLE
amsthm.sty: individual notefont

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1338]
Using the amsthm package, I often define a special theoremstyle in order to get some of my theorems with a bold-faced note in the heading:
```tex
\documentclass{article}
\usepackage{amsthm}
\newtheorem{theorem}{Theorem}
\makeatletter
\newtheoremstyle{myspecial}
  {\topsep}
  {\topsep}
  {\itshape}
  {}
  {\bfseries\thm@notefont{\bfseries}}
  {.}
  {5pt plus1pt minus1pt\relax}
  {}
\makeatother
\theoremstyle{myspecial}
\newtheorem{myspecial}{Myspecial}

\begin{document}
\begin{theorem}[notestring]
  bodystring
\end{theorem}
\begin{myspecial}[notestring]
  bodystring
\end{myspecial}
\end{document}
```
But running LaTeXML on this, the note in {myspecial} remains light-faced.
I figured out that with
```perl
DefRegister('\thm@notefont'     => Tokens(T_CS('\bfseries')));
```
the notes of all my theorems become bold. Do you know a trick to control the notefont dependent on theoremstyles?

**Comment by dginev** [comment]
There is an easy web-stack answer to your question, but I do not immediately have the TeX-side answer.

If you convert to HTML, you will see your custom theorem represented as:
```html
<div id="Thmmyspecial1" class="ltx_theorem ltx_theorem_myspecial">
  <h6 class="ltx_title ltx_runin ltx_title_theorem">
    <span class="ltx_tag ltx_tag_theorem"><span class="ltx_text ltx_font_bold">Theorem 1</span></span> (notestring).
  </h6>
```

You can write a custom CSS rule, such as:
```css
.ltx_theorem_myspecial .ltx_title_theorem { font-weight:bold; }
```

which will style as bold specifically the `{myspecial}` environments.

**Comment by brucemiller** [comment]
A small can-o-worms, that. It sent me massaging the various theorem packages to account for which theorem parameters are recorded as part of each theorem definition and which aren't, as well as exactly how each parameter is used. Interestingly, it turned up a lot of subtle bugs in my test cases.  I never noticed that the '.' after the theorem name is actually in bold if the name is!

Anyway, thanks for the clue and the report:  ebfccede should fix it.
