### ISSUE TITLE
Use of listings.sty with 'alsoletter' breaks math escape

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#1346]
Using `alsoletter` breaks math escape:
```tex
\documentclass[10pt,a4paper]{report}
\usepackage[utf8]{inputenc}
\NeedsTeXFormat{LaTeX2e}

\usepackage{listings}
\lstdefinelanguage{Lang}{
  alsoletter={.},
}
\lstset{
  language=Lang,
}

\begin{document}
\begin{lstlisting}[mathescape=true]
1 $\pm$ 2   --- works
1 :$\pm$ 3  --- works (':' is not in 'alsoletter')
1 .$\pm$ 3  --- doesn't work due to '.' being in 'alsoletter'
1 . $\pm$ 4 --- works, saved by whitespace
\end{lstlisting}
\end{document}
```

In the case it doesn't work, the output `1 .$\pm$ 3` is produced instead of `1 .± 3`.

(In my particular case, I don't know what the `.` is doing in the `alsoletters`, so I might be able to find a way around the problem.)

**Comment by dginev** [comment]
Thank you for the report and the minimal test case - very helpful! We'll take a look.

**Comment by brucemiller** [comment]
Are you running 0.8.4, by any chance?
The development version seems to work correctly (there have been
some listings patches).

(Yeah, we're due for a release very soon)

**Comment by henrikt-ma** [comment]
Right, I'm still on 0.8.4.  With several of the issues I've reported already being fixed in the development version, I think I need to figure out how to set up things so that I can switch back and forth between the released version we're using in our project, and the development version…
