### ISSUE TITLE
Use of <th> with standard CSS gives unexpected bold font weight

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#1349]
Build a `tabular` with some dividers:
```
\documentclass{article}
\begin{document}
\begin{center}
\begin{tabular}{l l|l l}
\hline
\textit{Column A} & \textit{Column B} & \textit{Column C} & \textit{Column D}\\
\hline
\hline
Hello & Hello & Hello & Hello\\
World & World & World & World\\
\hline
\end{tabular}
\end{center}
\end{document}
```

The resulting HTML makes some more or less unexpected use of `<th>` elements, and the default CSS files don't remove the bold font weight of these.  The result is a table that looks quite different than the original LaTeX table.

I was able to work around this by adding my own CSS with this content, that I think should be there by default:
```
/* Undo bold here to remove the browser's native th styling,
 */
.ltx_th { font-weight:normal; }
```

**Comment by dginev** [comment]
I have asked this question here myself some time ago and I recall Bruce gave me a good answer. Here is the link after some searching, along with some discussion:
https://github.com/brucemiller/LaTeXML/issues/591#issuecomment-91377540

@brucemiller : do you think we should document this specific behavior in the manual? It may be a common usage "gotcha".

**Comment by henrikt-ma** [comment]
Thanks for digging up that discussion!

My starting point here is just a little bit different: I don't mind if the use of `<th>` is considered a feature rather than a bug on its own, but I find it strange that the standard CSS files don't remove the standard styling that comes with it.  If someone really wants to make use of these (at least sometimes) heuristically inferred header markups, it will be rather easy to figure out the relevant elements and classes to be targeted in a user-defined CSS.

**Comment by brucemiller** [comment]
Two things:  You can globally disable such header guessing from perl (if you've got any personal bindings, or such) with
```
AssignValue(GUESS_TABULAR_HEADERS => 0);
```
(perhaps that should be available through a package option to `latexml.sty`?).

Second: Did you try using the "important" marker for you css (ie. "!") in the css rules to set the font for `<th>`?

**Comment by henrikt-ma** [comment]
Thanks, it's good to know that there's a way to turn off the header guessing.  I wasn't aware of the _latexml.sty_, should it be loaded like any other LaTeX package, allowing options to be passed in the normal way, or is there some other way to pass options?

Regarding the "important" marker, I didn't try it, because the rule for the class `ltx_th` is doing the job.

This issue was created because of the need to do _anything_ to get something that looks like the original LaTeX tables.

**Comment by brucemiller** [comment]
One of these days it'll sink in that if it worked well enough,
I wouldn't have to explain it all the time :>
And then I'll disable it by default.

**Comment by henrikt-ma** [comment]
Sounds good. :)

**Comment by dginev** [comment]
I closed here and linked to this issue under the more generic documentation issue we have for latexml's HTML5 at #896 .
