### ISSUE TITLE
LaTeXML selects wrong language -- missing re-input of TeX sources

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1357]
I have a document that employs US- and UK-english. In minimal form:
```tex
\documentclass[USenglish,UKenglish]{article}
\usepackage{babel}
\begin{document}
\languagename
\end{document}
```
While LaTeX outputs "UKenglish", LaTeXML writes "USenglish". As far as I can see, this happens because LaTeX inputs english.ldf once for USenglish and once for UKenglish, but LaTeXML omits the second input. I suppose this is because in Package.pm, `loadTeXDefinitions` says: "Don't load if we've already loaded it before." From LaTeX's perspective this is indeed expected for \usepackage and friends but not for \input. Can you put LaTeXML in a position to "re-\input" files?

**Comment by dginev** [comment]
Thanks for the great diagnostic @giovanni111 , that saved me a lot of time! Your analysis and proposed solution both make sense to me, and I made a minimal PR that implements them, by whitelisting `.ldf` files for being loaded as many times as requested. Now at #1361 , for the consideration of @brucemiller who may or may not like the solution approach :>
