### ISSUE TITLE
Beware of strange \lstinline escaping inside captions

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#1377]
Try this, and compare the normal pdfLaTeX output with the LaTeXML output:
```tex
\documentclass{article}
\usepackage{listings}
\begin{document}
\begin{table}
\caption{Inside a caption, \lstinline!lstinline! is a bit of a mess, so beware of extra backslashes in its arguments.
For example, braces will appear escaped: \lstinline!\{ \}!.
Another example is the backslash itself: \lstinline!\\sin!.}
\end{table}
\end{document}
```

Note that `\lstinline` behaves a bit odd (to people like myself who lack the proper LaTeX intuition) inside `\caption`, so the argument to `\lstinline` needs some kind of different processing of the backslash here.

What I see – using version 0.8.4 – is that the backslash gets processed as if it wasn't inside a caption, causing spurious backslashes in the output.

**Comment by brucemiller** [comment]
The `\lstinline` is not what the LaTeX folks call "robust", since it has 
to change character catcodes to work (like `\verb`).  The argument 
to`\caption` is called a "moving" argument, since it gets read in 
(tokenized, and catcodes assigned) before it gets used (and reused in 
TOC, etc).  So the rule is that you can only use robust commands in 
moving arguments, otherwise they won't be able to adjust catcodes as needed.

Actually, with your example, I have pdflatex giving errors (not just 
weird output).   With LaTeXML, we don't try as hard to emulate errors.

**Comment by henrikt-ma** [comment]
I get your point.  It's a bit unfortunate that the [_listings_ documentation](https://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/listings/listings.pdf) has the section 5.1 _Listings inside arguments_ that basically makes it a documented – albeit not recommended – workaround to put a backslash in front of certain characters.

**Comment by henrikt-ma** [comment]
> Actually, with your example, I have pdflatex giving errors (not just weird output). With LaTeXML, we don't try as hard to emulate errors.

With the installation I am having at the moment, I also get an error:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/MacPorts 2019.50896_2) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./mini.tex
LaTeX2e <2018-12-01>
(/opt/local/share/texmf-texlive/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/opt/local/share/texmf-texlive/tex/latex/base/size10.clo))
(/opt/local/share/texmf-texlive/tex/latex/listings/listings.sty
(/opt/local/share/texmf-texlive/tex/latex/graphics/keyval.sty)
(/opt/local/share/texmf-texlive/tex/latex/listings/lstmisc.sty)
(/opt/local/share/texmf-texlive/tex/latex/listings/listings.cfg)) (./mini.aux)
! Undefined control sequence.
\\->\let \reserved@e
                     \relax \let \reserved@f \relax \@ifstar {\let \reserved...
l.7 ...s the backslash itself: \lstinline!\\sin!.}
```

However, this is an older version compared to the installation used when reporting the issue:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/MacPorts 2020.54632_2) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./minimal.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>
(/opt/local/share/texmf-texlive/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/opt/local/share/texmf-texlive/tex/latex/base/size10.clo))
(/opt/local/share/texmf-texlive/tex/latex/listings/listings.sty
(/opt/local/share/texmf-texlive/tex/latex/graphics/keyval.sty)
(/opt/local/share/texmf-texlive/tex/latex/listings/lstmisc.sty)
(/opt/local/share/texmf-texlive/tex/latex/listings/listings.cfg))
(/opt/local/share/texmf-texlive/tex/latex/l3backend/l3backend-pdfmode.def)
No file minimal.aux.
(/opt/local/share/texmf-texlive/tex/latex/base/omscmr.fd) [1{/opt/local/var/db/
texmf/fonts/map/pdftex/updmap/pdftex.map}] (./minimal.aux) )</opt/local/share/t
exmf-texlive/fonts/type1/public/amsfonts/cm/cmr10.pfb></opt/local/share/texmf-t
exlive/fonts/type1/public/amsfonts/cm/cmsy10.pfb>
Output written on minimal.pdf (1 page, 23835 bytes).
Transcript written on minimal.log.
```

**Comment by brucemiller** [comment]
Darn! I thought I'd tested against texlive 2020 as well.  That makes it harder to justify inaction :<

**Comment by henrikt-ma** [comment]
Harder, but not impossible, I suspect. :)  The general reasoning about fragile commands still sounds rather convincing to me.

Either way, it would be very interesting to understand what difference between 2019 and 2020 that makes it work in 2020.

I should also mention that I am also able to build our real document with the 2019 version, but I don't have a minimal example for this.  Maybe _captions.sty_ could have something to do with it…
