### ISSUE TITLE
Support split-level/beveled fractions from xfrac.sty.

### ISSUE THREAD

**Issue by krivit** [brucemiller/LaTeXML#1379]
[`xfrac.sty`](https://ctan.org/pkg/xfrac?lang=en) implements what it calls "split-level" and what MathML calls "beveled" fractions https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfrac). As far as I can tell, one can render them just by specifying `<mfrac bevelled="true">`.

**Comment by brucemiller** [comment]
Interesting, that the MathML refresh effort was wondering if anybody 
even used that ... and concluding: probably not.

There is already a LaTeXML implementation of the same functionality in 
`nicefrac`.  Can probably clone that to produce a quick version of 
`xfrac`, but without all the bells, whistles and options (at least, not yet)

**Comment by krivit** [comment]
On further reading, it looks like the `bevelled="true"` setting is deprecated in MathML. I am not sure how it's supposed to be implemented, then.

**Comment by brucemiller** [comment]
Oh! This actually got done awhile back, I just forgot to close the issue.

And actually, I'd already  worked around the `bevelled` attribute anyway (since it was inconsistently supported). The trick is simply an inline `x/y`, but with a bit of positioning tweaks.

Thanks for the report!
