### ISSUE TITLE
Line break deactivation on long equations

### ISSUE THREAD

**Issue by luclaurent** [brucemiller/LaTeXML#1393]
I observe that LaTeXML breaks line on very long equation and add `%` at the end of the line before the break. Is there any possibility to deactivate this feature? I do not find the solution in the documentation.

**Comment by dginev** [comment]
This is a common issue for unsuspecting users of the `tex` attribute/annotations in math formulas, and has also been encountered by the arxiv-vanity folks [engrafo #523](https://github.com/arxiv-vanity/engrafo/issues/523).

I believe we currently don't have an option to disable that feature (which @brucemiller is fond of), but I continue to advise a regex that replaces the offending characters, as `%\n` is an unambiguous selector.

**Comment by luclaurent** [comment]
OK thanks, I will consider your regex's proposition.

**Comment by dginev** [comment]
To bookkeep some more, I tracked down the first time I stepped on this landmine back in 2013, also recorded in the issues here at [#437](https://github.com/brucemiller/LaTeXML/issues/437). 

At the present date, I am likely of the opinion that the added percent signs will be a surprise gotcha for anyone who uses this attribute expecting the original TeX. And should at the least be documented in some clear fashion as visibly as possible. But I am also quite happy to defer to Bruce for any official decisions.

**Comment by dginev** [comment]
Note that we had another complained for this filed in #1504, now closed as a duplicate.

**Comment by rgieseke** [comment]
Sorry for the dupe!
Another alternative to the alttext could also be to put the original TeX math in a `<tex-math>` element (in JATS):
```xml
<disp-formula id="eq_002">
<label>(2)</label>
<alternatives>
<mml:math>
<mml:mstyle displaystyle="true" scriptlevel="0">
<mml:mi mathvariant="normal">&Delta;</mml:mi>
<mml:mi>x</mml:mi>
<mml:mi mathvariant="normal">&Delta;</mml:mi>
<mml:mi>p</mml:mi>
<mml:mo>&ge;</mml:mo>
<mml:mfrac>
<mml:mn>1</mml:mn>
<mml:mn>2</mml:mn>
</mml:mfrac>
<mml:mi class="MJX-variant">&hbar;</mml:mi>
</mml:mstyle>
</mml:math>
<tex-math><![CDATA[\displaystyle \Delta x \Delta p \geq \frac{1}{2} \hbar]]></tex-math>
</alternatives>
</disp-formula>
```
https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/tex-math.html

**Comment by Artoria2e5** [comment]
The more MathML-correct way to do something similar to `<tex-math>` would be adding an element of `<annotation encoding="application/x-tex">` under `<math>`. Compared to alttext, having a distinct element would be less ambiguous (as to the encoding) and more conducive to including arbitrary text.

**Comment by dginev** [comment]
This issue is either an easy change or a wontfix, depending on whether @brucemiller still wants to keep the `\%\n` in reversions of long formulas.

Given that it's confusing for a variety of users, I would naively lean towards not using that at all, or have it disabled by default etc.

**Comment by flyn-org** [comment]
In my use of LaTeXML, I find long lines that make use of \lstinline{} contain a literal '%' character in the XML, but no '\n'. The '%' always appears at the same column. Is this related?

**Comment by brucemiller** [comment]
Actually, I'm a bit perplexed why this is a problem.  The TeX code is valid (or is intended to be), if you want to use it as TeX.  If you want to use it for some other purpose, why wouldn't you expect to filter it?
 Of course the TeX code is pretty lousy `alttext` in any case. 

For background, the feature was requested by a user who counts more than most of us, so it isn't going away by default.

@flyn-org I'm not sure about how this plays in `\lstinline`; do you have an example?
