### ISSUE TITLE
Listings and hyphens

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1399]
TeX, listings, and hyphens occasionally have trouble working together.  In shell languages and Prolog (among others, probably), multiple hyphens appear to run together into a single line (but are actually separate characters).  In C style syntaxes, there's some slight separation.

One fix for this problem is suggested at https://tex.stackexchange.com/a/282317/107497 which suggests separating these by (ab)using the option `literate={-}{-}1` (which means "replace `-` by `-`, where the latter is 1 character long").

LaTeXML, listings, and hyphens are having even more trouble.  It appears that hyphens follow the usual "2 become en-dash, 3 become em-dash" rule, which doesn't make sense for code listings.  It also appears that listings is not following the literate key.

The following code
``` tex
\documentclass{article}
\usepackage{listings}
\begin{document}

\begin{lstlisting}[language=C]
i--;
\end{lstlisting}

\begin{lstlisting}
latexml runtogether --dest=runtogether.xml
\end{lstlisting}

\begin{lstlisting}[literate={-}{-}1]
latexml runtogether --dest=runtogether.xml
\end{lstlisting}

\begin{lstlisting}[literate={fails}{succeeds}8]
literate fails
\end{lstlisting}

\end{document}
```
Produces the pdf
![Screen Shot 2020-11-27 at 7 24 14 PM](https://user-images.githubusercontent.com/13021169/100491049-7183b380-30e6-11eb-8fd2-9eaf6893c295.png)
(the second line of the output has two separate hyphens with no separation).  But LaTeXML produces the html
```
i–;
latexml runtogether –dest=runtogether.xml
latexml runtogether –dest=runtogether.xml
literate fails
```
(with 3 en-dashes).  `grep -ic` tells me that `literate` only occurs 14 times in my TeX style files, so it's possible that it's not too big of a fix.  I'm not sure how we would fix the hyphens in general.  On the other hand, if we can fix the hyphens in general, that would remove the need to (ab)use literate, since html wouldn't run them together in the first place.

**Comment by brucemiller** [comment]
The ligatures of hyphens is disabled for typewriter font. Personally, I find most code listings more readable in tt anyway, but that's a taste issue, I guess.
