### ISSUE TITLE
latexmlpost --format=xml does not seem to convert <Math> to MathML

### ISSUE THREAD

**Issue by nxg** [brucemiller/LaTeXML#1402]
The documentation for the `--format=xml` option says:

> For the default, xml, the output is left in LaTeXML’s internal xml, but the math is parsed and converted to presentation MathML.

However this doesn't appear to happen in fact.

For example:

    % cat try.tex
    \documentclass{book}
    \title{A book}
    \author{By me}
    \begin{document}
    \maketitle

    Hello, here is an equation: $E=mc^2$.
    \end{document}
    % latexml --dest=try.lxml try.tex
    latexml (LaTeXML version 0.8.4)
    ...
    % latexmlpost --format=xml --destination=try.xmlout try.lxml
    latexmlpost (LaTeXML version 0.8.4)
    ...
    % grep Math try.xmlout
    <p>Hello, here is an equation: <Math mode="inline" tex="E=mc^{2}" text="E = m * c ^ 2" xml:id="p1.m1" fragid="p1.m1">
        <XMath>
        </XMath>
      </Math>.</p>
    %

Using `--format=xhtml` does work as expected, so I don't think this is pointing to some grievous breakage in my installation (most recent version from macports).

My use-case here is that I (probably) want to use my own stylesheets to convert from the LaTeXML internal format to XHTML, but with the conversion to MathML done for me (the reason for that is that the conversion with `--format=xhtml` does 95% of what I want – LaTeXML is a wonderful piece of work! – but the last 5% is dissolving into a mess of special cases, which are messy enough that I suspect it'd be easier overall if I start my post-post-processing a little earlier in the toolchain).

**Comment by dginev** [comment]
Indeed, `--format=xml` does not _imply_ a math post-processor at the moment. You need to choose one explicitly by specifying one or more of: `--pmml`, `--cmml`, `--mathimages`, `--openmath`, `--mathtex`. 

If you specify multiple ones the first is considered primary and the rest are added as parallel annotations, so it is common to start with `--pmml`.

**Comment by dginev** [comment]
In my own mind I am used to expecting a simple pass-forward of latexml's XMath when using just `--format=xml`, so I am even wondering if in this case we should update the documentation to explicitly say that and require a `--pmml` switch for that format.

As to your use case @nxg , having your own set of stylesheets could be quite rewarding. If you're generating a standard output, it may even be interesting for us to see if we can add another format for latexml and include your work (this is e.g. the way we had the JATS and TEI outputs contributed to us).

We have been meaning to standardize a customization capability for user-defined formats e.g. in #1212 , but that's still future work to get back to.

**Comment by nxg** [comment]
Aha – that works beautifully.  I had seen the `--pmml` and related options, but put them aside, in my head, as being for possible later tuning.

I think it would indeed be worth a slight tweak to the documentation.  How about:

> For the default, xml, the output is left in LaTeXML’s internal xml, but the math may be parsed and converted to presentation MathML, if requested by `--presentationmathml` and related options.

Background: The format I'm working with is not a standard one, but a custom one of my own for lecture-notes, which is probably a good way away from being more broadly useful (but never say never...).  In this particular case, I'm experimenting with making an EPUB version of notes which are primarily targeted at PDF.  The LaTeX I'm passing in to LaTeXML is itself generated from source which has XML for the structuring and moving content, but which has most of the paragraph-level formatting, and all of the maths, in LaTeX.  LaTeXML's split-out XHTML output is _almost_ there, but getting the last bits of structural information from the source to the output, through multiple changes of format, has been a bit tricky (ie, descending into hacks); hence the Plan B of generating the final output from LaTeXML's schema, which is, crucially, after the _hard_ bit of parsing the LaTeX.  Since there's quite a lot of XSLT floating around this project anyway, this is a relatively natural strategy for my case.

If there's anything else about this that it would be useful for me to add or expand upon, do say.

(I'll just take this opportunity to say: thank you – I think I've been waiting for LaTeXML for about 30 years...)

**Comment by nxg** [comment]
As a footnote to this, I'll mention that I did also implement a pipeline for going to EPUB from the LaTeXML XHTML output (ie, Plan A, distinct from the Plan B mentioned above).  The LaTeXML output _almost_ satisfies the W3C EPUB validator, requiring only modest normalisation.  I posted the script I use to do that normalisation at https://lists.informatik.uni-erlangen.de/pipermail/latexml/2021-January/002497.html

**Comment by nxg** [comment]
The normalisation script is included in issue #1440
