### ISSUE TITLE
Add latexmlpost exit codes

### ISSUE THREAD

**Issue by epifanovsky** [brucemiller/LaTeXML#1417]
Executing `latexmlpost` from a shell script always returns 0, which prevents one from handling failures. This can be trivially resolved by exiting with a status code at the end of `latexmlpost`.

```
diff --git a/bin/latexmlpost b/bin/latexmlpost
index 20eda2fa..7294466c 100755
--- a/bin/latexmlpost
+++ b/bin/latexmlpost
@@ -461,6 +461,7 @@ print STDERR $@ if $@;
 my $code = $latexmlpost->getStatusCode;
 print STDERR "\nPostprocessing " . ($code == 3 ? 'failed' : 'complete') . ": " . $latexmlpost->getStatusMessage . "\n";
 print STDERR "processing " . ($code == 3 ? 'abandoned' : 'finished') . " " . localtime() . "\n" if $verbosity > -1;
+exit $code;

 #======================================================================
 # helpers
```

**Comment by dginev** [comment]
Thanks for the report! Seems reasonable from a shell scripting perspective.

**Comment by dginev** [comment]
We may want to double-check `latexmlc` and `latexmlmath` while we're at it. I recall we had an issue fine-tuning this for the main `latexml` process in #1208
