### ISSUE TITLE
\text supported ?

### ISSUE THREAD

**Issue by kzakza** [brucemiller/LaTeXML#1437]
Hi, 

I tried to convert  a single formula to MathML by using LaTeXML and gets an error as below( Inside "`\text`" are Japanese words).

command
`$ latexmlmath --pmml=- "\[\text{z得点}=\frac{\text{データの値} - \text{平均値}}{\text{標準偏差}}\]"`

output and error
> Error:undefined:\text The token T_CS[\text] is not defined.
>         at String; line 6 col 7 - line 6 col 7
>         Defining it now as &lt;ltx:ERROR/&gt;
>         In Core::Stomach[@0x5735b08] Literal String; from line 6 col 7 to line 6 col 7
>          &lt;= Core::Definition::Constructor[\[] &lt;= Core::Stomach[@0x5735b08] &lt;= ...
> &lt;?xml version="1.0" encoding="UTF-8"?&gt;
> &lt;math xmlns="http://www.w3.org/1998/Math/MathML" alttext="\text{z得点}=\frac{\text{データの値}-\text{平均値}}{\text{標準偏差}}" display="block"&gt;
>   &lt;mrow&gt;
>     &lt;mrow&gt;
>       &lt;merror class="ltx_ERROR undefined undefined"&gt;
>         &lt;mtext&gt;\text&lt;/mtext&gt;
>       &lt;/merror&gt;
>       &lt;mo&gt;?&lt;/mo&gt;
>       &lt;mi&gt;z&lt;/mi&gt;
>       &lt;mo&gt;?&lt;/mo&gt;
>       &lt;mi mathvariant="normal"&gt;得&lt;/mi&gt;
>       &lt;mo&gt;?&lt;/mo&gt;
>       &lt;mi mathvariant="normal"&gt;点&lt;/mi&gt;
>     &lt;/mrow&gt;
>     &lt;mo&gt;=&lt;/mo&gt;
>     &lt;mfrac&gt;
>       &lt;mrow&gt;
>         &lt;mrow&gt;
>           &lt;merror class="ltx_ERROR undefined undefined"&gt;
>             &lt;mtext&gt;\text&lt;/mtext&gt;
>           &lt;/merror&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;デ&lt;/mi&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;ー&lt;/mi&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;タ&lt;/mi&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;の&lt;/mi&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;値&lt;/mi&gt;
>         &lt;/mrow&gt;
>         &lt;mo&gt;-&lt;/mo&gt;
>         &lt;mrow&gt;
>           &lt;merror class="ltx_ERROR undefined undefined"&gt;
>             &lt;mtext&gt;\text&lt;/mtext&gt;
>           &lt;/merror&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;平&lt;/mi&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;均&lt;/mi&gt;
>           &lt;mo&gt;?&lt;/mo&gt;
>           &lt;mi mathvariant="normal"&gt;値&lt;/mi&gt;
>         &lt;/mrow&gt;
>       &lt;/mrow&gt;
>       &lt;mrow&gt;
>         &lt;merror class="ltx_ERROR undefined undefined"&gt;
>           &lt;mtext&gt;\text&lt;/mtext&gt;
>         &lt;/merror&gt;
>         &lt;mo&gt;?&lt;/mo&gt;
>         &lt;mi mathvariant="normal"&gt;標&lt;/mi&gt;
>         &lt;mo&gt;?&lt;/mo&gt;
>         &lt;mi mathvariant="normal"&gt;準&lt;/mi&gt;
>         &lt;mo&gt;?&lt;/mo&gt;
>         &lt;mi mathvariant="normal"&gt;偏&lt;/mi&gt;
>         &lt;mo&gt;?&lt;/mo&gt;
>         &lt;mi mathvariant="normal"&gt;差&lt;/mi&gt;
>       &lt;/mrow&gt;
>     &lt;/mfrac&gt;
>   &lt;/mrow&gt;
> &lt;/math&gt;

latexml.mathweb.org seems to support "`\text`"  and worked as desired.

Your advice would be much appreciated.

**Comment by dginev** [comment]
For latexmlmath you need to also add the `--preload=amsmath.sty` to enable the `\text` macro which isn't part of the default LaTeX macros.

The latexml.mathweb.org showcase is using a rough equivalent to:
```
latexmlc --profile=math 'literal:\[\text{z得点}=\frac{\text{データの値} - \text{平均値}}{\text{標準偏差}}\]'
```

which loads a lot more secondary packages and also generates multiple additional math formats. Let us know if this helps!

**Comment by kzakza** [comment]
Commands you propesed works for me. Thanks for such a prompt response @dginev!
