### ISSUE TITLE
Spelling errors in source code

### ISSUE THREAD

**Issue by hpreusse** [brucemiller/LaTeXML#1438]
The Debian lintian program detected a few spelling errors in the source code. I created [a patch](https://sources.debian.org/data/main/l/latexml/0.8.5-1/debian/patches/spelling_errors) for this, consider to apply it to your repository. Thanks!

**Comment by dginev** [comment]
Thanks for the cleanup! Any reason you didn't do a:
```
git checkout -b spelling-errors
git add --all
git commit -m 'fix some spelling errors'
git push
```

and open a PR? Would have been quite easy on both sides to merge that in. But we can use the patch as well, no problem, just wondering whether you're encountering any issues with github pull requests.

**Comment by hpreusse** [comment]
> Thanks for the cleanup! Any reason you didn't do a:
> 
> ```
> git checkout -b spelling-errors
> git add --all
> git commit -m 'fix some spelling errors'
> git push
> ```
> 
I'm not familiar yet with this kind of work flow. Will use it next time. Thanks!
