### ISSUE TITLE
download button in listings needs download attribute

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1450]
The download button for listings has stopped working for a while, since browsers stopped allowing navigation to data URLs [1]. I figure the appropriate solution is to add the empty `download` attribute to tell the browser to download the content, rather than navigating to it [2].

I suppose it would be even better to use the actual file name when it is available (i.e. when using `\lstinputlisting`).

[1] [Data URLs - HTTP | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)
[2] [HTML Standard](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-download)

**Comment by dginev** [comment]
was fixed by #1451 but remained open, closing
