### ISSUE TITLE
Add support for kvoptions.sty

### ISSUE THREAD

**Issue by Jazzpirate** [brucemiller/LaTeXML#1453]
Both are defined in `latex.ltx`, the latter is a simple helper macro which is occasionally used in packages, the former is redefined by `\ProcessOptions` in packages

**Comment by dginev** [comment]
The big question is whether you're relying on these in the option-passing logic. Latexml implements its own binding for `\ProcessOptions`, so ideally these internals would never get triggered and reported as errors.

Adding the empty stubs for them is easy, but making that `\ProcessOptions` call may be trickier, depending on what/how is redefining it. It may be a good idea to lock the `DefPrimitive('\ProcessOptions ` in LaTeX.pool while we're at it.

Would be nice to have a file to test with though.

**Comment by Jazzpirate** [comment]
ok, on further investigation: The problem is the kvoptions package, whose \ProcessKeyvalOptions-method uses \@unusedoptionlist. It claims (quote documentation) "A class puts not used options in the unused option list unless there is a defaulthandler." So the actual culprate might be `\documentclass`...?

**Comment by dginev** [comment]
Alright, unsupported package, make this a lot easier to think about, thanks.

**Comment by brucemiller** [comment]
LaTeXML now has support for `kvoptions`, so maybe this works for your usecase?  If not, please open a new issue, with details. Thanks!
