### ISSUE TITLE
Web2C-compliant line-breaks in Mouth?

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1467]
This bug is... irrelevant, because it is triggered only by files with spurious carriage returns next to single CRLF's, and that's hardly going to happen in real life. I only stumbled upon it by reading `Mouth.pm`.

If you run `latexml` on [this attachment](https://github.com/brucemiller/LaTeXML/files/5991393/MWE-wrong-newline-split.tex.zip), you will get
```xml
  <para xml:id="p1">
    <p>Line 1.
Line 2.</p>
  </para>
```
instead of the 'correct'
```xml
  <para xml:id="p1">
    <p>Line 1.</p>
  </para>
  <para xml:id="p2">
    <p>Line 2.</p>
  </para>
```

The cause is the use of both Perl's own `readline` as well as `split`, which has a peculiar behaviour with trailing empty records. I am already working on a fix as a Perl & LaTeXML internals learning exercise - I think I can simplify some bits of the mouth, which is probably worth doing anyway.

Edit: more [realistic example](https://github.com/brucemiller/LaTeXML/files/5998362/MWE.zip) with classic mac newlines from the included file getting discarded.

**Comment by dginev** [comment]
Rather than an attachment, you can inline it:
```tex
\documentclass{article}
\begin{document}
Line 1.

Line 2.
\end{document}
```

However, I can't reproduce what you're referring to. Running with the latest latexml creates:
```xml
  <para xml:id="p1">
    <p>Line 1.</p>
  </para>
  <para xml:id="p2">
    <p>Line 2.</p>
  </para>
```

i.e. the "correct" version

**Comment by dginev** [comment]
Oh I see, which characters exactly are in the line-break in the attached file? Even copy-paste ends up correcting them to `\n`. And indeed, quite a rare setup - I'm curious how you stumbled upon this?

**Comment by xworld21** [comment]
> Oh I see, which characters exactly are in the line-break in the attached file?

The bad sequence is `\r\r\n`: Perl passes the entire line (terminated by `\r\n`) to the mouth, and the mouth uses `split` on `\r\n|\r|\n`, but `split` discards the trailing empty strings, so the extra newline is lost.

> And indeed, quite a rare setup

A maybe existing in real life after all. I have made a more realistic MWE where a file `input`'s another one written in classic Mac style (carriage returns only). The trailing carriage returns in the included files are discarded by LaTeXML even though they should produce a `\par`. No system writes files like that any more, but I bet you could find some old ones on arXiv.

> I'm curious how you stumbled upon this?

I was trying to get rid of string modifications in the mouth related to newlines (some repeated adding and removing carriage returns which seemed wasteful), but I couldn't make sense of the code, until I realised it wasn't doing what TeX does!
