### ISSUE TITLE
latexml support for printglossary

### ISSUE THREAD

**Issue by aivokalu** [brucemiller/LaTeXML#1468]
Hello. 

I’m trying to use LaTeX `glossaries` package to manage the definitions and terms and also to convert the .tex into the .html and other formats with help of LaTeXML. It seems that while LaTeXML does have support for the glossaries package, the `\printglossary{}` command doesn’t seem to work. 

I’m using latest latexml (github master HEAD) and the `perl -Mblib t/50_structure.t` gives following output: 
```
   ...
   ok 29 - t/structure/glossary
   ...
```

So, it should be functioning well. When I take the example test file `t/structure/glossary.tex` and try to produce PDF output with pdflatex, everything seems to work fine. Terms are printed inside the text and there’s the “Glossary” section as well. However, when I try to produce the HTML output with following commands: 

```
latexml --destination=output/glossary-test.xml glossary-test.tex
latexmlpost --verbose --verbose --prescan --split --splitat=chapter --dbfile=building/glossary-test.dbfile --destination=output/website/index.html output/glossary-test.xml
latexmlpost --verbose --verbose --dbfile=building/glossary-test.dbfile --format=html --graphicimages --split --splitat=chapter --urlstyle=file --navigationtoc=context --destination=output/website/index.html --css=LaTeXML-navbar-left.css -css=LaTeXML-blue.css output/glossary-test.xml
```

The documentation is a bit lacking about how the TeX document with glossaries should be actually converted with LaTeXML, commands are kind of trial-and-error and perhaps I’m missing something? Please advise, what is the correct way to use LaTeXML in this case?

During the conversion, I currently get following warnings: 

```
latexmlpost (LaTeXML version 0.8.5; revision 848cef00)
processing started Fri Feb 19 11:09:03 2021
(post-processing...
(Split index.html processing...[not split] 0.00 sec)
(Scan index.html processing... [DBStatus: 14/14 objects] 0.00 sec)
(CrossRef index.html processing... [Filled in 14 glossaryrefs] [Filled in 1 TOCs] [Filled in fragment 6 ids] [Filled in 0 refs] [Filled in 0 RDFa refs] [Filled in 0 bibrefs] [Filled in 0 math links]
Warning:expected:ids Missing items:
	  Glossary () Entry for key: svm, potato, carrot, fishage, cabbage
	In Post::CrossRef[@0x7fe7f15c6f58] ->process
 0.00 sec)
(XSLT[using LaTeXML-html5.xsl] index.html processing... 0.00 sec)
(Writer index.html processing... 0.00 sec) 0.01 sec)
Postprocessing complete: 1 warning
processing finished Fri Feb 19 11:09:03 2021
INFO: latexmlpost/website finished with 0
```

and the index.html doesn’t have glossary entries printed. It just has an empty section: 

```
   …
   <section class="ltx_glossary ltx_list_main">
   </section>
   …
```

XML output file has the following empty section: 

```
   ... 
   <!--  %“printglossaries -->  <glossary lists="main"/>
   …

```
I have looked at https://github.com/brucemiller/LaTeXML/issues/682#issuecomment-574749064 and https://github.com/brucemiller/LaTeXML/pull/1086#issuecomment-529682644. It seems that there’s some ongoing work on this feature? 

Perhaps it might be useful to share the current state of code (in a separate branch?), even if it is not complete, so that other people could take a look and perhaps contribute?

**Comment by brucemiller** [comment]
Ah, this should also be fixed in #1908. Thanks for the report!
