### ISSUE TITLE
Question concerning dates

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1478]
I would appreciate some advice on the best way to stop document publication dates tags (`<div class="ltx_dates">`) being included on each page (except the topmost page, where I want to keep them) of a collection  of HTML pages obtained by converting to HTML and splitting a document with `latexmlpost` and LaTeXML 0.8.5. I have noticed that the part of XSLT sheet LaTeXML-structure-xhtml.xsl handling dates has changed since LaTeXML 0.8.2, and I thought of reverting to the code from LaTeXML 0.8.2, but am not sure if it would cause some undesirable effects elsewhere. Thanks

**Comment by goska** [comment]
Of course, the dates could be hidden in HTML with CSS, but the objective would be not to have (or have an option not to generate) these tags in sub-pages. The dates do not show on subpages generate with LaTeXML 0.8.2, because tag dates are empty. 
I forgot to add that I am working using report document class.

**Comment by dginev** [comment]
Thanks for reporting this @goska ! Sounds like a good case for a dedicated `--xsltparameter` to me, which may control a variety of date positioning details in the final format.

**Comment by goska** [comment]
Just in case someone else is facing the same problem, I have solved it for myself by making a modification in `LaTeXML-structure-xhtml.xsl`. In `maketitle` template I have made the call to `dates` template conditional by enclosing it with `xsl:if`:
```
<xsl:if test="(parent::ltx:document)">
      <xsl:call-template name="dates">
        <xsl:with-param name="context" select="$context"/>
        <xsl:with-param name="dates" select="../ltx:date"/>
      </xsl:call-template>
</xsl:if>
```

**Comment by evoludolab** [comment]
I was just about to open an issue regarding spurious dates after chapter headings when using ``splitat``. Fortunately I stumbled across this issue first - thanks for the simple workaround/solution!
