### ISSUE TITLE
TikZ shading stuck on first color

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1479]
This is a followup to #1168, where I've been trying to use TikZ's shading in my drawings.  It seems that we no longer have the fatal error thanks to #1360, but LaTeXML can't change the shading color.  With the following example:

``` tex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\tikz{\shadedraw[{left color}=blue](0,0)--(0,20pt)--(20pt,20pt)--(20pt,0)--cycle;}
\tikz{\shadedraw[{left color}=red](0,0)--(0,20pt)--(20pt,20pt)--(20pt,0)--cycle;}
\tikz{\draw[fill=red](0,0)--(0,20pt)--(20pt,20pt)--(20pt,0)--cycle;}
\tikz{\shadedraw[color=red](0,0)--(0,20pt)--(20pt,20pt)--(20pt,0)--cycle;} 
\tikz{\draw[{right color}=red](0,0)--(0,20pt)--(20pt,20pt)--(20pt,0)--cycle;}
\end{document}
```

I get the pdf:
![texOutput](https://user-images.githubusercontent.com/13021169/110033841-84b6a880-7cff-11eb-915d-a609fe58adb9.png)

But the html:
<img width="163" alt="LaTeXMLoutput" src="https://user-images.githubusercontent.com/13021169/110033498-1671e600-7cff-11eb-90d4-60db340564c6.png">

It looks like `\draw[fill]` is ok, but `\shadedraw` and `\draw[{left color}]` use whatever the first shading color happened to be.

**Comment by dginev** [comment]
Good to be reminded of the problem and with a new example, thanks @teepeemm ! Bruce has been looking into tikz upgrades recently, and landed quite a few, so we're definitely closer than before to working our way to this coloring problem.
