### ISSUE TITLE
\big(vee|wedge|otimes|...) are rendered with a non-optimal character

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1502]
Now that I have noticed, I can't unsee it: operators like `\bigvee`, `\bigwedge`, `\bigotimes` are rendered as `\vee`, `\wedge`, `\otimes` with an extra `mathsize="160%"`, but they have their own native Unicode 1.1 counterparts, and those render better.

I suspect this affects many/all of the "n-ary" characters (e.g. in [this list](https://www.fileformat.info/search/google.htm?q=n-ary&domains=www.fileformat.info&sitesearch=www.fileformat.info&client=pub-6975096118196151&forid=1&channel=1657057343&ie=UTF-8&oe=UTF-8&cof=GALT%3A%23008000%3BGL%3A1%3BDIV%3A%23336699%3BVLC%3A663399%3BAH%3Acenter%3BBGC%3AFFFFFF%3BLBGC%3A336699%3BALC%3A0000FF%3BLC%3A0000FF%3BT%3A000000%3BGFNT%3A0000FF%3BGIMP%3A0000FF%3BFORID%3A11&hl=en), although I am sure there are better references). I assume all the good fonts (MathJax TeX, STIX2, etc.) have 100% coverage of those.

Unless there is a strong backward compatibility reason, I'll start removing all the `mathsize`'s which can be done directly in Unicode. I hope it's not that many!

**Comment by xworld21** [comment]
Some notes. The Unicode characters are in fact [correct](https://github.com/brucemiller/LaTeXML/blob/adbaf8955146f858d08a970722215ddad192e8ec/lib/LaTeXML/Package/TeX.pool.ltxml#L5483), the problem comes from the additional `font => { size => 'Big' }`. I think I understand why it's there: non-specialist fonts are not consistent with n-ary operators, witness &#x2229; vs &#x22C2;, &#x2228; vs &#x22C1;, so the extra `size` helps. On the other hand, STIX behaves properly (e.g. check [here](https://fonts.adobe.com/fonts/stix#fonts-section)) and the `Big` size kind of breaks the output. Likewise for MathJax.

**Comment by dginev** [comment]
Aha, so _it was fonts all along_ ! That sounds more familiar now. I suppose the less intrusive style would be to move this sizing information to the CSS files, so as to make it clear you can override it when changing to a different font than the one LaTeXML is defaulting to?

**Comment by xworld21** [comment]
For what it's worth, I really like the idea of saving the information in a CSS class, so it's not lost, but can be manipulated easily. Especially if MathJax ignores the additional classes, that would be great.

The documentation should explain this somewhere, though. In fact, assuming CSS can set the fonts for the MathML tags why not add an optional `LaTeXML-math-fonts.css` that sets good fonts? With the documentation suggesting some links to where the fonts can be downloaded/imported (see e.g. [1] for a starting point).

> LaTeXML / mainstream browsers are defaulting to

I don't think there is a true default, though. The browser I am writing from shows `\vee` as _bigger_ than `\bigvee`, my laptop shows them as almost equal (both in Chrome!).

[1] https://trac.webkit.org/wiki/MathML/Fonts

**Comment by xworld21** [comment]
Quick report. The good news, browsers already default to reasonable fonts for MathML, no need for an optional CSS (for html output, at least). The bad news, the fonts are not as good as they should be!

I tested Safari, Firefox, and Chrome+MathJax, and both mess up `\bigodot`, `\bigotimes`, `\bigoplus`. `\biguplus` is better in Firefox than Safari. But the others look fine.

Better if you check [bigop-test.zip](https://github.com/brucemiller/LaTeXML/files/6207708/bigop-test.zip) yourself on your own browsers/devices, written without the `mathsize` attribute, you might see something different.

**Comment by xworld21** [comment]
With apologies to the font makers, it turns out it actually was LaTeXML after all. In short: some characters (`\bigvee`, `\bigwedge`, etc.) are correct, but are disproportionately large because of `size => 'Big'`; other characters are outdated (`\bigoplus` is the same as `\oplus`) and must use `size => 'Big'` unless updated.

This is a new example [bigop-test.zip](https://github.com/brucemiller/LaTeXML/files/6214037/bigop-test.zip), generated with the updated characters in `TeX.pool` and without the `size` attribute. It looks good to me in all the browsers. The EPUB is disastrous on my pretty modern Kobo, which does not even do `\bigvee` (Unicode 1.1!), nor plane 1, but I want to test embedding a modern font before drawing any conclusions.

BTW the 'new' characters are in the [Supplemental Mathematical Operators](https://en.wikipedia.org/wiki/Supplemental_Mathematical_Operators) block since Unicode 3.2 (2002, and in the BMP).

**Comment by brucemiller** [comment]
This kind of weirdness demonstrates why it's usually best to avoid special css (or other) hacks to get things to look right, because eventually the browsers do things right, and now your output looks wrong. But of course, we still do the hacks sometimes. :>
