### ISSUE TITLE
Newline from long formula and `tex`/`alttext` attribute

### ISSUE THREAD

**Issue by rgieseke** [brucemiller/LaTeXML#1504]
For a long formula LateXML inserts a linebreak and percent sign `%\n` into the `tex` (or for jats-xml `alttext`) field:

E.g. as a reproducible example in LaTeX:

```latex
\documentclass{article}

\begin{document}

$ b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 = b^2 $

\end{document}
```

Output from `latexml`:
```xml
...
<para xml:id="p1">
    <p><Math mode="inline" tex="b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=b^{2}=%&#10;b^{2}" text="b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2 = b ^ 2" xml:id="p1.m1">
        <XMath>
...
```

Is it possible to prevent this `%&#10;` from being inserted, it breaks later rendering with Katex for example.

**Comment by dginev** [comment]
This is a very common issue that people stumble on, and we've had several prior open tickets:
- mine from back in year 2013: #437
- the currently open one from 2020 at #1393

I will close here as a duplicate, but we can bookkeep yet _another_ latexml user has been ambushed by this behavior.
