### ISSUE TITLE
Unintentional Bolding in Tabular Rows

### ISSUE THREAD

**Issue by yatescr** [brucemiller/LaTeXML#1512]
It appears that using math in rows of a tabular environment causes unintentional bolding. Below is an example.Compiled with

latexmlc latexml-tabular-test-case.tex --xsltparameter=SIMPLIFY_HTML:true --includestyles --format=html --dest=latexml-tabular-test-case.htm 

--Randy
```tex
\documentclass[9pt]{article}
\begin{document}

test 1

\begin{tabular}{ll}
Column $11$ & Column 21 \\
Column 12 & Column 22 \\
Column 13 & Column 23 \\
Column 14 & Column 24 \\
\end{tabular}

test 2

\begin{tabular}{ll}
Column 11 & Column 21 \\
Column 12 & Column 22 \\
Column 13 & Column 23 \\
Column 14 & Column 24 \\
\end{tabular}

\end{document}
```

**Comment by dginev** [comment]
This is another installment of the possible surprise caused by latexml's algorithm for guessing table headers, with prior reports in #1273 and #591 .

The current suggestion is to change the CSS directive responsible for the "guessed" header bold appearance, e.g. via
```css
.ltx_th {
  font-weight: normal;
}
```

I'll leave it to @brucemiller to explain/think over whether having math in the top cell is sufficient reason to guess it is a header.

**Comment by yatescr** [comment]
Thanks for your response, Deyan. I don't understand why latexml has to guess anything regarding whether or not the first row is a header: why not just typeset what the author wrote?

I also do not understand why any such guess affects the subsequent rows of the table.

--Randy

**Comment by yatescr** [comment]
May I request an option be added in the next version to disable this guessing?

--Randy

**Comment by brucemiller** [comment]
Well, it's not that having math causes it to be a header, it's differences in the types, fonts, etc in the content of cells that trigger it.  Sigh, users have just got no sense of adventure!

It's easy to add an option to latexml.sty along the lines of
```
\usepackage[noguessheaders]{latexml}
```
or equivalently `--preload=[noguessheaders]{latexml}` on the commandline.
Either of which is obscure enough that we'll still get questions :>

Making noguessheaders be the default would be fine with me, but causes many/most test cases to need to be updated, or alternatively some way of feeding the option into `Test.pm`.  I'll leave that solution to the Test case expert :>

**Comment by yatescr** [comment]
Thanks Bruce. I tried 

\usepackage[noguessheaders]{latexml}

using the package file from https://raw.githubusercontent.com/brucemiller/LaTeXML/master/lib/LaTeXML/texmf/latexml.sty
but I'm getting the error below. Do I have an old version of latexml.sty?

--Randy

```txt
-*- mode: compilation; default-directory: "/home/local-yates/finance/cash-flow-math/" -*-
Compilation started at Tue Apr 20 08:58:20

make -f cash-flow-math.mak file=cash-flow-math viewhtm
pdflatex cash-flow-math
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./cash-flow-math.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
(../../texmf/tex/latex/latexml/latexml.sty

! LaTeX Error: Unknown option `noguessheaders' for package `latexml'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.34 \providecommand
                    {\XML}{\textsc{xml}}%
? 
```

**Comment by brucemiller** [comment]
You got ahead of me; I hadn't made the patch yet.  But it's in #1518, and for consistency's sake, I called it `(no)guesstabularheaders`.
