### ISSUE TITLE
\ifinner, \ifvmode, \ifhmode support

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1526]
I found a curious arXiv Fatal error, which seems to be distilled down to `\ifinner` not being correctly emulated. A minimal snippet I extracted is:

```tex
\documentclass{article}
\usepackage{amsmath}
\def\ifinlinemath#1#2{#2}
\def\mathshift{$}
\catcode`$=13
\def${\ifinner\expandafter\mathshift\else\expandafter\myshift\fi}
\def\myshift#1${{\def\ifinlinemath##1##2{##1}\raisebox{0ex}[0ex][0ex]{\mathshift#1\mathshift}}}

\begin{document}
\begin{equation}
  X \tag{$\star$}
\end{equation}
\end{document}
```

The interplay between redefining `$` and `\tag` is the exact spot the Fatal is encountered, with the rather unusual:
```
Fatal:expected:#1 Parameters for '1' not in order in #2
	at tag_fatal.tex; line 11 col 0 - line 11 col 17
```

The soft fatals PR #1525 successfully recovers the pieces of the original arXiv document upto this point, so it served a nice purpose in testing already. But we may want to fix the root cause here as well, which likely comes down to some reasonable approximation of these conditionals.

FWIW, the minimal example looks completely unreasonable to a casual author, almost like something that should be out of scope, and yet pdflatex converts this document incredibly smoothly.

**Comment by brucemiller** [comment]
Not quite sure when it was fixed, but it seems to work now. Can you verify?

**Comment by dginev** [comment]
Wow, when did that happen?? Impressively, the example above now converts exactly as it should:

![image](https://user-images.githubusercontent.com/348975/126851236-2fe8dc6e-e411-4cd5-b26f-dea406eda865.png)

Closing!
