### ISSUE TITLE
\documentstyle can allow \newcommand redefinitions

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1530]
The following minimal snippet from arXiv will produce a pdflatex error under `\documentclass`, but works just fine in the compatibility mode:

```tex
\documentstyle[12pt]{article}
\newcommand{\r}{r_{\mbox{\scriptsize min}}}
\begin{document}
$r=\r$
\end{document}
```

Apparently `\newcommand` can happily redefine macros in compatibility mode? I am not fully certain of the details, and I'm assuming I'd need to study `latex209.def` in greater detail to find out, so filing it in as a minor issue to be patched later.

**Comment by brucemiller** [comment]
Think this is fixed?

**Comment by dginev** [comment]
Indeed - just retested an all is OK. Thanks for revisiting the straggler issues!
