### ISSUE TITLE
MiKTeX stderr messages cause some tests to fail on Windows

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1559]
I am hitting a MiKTeX problem at work (LaTeXML 0.8.5, Strawberry Perl 5.32.0.1, MiKTeX 2.9.7742, Windows 10).

It seems like MiKTeX's `kpsewhich` sometimes spews out warnings, and those inject themselves in some tests, breaking them.

My issue can be solved by running the MiKTeX update as admin, of course. But I don't think the profile and format tests were intended to fail in this situation, were they?

```
t/92_profiles.t ........... 5/13
#   Failed test 't/daemon/profiles/fragment'
#   at C:\Users\pmtvlm\.cpanm\work\1625496636.31072\LaTeXML-0.8.5\blib\lib/LaTeXML/Util/Test.pm line 112.
# Difference at line 1 for t/daemon/profiles/fragment
#       got : 'kpsewhich: major issue: User/administrator updates are out-of-sync.'
#  expected : 'No obvious problems'
kpsewhich: major issue: User/administrator updates are out-of-sync.
t/92_profiles.t ........... 8/13
#   Failed test 't/daemon/profiles/math'
#   at C:\Users\pmtvlm\.cpanm\work\1625496636.31072\LaTeXML-0.8.5\blib\lib/LaTeXML/Util/Test.pm line 112.
# Difference at line 1 for t/daemon/profiles/math
#       got : 'kpsewhich: major issue: User/administrator updates are out-of-sync.'
#  expected : 'No obvious problems'
t/92_profiles.t ........... 11/13 # Looks like you failed 2 tests of 13.
t/92_profiles.t ........... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/13 subtests
t/931_epub.t .............. ok
t/93_formats.t ............ 2/37
#   Failed test 't/daemon/formats/citation'
#   at C:\Users\pmtvlm\.cpanm\work\1625496636.31072\LaTeXML-0.8.5\blib\lib/LaTeXML/Util/Test.pm line 112.
# Difference at line 1 for t/daemon/formats/citation
#       got : 'kpsewhich: major issue: User/administrator updates are out-of-sync.'
#  expected : 'No obvious problems'
t/93_formats.t ............ 5/37
#   Failed test 't/daemon/formats/citationraw'
#   at C:\Users\pmtvlm\.cpanm\work\1625496636.31072\LaTeXML-0.8.5\blib\lib/LaTeXML/Util/Test.pm line 112.
# Difference at line 1 for t/daemon/formats/citationraw
#       got : 'kpsewhich: major issue: User/administrator updates are out-of-sync.'
#  expected : 'No obvious problems'
kpsewhich: major issue: User/administrator updates are out-of-sync.
kpsewhich: major issue: User/administrator updates are out-of-sync.
kpsewhich: major issue: User/administrator updates are out-of-sync.
t/93_formats.t ............ 8/37
#   Failed test 't/daemon/formats/jats'
#   at C:\Users\pmtvlm\.cpanm\work\1625496636.31072\LaTeXML-0.8.5\blib\lib/LaTeXML/Util/Test.pm line 112.
# Difference at line 1 for t/daemon/formats/jats
#       got : 'kpsewhich: major issue: User/administrator updates are out-of-sync.'
#  expected : 'No obvious problems'
t/93_formats.t ............ 32/37 kpsewhich: major issue: User/administrator updates are out-of-sync.
t/93_formats.t ............ 35/37
#   Failed test 't/daemon/formats/tei'
#   at C:\Users\pmtvlm\.cpanm\work\1625496636.31072\LaTeXML-0.8.5\blib\lib/LaTeXML/Util/Test.pm line 112.
# Difference at line 1 for t/daemon/formats/tei
#       got : 'kpsewhich: major issue: User/administrator updates are out-of-sync.'
#  expected : 'No obvious problems'
# Looks like you failed 4 tests of 37.
t/93_formats.t ............ Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/37 subtests
```

**Comment by dginev** [comment]
I am very tempted to avoid this issue entirely, because none of the tests were really intended to collide with platform-specific rules imposed by MikTeX. Our Windows CI is still not enabled exactly because I have found it painful to find good robust strategies for dealing with kpsewhich permissions on Windows.

That said, a ray of hope is that the master branch of latexml has now entirely removed the `.status` tests from the daemon testing component, so all of these checks you are shawing in the issue **are obsolete** with the latest master.

But that is not to say we have figured out how to play nice with MikTeX. The followup to #1390 via github actions needs to nail this down next.

**Comment by xworld21** [comment]
I'll test master and close the issue if I can confirm that the `.status` change fixes this particular problem (it sounds like it should!). Except that on my machine, master fails for a completely different reason that seems unrelated to MiKTeX... I might come back with *another* issue, if I understand what it is.

**Comment by dginev** [comment]
Definitely do so. We still do not have a dedicated Windows maintainer, so it is quite unsurprising whenever news comes of the installation regressing under that OS. We try to keep it operational but... If anyone from the community who's reading here feels comfortable with Windows devops, we're certainly looking for volunteers!

**Comment by xworld21** [comment]
I confirm that this issue does not apply anymore. Using master, all tests (well, except `931_epub`) pass on Windows+MiKTeX even if `kpsewhich` prints out error messages. That's great news.

**Comment by dginev** [comment]
Well, that's good for as much as it achieves, thanks for testing!
