### ISSUE TITLE
Common::Locator::getShortSource confuses 'C:\...' with a url on Windows

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1567]
First report from Windows (not enjoying this!).

Plenty of tests fail on Windows on master. The failing lines are
https://github.com/brucemiller/LaTeXML/blob/13f394ec64e8a6acc3d3645bdcb569da3ab03cf8/lib/LaTeXML/Common/Locator.pm#L55-L57
This runs `url_split` on paths like `C:\Users\...`, receives two arguments instead of three because there are no slashes, then fails because `$ext` is undefined.

Changing `':'` with `':/'` in `Locator.pm` makes most tests happy (others still fail for different reasons). But that's not a good solution because it ignores potentially valid URLs.

At any rate, `url_split` returns two values, not three, which is also suspicious.

Edit: the definition of "[starts with a Windows drive letter](https://url.spec.whatwg.org/#start-with-a-windows-drive-letter)" seems relevant.

**Comment by brucemiller** [comment]
So, that suggests that changing the test from `!= -1` to `< 2` would work (given a comment to explain the magic number). Is that right?

**Comment by xworld21** [comment]
> So, that suggests that changing the test from `!= -1` to `< 2` would work (given a comment to explain the magic number). Is that right?

...right, I didn't think of this simple solution. You don't need to check the exact rules since your URIs are presumably going to be http(s):, file:, literal: etc. nothing weird like starting with `:`. Yeah, that should work.
