### ISSUE TITLE
LibXML::Dtd->new() fails when $dtdfile contains a space

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1571]
Another space related bug. This line
https://github.com/brucemiller/LaTeXML/blob/c2958fbe2f9d2d2a7d616fd59ab71441d1a9fcc7/lib/LaTeXML/Common/Model/DTD.pm#L120
fails when `$dtdfile` contains a space.

Two possible fixes: use `URI::file` to convert the path to a `file:` URI, or read the entire file into a string and use `Dtd->parse_string()` instead of `Dtd->new()`. Both seem to work on my machine.

**Comment by dginev** [comment]
Good catch!

[Aside: Every time I see the DTD module mentioned ... I wonder why we still have a DTD module. ]
