### ISSUE TITLE
new terminal output shows escape characters in cmd.exe

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1572]
As per subject, the new terminal output writes escape characters even when the terminal does not support them. At the very least, I see this on cmd.exe (Windows 10, StrawberryPerl 5.32.something). So something about the terminal capabilities goes wrong there.

If you point me at the right file, I can try to debug the problem.

**Comment by brucemiller** [comment]
I guess I knew that was going to happen, but just crossed my fingers. There's no real attempt to detect the terminal capabilities (how?). FWIW, it's in `LaTeXML::Common::Error`.

**Comment by xworld21** [comment]
> There's no real attempt to detect the terminal capabilities (how?)

I would guess [Term::Cap](https://perldoc.perl.org/Term::Cap), but indeed, how exactly? I know by `.bashrc` (straight from Debian) uses `tput setaf 1` to detect color support. That could be a start.

**Comment by brucemiller** [comment]
On 7/18/21 1:25 PM, Vincenzo Mantova wrote:
>     There's no real attempt to detect the terminal capabilities (how?)
> 
> I would guess Term::Cap

My "how?" was a bit facetious; when I looked into it, it seemed the 
solutions were worse (heavier) than the problem.  But I guess it has to 
be looked into...

**Comment by xworld21** [comment]
> My "how?" was a bit facetious; when I looked into it, it seemed the solutions were worse (heavier) than the problem

I can imagine!

By the way, I just tried emptying out `%color_theme`, which almost works (the spinner is still colored, but at least the output is readable). But it has the side effect of restoring the old standard error, which I did not expect.

**Comment by xworld21** [comment]
Uh, this is a lot better:
```perl
   use Win32::Console;
   Win32::Console::OutputCP(65001);
   system('');
```
from https://incusdata.site/pan/pl/Perl-%20Getting%20Started.html

Just plugged in, and I get colored spinners in cmd.exe.

So now the question in, for which values of `^O` does this need to happen? Is it safe to do in every Windows case?

**Comment by dginev** [comment]
> So now the question in, for which values of ^O does this need to happen? Is it safe to do in every Windows case?

See what happens when you have it enabled in PowerShell, which is what I expect most Windows users would be running nowadays - at least that's what I have been using in recent years. If it is unchanged, it may be safe to have enabled on Windows in general.

**Comment by xworld21** [comment]
> See what happens when you have it enabled in PowerShell

It works in PowerShell too! If the line is longer than the window, you suddenly get lots of lines, but that's not a big problem, it remains readable.

**Comment by brucemiller** [comment]
Was this issue fixed by #1575?

**Comment by xworld21** [comment]
The cmd.exe part yes. I think that checking if the terminal supports escape sequences and colours is still relevant. E.g. Emacs `shell` is not a terminal emulator.

**Comment by brucemiller** [comment]
Doesn't the `$IS_TERMINAL` guard keep them from Emacs, then (including with the latest #1576)?

**Comment by xworld21** [comment]
> Doesn't the `$IS_TERMINAL` guard keep them from Emacs, then (including with the latest #1576)?

Yes indeed, when I wrote that comment I was somehow not seeing the `-t STDERR` line. I am not aware of terminals that do not support ANSI sequences as of 2021, so, issue closed!
