### ISSUE TITLE
\tableofcontents within a section only generates TOC for that section if it's split out

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1606]
If you run `latexmlc --splitat=section` on the following file, the desired table of contents contains only the entries for section B, rather than for the entire document. Not a huge bug, but slightly annoying.
```latex
\documentclass{amsart}
\begin{document}
  \tableofcontents
  \section{A}
  \subsection{AA}
  \subsection{AB}
  \subsection{AC}
  \section{B}
  \subsection{BA}
  \tableofcontents
\end{document}
```

**Comment by dginev** [comment]
manually closing on behalf of PR #1923 ✅
