### ISSUE TITLE
too many colons in the date when using AMS classes and a few others

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1607]
The following
```latex
\documentclass{amsart}
\title{MWE}
\date{9 August 2021}
\begin{document}
  \maketitle
\end{document}
```
becomes
![image](https://user-images.githubusercontent.com/1962985/128760849-95eb2c62-0eb3-42b9-81d8-00824cf05e40.png)
because `\datename` contains the colon already. This is with all AMS classes and a few more obscure ones (elegantbook, imsproc...).

The trivial fix is to remove the colon from the `ltx:date` template. However, that will get rid of the colon from all the other classes! Unfortunately the use of `\datename` does not seem completely consistent – some classes even include a trailing space already.

**Comment by dginev** [comment]
Thanks for catching that @xworld21 . I'm doing a CSS pass over arXiv these days, and we have a range of hard to predict edge case styling bits to clean up. Issues like this one are quite helpful to catalog what we have not yet noticed. 

So feel encouraged (both you and others who may be reading) to more when issues you spot other visual cruft. Thanks again!
