### ISSUE TITLE
MuGlue widths need care when used

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1618]
Currently, a minimal snippet such as:
```tex
\documentclass{article}
\begin{document}
test $\; $ here 
\end{document}
```

produces a warning that shows we're missing a method:
```
Warning:perl:warn Argument "5.0mu plus 5.0mu" isn't numeric in division (/) at test.tex; line 3 col 8
```

I believe the MuGlue object for `\thickmuskip` falls back on Number's ptValue (via Glue->Dimension->Number). I'm not entirely clear what the correct sizing logic is with using `\;` on the internal side, so opening an issue instead of a PR. 

Likely Glue and MuGlue need dedicated sizing methods?

**Comment by brucemiller** [comment]
Probably just need something like
```
sub ptValue { $_[0]->ptValue; }
```
and similar for `pxValue`

**Comment by dginev** [comment]
Do you happen to mean `$$self[0]->ptValue` ?

A MuGlue is defined as a list of: `($scaledpoints, $plus, $pfill, $minus, $mfill)`

**Comment by dginev** [comment]
So, for a `MuGlue("5mu plus 5mu")` , what would be the logic of `ptValue` ?

The first arg is a string at the time of the call, hence the warning I pasted above.

**Comment by dginev** [comment]
Actually, now that I am reading this slowly, aren't Glue and MuGlue somehow _missing_ their spec parsers? The string ought to have been split into pieces on object creation, but... it wasn't?

**Comment by brucemiller** [comment]
Not sure all the context; did it fail to be parsed, or did it get converted back to a string (Perl!).  At any rate, the logic of ptValue and pxValue should be just the 0 element scaledpoints and ignoring the shrink/stretch.

**Comment by brucemiller** [comment]
The parser is in `Glue::new`

**Comment by dginev** [comment]
There's some subtle timing issue in my little test that's causing a lot of head-scratching over here. If I add the prints in `Glue::new` all looks fantastic - parsing is triggered and good values are parsed out and returned for `5em plus 5em`.

Yet the warning is still shown?! Which somehow suggests that I'm either looking at the wrong place, or I'm misunderstanding the exact timing of the steps... for:
```perl
DefPrimitiveI('\;', undef, sub {
    Box("\x{2004}", undef, undef, T_CS('\;'),
      name  => 'thickspace', isSpace => 1,
      width => LookupValue('\thickmuskip')); });
```

**Comment by dginev** [comment]
Oh my. OOPerl, 2021 edition.

Dumping $self in Number's ptValue, to see this MuGlue object, I was shocked to discover:

```
$VAR1 = bless( [
                 '5.0mu plus 5.0mu'
               ], 'LaTeXML::Common::Dimension' );
```

and indeed, going to Glue.pm, you see:
```perl
use base qw(LaTeXML::Common::Dimension);
```

Guess what gets called when you do `LaTeXML::Core::MuGlue->new` ?

Ok, PR incoming...

**Comment by dginev** [comment]
The wild goose chase for me has concluded. This turns out to be a very narrow issue, nothing to do with the original issue title. It's about the width attribute getting serialized out as a string and then (in a certain math context) getting bravely cast into a `Dimension` even when it is a Glue descriptor:

```perl
        if (my $width = $xmnode->getAttribute('width')) {
          # $width holds the string "5.0mu plus 5.0mu"
          if (my $space = DimensionToSpaces(Dimension($width))) {
```
