### ISSUE TITLE
TeX default language is US English, LaTeXML has no default

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1626]
Directly inspired by https://github.com/brucemiller/LaTeXML/issues/1440#issuecomment-897874048 (cc @nxg).

The TeX default language is deliberately US English. I think it makes sense for LaTeXML to set the language to US English by default, so that the output starts with the appropriate `<html lang="en-US">` even if the user does not import babel.

PS: I have tried sticking `MergeFont(language => "en-US")` in `TeX.pool.ltxml` and it seems to work correctly in like 90% of the situations. In some of the tests (especially the plain TeX ones), the language does not bubble up to `<ltx:document>`, and weird stuff happens.

**Comment by dginev** [comment]
A bit US-centric, but so is TeX's history. I don't directly object to this... and we already allow overriding this with the various babel.sty languages, so it seems workable.

We may also want a `\lxLang` macro for latexml.sty as a more exposed override that doesn't require babel?

**Comment by nxg** [comment]
+1 (I'm anglophone, but `en-GB` is A Thing!).

**Comment by xworld21** [comment]
> We may also want a `\lxLang` macro for latexml.sty as a more exposed override that doesn't require babel?

I suppose LaTeXML should also support the 'standard' mechanisms, which should be babel, polyglossia, or `\language=\l@LANGNAME` for *LaTeX, and `\uselanguage` for e-TeX. (Source: https://ctan.org/pkg/hyph-utf8.)

 I believe LaTeXML only supports babel at the moment.

**Comment by brucemiller** [comment]
When you say that the default language is "deliberately" US english, doesn't that only mean that it defaults to US english hyphenation patterns?  Does the language come into play in any other ways? (LaTeXML doesn't do hyphenation, of course).

OTOH, it seems to me that `xml:lang="en-US"` is an entirely different thing; it's *asserting* that the document language is english, which we have no way of knowing. In fact, you could have "lorem ipsum" Latin, with not even any Unicode clues.

The `\language` register is curious; it takes a number, but is there a list of "known" languages?

**Comment by xworld21** [comment]
> Does the language come into play in any other ways? (LaTeXML doesn't do hyphenation, of course).

Indeed, I had hyphenation patterns in mind, I am not aware of other areas where it plays a role. I interpret this as the default language being English, but in principle a document could e.g. be only formulas, or loren ispum. I can see why it would be odd to set `lang=en-US` on those. Good point. 

> The `\language` register is curious; it takes a number, but is there a list of "known" languages?

TeX Live generates the following
https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/generic/config/language.def?view=markup
from the TeX Live package database. It's for e-TeX but it matches the other files for (La)TeX and LuaTeX.

The numbers themselves have no meaning, except 0 = US English. The others depend on which packages are installed locally. I guess LaTeXML would have to lock its own list of languages, or something like that.
