### ISSUE TITLE
Math mode switch breaks on empty Digested args

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1641]
Minimal example from [arXiv:1905.00240](https://corpora.mathweb.org/preview/sandbox%5Farxiv%5F1905/tex%5Fto%5Fhtml/1905.00240) : 
```tex
\documentclass{article}
\usepackage{amsmath}
\begin{document}

Here  the "$\underbrace{}$" indicates that the terms originate from
either $E^H$ or $E^{AD}$, and we have used the expression $\Delta A  =2D\mathcal{M}_1$.

\end{document}
```

From what I can make out, there is a subtle problem with how the `Digested` parameter type is implemented for empty arguments in math mode, which make the definition of `\underbrace` get confused on the mode switch:
```perl
DefMath('\underbrace Digested', "\x{23DF}", operator_role => 'UNDERACCENT',   # BOTTOM CURLY BRACKET
  scriptpos => 'mid');
```

I won't have time to patch this today, but it looks both healthy impact for arXiv (quick 100 errors and Fatal when encountered), and easy to fix? So recording an issue.

**Comment by brucemiller** [comment]
Funny; That (and `\overbrace`) are the only basic TeX accent macros that do *not* accept a `Digested` style parameter!  Of course, there's a maze of uses and misuses and tests to sort it out.  But patch is coming up!
