### ISSUE TITLE
Some math macros need to be robust

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1649]
A follow-up to our recently discovered discrepancy for the argument reads of `\underbrace` in the [#1647 comments](https://github.com/brucemiller/LaTeXML/pull/1647#discussion_r702257568)

It appears in my texlive 2020 `fontmath.ltx` there are 46 definitions using `\DeclareRobustCommand`, among which the `\overbrace` and `\underbrace` examples. In the protected cases, some low-level programmatic uses become a bit subtle, as in the example:

```tex
\[ \expandafter\underbrace\underbrace foo \]
```

where the outer underbrace receives no arguments, while the inner one receives the letter `f`. Without the `\protect` machinery, latexml interprets the example as two nested underbraces over a missing argument, which may end up problematic.

It may be worthwhile adding a `protected => 1` flag to the DefMath API, and maybe even make all DefMaths protected by default? The default irrespective, going through the `.ltx` definitions and marking all protected macros as such in the latexml definitions would be a good upgrade to stay closer to pdflatex parity.

**Comment by brucemiller** [comment]
The protected option simulates eTeX's `\protected`, whereas the (new) robust option simulates the `\protect` mechanism used by LaTeX.  Yeah, they act diferently... pr in the works.
