### ISSUE TITLE
subequations tag should not appear in the output

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1660]
Discovered while investigating #1656. The following
```latex
\documentclass{amsart}
\begin{document}
\begin{subequations}
\begin{equation*}
x^2
\end{equation*}
\end{subequations}
\end{document}
```
prints out an equation number, but it shouldn't.

PDF:
![image](https://user-images.githubusercontent.com/1962985/134804202-fbb98af6-0ffe-41ba-9293-5ae282dc3ecf.png)

HTML:
![image](https://user-images.githubusercontent.com/1962985/134804212-7af7893d-144a-48d5-a789-3232360a917d.png)

To make the problem difficult, the following code generates the same `ltx:equationgroup` structure, so this cannot be fixed from XSLT. The XML needs to know if the group tag was meant to be printed or not.
```latex
\documentclass{amsart}
\begin{document}
\begin{equation}
\begin{aligned}
  x^2
\end{aligned}
\end{equation}
\end{document}
```

**Comment by dginev** [comment]
Btw, it is interesting that while it is not displayed, it is indeed counted. For the combined example:
```tex
\documentclass{amsart}
\begin{document}
\begin{subequations}
\begin{equation*}
x^2
\end{equation*}
\end{subequations}


\begin{equation}
\begin{aligned}
  x^3
\end{aligned}
\end{equation}

\end{document}
```

We see in PDF:
![image](https://user-images.githubusercontent.com/348975/146268051-ac274644-6330-42a9-a8c7-53aac43f92b9.png)

So maybe adding an extra class attribute for `{subequations}`, and a XSLT or CSS rule that hides the tag, gets us there.
