### ISSUE TITLE
nesting cases into align increases the equation numbers

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1661]
Weird problem with equation numbers.
```latex
\documentclass{amsart}
\begin{document}
\begin{align}
\begin{cases}
a \\
b
\end{cases} \\
c
\end{align}
\begin{equation}
d
\end{equation}
\end{document}
```
produces
![image](https://user-images.githubusercontent.com/1962985/134804565-b41301fc-f9c6-4e60-ae8c-812787fa3770.png)

The numbers are clearly off. It seems like the lines within `{cases}` are increasing the counter.

PDF:
![image](https://user-images.githubusercontent.com/1962985/134804595-43e16aa1-7448-426f-ab28-bc4a431025b2.png)

**Comment by brucemiller** [comment]
Hmm, this should have been fixed by #1742
