### ISSUE TITLE
mathtools.sty.ltxml: replace \vdotswithin by \vdots

### ISSUE THREAD

**Issue by molke-productions** [brucemiller/LaTeXML#1672]
Currently, `\vdotswithin` is apparently replaced with an empty string:
https://github.com/brucemiller/LaTeXML/blob/be6bbab59dbf48b7834d96db65c49226c27a96b4/lib/LaTeXML/Package/mathtools.sty.ltxml#L642
Maybe, at least `\vdots` would be more appropriate, disregarding the alignment (probably the same for `\shortvdotswithin`).

**Comment by molke-productions** [comment]
Thanks, I’ll take more appropriate semantics over alignment anytime.

**Comment by dginev** [comment]
Certainly! And thanks for reporting the issue in the first place @molke-productions , much appreciated.
