### ISSUE TITLE
Rotation of arrows from tikz

### ISSUE THREAD

**Issue by Yunelsy** [brucemiller/LaTeXML#1691]
Hello, I am having a problem with the tikz conversion. For example, if we consider the document Tikz_Issue.tex: 

```tex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{positioning,shapes.misc}
\usetikzlibrary{patterns}
\usetikzlibrary{decorations.pathreplacing}
\begin{document}
\begin{tikzpicture}[line width=1pt,>=latex]
\fill[lightgray] (-1.73,1) -- (0,0) -- (2.82,1.03) -- cycle;
\draw[gray] (-1.72,0.99) -- (2.82,1.03);
\draw[->] (-2,0) -- (3.5,0);
\draw[->] (0,-1) -- (0,2.5);
\draw[->,gray] (0,0) -- (-2.17,-1.25);
\draw[->,gray] (0,0) -- (-1.73,1) node[below right,yshift=-5pt,black]{$u$};
\draw[->,gray] (0,0) -- (2.82,1.03) node[below left,yshift=-5pt,black]{$v$};
%\draw[<->,gray] (-1.73,1) node[below right,yshift=-5pt,black]{$u$} -- (0,0) -- (2.82,1.03) node[below left,yshift=-5pt,black]{$v$};
\draw[<->,gray!50!gray] (0.38,0.14) node[above left,yshift=5pt,black]{$\theta$} arc (20:150:0.4);
\end{tikzpicture}
\end{document}
```

and we use 
`latexml --dest=test.xml  Tikz_Issue.tex`
and then
`latexmlpost --dest=test.html test.xml`

I obtain the following svg image in HTML in which all arrows that are neither vertical nor horizontal are rotated to these positions. 

![wrong](https://user-images.githubusercontent.com/71239961/136844439-00063038-ccfd-4457-895e-67a36f4a1689.png)

while the correct one is 

![correct](https://user-images.githubusercontent.com/71239961/136846759-fa8c8c25-07ff-41f9-b388-e4575ea114eb.png)

Observe that the lines also have changed the angle due to this rotation.

Anyone can help?

**Comment by dginev** [comment]
Possibly good (or bad, depending) news - this may already be fixed in the latest master, assuming texlive 2020 (which i have locally). On my machine your sources produce:

![image](https://user-images.githubusercontent.com/348975/136847379-62126476-d5c6-48bc-bcfc-835f2f877b6d.png)

Which *impressively* matches the target image you have shared. I am using the latest latexml from this repository.

Could you share your latexml and texlive versions? You can get those via `latexml --version` and `tex --version`. Thanks!

**Comment by dginev** [comment]
Ah, perfect, great news. @Yunelsy your latexml version is a release behind of it indeed says 0.8.5. The 0.8.6 release happened end of September, and hopefully reaches you soon. The fixes to these graphics happened exactly in our last release, made by Bruce, so there is hope this will work just fine with your miktex version, as long as you successfully update to 0.8.6.

Did you install latexml via Chocolatey ?

**Comment by Yunelsy** [comment]
Hi @dginev 
I have already uptated latexml to the 0.8.6 version and everything works perfectly! 
![figure](https://user-images.githubusercontent.com/71239961/136857606-3cf2412c-fb30-47c8-b8d4-f17cb75915e4.png)

Thank you very much for your help!

**Comment by dginev** [comment]
Fantastic, glad we don't need to do any further work over here! Enjoy the feature @Yunelsy and let us know if any other important pieces look defective or missing.
