### ISSUE TITLE
math images fail on cases in align

### ISSUE THREAD

**Issue by molke-productions** [brucemiller/LaTeXML#1696]
LaTeXML 0.8.6 ends with an error
```
! Undefined control sequence.
l.57 \beginDISPLAY a=\begin{cases}\hidden
                                         @noalign{}\textstyle b&x,\\
```
and
```
! Undefined control sequence.
l.58 \hidden
            @noalign{}\textstyle c&y.\end{cases}\endDISPLAY\clearpage
```
with cases in align at math image generation:
```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{align*}
a = \begin{cases}
b & x,\\
c & y.
\end{cases}
\end{align*}
\end{document}
```
Using aligned instead seems to work fine.

**Comment by dginev** [comment]
This seems to be working OK with the latest latexml in the repository, could you double-check @molke-productions ?

Here is the log:
```
latexmlc (LaTeXML version 0.8.6; revision acc8f0ca)
processing started Sat Dec 11 21:27:15 2021
Conversion complete: No obvious problems
Post-processing complete: No obvious problems
Status:conversion:0
```

and an example screenshot:
![Screenshot 2021-12-11 at 21-29-06 Untitled Document](https://user-images.githubusercontent.com/348975/145698108-d617b3d8-2cbd-448b-aa3f-06712ef75faf.png)

**Comment by dginev** [comment]
I somehow skimmed over the "math image generation" comment. Indeed, I can reproduce when using `--mathimages`

**Comment by molke-productions** [comment]
Thanks for further investigating. To be clear, #1681 affects only `--mathimages` too.
