### ISSUE TITLE
Position-dependent \label in align

### ISSUE THREAD

**Issue by molke-productions** [brucemiller/LaTeXML#1703]
If the label is before (the alignment character `&`?), then `\eqref` won’t find the ID:
```tex
Equations \eqref{eq:before} and \eqref{eq:after}:
\begin{align}
\label{eq:before}
&x \quad c_1,
\end{align}
and
\begin{align}
&y \quad c_2,
\label{eq:after}
\end{align}
```
In the resulting XML, the IDs and the equation tags  are apparently correct.

**Comment by molke-productions** [comment]
As a follow-up, this seems to be a more general problem with align/aligned regarding the alignment character.
For example,
```latex
\begin{align}
\begin{aligned}
& a\\
& b
\end{aligned}
\end{align}
```
won’t even compile (starting with `Error:misdefined:&`), whereas the same in `equation` instead of `align` works fine.

**Comment by dginev** [comment]
This is definitely suspiciously broken, I reproduced the report exactly as written. I also stumbled on a possibly related issue from arXiv where leading labels of eqnarray do not get recorded. Maybe even the same exact cause, so I'm recording my minimal example here:

```tex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{eqnarray}
\label{eq:this}
\sum_{k=1}^{M}\mathrm{prob}(Y_k|X,I)&=&1.
\end{eqnarray}

Ref \ref{eq:this}
\end{document}
```
