### ISSUE TITLE
Missing left/right padding in framed.sty.ltxml

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1704]
```latex
\documentclass{article}
\usepackage{framed}
\begin{document}
  \begin{framed}
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur dictum gravida mauris.
  \end{framed}
\end{document}
```
compiles as follows (PDF vs HTML)
![PDF](https://user-images.githubusercontent.com/1962985/140611958-584acbbc-c597-40be-9c82-e0d305f7916f.png)
![HTML](https://user-images.githubusercontent.com/1962985/140611940-b876888b-7eb2-4ae7-8840-f308643c005b.png)

Offending line (6 occurrences in the file):
https://github.com/brucemiller/LaTeXML/blob/48239014cf05ba2c72ad62b10f4105d592117cdc/lib/LaTeXML/Package/framed.sty.ltxml#L27
sets only `padding-top` and `padding-bottom`, even though `\framebox` applies the padding `\fboxsep` to all sides.

**Comment by dginev** [comment]
Nice catch!

**Comment by dginev** [comment]
I'm also wondering whether we can add a related upgrade where we switch to using class-based sizing, rather than absolute values in a `style` attribute.

On the lines of `ltx_pad_small`, `ltx_pad_medium`, `ltx_pad_large`, eventually refined to the optimal level of granularity.
