### ISSUE TITLE
math struts breaking in MathJax

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1708]
The tex document
```tex
\documentclass{article}
\begin{document}
My strut $\left(\rule{0pt}{30pt}\right)$.
\end{document}
```
Produces html containing:
```html
<p class="ltx_p">My strut <math id="p7.m1" class="ltx_Math" alttext="\left(\rule{0.0pt}{30.0pt}\right)" display="inline"><mrow><mo>(</mo><mtext mathcolor="red"><span class="ltx_rule" style="width:0.0pt;height:30.0pt;background:black;display:inline-block;"></span></mtext><mo>)</mo></mrow></math>.</p>
```

This renders fine with MathML (eg, Firefox).  But with MathJax, this becomes "Unknown node type: span".  It looks like this is an example of issue #1477, which boils down to MathJax not being able to handle anything inside an `mtext` tag.  I don't know MathML, but it seems like an `.ltx_rule` doesn't need to be text.  I tried removing the `mtext` but leaving the `span`, but that didn't keep the height.  Would it be possible to use some other MathML tag instead of `span` in order to form the strut?

**Comment by dginev** [comment]
As you've nicely pointed out, this is a mathjax rendering issue first and foremost, and ideally you should reach out to them so that they know you've encountered the problem. 

As you've seen in the emph issue you mention, the link for that is:
https://github.com/mathjax/MathJax/issues/487

That issue has a new workaround mentioned since the last time I checked, maybe there is a path to getting full support in mathjax soon?

The HTML for your example seems to render just fine in normal Firefox today:
![image](https://user-images.githubusercontent.com/348975/141210755-0987061e-fcc3-41f1-8b0e-79b2d8ed5c99.png)

That said, in your specific case I seem to be getting the same rendering if I swap the `mtext` entirely with an equivalent mspace, as in:

```xml
<mspace width="0" height="30.0pt"></mspace>
```

So maybe we could refine that for some cases? Would have to read a bit more about strut to see if that is a reliable technique or not, just a quick reply for now. I'm sure Bruce knows more on the subject.

**Comment by teepeemm** [comment]
Their workaround of replacing `<mtext>...</mtext>` with `<semantics><annotation-xml encoding="application/xhtml+xml"><span>...</span></annotation-xml></semantics>` makes the strut work with MathML and MathJax.  The replacement also makes `<mtext><a href="#label">label</a></mtext>` and `<text><svg>...</svg></mtext>` not give errors (although MathJax makes the link no longer work and vanishes the svg).  Would it make sense to use those three instead of mtext when mtext contains some other tag?

**Comment by teepeemm** [comment]
I ended up implementing struts as mspace and removing all other tags by loading jQuery and then
```javascript
    MathJax = {
        startup: {
            ready: function() {
                $('mtext').has('span.ltx_rule[style*="width:0.0pt"][style*="height"]').each(function() {
                    const jThis = $(this),
                        height = jThis
                            .children('span.ltx_rule[style*="width:0.0pt"][style*="height"]')
                            .get(0).style.height;
                    jThis.replaceWith('<mspace height="'+height+'" />');
                });
                $('mtext').has('*').each(function() {
                    const jThiss = $(this);
                    jThiss.html(jThiss.text());
                });
                MathJax.startup.defaultReady();
            }
        }
    }
```
before loading LaTeXML-maybeMathJax.js.  (But is there a bug with maybeMathJax?  I was getting that `MathJax.Hub` is undefined, so that `refreshMath` was causing errors.  But I don't understand why no one else would have seen that in the past year since you went to MathJax v3.)

**Comment by xworld21** [comment]
@teepeemm I have had some luck with the following:
```xslt
<xsl:template match="m:mtext[*]">
  <m:semantics>
    <xsl:for-each select="@*">
      <xsl:apply-templates select="." mode="copy-attribute"/>
    </xsl:for-each>
    <m:annotation-xml encoding="text/html" style="display: block;">
      <xsl:apply-templates/>
    </m:annotation-xml>
  </m:semantics>
</xsl:template>
```
The `display: block;` is needed by the Chrome native MathML renderer, although that may be a bug (the renderer is experimental). In my very limited tests, MathJax renders embedded `<svg>` tags, `<img>`, and links, but maybe I am doing something different.

By looking at the spec, I can't tell if `<annotation-xml>` is really equivalent to `<mtext>`, though. For instance, will it be treated the same by screen readers?

**Comment by teepeemm** [comment]
@dginev FYI, MathJax 487 (linked above) now has a link to a PR that might fix this.

**Comment by xworld21** [comment]
It looks like MathJax will be able to render HTML content within MathML: https://github.com/mathjax/MathJax-src/pull/781#event-7165157359 has been merged.

MathJax 487 is still open, presumably it will be closed when the new code gets into a release.

**Comment by brucemiller** [comment]
So, I'll assume we can close here. If further issues arise, we'll have new issues with new specifics. Thanks!
