### ISSUE TITLE
\centering escaping its group

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1712]
In the tex document
```tex
\documentclass{article}
\begin{document}
This should not be centered.

{\centering
This is the only thing that should be centered.\\
}

This should not be centered.
\end{document}
```
The `{}` aren't forming a group in the xml (nor does `\bgroup/\egroup` nor `\begingroup/\endgroup`), so that the `.ltx_align_center` escapes and applies to everything on the page.

**Comment by teepeemm** [comment]
It turns out this issue is already known: https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/LaTeX.pool.ltxml#L1271

**Comment by dginev** [comment]
Btw, the PDF behavior of centering is also not intuitive. Here is a slightly more diverse test:

```tex
\documentclass{article}
\begin{document}

{\centering REGULAR lead-in p}

top level p 1

top level {\centering centered p2

top level REGULAR p3}.

top level p 4

\section{A section}

in-section p 1

in-section {\centering centered p2

in-section REGULAR p3}.

in-section p 4

\end{document}
```

with PDF:
![image](https://github.com/brucemiller/LaTeXML/assets/348975/59ac1a9a-0662-4376-ab96-21949ed8ed27)

It almost looks as if we should be dropping some `<ltx:_Capture_ role="centering"/>` element, and then rewriting that away based on its parent. If in a pre-existing logical or block parent (e.g. `ltx:para`, `ltx:p`) we can set the attribute specifically on that parent.

That seems consistent with the `p3` cases in my example not actually applying the `\centering` information despite being in the same group. `\par` seems to terminate the directive.

If a simple approach of this nature is workable, I can make a PR for v0.8.8 (cc @brucemiller). Or we can defer...
