### ISSUE TITLE
latexmlpost 0.8.6 --mathtex

### ISSUE THREAD

**Issue by peppobon** [brucemiller/LaTeXML#1727]
In 0.8.6 with: 
latexmlpost --format=xhtml --mathtex 
I get <span id="..." class="ltx_Math">text formula</span>
and the mathml gets lost (along with the display=block|inline attr).

Using 0.8.4 I get the <math ... display="block|inline">mathml formula <annotation>text formula</annotation></mathml>, which is what I expect.

Is this a bug in 0.8.6 or I am missing something?

Many thanks,

__peppo

**Comment by peppobon** [comment]
Sorry, I reformat the message above:

with 0.8.6 I get:
`<script class="ltx_Math">tex formula</span>`

in 0.8.4 I get the the expected code:
`
<math ... display="block|inline">
mathml formula
<annotation>tex formula</annotation>
</math>
`

**Comment by peppobon** [comment]
Thank Deyan for the super speedy answer.

**Comment by dginev** [comment]
Sure thing, feel free to open other issues as questions come up!
