### ISSUE TITLE
Allow catcode changes from within packages loaded raw

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1729]
Here is a minimal working example from arXiv:
```tex
% @ is a character (catcode 12)
\documentclass{article}
\usepackage{pgfplots}
\usepgfplotslibrary{external}
% @ is now a letter (catcode 11) in pdftex
% but is still catcode 12 in latexml, leading to errors
%
% due to pgfplotsbinary.code.tex having a top-level
% \catcode`\@=11 
%
% and this works out in arXiv:1802.06832
\newcommand*\env@matrix[1][*\c@MaxMatrixCols c]{%
  \hskip -\arraycolsep
  \let\@ifnextchar\new@ifnextchar
  \array{#1}}

\begin{document}
test
\end{document}
```

It is a bit tricky for me to suggest a code change that solves this, since it may involve a refactor that undoes some assumptions about reverting the @ catcode in Mouths marked `fordefinitions`, **and** the same assumptions for the `RawTeX` interface.

I found one article that exhibited a chain of errors starting with the renewcommand above (simplified to a \newcommand here to make the code snippet smaller), which you can see at [1802.06832](https://ar5iv.org/html/1802.06832)

**Comment by brucemiller** [comment]
Looks to me like somebody taking advantage of a bug in (perhaps) `\usepgfplotslibrary`.  Seems to be a really bad idea if they intentionally left @ with letter catcode.

**Comment by dginev** [comment]
Right, but I assume we can't overcorrect in the other direction either - i.e. use a letter catcode for @ whenever reading the main command sequence arguments for \def, \newcommand, etc. defining macros. Since I'll be tempted to conjecture that over 99% of uses of @ in that specific context are meant to have it as letter catcode.

**Comment by dginev** [comment]
No obvious solution, closing.
