### ISSUE TITLE
How to use Katex with LaTeXML?

### ISSUE THREAD

**Issue by btjanaka** [brucemiller/LaTeXML#1791]
Hi! I am wondering how I can use Katex with LaTeXML. So far, I have a Latex file e.g. `test.tex`:

```
\documentclass{article}

\begin{document}

$x$

\end{document}
```

I then run `latexmlc --noparse --mathtex test.tex --dest=test.html`.

Inside of `test.html`, I insert the [Katex installation](https://katex.org/docs/browser.html) into the `<head>` (currently doing this manually):

```
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css" integrity="sha384-MlJdn/WNKDGXveldHDdyRP1R4CTHr3FeuDNfhsLPYrq2t0UBkUdK2jyTnXPEK1NQ" crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js" integrity="sha384-VQ8d8WVFw0yHhCk5E8I86oOhv48xLpnDZx5T9GogA/Y84DcCKWXDmSDfn13bzFZY" crossorigin="anonymous"></script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
```

However, when I open the browser, my math does not render with Katex (`x` is just plaintext in the image below).

<img src="https://user-images.githubusercontent.com/38124174/152595407-e6db02c9-e465-478f-825e-b5e583f50599.png" width=400>

I am thinking it may be best to just make LaTeXML output the raw Latex formulae -- is it possible to do that?

Thanks!

**Comment by dginev** [comment]
We have not made it easy to use the TeX output of latexml with either katex or mathjax. I think one of the original motivations is to *encourage* using MathML, which you should if you can.

That said, say you converted a square root, to see this a bit better:
````tex
\documentclass{article}
\begin{document}
$\sqrt{x}$
\end{document}
```
with 
```
latexmlc test.tex --noparse --mathtex --dest=test.html
```

gets you to:
```html
<span id="p1.m1" class="ltx_Math">\sqrt{x}</span>
```

So you would like to write a custom bit of javascript that runs katex over elements with the `ltx_Math` class. We could use that script to create a sibling officially distributed script to `LaTeXML-maybeMathjax.js`, and let people choose their polyfill.

Do you think you'd like to try to create a PR for that @btjanaka ? If my explanation is not clear enough, I can try to quickly write the script as a comment here.

**Comment by tkw1536** [comment]
I actually did write a script for this some time ago (for large documents where MathJax was performing poorly. 
I never ended up making a PR out of it. 

https://gist.github.com/tkw1536/5c1437bd17e743d0f553874d891e444c./

**Comment by dginev** [comment]
Oh nice, good to know! I now remember seeing it, but it slipped my mind - thanks for bringing this up Tom!

**Comment by btjanaka** [comment]
Thanks for all the responses! I'll definitely take a look at your script @tkw1536 -- if it works on MathML, that would be fine for me, as I can first convert to MathML and then run Katex on it.

@dginev Now that we have this script, I'm not sure a PR is necessary, but I'll take a look first and then let you know how it goes.

**Comment by btjanaka** [comment]
I can confirm that the Katex polyfill works. I ran with `--noparse` and `--mathtex` and sourced the script in the head, and things seem to render fine.

**Comment by dginev** [comment]
Excellent. Let's keep this issue open until we hear if @brucemiller is OK with me adding a `LaTeXML-maybeKaTeX.js` script that is an alternative to the mathjax one, based on the tex formula annotations.

**Comment by brucemiller** [comment]
If I understood correctly, with the `--mathtex` output (no mathml), you'd be using KaTeX unconditionally, so should be able to point to that with `--javascript` and no need for an additional  "maybe" version.
