### ISSUE TITLE
Spans in multi-element frontmatter cards

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1792]
Anonymized example from [1811.12808](https://ar5iv.org/html/1811.12808):
```html
<span class="ltx_personname">
  First Last Names
  <br class="ltx_break">University
  <br class="ltx_break">Department
  <br class="ltx_break">Some Date
  <br class="ltx_break">
  <span class="ltx_text ltx_font_typewriter">some@email</span>
</span>
```

This seems fine on the surface, until one also encounters different articles where the author tried to forcefully add the styling to the frontmatter via multiple breaks, as in:
```html
<span class="ltx_personname">
  First Last Names
  <br class="ltx_break">University
  <br class="ltx_break">Department
  <br class="ltx_break">
  <br class="ltx_break">
  <br class="ltx_break">
  <br class="ltx_break">Some Date
  <br class="ltx_break">
  <span class="ltx_text ltx_font_typewriter">some@email</span>
</span>
```

Wearing the hat of a vendor designer, I would like to add a CSS rule that disables these multiple breaks, as:
```css
span.ltx_personname > .ltx_break + .ltx_break {
  display: none;
}
```

However, due to the text nodes being left without dedicated HTML elements (i.e. not wrapped in spans), that CSS rule will also match the *intended* single breaks. `.ltx_break + .ltx_break` matches `<br class="ltx_break"> text  <br class="ltx_break">` as CSS skips over text nodes.

So, several directions for possible improvements:
 - preferred: add wrapping spans to text nodes in "ltx_personname" and other frontmatter elements that have >1 children
 - alt 1: avoid multiple breaks in frontmatter (a bit too constraining)
 - alt 2: switch to a flex or grid internal model in frontmatter cards and avoid the simple `br` breaks (a bit too much work)

It's minor stylistic flourish, but it can be felt in the page fidelity. The multiple breaks look really bad at least in my ar5iv styling.

**Comment by brucemiller** [comment]
I'm wondering if adjacent `ltx:break` ever really makes sense; could add a simple rewrite rule to collapse them.

**Comment by brucemiller** [comment]
Actually, this seems to be working now; we don't end up with repeated `ltx:break`.
