### ISSUE TITLE
Modernize mspace width values

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1801]
There is a scary deprecation warning in Firefox:
```
“veryverythinmathspace”, “verythinmathspace”, “thinmathspace”, “mediummathspace”, “thickmathspace”,
  “verythickmathspace” and “veryverythickmathspace” are 
  deprecated values for MathML lengths and will be removed at a future date.
```

Changing these in latexml is technically easy -- the question is what should we change them to?

We might as well stay a step ahead of the deprecation status changing.

**Comment by fred-wang** [comment]
@dginev What's the status of this in LaTeXML?

The replacement proposed is https://github.com/w3c/mathml/issues/75#issuecomment-523016332

**Comment by dginev** [comment]
@fred-wang Thank you for pointing out the replacements! And for the issue bump.

I believe @brucemiller and I still intend to get this refactor done for the upcoming release, together with the other spacing-related issue at #1925 .

0.8.7 is tentatively scheduled for early November, and we'll try to make it as compatible with MathML Core as we can.
