### ISSUE TITLE
Refactor away from relative mpadded widths

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1804]
In the upcoming MathML Core recommendation, mpadded [width](https://www.w3.org/TR/2021/WD-mathml-core-20210816/#attribute-mpadded-width) is restricted to "a valid [length-percentage](https://www.w3.org/TR/2021/WD-mathml-core-20210816/#dfn-length-percentage)". This excludes the relative values such as `width="+5pt"`, `width="-2pt"`.

LaTeXML relies on these relative values in MathML.pm and Linebreaker.pm, and we should try to find a different formulation that achieves the same spacing effect.

Since the code seems to be dealing with left/right padding, maybe there is a way to translate that into a CSS-near "style" attribute with `padding-left` and `padding-right` values? For some standard cases we could also consider adding specialized spacing classes, which will be a little more configurable on the publisher end.

**Comment by dginev** [comment]
Good news-bad news early peek:

The experimental MathML Core support in Chrome does quite well (perfectly?) with a refactor that relies on "style", by just keeping the padding information. 

```tex
\quad x\ = 0
```

can translate to
```xml
<mrow>
  <mrow style="padding-left: 10pt; padding-right: 5pt;">
    <mi>x</mi>
  </mrow>
  <mo>=</mo>
  <mn> 0</mn>
</mrow>
```

Which already renders accurately in Chrome!

Yet the style attribute appears to be completely ignored in Firefox, so I won't be making that PR exactly today. But we could discuss if this looks like the right way forward?

I think it does, since standardizing all styling closer to CSS has a range of benefits: more reliable, but also allows to eventually simplify the MathML specification further, and get closer to the [one platform](https://bkardell.com/blog/OnePlatform.html) vision for the W3C ecosystem.

**Comment by dginev** [comment]
P.S. `\quad` may be the type of spacing where we can invent two classes `pad_left_quad` and `pad_right_quad`, and allow downstream vendor-provided CSS to make the final call on how much space that ought to be.

**Comment by dginev** [comment]
Here is the respective w3c/mathml issue, which still needs some resolution, cross-referencing for context:
https://github.com/w3c/mathml/issues/103

**Comment by dginev** [comment]
I should mention that we also have an option that may remain operational on all browsers, namely detaching from the underlying math tree and depositing standalone `<mspace>` elements - which is what mathjax and katex do today.

Say for `\quad`:
```xml
<mspace width="1em"></mspace>
```

or MathJax's even more careful:
```xml
  <mstyle scriptlevel="0">
    <mspace width="1em"></mspace>
  </mstyle>
```

**Comment by dginev** [comment]
Rather than opening a new issue, here is a comment with another problem that I stumbled on with the experimental Chrome support, namely the `maxsize` attribute on vertical bars in a superscript:

```xml
<math>
  <msup>
    <mi>ℝ</mi>
    <mrow>
      <mo maxsize="90%">|</mo>
      <mi>V</mi>
      <mo maxsize="90%">|</mo>
    </mrow>
  </msup>
</math>
```

which can be seen in Table 1 of [2202.06991](https://ar5iv.labs.arxiv.org/html/2202.06991).
rendered in Chrome with experimental MathML as:
![image](https://user-images.githubusercontent.com/348975/163690805-33df7a28-d2bb-4632-bb2c-b916c652cc3a.png)

This may be something to propagate to the Igalia team, as I believe maxsize is still allowed on the `mo` element. Recording here to keep these examples together.

**Comment by teepeemm** [comment]
Another consideration: it looks like a number of epub readers don't display `<mpadded width="-1.7pt"><mi>stuff</mi></mpadded>` when there is a negative width (in our case, this usually comes from `$stuff\!$`).  Calibre on Windows or Mac is the only ereader I've found so far that displays this snippet properly.  (The other alternative is to use `<xsl:template match="m:mpadded[starts-with(@width,'-')]"><xsl:apply-templates /></xsl:template>` to not use `mpadded` in that case.)

**Comment by dginev** [comment]
I have just [caught word](https://twitter.com/html5/status/1559527349842235393) that the Google Chrome 106 release, scheduled for Sep 27, is likely to ship with MathML Core fully enabled. 

Very exciting!!

In light of that advanced timeline (previous news was of a possible delay...) I will jump on this issue and see if I can get a PR out this week.

**Comment by dginev** [comment]
Correction: It will be Chrome 109, end of December, now [officially decided](https://groups.google.com/a/chromium.org/g/blink-dev/c/n4zf_3FWmAA/m/Bdn-zgJHCQAJ).

It should take about 6 weeks for a full arXiv rerun, so finalizing all MathML Core issues approximately by say November 10 will put us in a great position for the start of 2023. I'll try to keep my focus here...
