### ISSUE TITLE
\smashoperator bad conversion

### ISSUE THREAD

**Issue by FelixBenning** [brucemiller/LaTeXML#1818]
I once had the issue, of aligning equal signs when somehting is written on top of them. If the thing on top of it is larger than the equal sign it would result in a weird alignment. For this reason I created an `\lstackrel{"explanation"}{=}` which is defined like this

```tex
\newcommand*{\lstackrel}[2]{ %uses leftsides smashoperator thus ignoring overlap towards the left
    \mathrel{% makes the resulting stack a relation class (like =,<,>,...)
        \smashoperator[l]{\mathop{#2}^{#1}}
    }
}% use when aligning to the left
```
Using `\smashoperator` from the mathtools package.
In LaTeX this looks like this:
<img width="524" alt="Screenshot 2022-03-09 at 11 54 41" src="https://user-images.githubusercontent.com/29106652/157427867-f735bb93-3bae-42eb-9071-e032eabedc22.png">

When applying LaTeXML it on the other hand comes out like this:
<img width="621" alt="Screenshot 2022-03-09 at 11 55 39" src="https://user-images.githubusercontent.com/29106652/157428051-70e1d3dd-30bb-405b-90c6-f68eaabc3593.png">

The code is
```LaTeX
\begin{align*}
	\E\big[ \V(X\,|\,\G)\big] + \V\big( \E[X\,|\,\G]\big)
	&= \E\big[ \V(X\,|\,\G)\big] + \E\big[\E[X\,|\,\G]^2\big] -  \E\big[\E[X\,|\,\G]\big]^2 \\
	&= \E \big[ \V(X\,|\,\G)+\E[X\,|\,\G]^2\big] - \E\big[\E[X\,|\,\G]\big]^2 \\
	&\lstackrel{(\ref{conditional var repr})}{=}  \E\big[\E[X^2 \,|\,\G]\big] - \E\big[\E[X\,|\,\G]\big]^2 \\
	&= \E[X^2] - \E[X]^2 \\
	&= \V(X) \qedhere
\end{align*}
```

A possible reason might be, that the url size of the reference is somehow counted towards the space it takes

**Comment by brucemiller** [comment]
Your guess is exactly what was happening; fix on the way. Thanks for the report!
