### ISSUE TITLE
\cline

### ISSUE THREAD

**Issue by pksweby** [brucemiller/LaTeXML#1830]
Hi, we have chosen to use LaTeXML to convert legacy LaTeXML notes to be accessible. A colleague raised an issue with me about \cline not working. I discovered that under version 0.8.6 the line is not drawn, whereas under a previous version 0.8.4 it is.

The LaTeX code which demonstrates this is 

```tex
\[\begin{array}{rrrrrr}
                             &          &           &               & -3x& +1 \\
                             \cline{2-6}%\rule{0em}{5mm}
x^3 -3x^2 + 5x-15~ \Big)& -3x^4 & +10 x^3 & -15x^2 & +39x     & -9 \\
                           &3x^4   & -9x^3 &+15x^2   & -45x  & \\
                           \cline{2-5}%\rule{0em}{5mm}
                           &          &  x^3   &     & -6x &-9 \\
                           &          & -x^3      & +3x^2 &-5x & + 15  \\
                           \cline{3-6}%\rule{0em}{5mm}
                           &          &           &            3x^2   & -11x& +6 
\end{array}\]
```

(in addition, the \rule produces Unknown node type: span error once MathJax is loaded and so has been removed for now, but has no effect on whether line is drawn).

For now we have worked around the problem by redefining \cline to be the earlier version in a local .sty.ltxml file

many thanks

Peter

**Comment by brucemiller** [comment]
Ah weird; I think I got it fixed. Thanks for the report!
