### ISSUE TITLE
Markup for alignments via \hfill in headings and paragraphs

### ISSUE THREAD

**Issue by FelixBenning** [brucemiller/LaTeXML#1839]
I am using an existing header which right aligns parts using `\hfill` after using `latexml`, the previously right-aligned stuff is also left-aligned and displayed right after the left-aligned stuff

**Comment by dginev** [comment]
LaTeXML already tries to model `\hfill` and has an internal `isFill` property carried around - and at times used - to try and interpret how the fill should be represented in the XML.

But I do not think we have yet written the code needed to map that fill information to alignment markup for headers or regular paragraphs? Could be relatively easy to add.

**Comment by brucemiller** [comment]
Do you have a small example of what you're trying to use, so we can be sure we're dealing with the right problem? Thanks!

**Comment by brucemiller** [comment]
not really sure what to do.
