### ISSUE TITLE
mathimages fails on matrix with more than 10 columns

### ISSUE THREAD

**Issue by molke-productions** [brucemiller/LaTeXML#1843]
LaTeXML 0.8.6 fails at `--mathimages` with the following test:
``` LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
Default: 10 columns
\[
\begin{matrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10
\end{matrix},
\]
\setcounter{MaxMatrixCols}{11}
Eleven columns
\[
\begin{matrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11
\end{matrix},
\]
\end{document}
```
MathML works fine, so apparently the implementation doesn’t use any restriction on the column count.

In LaTeX, `amsmath` defines the counter and sets a default value:
``` TeX
\newcount\c@MaxMatrixCols \c@MaxMatrixCols=10
```
while I can’t find any place where `MaxMatrixCols` is defined or used in LaTeXML.

**Comment by brucemiller** [comment]
That's just weird; I'd never noticed that restriction.

At any rate, fix is on the way. Thanks for the report!
