### ISSUE TITLE
Interleaving HTML with MathML, round 3

### ISSUE THREAD

**Issue by FelixBenning** [brucemiller/LaTeXML#1844]
latexml puts link tags (`<a>`)  into the mathml code, which causes MathJax to throw an error. This appears to be [expected behavior](https://github.com/mathjax/MathJax/issues/2860#issuecomment-1090868567).

Question is whether latexml wants to accommodate MathJax in order to generate working pages on browsers other than firefox or hope that these issues will solve themselves over time (e.g. MathJax apparently wants to fix this by summer)

**Comment by xworld21** [comment]
I have mentioned this in https://github.com/brucemiller/LaTeXML/issues/1708#issuecomment-973214264, but I can offer a more complete workaround: use `--stylesheet=mathjax-html5.xsl`, where the `mathjax-html5.xsl` file contains the following
```xslt
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
    version   = "1.0"
    xmlns:xsl = "http://www.w3.org/1999/XSL/Transform"
    xmlns:m   = "http://www.w3.org/1998/Math/MathML">

  <!-- include the standard LaTeXML html5 stylesheet -->
  <xsl:import href="urn:x-LaTeXML:XSLT:LaTeXML-html5.xsl"/>

  <xsl:template match="m:mtext[*]">
    <semantics>
      <xsl:for-each select="@*">
        <xsl:apply-templates select="." mode="copy-attribute"/>
      </xsl:for-each>
      <annotation-xml encoding="text/html" style="display: block;">
        <xsl:apply-templates/>
      </annotation-xml>
    </semantics>
  </xsl:template>

</xsl:stylesheet>
```
The generated HTML5 will have `<semantics>` in place of `<mtext>` whenever `<mtext>` is not pure text. It seems to work with MathJax (see the example https://vlmantova.github.io/bookml/#S4.F2).

If you call the file `LaTeXML-html5.xsl`, in the same folder where you run latexmlpost, it will be applied automatically without the `--stylesheet=` option.

**Comment by FelixBenning** [comment]
@xworld21  that looks interesting but I am not quite sure what that entails. So I assume that this xsl overrides the default template and changes the template for `m:mtext[*]` right? But that also means it will be changed for browsers that do in fact support mathML - won't that cause troubles there?

I really need to read up on XSLT

**Comment by xworld21** [comment]
@FelixBenning yes, the stylesheet transforms `<m:mtext>` into `<semantics>` (with no namespaces as I am assuming you do plain HTML5). The test `[*]` checks that `<m:mtext>` contains some XML elements, so simple text won't be affected.

> But that also means it will be changed for browsers that do in fact support mathML - won't that cause troubles there?

I had the same concern, but in my (admittedly very limited) tests, Chrome, Firefox and Safari all seem to render `<semantics>` tags just like `<mtext>`. I haven't tested it seriously with screen readers, though.
