### ISSUE TITLE
Test t/tokenize/verb.tex inconsistent between texlives

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1848]
I was seeing discrepancies in an unnamed porting effort, and when I tried to regenerate the PDF, I stumbled on:
```
! LaTeX Error: \verb ended by end of line.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.53 {\verb tricky} }
```

which was a hard error. This pointed out that latexml is using the space character as a `\verb` delimiter, which is not what my `latex` executable does in texlive 2021. Maybe this has changed, maybe it was always broken?

For the same reason, a different part of the test has the XML:
```
<para xml:id="S2.p9">
      <p><verbatim font="typewriter">|a}b#c^d_e$f|</verbatim>stuff</p>
    </para>
```

but in the PDF output, the two vertical bars are not displayed - as | is used as the fencing char.

**Comment by dginev** [comment]
Sigh. I went and checked today with an older texlive. The `verb.pdf` is indeed correct there. I am attaching images for the two PDFs I am seeing with my slightly modified source that can compile in both texlives -- producing different outputs.

The main difference is at the end -- spaces are no longer used as delimiters.

2015 | 2021
:------:|:-------:
<img width="400" src="https://user-images.githubusercontent.com/348975/163625200-a7545166-f29a-4aa8-8805-9ca75f580db5.png"> | <img width="400" src="https://user-images.githubusercontent.com/348975/163625290-bb5fa2bd-473c-403b-a9e7-2190539a5b92.png">


This sadly adds a whole lot of uncertainty as to what may be a productive issue resolution. Should we take a step back and emulate `\verb` from the raw texlive installation? Sounds highly unpleasant. Alternatively, should we check if we are running in a modern texlive, and have the second behavior in those cases?

I checked several texlives back and v2021 is the first that has this new behavior that avoids using spaces. from 2015 to 2020 we consistently get the PDF that is currently in `t/tokenize/verb.pdf`. 

At this point, I'll definitely welcome some thoughts by @brucemiller .

**Comment by dginev** [comment]
An even weirder update from the recent texlive 10.2022 testing. The test no longer converts error-free:

```
$ cd LaTeXML/t/tokenize ; pdflatex verb.tex 
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./verb.tex
LaTeX2e <2022-06-01> patch level 5
L3 programming layer <2022-09-28>
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(./verb.aux)
Underfull \hbox (badness 10000) detected at line 40
\OT1/cmr/bx/n/10 x[]\OT1/cmtt/m/n/10 \verb\OT1/cmr/bx/n/10 y.

! LaTeX Error: \verb ended by end of line.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.53 {\verb tricky} }
```

Is it still a good test?

**Comment by dginev** [comment]
Hi David! @davidcarlisle If I may borrow your attention for a minute, it would be a big help. I'll try to be as brief as possible.

We seem to have noticed a discrepancy between texlives 2015-2020 and 2021 with the PDFs generated for one of the latexml tests. I would like to ask your opinion if there is a new/old **correct** behavior, or should we try to live with both variants?

The minimal example is:
```tex
\documentclass{article}
\begin{document}
\verb | a | .
\end{document}
```

where the question is whether `\verb` *should* use the space characters as delimiters, or instead skip space. Thanks in advance for any thoughts!

**Comment by davidcarlisle** [comment]
I'd forgoten about that but it was an intentional bug fix/change  

base/ltmiscen.dtx has

```
%<latexrelease>\IncludeInRelease{2020/10/01}%
%<latexrelease>                 {\@sverb}{Drop spaces before \verb delimiter}%
%    \end{macrocode}
%    
%    If the users types \verb=\verb !~! foo= then surprisingly we would
%    get the space as the delimiter and thus
%    ``\verb=!~!foo='' in the output.
%    To avoid this scenario we check if  \verb=#1= has the character
%    code of a space, if so we recurse otherwise we call \cs{@@sverb}
%    (which is the original definition of \cs{@sverb}.
% \changes{v1.1u}{2020/04/22}{Drop spaces before \cs{verb} delimiter (gh/327)}
%    \begin{macrocode}
\def\@sverb#1{\if\noexpand#1 \expandafter\@sverb\else\@@sverb{#1}\fi}
```

see latex3/latex2e#327

**Comment by brucemiller** [comment]
Aha! The surprising use of space as a delimiter is exactly why that line was added in the test case.  The test case is easily adapted to not cause errors and work (but differently) in the various texlive versions.  And LaTeXML can adopt the new behaviour by removing 1 line ---  @dginev Should I go ahead and PR that?

@davidcarlisle Thanks for the clarification. The new behaviour is obviously more sensible, but also kind of "breaking";  the discussion on latex2 was enlightening.  I need to watch those repos more carefully!

**Comment by dginev** [comment]
Sounds good @brucemiller ! Glad that we now have a clear picture what happened, and a clear resolution to move to the new behavior.

And indeed: going forward we may want to track the merged PRs in `latex3/latex2e`, to preempt any subtle changes we may not otherwise realize are coming. Maybe we can do that once every so often, e.g. when we do the annual release prep? I recall there was a checklist for that somewhere... Ah yes, we could add to `LaTeXML/release/notes`.
