### ISSUE TITLE
gensymb and mathimages

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1852]
Processing
```
\documentclass{article}
\usepackage{gensymb}
\begin{document}
$a\degree$
\end{document}
```
with `latexml` and the result with `latexmlpost --mathimages` throws the latex error:
```
Undefined control sequence \lx@math@degree
```
Perhaps `\degree` shouldn't b expanded by `latexml`?

**Comment by brucemiller** [comment]
Needs an alias for the internal command; Fix on the way. Thanks for the report!
