### ISSUE TITLE
The command in PowerShell is not recognized

### ISSUE THREAD

**Issue by ToastDoggo** [brucemiller/LaTeXML#1853]
Hello, I've installed the program through Chocolatey because it said that it also installs all the prerequisites, but when I try to use the program it says that the command is not recognized, I also can't see anything out of ordinary on the logs.
![image](https://user-images.githubusercontent.com/94985056/167384338-62ef7538-ecdd-439e-92d3-dfb7ee4cce7c.png)
I'm using Windows 10.
I've been looking for the problem around but I haven't seen anyone else posting it, sorry if it's duplicated. Thank you for your attention 😄

**Comment by dginev** [comment]
@ToastDoggo This looks like a path issue with Chocolatey, where the paths of the installed latexml are not made available in PowerShell.

I wonder if it would be worth opening an issue at [metanorma/chocolatey-latexml](https://github.com/metanorma/chocolatey-latexml) and cross-referencing this one here? If they help you diagnose what went wrong, we can try to make any needed amends on our end.

**Comment by dginev** [comment]
I'm going to close here, since it seems like we can't be of much further help on our end.
