### ISSUE TITLE
Referring to a listings line number

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1867]
The TeX
``` tex
\documentclass{article}
\usepackage{listings}

\begin{document}
\section{Section Title}
\begin{lstlisting}[escapechar=|,firstnumber=4,numbers=left]
print("Label me!");|\label{line:sp}|
\end{lstlisting}

``Line~\ref{line:sp}'' should be ``Line~4''.
\end{document}
```
generates a pdf that says `“Line 4” should be “Line 4”.`, an XML that has
``` xml
<listingline labels="LABEL:line:sp" xml:id="lstnumberx1"><tags>
    <tag>4</tag>
  </tags><text class="ltx_lst_identifier">print</text>(”<text class="ltx_lst_identifier">Label</text><text class="ltx_lst_space"> </text><text class="ltx_lst_identifier">me</text>!”);</listingline>
```
and an HTML that says `“Line 1” should be “Line 4”.`. It appears that the reference is to the section number instead of the line number.

**Comment by brucemiller** [comment]
Interesting; someone else was asking a similar question about random use of `\refstepcounter` and `\label` and why they didn't connect up.  Maybe LaTeXML's approach is too formal (assumes only "Important" things should be labelled).  I have a mental model of a more flexible approach, but will have to work it out...
