### ISSUE TITLE
filenames clashing?

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1872]
Something I came across recently: Windows and Mac OS X have case insensitive file systems.  This means that when genpods converts bin/latexml to doc/manual/pods/latexml.tex and lib/LaTeXML.pm to doc/manual/pods/LaTeXML.tex, the latter is overwriting the former.  The easy fix is for the bins to go to a different file, but this has me wondering if I'm overlooking some way to avoid this happening, or if only Unixy people have been making the manual beforehand and no one really noticed this was happening.

**Comment by dginev** [comment]
Good catch! Didn't realize this was going on either.
