### ISSUE TITLE
Can latexmlpost create an epub?

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1873]
`latexmlc myfile --dest=myfile.epub` will correctly create an epub file.

`latexml myfile --dest=myfile.xml` and then `latexmlpost myfile --dest=myfile.epub` will claim to create `myfile.epub`, but it actually creates the xhtml version and names it as an epub.

Since the xml creation is the time consuming part, I would like to do that as rarely as possible, and then go from that point to a website or epub.

I don't understand the executables well enough to see how they work, but is there anything stopping us from having `latexmlpost` also be able to create an epub?

**Comment by dginev** [comment]
Hi @teepeemm - that is a good observation - only `latexmlc` can create ePub at the moment.

The intention has been for the longest time to move a little closer to a single executable which can do all of 1) core processing, 2) post-processing, 3)joint core+post processing, based on the initial experiment with `latexmlc`. I think that intention is still there.

For now, only latexmlc can generate ePub, as you have noticed.

**Comment by teepeemm** [comment]
And for posterity: it appears that I'll need to watch #1496 (and maybe #1497) in order to have latexmlc create the epub from the xml.
