### ISSUE TITLE
converting problems

### ISSUE THREAD

**Issue by sparkyqin** [brucemiller/LaTeXML#1905]
Dear friend,
For this paper https://arxiv.org/abs/nucl-th/0002023v1, I use following command to convert it to html
`latexmlc --dest=doc.html  mix_delrho`
and it thows following waring and error
`Warning:unexpected:\bm \bm should only appear in math mode`
`Error:malformed:ltx:biblist Attempt to close </ltx:biblist>, which isn't open`
but when I use ar5iv, https://ar5iv.labs.arxiv.org/html/nucl-th/0002023v1, there is no above waring and error.
So is there something wrong with my command, and may I know the converting command using in ar5iv? Thanks.

**Comment by dginev** [comment]
Hi @sparkyqin ,

I see that you also opened an issue at the ar5iv repository [here](https://github.com/dginev/ar5iv/issues/169), which is indeed the better place to answer the question. I will close here and anyone interested can jump over to the other repository.
