### ISSUE TITLE
Can we make \iflatexml readonly within latexml.sty ?

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1907]
This will be either a question or a suggested enhancement.

In [latexml.sty](https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/texmf/latexml.sty#L15), we have `\newif\iflatexml\latexmlfalse`.  At the corresponding place in [latexml.sty.ltxml](https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/latexml.sty.ltxml#L27), we have
``` perl
DefConditional('\iflatexml', sub { 1; });
DefPrimitive('\latexmltrue', sub {
    Warning('unexpected', '\\latexmltrue', $_[0], "Cannot change \\iflatexml!"); });
DefPrimitive('\latexmlfalse', sub {
    Warning('unexpected', '\\latexmlfalse', $_[0], "Cannot change \\iflatexml!"); });
```
We don't appear to show a similar warning within latexml.sty.

Would it work to instead have
``` tex
\let\iflatexml=\iffalse
\newcommand{\latexmltrue}{\PackageWarning{latexml}{Cannot change \string\iflatexml!}}
\newcommand{\latexmlfalse}{\PackageWarning{latexml}{Cannot change \string\iflatexml!}}
```
My initial testing shows that it would work out, but I don't know if I'm missing anything.

**Comment by brucemiller** [comment]
Or alternatively, remove the warnings from `latexml.sty.ltxml`?

Is there a danger of people unintentionally changing them? (other than intentionally for debugging purposes)

**Comment by teepeemm** [comment]
Removing the warnings entirely could make sense.  I don't know of any LaTeX booleans that are actually read only, so I don't know that we would want to be an exception.

**Comment by teepeemm** [comment]
To follow up on this, should I submit a PR to remove the warnings from `latexml.sty.ltxml`?

It does seem more in the spirit of TeX to assume the user knows what they're doing when they change a boolean.

**Comment by dginev** [comment]
@teepeemm Since you and Bruce seem to have reached the same conclusion, let me encourage you to make a PR - it seems there is a high likelihood we'll merge it :>
