### ISSUE TITLE
\hat in combination with \middle eats \vert delimiter

### ISSUE THREAD

**Issue by jgmakin** [brucemiller/LaTeXML#1916]
MWE:
```tex
\documentclass[11pt,letterpaper]{report}

\begin{document}

$p\left(\hat{x}\middle\vert y\right)$: delimiter vanishes

$p\left(x\middle\vert \hat{y}\right)$: delimiter vanishes


$p\left(x\middle\vert y\right)$: no problem with no diacritic

$p\left(x\middle\vert \check{y}\right)$: no problem with another diacritic

$p\left(\hat{x}\vert y\right)$: no problem without middle

$p\left(\hat{x}\| y\right)$: no problem w/a different middle delimiter


\end{document}
```
All of these conditional expectations come out right under pdflatex.

**Comment by dginev** [comment]
Thank you for the report @jgmakin !

Here is what I am seeing with the latest latexml master, using Firefox - does this match up on your end?

```
$ latexml -V
latexml (LaTeXML version 0.8.6; revision d17c2871)
```

![latest latexml rendering of reported issue](https://user-images.githubusercontent.com/348975/184450563-f3299535-e94c-4b4c-aecd-b2dcad87e218.png)

And here is the PDF:
![image](https://user-images.githubusercontent.com/348975/184450670-ed0de981-8aa1-493d-a3f9-8f5adcb88725.png)

**Comment by jgmakin** [comment]
Thanks for the very quick response.

This is what I get:

![image](https://user-images.githubusercontent.com/5614540/184459056-7f881817-42ee-47dd-87c6-f52bed25e69e.png)

But you're right, it's not a bug!  It's just that at this screen resolution, the vertical bars are in the first two cases invisible.  But zooming in I can see them again.  I apologize for raising the issue and thanks.

**Comment by dginev** [comment]
Good to hear @jgmakin ! Could you also let me know what screen resolution and browser+device combination you are using when the bar vanishes? 

This would be good to know more about in general, maybe there is a different path to avoiding the broken rendering...
