### ISSUE TITLE
ugly lists with SIMPLIFY_HTML

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1918]
Lists are now ugly when passing `--xsltparam=SIMPLIFY_HTML:true`:
![image](https://user-images.githubusercontent.com/1962985/184681065-46ba1398-1f20-4044-970b-28130fc6fbd3.png)
because the `display: inline` rule is activated by the selector `.ltx_item .ltx_tag + .ltx_para`, and there is no `.ltx_tag` when the output is simplified.

**Comment by brucemiller** [comment]
As near as I can recall it (which is only barely), the point of `SIMPLIFY_HTML` was to dumb down the output by omitting the tag for when CSS wasn't even available to disable the default `list-style-type`.  So, I'm not really clear what is expected in this case.

**Comment by xworld21** [comment]
> So, I'm not really clear what is expected in this case.

I think `.ltx_item .ltx_tag + .ltx_para` should rather be `.ltx_item:nth-child(1 of .ltx_para)`, i.e. the inline style should be applied to the first child paragraph, whether the tag is there or not. Otherwise with SIMPLIFY_HTML the alignment of the first paragraph is wrong, as you can see from the exaggerate spacing between "1." and "test" in the example (it may be indentation).

**Comment by brucemiller** [comment]
But such hairy selectors are kinda ironic, given that the whole reason for having `SIMPLIFY_HTML` is for contexts with no (or minimal) css support.  Omitting the `<tag>` means that the items will get whatever numbering the user agent applies, and which means it will *not* match the tag that LaTeX (& LaTeXML) thought the item would have. (eg what you'd see with `\label` and `\ref`).

**Comment by xworld21** [comment]
> In other words, "not really clear what is expected" is in the sense that if you're concerned about the aesthetics, you probably don't want to be using `SIMPLIFY_HTML` in the first place.

That's fair. Interestingly, I was sure that `SIMPLIFY_HTML` was styled correctly in 0.8.5, as I was using it for old accessibility concerns (now irrelevant). But my memory is quite wrong: the paragraph gets indented with 0.8.5 and 0.8.4 too. A possible fix is `.ltx_item > .ltx_para:first-child > .ltx_p:first-child {text-indent:0em;}`.

However I now notice that the documentation is quite clear about the purpose of `SIMPLIFY_HTML`. I missed that.

**Comment by dginev** [comment]
What is the expected resolution here? @xworld21 are you suggesting a patch to the CSS?

I must admit that I haven't used `SIMPLIFY_HTML` myself, so it's hard for me to estimate if we can close with "worksforme" or if we should be improving the CSS quality.

**Comment by xworld21** [comment]
> What is the expected resolution here? @xworld21 are you suggesting a patch to the CSS?

I forgot about this issue! This is exactly the same problem as #2158, that's why it looked familiar: the CSS selector is coupled with the presence of `.ltx_tag`, so it's broken with `SIMPLIFY_HTML`, and also used to be broken with suppressed labels until you re-added an empty tag.

I believe there is scope for more robust CSS selectors that follow the schema, preempting this kind of issues (e.g. the schema says that an item contains an optional tag and anything from the Para model, so the CSS shouldn't assume that the tag is present).

Other than that, I think that `SIMPLIFY_HTML` is broken enough for other reasons (it resets custom enumerations, thus it drops content!) so you can close the issue as far as I am concerned.

**Comment by brucemiller** [comment]
I suppose you can call `SIMPLIFY_HTML` as "broken by design"; you really aren't expected to use it except in the most restricted circumstances, and then not try to restyle it.
