### ISSUE TITLE
support SOURCE_DATE_EPOCH

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1919]
It would be nice to support [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/), which would allow for (mostly) reproducible outputs.

**Comment by nschloe** [comment]
This is fixed by https://github.com/brucemiller/LaTeXML/pull/1920 and released in 0.8.7. Can be closed. Use as

```
export SOURCE_DATE_EPOCH=1641023584
```
(for Jan 1, 2022).
