### ISSUE TITLE
enumitem package parameters not working ?

### ISSUE THREAD

**Issue by dfrankow** [brucemiller/LaTeXML#1927]
I wrote

```
\usepackage{enumitem}

% ...

\begin{enumerate} [label=,wide=0pt,nosep]
\item item 1
\item item 2
\end{enumerate}
```

In the PDF I generate with LaTeX, it looks like:

> item 1
> item 2

However, in the book.html it looks like:

> [label=,wide=0pt,nosep]
> 1. item 1
> 2. item 2

Perhaps the `enumitem` isn't being used?

The command I used to generate:

```
latexml --dest ../book.xml main.tex
latexmlpost  -dest=../book.html  ../book.xml
```

I'm using `latexml` 0.8.5.

**Comment by dginev** [comment]
Thanks for the report @dfrankow . It looks like latexml's enumitem got confused by the space separator before the optional argument. A short-term fix on your end would be:

```tex
\begin{enumerate}[label=,wide=0pt,nosep]
```

until we get the latexml binding to also accept the spaced out variant.

**Comment by brucemiller** [comment]
> until we get the latexml binding to also accept the spaced out variant.
Or until we figure out exactly which situations with which packages
ignore a space before "[" and which don't!

**Comment by dfrankow** [comment]
For some reason, I thought I needed the space. (I thought I got an error without it, or it was advised on some website. I can't remember.) However, when I try it without the space it works fine.

Thank you!

**Comment by dginev** [comment]
@brucemiller indeed, this may be a lot more general. It appears that any use of `\newenvironment` and `\renewenvironment` with an optional argument will allow an arbitrary number of spaces. This snippet works out for example:
```tex
\documentclass{article}

\newenvironment{foo}[1][]{}{}
\newenvironment{baz}{}{}
\renewenvironment{baz}[1][]{pre}{post}

\begin{document}
\begin{foo}                             [label=,wide=0pt,nosep]
FOO
\end{foo}

\begin{baz}                             [label=,wide=0pt,nosep]
BAZ
\end{baz}

\end{document}
```

And indeed latexml does the Right Thing for explicit uses of `\newenvironment` and `\renewenvironment` already, which is neat - this example comes out correct.

The enumitem.sty environments are all accomplished internally via `\renewenvironment`, so the dots connect there.

The next question would be which environments _shouldn't_ skip spaces before an optional argument, if any. That may be harder to answer...

**Comment by brucemiller** [comment]
Many or all of the ams commands avoid skipping spaces, at least on `\\", since math often starts with "[" (and remember "\n" is space!).

But I had thought that this stuff was working correctly, so maybe a small bug has crept in. Have to track what happened...
