### ISSUE TITLE
errors with nested list's

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1961]
The following code
```latex
\newcounter{question}
\newcounter{subquestion}
\begin{list}{\textbf{\thequestion.}}{\usecounter{question}}
  \item One.
  \item Two.
  \begin{list}{\emph{\thesubquestion.}}{\usecounter{subquestion}}
    \item a.
    \item b.
  \end{list}
\end{list}
```
triggers something odd with the counters:
```
Error:undefined:\thequestioni@ID The token T_CS[\thequestioni@ID] is not defined. at test.tex; line 56 col 0
```
Of course the output is not quite right.

I think the culprit are `\usecounter` and `beginItemize` (LaTeXML.pool.ltxml), but I can't completely make sense of it.

**Comment by dginev** [comment]
Thank you for the report.
I think that is a limitation to the custom `\list` implementation in LaTeX.pool.ltxml.

And the snippet you have provided would be a good new test to add, once we have the support fleshed out.

**Comment by dginev** [comment]
I think we also have variants of this error also hurting the arXiv conversion, where the `error:undefined` report shows 351 distinct unknown macros ending in `@ID`.
