### ISSUE TITLE
Question: how can I add some text to the footer?

### ISSUE THREAD

**Issue by user4815162342** [brucemiller/LaTeXML#1968]
I'm converting a book to html5, split by chapters, and I'm trying to add a copyright notice into the footer of each page. 

I've got a few books I'm generating from, each with slight variations in the copyright text. I also want to keep it the same as the PDF versions. So I want to be able to pass the text from the latex code.

So far, I've added the code `\@add@frontmatter{ltx:note}[role=footerlegal]{\getfooterlegal}` into my style file, which according to issue #1838 seems to be a good way of adding custom metadata. I then customized the XSLT to produce a different footer that includes `<xsl:copy-of select="//ltx:note[@role='footerlegal']"/>` to add that text to the webpage. 

Given as I'm new to XSLT, I was pleasantly surprised to see that work. Unfortunately, it only works on the first page of the website. The text does not appear on the pages for any of the chapters. As far as I can tell, that xml node is not passed through to the XML for the chapter splits.

Is there some way I can create some metadata that rides along with the navigation text, which does get added to each chapter? Is there a better approach to get what I want here?

**Comment by dginev** [comment]
@user4815162342 we have some utility macros in `latexml.sty`, and I think two apply directly to header/footer boilerplate. You can try using `{lxFooter}` and `{lxHeader}` environments.

So this ought to work:
```tex
\documentclass{book}
\usepackage{latexml}
\begin{document}
\chapter{C1}
Hello
\chapter{C2}
World.
\begin{lxFooter}
  footer boilerplate.
\end{lxFooter}
\end{document}
```

converted with:
```
$ latexmlc test.tex --splitat=chapter --dest=test.html
```

Let me know if this helps.

**Comment by dginev** [comment]
Also, you may already be aware of this, but there is also a simple trick to have different behaviors in PDF and latexml's HTML by using `\iflatexml` (also from `latexml.sty`).

So you can make the footer directive latexml-only via:
```tex
\iflatexml
  \begin{lxFooter} footer boilerplate. \end{lxFooter}
\fi
```

**Comment by user4815162342** [comment]
Thank you. That worked.

But that replaces the navigation links and latexml logo. Is there any way that I can add those back in, or will I have to check the xslt to do that?

**Comment by dginev** [comment]
Right, that is a non-standard default that is currently induced by the XSLT. You can copy the line from `LaTeXML-webpage-xhtml.xsl`:

```xslt
<xsl:apply-templates select="." mode="footer-generator-identifier"/>
```

to also execute after the code that copies an existing footer, so after this line in the same file:
```xml
<xsl:apply-templates select="//ltx:navigation/ltx:inline-para[@class='ltx_page_footer']/*"/>
```

I think this is the first time someone has requested using latexml's default footer boilerplate together with their own footer content, which is why there is no easy way of doing it yet. We can add an XSLT parameter that marks that preference, if you'd prefer using a command-line option such as

```
--xsltparameter=lxFooterLogo:true
--xsltparameter=lxFooterLogo:false
```

**Comment by user4815162342** [comment]
Thank you, that worked.

The xslt parameter would be useful, but if I'm the only one asking,  I'll leave it up to you whether that's worth doing. I installed latexml via package manager, so any changes to the code will take some time to get updated on my system.

If it were completely up to me, I would prefer commands that could be used in the latex code to insert the navigation links or logo into the footer where they are needed. But, I don't know if that fits the vision for the project, and that sounds like more work than the xslt parameter.

I have to say, this is the quickest responses I've ever gotten from a github issue.

**Comment by dginev** [comment]
> I have to say, these are the quickest responses I've ever gotten from a github issue. Thanks again.

I am afraid responding here is the easiest thing I get to do this Monday morning. You're welcome!

I will close here for now, and we'll keep the potential extensions in mind for the next time we touch those pieces of the code base.
