### ISSUE TITLE
Is it possible to convert presentation MathML to content MathML?

### ISSUE THREAD

**Issue by ualiangzhang** [brucemiller/LaTeXML#1977]
I did several tries, but still couldn't figure out how to convert presentation MathML to content MathML using LaTeXML. Thanks!

**Comment by dginev** [comment]
@ualiangzhang for LaTeXML the only input language is TeX itself, and the various supported LaTeX packages, such as amsmath.

We do not try to convert between different flavors of MathML, and do not take MathML as input.

But indeed we have both Presentation and Content MathML supported. The important options to remember are `--pmml` for enabling Presentation MathML and `--cmml` for enabling Content MathML.

As one minimal example, you can try:

```
$ latexmlc 'literal:\sqrt{n}' --whatsin=math --whatsout=math --format=html5 --pmml --cmml
```

Which will output a fragment of cross-referenced Presentation+Content MathML for a square root:

```xml
<math id="p1.m1" class="ltx_Math" alttext="\sqrt{n}" display="inline">
  <semantics>
    <msqrt id="p1.m1.2" xref="p1.m1.2.cmml">
      <mi id="p1.m1.1" xref="p1.m1.1.cmml">n</mi>
    </msqrt>
    <annotation-xml encoding="MathML-Content">
      <apply id="p1.m1.2.cmml" xref="p1.m1.2">
        <root id="p1.m1.2a.cmml" xref="p1.m1.2"></root>
        <ci id="p1.m1.1.cmml" xref="p1.m1.1">𝑛</ci>
      </apply>
    </annotation-xml>
  </semantics>
</math>
```

Let me know if this helps - and thanks for the question!

**Comment by ualiangzhang** [comment]
@dginev Thank you for your quick response! I was thinking if I could wrap presentation MathML into an XML or HTML file, and then use "latexmlpost --cmml --destination=test.html test.xml" to convert P MathML to C MathML. But, it still returns P MathML.

**Comment by dginev** [comment]
Yes, that is out of scope for latexml . To use our content generation you would have to convert PMML back to TeX and then feed that TeX formula as input.

What kinds of mathematics are you trying to process? For some types of syntax out Content dialect is also a bit limited at the moment.

**Comment by ualiangzhang** [comment]
Thank you again! I now need to process Presentation MathML (for general equations) to generate specific diagrams, but Content MathML is easier to work with. So, I want to convert from P MathML to C MathML first.

**Comment by dginev** [comment]
Alright, I'll close here for now. You may want to address the general question to the www-math mailing list, where the wider MathML community may have better answers.

Details here:
https://lists.w3.org/Archives/Public/www-math/

**Comment by ualiangzhang** [comment]
I do appreciate your help!
