### ISSUE TITLE
quotation environment paragraphs are converted into breaks

### ISSUE THREAD

**Issue by user4815162342** [brucemiller/LaTeXML#1978]
For some reason, my multi-paragraph quotation environments are separated by `<br/>` instead of converting them into multiple `<p>` elements. I've traced it as far back as the XML output of latexml, where `<break/>` elements are inserted where there should be new paragraphs. I don't know enough about perl to trace it back any further than that, but I'm pretty sure the XSLT will convert that `break` to a `br`.

The input latex file:

```tex
          \documentclass{book}
          
          \begin{document}
              
          \begin{quotation}
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras luctus ligula diam, sit amet laoreet nulla ultrices at. Morbi mollis feugiat felis ac molestie. Vestibulum pellentesque metus magna, in iaculis tellus porta vel. 
              
              Nunc tempor turpis dolor, ac viverra leo suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec non libero risus. Aliquam nulla dui, varius sit amet dolor vel, dapibus malesuada magna.
          \end{quotation}
                    
          \end{document}
```

The output xml:

```xml
          <?xml version="1.0" encoding="UTF-8"?>
          <?latexml searchpaths="/home/neil/Role Playing Games/Projects/rpg-latex"?>
          <?latexml class="book"?>
          <?latexml RelaxNGSchema="LaTeXML"?>
          <document xmlns="http://dlmf.nist.gov/LaTeXML">
            <resource src="LaTeXML.css" type="text/css"/>
            <resource src="ltx-book.css" type="text/css"/>
            <para xml:id="p1">
              <quote>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras luctus ligula diam, sit amet laoreet nulla ultrices at. Morbi mollis feugiat felis ac molestie. Vestibulum pellentesque metus magna, in iaculis tellus porta vel.
          <break/>
          Nunc tempor turpis dolor, ac viverra leo suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec non libero risus. Aliquam nulla dui, varius sit amet dolor vel, dapibus malesuada magna.</p>
              </quote>
            </para>
          </document>
```

**Comment by dginev** [comment]
Thank you for reporting the expectation @user4815162342 . Indeed, this is intentionally implemented this way for `{quote}`, `{quotation}` and `{verse}`, as seen in [LaTeX.pool, C.6.1](https://github.com/brucemiller/LaTeXML/blob/73f0af6072be68fd3fca4d996577404f9e883893/lib/LaTeXML/Package/LaTeX.pool.ltxml#L1397).

Looking at the pdflatex output for your example, there indeed appear to be two separate paragraphs, as one would obtain via the usual `\\`. 

Here's the PDF output for the 3 environments:
<img width="600px" src="https://user-images.githubusercontent.com/348975/198904517-aa4a9e11-64ab-4024-8dd0-f6069e06ca9c.png">

**Comment by dginev** [comment]
Maybe @brucemiller remembers the original reasoning for the soft break in a single paragraph? If it no longer applies, we could switch to the usual paragraph breaks.

**Comment by user4815162342** [comment]
Thank you. As a workaround, I'm putting the following in the .ltxml file for my custom style, which seems to resolve the issue:

```
    DefEnvironment('{quotation}','<ltx:quote>#body</ltx:quote>');
```
