### ISSUE TITLE
Bug somewhere in latex3 ior-package

### ISSUE THREAD

**Issue by Jazzpirate** [brucemiller/LaTeXML#1984]
The following yields an empty HTML:
```
\RequirePackage{expl3}
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\ior_new:N \temp_ior
\ior_open:Nn \temp_ior {SOME_NONEMPTY_FILE}
\ior_map_inline:Nn \temp_ior {
    Here:~#1\par
}
\ior_close:N \temp_ior
\ExplSyntaxOff
\end{document}
```
but correctly yields the file contents line by line with `pdflatex`.

The "traditional" way to do the same works, however, so there's *something* buggy with LaTeXML's interpretation of the `\ior_`-macros in expl3:
```
\RequirePackage{expl3}
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\newread\temp_ior
\openin \temp_ior = SOME_NONEMPTY_FILE\relax
\def\loop{
    \ifeof\temp_ior\else
        \readline \temp_ior to \temp_line
        Here:~\temp_line\par
    \expandafter\loop\fi
}
\loop
\closein \temp_ior
\ExplSyntaxOff
\end{document}
```

using latest version of LaTeXML and with TeXLive packages updated earlier this week

**Comment by dginev** [comment]
I ran a check today and the reported example now works with the latest LaTeXML from the repository, when testing with `texlive 2022` on Ubuntu.

We may want to double-check if the latest `2023` texlive is also operational, and resolve the issue as fixed.

**Comment by Jazzpirate** [comment]
awesome - one step closer for sTeX+LaTeXML :)

**Comment by dginev** [comment]
Just confirmed this now converts correctly with texlive 2023 (although it takes 20 minutes, so I wouldn't recommend it to users for now).

Closing as fixed 🎉
