### ISSUE TITLE
Problems when a url has a percent sign

### ISSUE THREAD

**Issue by jimhefferon** [brucemiller/LaTeXML#1986]
In the file below, I get an error from LaTeXML.  (I'll note that the input file has ten lines.)
```
jim@millstone:~/src/computing/tmp$ latexmlc test.tex --dest=test.html --includestyles
latexmlc (LaTeXML version 0.8.6; revision e52efffc)
processing started Sat Nov 12 08:00:40 2022
Error:expected:} Gullet->readBalanced ran out of input in an unbalanced state. at test.tex; line 11 col 0
Error:expected:{} Missing argument {} for Core::Definition::Expandable[\href Semiverbatim{}] at test.tex; line 13 col 0
Warning:unexpected:\end{document} Attempt to end document with open groups, environments or conditionals at test.tex; line 14 col 0
Error:unexpected:<closed> Mouth is unexpectedly already closed at String; line 0 col 0
Error:unexpected:<endgroup> Attempt to pop last locked stack frame at String; line 1 col 0
Error:expected:{} Missing argument {} for Core::Definition::Constructor[\@@Url Undigested{}{}Semiverbatim{}] at String; line 2 col 0
Conversion complete: 1 warning; 5 errors (See /home/jim/src/computing/tmp/test.latexml.log)
Post-processing complete: No obvious problems
Status:conversion:2
jim@millstone:~/src/computing/tmp$
```

If I run it through pdfLaTeX then I get no error and the link points to a URL with a percent sign (I have an up to date TeX Live).  If I comment out the first \href{}{} and uncomment the second then LaTeXML reports no error and the link goes to the URL in the uncommented line.

Just to have clearly stated the behavior I was hoping for: it would be great if it took the URL with the percent sign. 

Thank you,  Jim
+++++++++++++++++++++
```tex
\documentclass{article}
\usepackage{hyperref}

\begin{document}
Hello.
\href{http://scherk.pbworks.com/w/page/14864221/Quiz%3A%20Countable%20sets}{User scherk at \texttt{pbworks.com}}
% \href{http://scherk.pbworks.com/w/page/14864221/Quiz}{User scherk at \texttt{pbworks.com}}
Goodbye.

\end{document}
```

**Comment by tkw1536** [comment]
Could have to do with #1831 and the associated fix #1832.

**Comment by dginev** [comment]
That's exactly it @tkw1536 . In latexml's parameter types, Semiverbatim does not neutralize `%` while Verbatim did. I wish I had included the `%` sign in my test in that PR.

If we look at the code, `Verbatim` is extending on `Semierbatim` by deactivating two further chars - `StartSemiverbatim('%', '\\');`

Apparently, for `\href` we need a parameter type that deactivates just the CS, as in `StartSemiverbatim('%');`.

Should we introduce a new parameter type for this @brucemiller ? I think we can fix this issue before the release.

**Comment by dginev** [comment]
Maybe `EscapableVerbatim` is a nice name? Suggestions welcome.
