### ISSUE TITLE
avoid latexmlc timeout on long document

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1997]
I have a long document that I'd like to convert to an epub, but latexmlc keeps timing out after 10 minutes.  I can convert to html via latexml (1 hour) and then latexmlpost (20 minutes), but the pair can't create an epub.  Is there a way I can tell latexmlc, "I know this is going to take awhile, please don't time out"?

**Comment by dginev** [comment]
@teepeemm Shouldn't you also have access to the regular `--timeout` command-line switch? That is in seconds, so one hour will be `--timeout=3600`.

**Comment by teepeemm** [comment]
@dginev `--timeout` worked.

I had assumed that the switches for `latexmlc` were those listed for `latexml` and `latexmlpost`.  But now I see that https://math.nist.gov/~BMiller/LaTeXML/manual/commands/latexmlc.html refers to https://math.nist.gov/~BMiller/LaTeXML/manual/modules/common/LaTeXML_Common_Config.html, and that does list `--timeout`.
