### ISSUE TITLE
latexmlpost can't find an image if the extension is capitalized

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1998]
If I have `image.JPG`, then `\includegraphics{image}` yields the XML `<graphics candidates="image.JPG" graphic="NotebookPictures/image" xml:id="p1.g1"/>`, but latexmlpost says "Error:imageprocessing:imageclass No image processing module found to convert types".

I think this will involve adjusting `lib/LaTeXML/Post/Graphics.pm` in its constructor.  The best would be to call `lc` on the extension.  The alternative might be to add `JPG` (and the others capitalized) to the `graphics_types`, and ignore those tortured souls who like to work with `jPg` files.

**Comment by dginev** [comment]
The PR I am thinking of is #1744, which focused on the base filename.

**Comment by teepeemm** [comment]
@dginev Yes, a default MacOS.

**Comment by dginev** [comment]
@brucemiller certainly, on it.

**Comment by dginev** [comment]
@teepeemm I made a minimal example that worked well for me:
```tex
\documentclass{article}
\usepackage{graphicx}
\graphicspath{NotebookPictures}
\begin{document}
\includegraphics{image}
\end{document}
```
with a file `NotebookPictures/image.JPG` adjacent to this TeX test. It converts to HTML and the graphic is visible for me.

Then I double-checked the error you shared, and it is actually referring the image conversion capability available to the post-processor:
> No image processing module found to convert types.

This is usually the case if you haven't installed the ImageMagick parts of the dependencies. Looking at our Mac instructions [here](https://math.nist.gov/~BMiller/LaTeXML/get.html#macos.macports), Bruce seems to suggest:
```
 sudo port install \
  p5-archive-zip p5-file-which p5-getopt-long p5-image-size \
  p5-io-string p5-json-xs p5-text-unidecode p5-libwww-perl \
  p5-parse-recdescent p5-time-hires p5-uri p5-xml-libxml \
  p5-xml-libxslt p5-perlmagick 
```

Is this helpful for resolving the issue at all?

**Comment by dginev** [comment]
Alright, I think this has to be an installation issue with imagemagick, though that sounds painful in its own way.

I don't have a Mac, so maybe I can loop @brucemiller back in for some advice?

**Comment by dginev** [comment]
@teepeemm I think one way to test imagemagick on any OS is to ask for convert's version. For example, I get:
```
$ convert --version

Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

How does that look on your end?

**Comment by teepeemm** [comment]
@dginev Yes, `convert --version` and `magick --version` are giving identical information: ImageMagick 7.1.0-53.

**Comment by dginev** [comment]
@teepeemm and do you see any errors for:
```sh
$ perl -MImage::Magick -e '1;'
```

If that module is available, you shouldn't be seeing the exact error you reported. And if not, I wonder if there's an explanation as to why...

**Comment by teepeemm** [comment]
That solved things.  Image::Magick wasn't installed, and `cpan Image::Magick` has things working as expected (I could have sworn I tried that - maybe that was when homebrew was still out of date).

**Comment by dginev** [comment]
Ah, fantastic! I was really afraid there was a deeper installation hurdle we were about to discover in recent ImageMagick versions. If installing the Perl module gets everything working smoothly, no action needed on our part. Thanks for the patience in troubleshooting here!

**Comment by brucemiller** [comment]
On 12/9/22 17:57, Deyan Ginev wrote:
> Ah, fantastic! I was really afraid there was a deeper installation 
> hurdle

Except that it still leaves unclear why macport's ImageMagick didn't 
work. [Generally you shouldn't have to use cpan on a managed (repo 
style) system,]
