### ISSUE TITLE
empty tabular rows and columns disappear

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1999]
The tex
```tex
\documentclass{article}
\begin{document}
\begin{tabular}{|c|c|c|}\hline
x&&x\\\hline
&&\\\hline
x&&x\\\hline
\end{tabular}
\end{document}
```
creates the pdf
<img width="103" alt="Screen Shot 2022-12-01 at 12 17 22 PM" src="https://user-images.githubusercontent.com/13021169/205129801-a670f902-028c-46d3-9f96-36620c5746a9.png">
and the html
<img width="61" alt="Screen Shot 2022-12-01 at 12 17 49 PM" src="https://user-images.githubusercontent.com/13021169/205129867-7d890970-2f20-4366-a08f-eb11f2c9cf16.png">

In fact, looking at the code, the empty row and column are gone, and the double line is accomplished by borders from the cells above or to the left.  I seem to recall seeing a PR talking about collapsing table cells, but can't find it.  Is there a reason we're taking this approach?  Is there a way to retain an empty row or column?  I've tried `\phantom` and other whitespace, to no avail.

**Comment by dginev** [comment]
Could be related to #1979 . It seems that the current pruning strategy is a bit too eager.

**Comment by teepeemm** [comment]
Probably related to the current pruning strategy:
```tex
\documentclass{article}
\begin{document}
one\vspace{2in}\\two
\end{document}
```
ignores the vspace.
