### ISSUE TITLE
using a better caption for longtable

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#2004]
longtable allows specifying table captions in the firsthead, head, foot, and lastfoot.  By my testing, any caption that gets typeset in TeX can contribute to the list of tables, so most of the captions should have an empty optional argument to avoid that.  In LaTeXML, we use whatever caption came last in the code, and always put it in the head.  I think it would be better to emulate what happens when a longtable ends up only taking one page: we use the firsthead and lastfoot, with the appropriate captions.  The following TeX:
```tex
\documentclass{article}
\usepackage{longtable}
\begin{document}
\listoftables
\section{The section}
one page longtable:
\begin{longtable}{c}
 \caption[first head optional caption]{first head caption}\\first head\endfirsthead
 \caption[]{other head caption}\\other head\endhead
\caption[]{other foot caption}\\other foot\endfoot
\caption[]{last foot caption}\\last foot\endlastfoot
 data
\end{longtable}
\end{document}
```
has the pdf:
<img width="413" alt="Screen Shot 2022-12-07 at 12 27 47 PM" src="https://user-images.githubusercontent.com/13021169/206266249-4a027f16-853e-43f9-82d7-bd2674ba69a0.png">
The html renders as:
<img width="476" alt="Screen Shot 2022-12-07 at 12 28 19 PM" src="https://user-images.githubusercontent.com/13021169/206266282-4cf1112e-60de-40ea-add2-6cba41c1f2e8.png">

**Comment by brucemiller** [comment]
Your example kinda abuses the intentions of `longtable`, namely while you might provide a `\caption` for both the first & not first (or last & not last), to support continuation captions, you'd likely not give them for both head and foot. And generally the `\caption` in the foot would come *after* the footer columns.  However, it was a provacative enough test case to figure things out, so thanks! :>
