### ISSUE TITLE
Implementing pipe (call command) in indices

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#2007]
What would it take to implement the `|` notation for indices?  It appears that `\index{term|mycommand{arg}}` should create the entry "term, \mycommand{arg}{page}" in TeX.  On the other hand, we only handle a few font changing commands (see [& process_index_phrases in LaTeX.pool.ltxml](https://github.com/brucemiller/LaTeXML/blob/0f8c2e389fe528bc7d20f838daef1110a7d7bf2f/lib/LaTeXML/Package/LaTeX.pool.ltxml#L4343)), and put the result in the styling for the indexmark.  For example:
```tex
\documentclass{article}
\usepackage{makeidx}
\makeatletter
\let\mycommand=\@firstoftwo
\makeatother
\makeindex
\begin{document}
\section{Introduction}
one\index{isbold|textbf} two\index{isemph|emph} three\index{iscustom|mycommand{15}} four\index{isplain}
\printindex
\end{document}
```
has the index:
<img width="82" alt="Screen Shot 2022-12-08 at 9 48 13 AM" src="https://user-images.githubusercontent.com/13021169/206492995-5d30ea4b-869e-4218-971a-c1b2b124c5c8.png">
but we create the xml:
```xml
      <p>one<indexmark style="bold">
          <indexphrase key="isbold">isbold</indexphrase>
        </indexmark> two<indexmark style="italic">
          <indexphrase key="isemph">isemph</indexphrase>
        </indexmark> three<indexmark style="mycommand–15˝">
          <indexphrase key="iscustom">iscustom</indexphrase>
        </indexmark> four<indexmark>
          <indexphrase key="isplain">isplain</indexphrase>
        </indexmark></p>
```
and the output:
<img width="153" alt="Screen Shot 2022-12-08 at 9 49 08 AM" src="https://user-images.githubusercontent.com/13021169/206493252-1ef0cf9d-9236-4de3-97e1-90cc657117ca.png">

Why am I doing this?  I'm wanting to index the line of code where keywords occur.  I've figured out how to create a custom environment that mimics an lstlisting and spots the keywords so that I end up tacking `\index{keyword|mycommand{lineno}}` onto the end of the environment.  I think it would be possible to hijack the xslt so that `style="mycommand–1234˝"` became `<a href="#lstnumberx1234">1234</a>`, but that seems to be a roundabout way to accomplish things (and I'm not good at xslt under the best of circumstances, and the index is not the best of circumstances).

**Comment by brucemiller** [comment]
Opening up the pipe commands of `\index` to arbitrary commands would be tricky, since in general they're "styling" the reference (eg page number) which isn't even there yet. And I think in your case, it's not really a question of styling.

Isn't what you're really trying to do is to have the listing line itself be referenceable? (and then the index would simply point back to that line)
