### ISSUE TITLE
Missing LaTexML manual section in online HTML version.

### ISSUE THREAD

**Issue by chrisjcameron** [brucemiller/LaTeXML#2008]
A section of the Latexml manual is missing: Appendix C, Core Modules is missing from the generated documentation. It should be at https://math.nist.gov/~BMiller/LaTeXML/manual/modules/core/) but it is not found.

**Comment by dginev** [comment]
Thanks for the report @chrisjcameron !

**Comment by brucemiller** [comment]
Turns out it was due to the configuration of the server software. Fixed now.  Thanks for the report!
