### ISSUE TITLE
MikTeX kpsewhich "maintenance" output breaks pathname_kpsewhich

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#2025]
It seems like kpsewhich from MIkTeX prints stuff on the *standard output* when installing a package on the fly:
```

======[not sure how many!]
starting package maintenance...
installation directory: "C:\..."
...
======[...]
C:\....
```
which of course breaks `pathname_kpsewhich`.

If anybody reading this knows the 'official' behaviour of MikTeX, please let me know, because I can't find any documentation about it! In the meanwhile, I'll send a mildly unsatisfying PR that ignores the lines between `/^=+$/`, as well as empty lines.

**Comment by brucemiller** [comment]
Fixed upstream (?)
