### ISSUE TITLE
Question about formula parse failure reports

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#2043]
A question to @brucemiller (and possible report, depending on answer):

In the minimal TeX with two copies of the same intentionally unparseable formula:
```tex
\documentclass{article}
\begin{document}
one: $---x;$ 

two: $---x;$
\end{document}
```

latexml currently produces two distinct MathParser warnings:
```
Warning:not_parsed:ADDOP.ADDOP.ADDOP>UNKNOWN MathParser failed to match rule 'Anything' at test.tex; line 3 col 7
Warning:not_parsed:ADDOP.ADDOP.ADDOP>UNKNOWN MathParser failed to match rule 'Anything' at test.tex; line 5 col 7
Conversion complete 2 warnings (See /tmp/test.latexml.log) (reqd. 1.26s)
```

I remember we recently discussed that latexml aims to only ever produce one warning for the same formula failing to parse in the same document. 

So is this example a signal for a regression, where we have started to flag each instance of the same formula? Or was the warning-reducing behavior in question different from what I understood? Thanks!

**Comment by brucemiller** [comment]
> I remember we recently discussed that latexml aims to only ever produce 
> one warning for the same formula failing to parse in the same document.

No, there's no such aim.  In fact, the opposite: a given formula can 
produce multiple warnings upon failing to parse subexpressions.

Moreover, the math parser doesn't see these as the "same" anyway; 
they're parsed individually.  (The math image generator would see them 
as the same, however: they're converted to TeX strings and only the 
unique strings are used to create images.)

**Comment by dginev** [comment]
I see, I must have misunderstood. Thanks!
