### ISSUE TITLE
How to set maxbibnames in bibliography?

### ISSUE THREAD

**Issue by MilesCranmer** [brucemiller/LaTeXML#2047]
Hey @brucemiller @dginev,

First of all, thanks so much for creating and maintaining this project. I am using it to compile a web version of my PhD thesis (I figure that nobody will scroll through a 250 page PDF, but maybe they will read pages of a website!) and LaTeXML is just an incredible tool for this.

My question relates to formatting of the bibliography. In LaTeX, I am using biblatex with the option `maxbibnames=30`, which lets me print out up to 30 author names before abbreviating them with "et al.":

```
\usepackage[backend=biber,style=authoryear,maxbibnames=30,natbib=true]{biblatex}
```

However, this option does not transfer to the LaTeXML printout. For example:

<img width="786" alt="Screenshot 2023-01-29 at 4 36 58 PM" src="https://user-images.githubusercontent.com/7593028/215356975-c2146c54-93f4-44e5-a73b-26726221537a.png">

which is from a 6 author paper.

It would be great if there was a way I could get all authors to display in this printout. For your information, I am using the following `latexmlc` settings from the ar5iv project, with some custom tweaks (run within a dockerfile based on ar5ivist):

```bash
latexmlc \
   --preload='[nobibtex,ids,localrawstyles,mathlexemes,nobreakuntex,magnify=2,zoomout=2,tokenlimit=99999999,iflimit=1499999,absorblimit=1299999,pushbacklimit=599999]latexml.sty' \
   --preload=ar5iv.sty \
   --path=/opt/ar5iv-bindings/bindings \  # from the ar5ivist dockerfile
   --path=/opt/ar5iv-bindings/supported_originals \  # from the ar5ivist dockerfile
   --format=html5 \
   --pmml \
   --cmml \
   --mathtex \
   --timeout=2700 \
   --nodefaultresources \
   --css=https://cdn.jsdelivr.net/gh/dginev/ar5iv-css@0.7.6/css/ar5iv.min.css \
   --css=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css \
   --source=preprocessed/main.tex \  # this dir contains main.bbl; but no main.bib
   --destination=build/main.html
```

I first generate the `main.bbl` file with a run of `pdflatex` and `biber` – which is what `latexmlc` uses to generate my bibliography. So, in theory, all the author information should be there.

I also looked through the docs pages, did a few searches of past issues, but couldn't seem to find any flags for this aside from the basic bibtex ones. Please let me know if I am missing something simple, or if there is otherwise a way I could hack this – I am very willing to do so to get a nice web version of my thesis.

Thanks!
Miles

**Comment by dginev** [comment]
Hey @MilesCranmer ,

It's great to hear you're giving latexml a spin! Trying it on a PhD thesis may be a rather hard bite to swallow though, as the complexity of large theses often exceeds our current LaTeX coverage. Most theses-like documents still convert with Errors (or even Fatal) on arXiv.

That said, on your specific question. biblatex actually isn't "officially" supported by LaTeXML, see the open #373 . What is instead available in the `ar5ivist` Dockerfile you are using is the experimental binding I added in [ar5iv-bindings/biblatex.sty.ltxml](https://github.com/dginev/ar5iv-bindings/blob/main/bindings/biblatex.sty.ltxml).

And indeed, the advanced options are not supported there yet, including `maxbibnames`.
It is certainly possible to extend support to also recognize that key, the big question would be "when" we will have the time to do so.

I am not sure this issue is "hackable" in a quick and simple way, the way a normal binding would be - since one would need a reasonable understanding of the MakeBibliography and CrossRef post-processors to identify the right places to handle the feature. Currently that's mostly in @brucemiller's working memory, and not in mine. Although I can get back up to speed given a sufficient chunk of time.

**Comment by MilesCranmer** [comment]
> It's great to hear you're giving latexml a spin! Trying it on a PhD thesis may be a rather hard bite to swallow though, as the complexity of large theses often exceeds our current LaTeX coverage. Most theses-like documents still convert with Errors (or even Fatal) on arXiv.

You will be happy to know that I got it all working 🙂 I had to tweak a few things on the LaTeX side, but currently, the entirety of my PhD thesis can be rendered into nice HTML with full navigation between chapters/figures/etc! I'll share the live version in a few weeks so you can see it. The format is looking really nice. My remaining development basically relates to fine-tuning things.

> And indeed, the advanced options are not supported there yet, including maxbibnames. It is certainly possible to extend support to also recognize that key, the big question would be "when" we will have the time to do so.
> I am not sure this issue is "hackable" in a quick and simple way, the way a normal binding would be - since one would need a reasonable understanding of the MakeBibliography and CrossRef post-processors to identify the right places to handle the feature. Currently that's mostly in @brucemiller's working memory, and not in mine. Although I can get back up to speed given a sufficient chunk of time.

Sounds good to me. I have reserved quite a bit of time to work on these sorts of things over the next couple of weeks, so if you might be able to point my in the right direction, I would be happy to put time into implementing a hack to get it working.

**Comment by MilesCranmer** [comment]
I wonder if I just increase these two numbers:

https://github.com/brucemiller/LaTeXML/blob/5b4f59039a777222368c295f0233ba3466ddef89/lib/LaTeXML/Post/MakeBibliography.pm#L434

https://github.com/brucemiller/LaTeXML/blob/5b4f59039a777222368c295f0233ba3466ddef89/lib/LaTeXML/Post/MakeBibliography.pm#L326

to `maxbibnames`, it would work?

**Comment by dginev** [comment]
I'll take a look tomorrow - if it's as easy as you suggest I can patch the experimental binding relatively simply.

**Comment by dginev** [comment]
@MilesCranmer the basic upgrade was indeed simple, as far as we are only talking about the arXiv use of biblatex. The PR was at [ar5iv-bindings#1](https://github.com/dginev/ar5iv-bindings/pull/1).

I have updated the ar5ivist Dockerfile, (and updated it [on dockerhub](https://hub.docker.com/repository/docker/latexml/ar5ivist/general) ) - so if you update your ar5ivist image, it may work as you expect.

Let me know how it goes!

**Comment by dginev** [comment]
Oh, interesting, my "fix" comment in the ar5iv-bindings repo led to Github closing this issue directly. I wasn't aware cross-repository issue management was possible here. I'd rather close by hand, once we're sure things are working for Miles.

**Comment by MilesCranmer** [comment]
Thanks, trying now. By the way – I will DM you my thesis rendering on Twitter so you can see it.

**Comment by MilesCranmer** [comment]
All working! Thanks!
