### ISSUE TITLE
`DontPrintSemicolon` breaks newline parsing for algorithm2e

### ISSUE THREAD

**Issue by MilesCranmer** [brucemiller/LaTeXML#2049]
Hey @dginev @brucemiller,

I wanted to report an edge case bug I am seeing with `algorithm2e.sty.ltxml` environments, which I believe is due to `\DontPrintSemicolon` (which turns off the printing of `;` at the end of each line) interfering with how `algorithm2e.sty.ltxml` parses the contents of an algorithm. Here is an example:
```latex
\usepackage[linesnumbered,lined,ruled,commentsnumbered]{algorithm2e}

...

\begin{algorithm}[h!]
\algsize
\DontPrintSemicolon
\Data{$P$, a population of expressions}
\Data{$\data$ as in \cref{alg:pysr}}
\Result{a single expression (the winner of the tournament)}
\Param{$n_s$, the tournament size (=12)}
\Param{$p_\text{tournament}$, the probability of selecting the fittest individual (=0.9)}
\BlankLine
\Fn{\Tournament{$P, \data$} \algcomment{\href{https://github.com/MilesCranmer/SymbolicRegression.jl/blob/0bb8b2bb58a4338729c84e3f52575ac475c86a09/src/Population.jl\#L100-L121}{[code]}}}{
    $Q \gets $ a random subset of size $n_s$ of $P$\;
    \While{$\Length{Q} > 1$}{
        {$E \gets \GetFittest{Q}$}\;
        \If{$\Rand{} < p_\text{tournament}$}{
            \Break
        }
        remove $E$ from $Q$\;
    }
    \KwRet{$E$}
}
\BlankLine\;
\Fn{\GetFittest{$P$} \algcomment{\href{https://github.com/MilesCranmer/SymbolicRegression.jl/blob/0bb8b2bb58a4338729c84e3f52575ac475c86a09/src/Population.jl\#L86-L95}{[code]}}}{
    $\ell_\text{best} \gets \infty$ \;
    \For{$E$ \KwTo $P$}{
        $C \gets$ complexity of $E$\;
        $\ell \gets \text{accuracy of }E$ \;
        \;
        \algcomment{include adaptive parsimony:}\;
        ${\ell \gets \ell}\times\exp(\text{recent number of expressions seen at size }C)$\;
        \;
        \If{$\ell < \ell_\text{best}$}{
            $\ell_\text{best} \gets \ell$ \;
            $E^\ast \gets E$\;
        }
    }
    \KwRet{$E^\ast$}
}
\caption{Tournament selection.\label{alg:tournament} }
\end{algorithm}
```

In the PDF this renders as:

<img width="1289" alt="Screenshot 2023-02-05 at 7 40 01 PM" src="https://user-images.githubusercontent.com/7593028/216856593-0f8a1d96-5791-4ec8-901a-eac20a716b08.png">

When I put this through LaTeXML, it renders as:

<img width="1088" alt="Screenshot 2023-02-05 at 7 38 45 PM" src="https://user-images.githubusercontent.com/7593028/216856512-29a24ee6-def6-4d8e-bb36-bed4903a8245.png">

So it seems like it is somehow missing the line breaks.

I looked into this and it is due to the `\DontPrintSemicolons`. If I turn that macro off, LaTeXML instead renders like this:

<img width="637" alt="Screenshot 2023-02-05 at 7 42 43 PM" src="https://user-images.githubusercontent.com/7593028/216856793-7582ae8c-17a2-4f36-891a-0c32822c9d77.png">

Which is correct. So perhaps this command is removing `\;` before LaTeXML is able to parse them?

Best,
Miles

**Comment by brucemiller** [comment]
Do you have a minimum working example? The snippet you've provided is missing some dependencies. Thanks;

**Comment by dginev** [comment]
@MilesCranmer we were discussing this issue in our latexml meeting today and I wanted to briefly ping and check if you can provide a minimal example, or I should trim down your report into one. Thanks! (no worries either way)

**Comment by brucemiller** [comment]
I can't reproduce this, in that there are missing dependencies.   Please re-open with clarifications; Thanks for your interest!
