### ISSUE TITLE
[MathML] remove reliance on mathvariant

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#2051]
With MathML Core [issue#182](https://github.com/w3c/mathml-core/issues/182), we no longer have mathvariant available, and newly prefer a combination of Unicode and CSS for this kind of styling.

An example of the previous mixed state of affairs is available in [ar5iv#184](https://github.com/dginev/ar5iv/issues/184).

I suspect we should add a selection of `math_variant` (or similarly named) CSS classes for the cases where Unicode does not have available codepoints.

**Comment by roobinhoood** [comment]
Can anyone help me, how new release version 0.8.7 (tar.gz) will be installed in windows 7 32,

**Comment by dginev** [comment]
Hey @roobinhoood , you can find more information on installation at
https://math.nist.gov/~BMiller/LaTeXML/get.html#windows

We currently don't have an active Windows maintainer, so it will be hard for us to help with debugging a specific Windows version ourselves. We can certainly patch any underlying issues with latexml however.

Also, could you please open a new issue if you want to pursue this? This one is specifically for dealing a change to MathML, so the installation question is off-topic. To do so, you can follow:
https://github.com/brucemiller/LaTeXML/issues/new

Thanks!

**Comment by brucemiller** [comment]
Isn't this actually fixed by now (the MathML question)? Or if not, could you provide a MWE with a bit more specifics? Thanks!

**Comment by dginev** [comment]
A minimal example from the ar5iv issue is:
```tex
$\mathit{55.4_{1.8}}$
```

Currently that would output MathML with the mathvariant attribute set for each of the numeric pieces, such as:
```xml
 <mn mathvariant="italic">55.4</mn>
```

where I propose instead of `mathvariant` we emit a class.
Either the already available `ltx_font_italic`, or a math-specific one that still has the `font-style: italic;` styling rule. Something like:

```xml
 <mn class="math_variant_italic">55.4</mn>
```

A [brief investigation in the ar5iv issue](https://github.com/dginev/ar5iv/issues/184#issuecomment-1213478546) suggested that as long as we style the class as a standalone rule, such directives will work in both native MathML browser renderers, as well as mainstream polyfills.
