### ISSUE TITLE
About Vietnamese and LaTeXML

### ISSUE THREAD

**Issue by hoanganhduc** [brucemiller/LaTeXML#2052]
Hello,

I want to ask if there is any working example of using LaTeXML with
Vietnamese to generate HTML files. I tried to construct one but the
generated HTML seems to have some issues with unicode characters.
Here is my example:

```
\documentclass{article}

\usepackage[T1, T5]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[vietnamese]{babel}
%\usepackage{vietnam}

\title{An example}
\author{Hoàng Anh Đức}

\begin{document}
	\maketitle

	Đây là một ví dụ về việc sử dụng tiếng Việt với LaTeXML.
\end{document}
```

Thanks!
Duc A. Hoang

**Comment by brucemiller** [comment]
We don't have any working examples (Yet!), but it seems like it ought to be workable.  And in fact your example gets somewhat close. The first thing I encounter is that `\h` is undefined.  It appears to be defined in `vntex/pdf1supp.def` to be equivalent to `\texthookabove` which should (I guess) involve the combining char `U+0309`.  However, it is unclear to me when/how that file gets loaded by latex (is it preloaded?).

If I provide such a definition anyway, your sample processes without error, but the result seems still to be wrong. It appears that many (all?) of the vowels which should get multiple accents aren't getting them. Perhaps the order of combining?

It looks close to working, but I think we'll need guidance from someone that understands the unicode/accent machinery of LaTeX better than us.
