### ISSUE TITLE
make listings output copy-pasteable

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#2067]
It looks like LaTeXML translates spaces in listings to non-breaking spaces, which has the side effect of breaking copy & paste of the code presented on screen. Minimal example:
```latex
\documentclass{article}
\usepackage{listings}
\begin{document}
\begin{lstlisting}
  Three spaces   then the rest.
\end{lstlisting}
\end{document}
```
will produce non-breaking spaces in the XML output.

I figure LaTeXML should output normal spaces and adjust the CSS instead (and maybe also use `<pre>` and `<code>` tags rather than plain `<div>` and `<span>`).

**Comment by dginev** [comment]
Could you elaborate what on "breaking copy & paste of the code presented on screen"?

Are we talking of a copy from a rendered browser page into a plain-text editor? Or some other scenario.

**Comment by xworld21** [comment]
> Are we talking about a copy from a rendered browser page into a plain-text editor? Or some other scenario.

Yes, exactly, copying the code straight from the browser, then pasting into an editor (w/o formatting of course).

I have found some people just do that (on our pages) and then are puzzled that the code doesn't work. Most editors don't flag non-breaking spaces, which doesn't help, at all.

**Comment by dginev** [comment]
Got it, thanks. The request sounds reasonable, in light of `white-space:nowrap;` or some of the other CSS techniques we have available to ensure that the listing doesn't re-flow on small viewports.

**Comment by brucemiller** [comment]
In general, the listing package produces lots of markup, styling and extra spans, so that cut-n-paste directly from the displayed listing usually wont work, independent of the spaces.  That's why I've tried to provide that download link on listings, which hopefully should supply the clean code.

**Comment by xworld21** [comment]
> the listing package produces lots of markup, styling and extra spans, so that cut-n-paste directly from the displayed listing usually wont work

Pasting the text/plain part works at least in the simple cases I am confronted with, except for the non-breaking spaces and the smart quotes (which are enabled by default, but can be disabled with a package option). Then there are of course options like `showspaces` and the likes, for which the download button is unavoidable.
