### ISSUE TITLE
,, -> Double Low-9 Quotation Mark

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2073]
In LaTeX, a double comma
```latex
,,
```
compiles to the [Double Low-9 Quotation Mark](https://www.compart.com/en/unicode/U+201E). LaTeXML doesn't honor this right now and instead produces two commas.

```
,,A`` ``B'' `C'
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/home/nschloe/software/texworld/texc-dev,/tmp/tmpkpv34_02"?>
<?latexml class="article"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-article.css" type="text/css"/>
  <para xml:id="p1">
    <p>,,A“ “B” ‘C’</p>
  </para>
</document>
```

**Comment by brucemiller** [comment]
Does it? the pdf looks like 2 commas to me.  You sure you don't have some extra packages loaded? Babel's `\glqq` gives you `U+201E`, for example.

**Comment by dginev** [comment]
> Does it? the pdf looks like 2 commas to me.

This is pretty interesting. `pdflatex` indeed outputs 2 commas, but `xelatex` and `lualatex` output the Unicode char `„`, exactly `U+201E`.

**Comment by brucemiller** [comment]
Yuck. It's easy to handle the commas, but it would be an error to change them by default and I'd hate to have to introduce a xelatex special case or option.  I feel kinda stuck responding with a `wontfix` (at least for now)

**Comment by brucemiller** [comment]
We don't really have a foreseeable xetex mode, although we try to accept unicode as much as possible, so I don't see how to fix this generally.  You could write a local binding that defined that ligature, however.
