### ISSUE TITLE
\medspace, \thickspace are now LaTeX native

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2083]
LaTeXML can't handle `\medspace`, `\thickspace`.

MWE:
```latex
\documentclass{article}
\begin{document}
a\thickspace b\medspace c
\end{document}
```

LaTeXML output:
```xml
  <para xml:id="p1">
    <p>a<ERROR class="undefined">\thickspace</ERROR>b<ERROR class="undefined">\medspace</ERROR>c</p>
  </para>
```

Suggestion:

- `\medspace` is 2/9 em → Unicode [Medium Mathematical Space (MMSP)](https://www.compart.com/en/unicode/U+205F)
- `\thickspace` is 5/18 em → Not available exactly in Unicode. Closest matches:
  - [Four-Per-Em Space](https://www.compart.com/en/unicode/U+2005) 4.5/18 em (error 1/36 = 0.027777 em)
  - [Three-Per-Em Space](https://www.compart.com/en/unicode/U+2004) 6/18 em (error 1/18 = 0.055555 em)

**Comment by dginev** [comment]
latexml has a by now outdated working assumption that `\medspace` and `\thickspace` belong to `amsmath.sty`. If you load that package you'll get the current support.

But indeed, it appears that they are now natively available from the main latex load. We should probably move them to `LaTeX.pool.ltxml` respectively.
