### ISSUE TITLE
ifdraft.sty support

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2086]
MWE:

```latex
\documentclass{article}
\usepackage{ifdraft}
\begin{document}
\ifdraft{a}{b}
\end{document}
```

LaTeX output:

> b

LaTeXML output:
> Error:undefined:\ifdraft

**Comment by dginev** [comment]
This may be relatively easy to support, given that loading it raw already produces reasonable outcomes.

You can try raw loading by adding the `--includestyles` option. There is ongoing work that will extend what we can cover using it, but it can often be useful already.
