### ISSUE TITLE
timeout: mdframed

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2089]
Running
```
latexml a.tex
```

on

```latex
\documentclass{article}

\usepackage{mdframed}

\begin{document}
\end{document}
```

runs forever on my machine. (Ubuntu 23.04, TeXLive)

**Comment by dginev** [comment]
I suspect this is a duplicate of #1483 - we just don't have support for mdframed.sty yet.

It is also a commonly requested ar5iv package.
