### ISSUE TITLE
mismatch between $doc URI and working folder

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#2093]
Tricky issue to explain. During postprocessing, all URLs to resources (CSS, images, etc) are relative to the working folder. So if I call e.g. `latexmlpost folder/file.xml` and `file.xml` includes the image `images/one.svg`, latexmlpost will look for `images/one.svg` in the current directory. However, if I call `document(@href)`, where `@href="images/one.svg"`, latexmlpost will look for `folder/images/one.svg`. ^

Now `document()` is not exactly supported by LaTeXML, but it has use cases (e.g. if you remember, I inspect SVGs in postprocessing to decide whether to use img or object; very effective in practice). So it would be nice if `document()` and latexmlpost treated relative URLs in a consistent way.

~~The backward compatible solution is to change the internal URI of `$doc` so that it's in the working folder; it doesn't change the behaviour of latexmlpost and fixes the discrepancy. It should be an easy change too.~~

Edit: `document()` receives URIs that are relative to the *destination* folder, so the URI must be set to the destination.

^ The semantics of `document()` is delicate – if called on a pure string, it's relative to the _stylesheet_. When called on a node, such as `document(@href)`, it will resolve relative to the URI of the document containing that node.

**Comment by brucemiller** [comment]
Are you referring to some perl level `document()`, or an XPath `document()` from within a Perl module, or to XSLT `document()` from within stylesheets?  (Or some combination, or all of them)

**Comment by xworld21** [comment]
Right! I mean XPath `document()` called from a stylesheet.
