### ISSUE TITLE
subfigures get wrong reference

### ISSUE THREAD

**Issue by eelcovv** [brucemiller/LaTeXML#2095]
Hello, 

I would like to report a bug (I think) in Latexml 0.8.6

It appears that references to subfigures are not correctly converted if you make a reference in the text. I have made a mwe (which  can be downloaded from here as well: git@github.com:eelcovv/subfigure_bug_latexml_mwe.git):
```
% Preamble
\documentclass[11pt]{article}
\usepackage{graphicx}
\usepackage{caption}
\usepackage[english]{babel}
\usepackage{subcaption}
\usepackage{xcolor}
\usepackage[colorlinks=true,
    allbordercolors=white,
    hypertexnames=false]{hyperref}

%    \end{macrocode}

% Document
\begin{document}

    This is een example of a reference to the total figure~\ref{fig:caption_of_example_figure} and the reference of
    the sub figure example A, in figure~\ref{fig:example_a}, en example B, in figure~\ref{fig:example_b}.

    \begin{figure}[t!]%
        \begin{subfigure}[t]{0.5\linewidth}%
            \includegraphics[width=\columnwidth]{example-image-a}
            \caption{\footnotesize{Example A}}%
            \label{fig:example_a}%
        \end{subfigure}%

        \begin{subfigure}[t]{0.5\linewidth}%
            \includegraphics[width=\columnwidth]{example-image-b}
            \caption{\footnotesize{Example B}}%
            \label{fig:example_b}%
        \end{subfigure}%
        \caption{Caption of example figure}
        \label{fig:caption_of_example_figure}%
    \end{figure}

\end{document}

```

Now if I compile this with latex, to the main figure \ref{fig:caption_of_example_figure} yields 1, in both the pdf as the html output. However, the referencse to the subfigures  \label{fig:example_a} and \label{fig:example_b} yields 0(a) and 0(b), whereas in the pdf this label gets 1a and 1b. I have another report where even the 0 is not given, all the figures het a label equal to (a) and (b), regardless of the figure number. 

Would it be possible to fix this?

**Comment by dginev** [comment]
I did some basic diagnostics here. The latexml problem originates from the timing of depositing the `ltx:tags` for the inner `ltx:figure` elements for each `{subfigure}`.

They are getting filled in too early - particularly before the latex `\caption` is processed, which is our current trigger for incrementing the outer figure counter. A quick way to check that is moving the caption on the top of the figure, in which case the subfigure tags come out correct (say `1(a)` instead of `0(a)`).

The tricky bit is deciding which later phase we should defer to (I think).

**Comment by dginev** [comment]
Btw @eelcovv you also stated:
> I have another report where even the 0 is not given, all the figures het a label equal to (a) and (b), regardless of the figure number.

Could you attach that as a minimal example as well? It could be a separate issue.
