### ISSUE TITLE
`{tabbing}` -> `<tr>` without `<table>`, `<tbody>`

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2101]
I had assumed that LaTeXML `<tabular>`s will always contain a `<table>`. However, with `{tabbing}`, one gets

```latex
\documentclass{article}
\begin{document}

\begin{tabbing}
x
\end{tabbing}

\end{document}
```

```xml
    <tabular class="ltx_tabbing">
      <tr>
        <td align="left">x</td>
      </tr>
    </tabular>
```

Note that `<tr>` is not in a `<table>` env, also `<tbody>` is missing.

Is this intentional?

**Comment by dginev** [comment]
I believe the `ltx:tabular` element corresponds to LaTeX environments loosely equivalent to a `{tabular}` environment, while the `ltx:table` element corresponds to environments loosely equivalent to a LaTeX `{table}` (which may contain a caption and be numbered).

I think `{tabbing}` is probably closer to `{tabular}`, if that. At the end of the tabbing entry in latexref [here](https://latexref.xyz/tabbing.html) you'd see it used for a code snippet:
```tex
\begin{tabbing}
function \= fact(n : integer) : integer;\\
         \> begin \= \+ \\
               \> if \= n > 1 then \+ \\
                        fact := n * fact(n-1) \- \\
                  else \+ \\
                        fact := 1; \-\- \\
            end;\\
\end{tabbing}
```

I suspect this is rather slippery...

**Comment by dginev** [comment]
Here is the schema docs page for [ltx:tabular](https://math.nist.gov/~BMiller/LaTeXML/manual/schema/LaTeXML-tabular/) and the page for [ltx:table](https://math.nist.gov/~BMiller/LaTeXML/manual/schema/LaTeXML-para/#schema.table)

**Comment by brucemiller** [comment]
Exactly: the latexml name `table` was taken by the floating table environment; so `ltx:tabular` corresponds to html's `table`, and when you postprocess into html you'll get a `table` and `tbody`.

So it's all as it should be, even if the element names are a little surprising.  But thanks for the query!

**Comment by nschloe** [comment]
Thanks for the clarification!
