### ISSUE TITLE
New class: aa (probably equal aastex)

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2102]
A bunch of articles use the `aa` class (attached). From what I can tell, it's more or less an old version of `aastex` for which LaTeXML has support. Can perhaps be treated as an alias.

[aa.zip](https://github.com/brucemiller/LaTeXML/files/11468055/aa.zip)

**Comment by dginev** [comment]
We already have [aa.cls.ltxml](https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/aa.cls.ltxml), so it should already be supported?

Let me know if there is a different issue at play, or we can close this as invalid.

**Comment by nschloe** [comment]
Yeah no sorry, my mistake.
