### ISSUE TITLE
parseParameters not using current catcodes

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#2104]
The following TeX:
```tex
\documentclass{article}
\catcode`_ = 11\relax
\def\qstop{\qstop}
\def\q_stop{\q_stop}
\def\myreaduntilplain#1\qstop{A #1 C}
\def\myreaduntilunderscore#1\q_stop{D #1 F}
\usepackage{mystyles}
\begin{document}
\myreaduntilplain B\qstop
\myreaduntilunderscore E\q_stop
\end{document}
```
(with an empty `mystyls.sty`) has the output "A B CD E F".  With the `mystyls.sty.ltxml` file:
```perl
DefMacro('\myreaduntilplain Until:\qstop','A #1 C');
DefMacro('\myreaduntilunderscore Until:\q_stop','D #1 F');
```
there's two errors:
```
Error:expected:Until:\q_stop Missing argument Until:\q_stop for Core::Definition::Expandable[\myreaduntilunderscore Until:\q_stop]
        at file.tex; line 34 col 0 - line 34 col 0
        Ended at file.tex; line 34 col 0 - line 34 col 0
        Next token is T_LETTER[E] ( == T_LETTER[E]) more: \q_stop\end{document}
Error:recursion:\q_stop Token T_CS[\q_stop] expands into itself!
        at file.tex; line 34 col 0 - line 34 col 0
        defining as empty
        Next token is T_CS[\end] ( == Core::Definition::Expandable[\end {}]) more: {document}
```
and it ends up with the output `<p>A B CD missing FE</p>`.

I think this is because `LaTeXML::Package::parseParameters` calls `TokenizeInternal` on the part after the `Until:`.  Shouldn't we be using the current catcodes for this call?  (Speaking of which, is there a function that tokenizes according to the *current* catcodes?)

**Comment by dginev** [comment]
@teepeemm Using the traditional LaTeX 2 preamble catcodes is indeed a fixed assumption for `TokenizeInternal` and `parseParameters` respectively.

A version of it that doesn't swap in those catcodes but uses the current ones would be simply trimming it down to:
```perl
sub TokenizeAsIs {
  my ($string) = @_;
  return LaTeXML::Core::Mouth->new($string)->readTokens;
}
```

We don't have such a function at the moment, but you're welcome to use it in your binding file (and to request that we add it).

**Comment by dginev** [comment]
As to the general question if latexml bindings should be processed using the current catcodes... I think it's a tricky decision.

Yes, in TeX it would, and an expert TeXnician would be able to use that feature to properly remain in the flow of whichever catcode realm they are in (e.g. the LaTeX 3 realm).

But a novice to intermediate TeXnician (or latexml binding writer) will have a brand new class of context-dependent bugs to encounter, as the binding definitions *in perl* will now vary depending on the order in which packages are loaded.

Likely something that needs some thought, and definitely needs input from @brucemiller

**Comment by teepeemm** [comment]
Or we could also have `TokenizeThree` that would tokenize according to LaTeX 3 catcodes.  But either of those `Tokenize`s would still require that I pull apart the `parseParameters` to use the different `Tokenize` variant (or we add an option to `DefMacro` that tells what catcodes to use).

I realized that if I'm going to be pulling apart `ParseParameters` anyway, I might as well mock what commands I want to get and use that instead.  So having
```perl
DefMacroI(T_CS('\myreaduntilunderscore'),
    LaTeXML::Core::Parameters->new(
        LaTeXML::Core::Parameter->new('Until','Until:\q_stop',extra=>[T_CS('\q_stop')]) ),
    'D #1 F' );
```
works with my original intention, and doesn't require any new code.

I think since I have a viable work around, and `Tokenize` is using the standard catcodes intentionally, that we can leave things as they are.

**Comment by dginev** [comment]
Thanks. This is nevertheless a useful report for us, as we are doing a lot of forward thinking about adapting LaTeXML to a world where LaTeX 3 is primary. The implied catcodes for binding prototypes are something to keep in mind as we get there...

**Comment by brucemiller** [comment]
Sorry, I wasn't paying attention...

The .ltxml bindings are intended to be somewhat reproducible, so such 
things as
DefMacro('\myreaduntilunderscore Until:\q_stop','D #1 F');
intentionally parse the prototype using standard catcodes.

Your aproach:
On 5/16/23 10:32, Tim Prescott wrote:
> DefMacroI(T_CS('\myreaduntilunderscore'),
>      LaTeXML::Core::Parameters->new(
>          LaTeXML::Core::Parameter->new('Until','Until:\q_stop',extra=>[T_CS('\q_stop')]) ),
>      'D #1 F'  );

although it's kinda ugly, is exactly the way to do it.
I've occasionally wondered whether shorthand constructors like 
`Parameter(...)` and `Parameter(...)` would be useful, but never quite
reached the pain threshold.
