### ISSUE TITLE
newlines and indentation in figures

### ISSUE THREAD

**Issue by davpoole** [brucemiller/LaTeXML#2107]
Hi!
I need to have breaks followed by indentation (Works in latex), and it needs work the same in text and in figures. It doesn't now. (See attached file).

<pre>
\begin{figure}
\begin{flushleft}
  In fig: This should be left\\
  \mbox{} ~~~~~This should be indented on the next line
\end{flushleft}
  \caption{A figure}
\end{figure}
</pre>

Does not obey \\ (when the window is wide enough). This is with (LaTeXML version 0.8.7) tested on multiple browsers (Safari, Firefox, Chrome).

Also I'm not sure why figure tries to center. This is not the default in latex. (But I know how to fix it by editing .ltx_flex_figure in LeTexML.css)

Here is a small test example you can run:

[latexmltest.tex.zip](https://github.com/brucemiller/LaTeXML/files/11520592/latexmltest.tex.zip)

**Comment by dginev** [comment]
I am not sure how much of this we want to emulate precisely (@brucemiller may want to opine).

With the WIP #2302 , the example above gets mapped into a flex figure with 2 panels (the right one of which is indeed an indented `<p>`). 

The current latexml XML when converted via the PR is:
```xml
  <figure inlist="lof" xml:id="S0.F1">
    <tags>
      <tag>Figure 1</tag>
      <tag role="refnum">1</tag>
      <tag role="typerefnum">Figure 1</tag>
    </tags>
    <p align="left" class="ltx_figure_panel">In fig: This should be left</p>
    <p align="left" class="ltx_figure_panel">      This should be indented on the next line</p>
    <toccaption><tag close=" ">1</tag>A figure</toccaption>
    <caption><tag close=": ">Figure 1</tag>A figure</caption>
  </figure>
```

Where the `\\` from the source caused the two paragraph elements. I guess the question I can formulate based on this markup is: should the HTML always force a "flex break" after a `ltx:p` ? Arguably it should - if so, I can proceed to add it. I wonder which other elements require an inferred break?
