### ISSUE TITLE
MakeBibliography.pm typo?

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#2113]
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Post/MakeBibliography.pm, line 785 says
`ltx:title` 
while the other bibliographic types use `ltx:bib-title` .
Please check if this is by design or a typo.

**Comment by dginev** [comment]
Thanks for the report @giovanni111 !

You can also link to specific lines with exact commit in github, by clicking on the line number and "copy permalink". In this case that yields:

https://github.com/brucemiller/LaTeXML/blob/a62418aaf062eea0b5ec1d1a50e05c2fd9ccd263/lib/LaTeXML/Post/MakeBibliography.pm#L785

It indeed looks like a typo at a glance, unless there is some special consideration for the `website` case of a formatting specification. Would defer to @brucemiller for confirmation.
