### ISSUE TITLE
Feature request: `\textcircled` with digits

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2122]
LaTeX:

```latex
\documentclass{article}

\begin{document}
\textcircled{0}
\textcircled{1}
\textcircled{2}
\textcircled{3}
\end{document}
```

LaTeXML output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/tmp"?>
<?latexml class="article"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-article.css" type="text/css"/>
  <para xml:id="p1">
    <p>0⃝
1⃝
2⃝
3⃝</p>
  </para>
</document>
```

Better Unicode match: https://www.compart.com/en/unicode/U+24EA ff.

**Comment by brucemiller** [comment]
LaTeXML does `\textcircled`  using the combining character `U+20DD`.  What exactly are you requesting here?

**Comment by dginev** [comment]
I think the request is to use `⓪` i.e. U+24EA for the zero case, maybe followed by U+2460 .. U+2473 for the first 20 natural numbers.

The current latexml treatment doesn't render neatly when I open the HTML in Chrome or Firefox - is there a font selection or other customization that would be needed to get a healthy browser rendering?

**Comment by dginev** [comment]
For archival, a more complete request for support (able to handle a `\raisebox` argument) has since been also voiced in arXiv:
https://github.com/arXiv/html_feedback/issues/2788

I won't open a new issue as I expect v0.8.9 of latexml will handle this better, but wanted to bookkeep the connection.
