### ISSUE TITLE
aa abstract: no space after colon

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2130]
MWE:

```latex
\documentclass{aa}

\begin{document}
\abstract{a}{b}{c}{d}{e}
\maketitle
\end{document}
```

LaTeX output:

![screenshot](https://github.com/brucemiller/LaTeXML/assets/181628/4d1a53c2-1c7d-499b-8631-d224e7cd61c7)

LaTeXML output:

```xml
  <abstract name="Abstract">
    <p>Context:a</p>
    <p>Aims:b</p>
    <p>Methods:c</p>
    <p>Results:d</p>
    <p>Conclusions:e</p>
  </abstract>
```

Note the missing space, full stop, italic styling.

**Comment by dginev** [comment]
@nschloe if you encounter a series of issues with the same package, feel free to group them in a single issue - #2129, #2130 and #2131 look just a tad too split apart, since they are atomic problems on the same theme.

Thanks for the reports!
