### ISSUE TITLE
[question] bibliography sometimes not processed?

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2143]
Sometimes, I'm getting empty bibliographies with LaTeXML, and I'm not quite sure why that is.

MWE:

- `g01.tex`
  ```latex
  \documentclass{article}

  \begin{document}
      \cite{test01}
      \bibliographystyle{alpha}
      \bibliography{g01}
  \end{document}
  ```
- `g01.bib`
  ```bibtex
  @article{test01,
    title={X}
  }
  ```

LaTeXML output:
```xml
  <para xml:id="p1">
    <p><cite class="ltx_citemacro_cite">[<bibref bibrefs="test01" separator="," yyseparator=","/>]</cite></p>
  </para>
  <bibliography bibstyle="alpha" citestyle="AY" files="g01" xml:id="bib">
    <title>References</title>
    <!-- Empty?? -->
  </bibliography>
```

latex output:

![screenshot_2023-07-04-152322](https://github.com/brucemiller/LaTeXML/assets/181628/2947107a-f6e4-409d-aaa0-df36c7f6e171)

**Comment by dginev** [comment]
This one I believe I can answer quickly. LaTeXML processes the bibliography in multiple stages, much like LaTeX would, but in our own paradigm of Core vs Post processing. Which allows to convert the document with a single call to latexmlc, or latexml+latexmlpost.

The important detail here is that the actual references section is filled in during post-processing. There is a combination of processors, importantly `LaTeXML::Post::Scan`, `LaTeXML::Post::Crossref` and `LaTeXML::Post::MakeBibliography` which can recognize the used citations, and then fill in the inline cites and the backmatter section.

So if you'd want to see a bibliography generated in LaTeXML's XML dialect, you could run post-processing with an XML target, as in:
```
latexmlc g01.tex  --post --format=xml
```

and for the usual HTML
```
latexmlc g01.tex --format=html
```

**Comment by brucemiller** [comment]
Yep, that's the problem: the bibliography is filled in by `latexmlpost` (or `latexmlc`).  Thanks for the report, though.
