### ISSUE TITLE
MathML splitting occurs for individual equations.

### ISSUE THREAD

**Issue by Ramnath-Karthikesan** [brucemiller/LaTeXML#2145]
```latex
\documentclass{article}

\begin{document}

\begin{eqnarray}
    \mathcal{L} &=& F_\mathrm{core} + F_\mathrm{shell} + F_\mathrm{bulk} + \mu \left(N_\mathrm{T} - N_\mathrm{fc} - N_\mathrm{d} - N_\mathrm{bulk} \right) \nonumber \\ && -\Pi \left(V_\mathrm{T} - V_\mathrm{core} - 2 L_\mathrm{A} S - V_\mathrm{bulk} \right) \, , 
\end{eqnarray}


\end{document}
```

When converting the LaTeX file to HTML, the resulting equations are often split into multiple math tags. It would be preferable to have each equation enclosed within a single math tag.

HTML OUTPUT:

```html
<table id="S0.EGx1" class="ltx_equationgroup ltx_eqn_eqnarray ltx_eqn_table">

<tbody id="S0.E1">
<tr class="ltx_equation ltx_eqn_row ltx_align_baseline">
<td class="ltx_eqn_cell ltx_eqn_center_padleft"></td>
<td class="ltx_td ltx_align_right ltx_eqn_cell"><math id="S0.Ex1.m1" class="ltx_Math" alttext="\displaystyle\mathcal{L}" display="inline"><mi class="ltx_font_mathcaligraphic">ℒ</mi></math></td>
<td class="ltx_td ltx_align_center ltx_eqn_cell"><math id="S0.Ex1.m2" class="ltx_Math" alttext="\displaystyle=" display="inline"><mo>=</mo></math></td>
<td class="ltx_td ltx_align_left ltx_eqn_cell"><math id="S0.Ex1.m3" class="ltx_Math" alttext="\displaystyle F_{\mathrm{core}}+F_{\mathrm{shell}}+F_{\mathrm{bulk}}+\mu\left(%
N_{\mathrm{T}}-N_{\mathrm{fc}}-N_{\mathrm{d}}-N_{\mathrm{bulk}}\right)" display="inline"><mrow><msub><mi>F</mi><mi>core</mi></msub><mo>+</mo><msub><mi>F</mi><mi>shell</mi></msub><mo>+</mo><msub><mi>F</mi><mi>bulk</mi></msub><mo>+</mo><mrow><mi>μ</mi><mo>⁢</mo><mrow><mo>(</mo><mrow><msub><mi>N</mi><mi mathvariant="normal">T</mi></msub><mo>-</mo><msub><mi>N</mi><mi>fc</mi></msub><mo>-</mo><msub><mi>N</mi><mi mathvariant="normal">d</mi></msub><mo>-</mo><msub><mi>N</mi><mi>bulk</mi></msub></mrow><mo>)</mo></mrow></mrow></mrow></math></td>
<td class="ltx_eqn_cell ltx_eqn_center_padright"></td>
<td rowspan="2" class="ltx_eqn_cell ltx_eqn_eqno ltx_align_middle ltx_align_right"><span class="ltx_tag ltx_tag_equation ltx_align_right">(1)</span></td>
</tr>
<tr class="ltx_eqn_row ltx_align_baseline">
<td class="ltx_eqn_cell ltx_eqn_center_padleft"></td>
<td class="ltx_td ltx_eqn_cell"></td>
<td class="ltx_td ltx_eqn_cell"></td>
<td class="ltx_td ltx_align_left ltx_eqn_cell"><math id="S0.E1.m1" class="ltx_Math" alttext="\displaystyle-\Pi\left(V_{\mathrm{T}}-V_{\mathrm{core}}-2L_{\mathrm{A}}S-V_{%
\mathrm{bulk}}\right)\,," display="inline"><mrow><mrow><mo>-</mo><mrow><mi mathvariant="normal">Π</mi><mo>⁢</mo><mrow><mo>(</mo><mrow><msub><mi>V</mi><mi mathvariant="normal">T</mi></msub><mo>-</mo><msub><mi>V</mi><mi>core</mi></msub><mo>-</mo><mrow><mn>2</mn><mo>⁢</mo><msub><mi>L</mi><mi mathvariant="normal">A</mi></msub><mo>⁢</mo><mi>S</mi></mrow><mo>-</mo><msub><mi>V</mi><mi>bulk</mi></msub></mrow><mo rspace="4.2pt">)</mo></mrow></mrow></mrow><mo>,</mo></mrow></math></td>
<td class="ltx_eqn_cell ltx_eqn_center_padright"></td>
</tr>
</tbody>
</table>

```

A similar problem occurs when the equations are enclosed within \begin{align} or \begin{aligned} or \begin{align*}

**Comment by dginev** [comment]
Let me start by saying this has been a deliberate choice in latexml, and is not an accident.

There is a high level discussion, which we've had internally on occasion, about `<mtable>` inside a math tag vs the regular `<table>` element in HTML. The choice should be easy for the extreme examples - a small numerical matrix should use `<mtable>`, while a huge multi-page table of equations should use a `<table>`. It gets trickier to separate the cases in between. An "equation array" has pieces that are clearly not part of a standalone `<math>` formula, such as right-aligned row numbers - the `<span>(1)</span>` in your example.

I believe the implementation so far has approached things in practical terms - following the best *browser rendering support* for these tabular layout constructs. The MathML `<mtable>` has traditionally had partial (and at times poor) support, but that may indeed improve substantially as MathML Core implementations mature.

May I ask one clarifying question @Ramnath-Karthikesan . When you state:
> It would be preferable to have each equation enclosed within a single math tag.

Could you elaborate as to "preferable" for which practical purpose? For example a math clipboard (copy/paste), accessibility (using math-focused text-to-speech tools), display (improved rendering), etc.

**Comment by Ramnath-Karthikesan** [comment]
I mainly use it for display (improved rendering) purpose

**Comment by brucemiller** [comment]
In general, I think you're going to find the display better the way we've done it, rather than keeping it all within a single `math` element.  It does, however, impact accessibility and reuse, so we'll occasionally reconsider the approach in the future, as browsers improve, etc.  That will involve a lot of refactoring and testing, though.  For the time being, this is a feature, not a bug.
