### ISSUE TITLE
\ce command is undefined

### ISSUE THREAD

**Issue by Ramnath-Karthikesan** [brucemiller/LaTeXML#2146]
Due to the absence of a binding file for the mhchem.sty package, the commands and functionalities provided by this package, such as \ce, are not functioning correctly. It would be highly beneficial to have the necessary functionality properly implemented.

```latex
\documentclass{article}

\usepackage[version=4]{mhchem}


\begin{document}

\ce{OH-}

\end{document}
```

HTML output:
\ceOH-

**Comment by dginev** [comment]
Hi @Ramnath-Karthikesan - thank you for the report.

LaTeXML currently does not have native support for mhchem.sty, and we have an existing tracking issue - see #706 . I will close here as a duplicate - the key question is finding developer time to write a `.ltxml` binding for this package.

Side note: In our list of *not yet supported* packages in arXiv, mhchem.sty comes seventh, with [0.53% of arXiv articles](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/warning/missing%5Ffile?all=true).
