### ISSUE TITLE
styling inconsistencies with framed.sty

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#2224]
I have noticed that the framed.sty.ltxml binding differs from framed.sty in a few places, some with ugly results. At a minimum
- the default value of `\FrameSep` is three times `\fboxsep` (at package load time), not `12pt`
- the titled-frame environment has no padding at all (can be fixed using negative margins on the title span, instead of `width:100%`)
- padding inside the title span seems to be hardcoded to `8pt`
- similar considerations for `\FrameRule`

This might be all. If you don't mind, I'll just go through the code of both binding and package line by line, and write a PR with CSS only fixes.

**Comment by dginev** [comment]
> This might be all. If you don't mind, I'll just go through the code of both binding and package line by line, and write a PR with CSS only fixes.

That is very much appreciated - thank you for spending the time!
