### ISSUE TITLE
Multiple titles, dates etc.

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2242]
When accidentally specifying multiply titles, dates, etc., LaTeX will only use the last upon `\maketitle`

```latex
\documentclass{article}

\title{Lorem}
\title{ipsum}
\date{A}
\date{B}

\begin{document}

a

\maketitle

b

\end{document}
```

LaTeX output:

```
a

ipsum
B

b
```

LaTeXML however returns them all:

```xml
<document xmlns="http://dlmf.nist.gov/LaTeXML" class="ltx_authors_1line">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-article.css" type="text/css"/>
  <para xml:id="p1">
    <p>a</p>
  </para>
  <title>Lorem</title>
  <title>ipsum</title>
  <date role="creation">A</date>
  <date role="creation">B</date>
  <para xml:id="p2">
    <p>b</p>
  </para>
</document>
```

**Comment by dginev** [comment]
This one appears to be a minimal report for the larger topics discussed in #1929 and #1937 - we are pending a redesign for the latexml frontmatter handling that keeps closer to the LaTeX internals, exactly to better handle the less usual tricks and patterns.

I'll close here as a duplicate, that redesign will handle double uses of `\title` as well. (And maybe I should move the other issues to the next milestone while I'm at it...)
