### ISSUE TITLE
Seeking Method to Obtain Mapping Between LaTeX (.tex) and Generated HTML during Conversion using LaTeXML

### ISSUE THREAD

**Issue by circlestarzero** [brucemiller/LaTeXML#2243]
Hello,

I'm currently using LaTeXML to convert LaTeX documents into HTML. For my use case, I require a detailed mapping between the lines or elements in the original .tex file and the corresponding parts in the generated HTML. This mapping is crucial for tracing back the HTML content to its original LaTeX source line or element.

I've browsed through the documentation and related resources but haven't found a straightforward way to achieve this. Is there a feature, option, or plugin in LaTeXML that facilitates this kind of mapping? Or is there a recommended approach or best practice to implement this functionality?

Any guidance or references would be greatly appreciated. Thank you in advance for your time and assistance!

**Comment by dginev** [comment]
Hi @circlestarzero ,

I believe the only project that tried to achieve this with latexml was sTeX, by means of adding a custom attribute to the HTML which tracked the original TeX soure location for a given element.

You may benefit from examining issue #736, especially the last comment by Tom which shows a small example of how a concrete `.ltxml` binding may look like.
