### ISSUE TITLE
Definition "after" first use

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2248]
It's possible in LaTeX to use a newcommand in a `\title` if the newcommand is defined _after_ the title, but _before_ its use in, e.g. , `\maketitle`. For example, this is perfectly legal LaTeX:

```latex
\documentclass{article}

\title{Lorem \IR}

\newcommand\IR{ipsum}

\begin{document}
\maketitle

\IR
\end{document}
```

LaTeXML gets confused though and doesn't ever resolve `\IR`, not even in later uses:

```xml
  <title>Lorem <ERROR class="undefined">\IR</ERROR></title>
  <ERROR class="undefined">\IR</ERROR>
```

**Comment by dginev** [comment]
I think we just discussed this in https://github.com/brucemiller/LaTeXML/issues/2242#issuecomment-1771051841

We probably want a test which ensures this `\newcommand`+`\title` pattern works, given that you've raised our attention to the need. 

But yes, this is also covered by #1929 .

**Comment by nschloe** [comment]
I hadn't realized this is covered by the same discussion. Thanks for clarifying!
