### ISSUE TITLE
float labels are added to the section if there's no caption; identify "true" labels?

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2260]
If a LaTeX entities has multiple labels, the labels will always appear alphabetically sorted in the LaTeXML output. For example, this

```latex
\documentclass{article}
\usepackage{algorithm2e}
\begin{document}

\ref{sec:intro}

\section{Intro}\label{sec:intro2}\label{sec:intro1}

\begin{algorithm}\label{alg:1}
  % \caption{123}
\end{algorithm}

\end{document}
```

produces

```xml
<section inlist="toc" labels="LABEL:alg:1 LABEL:sec:intro1 LABEL:sec:intro2" xml:id="S1">
```

(Note that the `alg:1` label appears here because the `{algorithm}` doesn't have a caption which could contain a tag.)

I'd like to see the labels sorted in order of appearences such that I could employ _some_ heuristic to find a "true" label. There may be alternatives for separating the _section_ and _algo_ labels in the above example.

**Comment by dginev** [comment]
I am not sure if this request makes sense in the LaTeX sense, since for this example:

```tex
They are all true: \ref{sec:intro1} = \ref{sec:intro2} = \ref{alg:1}
```

**Comment by nschloe** [comment]
Yeah I know, they're technically all equal, and also the order in `labels={}` in the XML doesn't play a role. Since it all doesn't matter, I'd like to see the same order of labels in the XML as in in the LaTeX. That'd allow me, in the above example, to use `{sec:intro2}` instead of the arguably accidental `{alg:1}` label for the secion.

**Comment by dginev** [comment]
I think the order is already preserved, just that the last label encountered in the source comes first in the attribute. The last value in the attribute is the first one in the source.

But I am not sure latexml should advertise this as a stable feature, more of an accident of bookkeeping?

Really, all of them are equally usable.

**Comment by nschloe** [comment]
Never mind then, I'll close.

**Comment by xworld21** [comment]
I believe the order of the labels is meaningful for things like `--splitnaming=label`, so the order must be somewhat intentional for latexmlpost to work in a predictable way.
