### ISSUE TITLE
Howdo I stop creating log file in latexml

### ISSUE THREAD

**Issue by HGGshiwo** [brucemiller/LaTeXML#2299]
How to cancel the log file generated by the latexml command？I do not need it at all

**Comment by tkw1536** [comment]
Per [Documentation](https://math.nist.gov/~BMiller/LaTeXML/manual/commands/latexml.html) of the command line flags you can use ```--log``` flag. Something like  ```latexml --log=/dev/null something.tex``` should convert without creating a logfile.

**Comment by dginev** [comment]
Hi @HGGshiwo , thanks for the question! And I see Tom just beat me to answering.

We discard the log information during latexml's testing harness, so we've also recognized to ignore the log information for certain jobs.

The option you need to add to your conversions is:
```
--log=/dev/null
```

You may want to use the `latexmlc` executable if you also need the logs disabled for post-processing, as I am not sure if `latexmlpost` ever received an equivalent switch.
