### ISSUE TITLE
Implement algorithm2e bindings

### ISSUE THREAD

**Issue by brucemiller** [brucemiller/LaTeXML#233]
[Originally Ticket 1557, reported by cheshirekow]

I would like to request that the algorithm2e package be implemented for latexml.

**Comment by binarez** [comment]
I'm not exactly sure how to signify that I would really like this feature implemented so I'll just say it here in this comment. :+1: 

[Discussion on tex.sx](http://tex.stackexchange.com/questions/292700/is-there-a-latex-to-html-tool-that-supports-the-algorithm2e-package)

**Comment by dginev** [comment]
Thanks for speaking up @binarez , we hear you!

**Comment by bulibuta** [comment]
Is there even an experimental algorithm2e binding that I can test? I could not get the one I wrote to define and pass the @float and end@float undefined errors:

`Error:undefined:\@float The token T_CS[\@float] is not defined.`
[algorithm2e.sty.ltxml.txt](https://github.com/brucemiller/LaTeXML/files/967695/algorithm2e.sty.ltxml.txt)

**Comment by brucemiller** [comment]
On 05/01/2017 06:44 AM, Paul Irofti wrote:
> Is there even an experimental algorithm2e binding that I can test? I
> could not get the one I wrote to define and pass the @float
> <https://github.com/float> and end@float undefined errors:

Funny you should mention that. I recently was looking at your
binding, and the docs, and experimenting with the newer approach
to let algorithm2e.sty do most of the work, with some clever
low-level latexml-specific stuff.  It actually mostly works,
but for one deep problem.

algorithm2e relys on \afterpar and *lots* of \par in order
to number lines, indent, draw lines, etc.  Unfortunately,
it uses lots of redundant \par's; Real TeX ignores \par
when it's already in vertical mode.  Alas, LaTeXML currently
only understands text and math modes, so it generates a bunch
of blank lines and junk.

There's a couple of Tricky Bits to that, but it's being
thought about; so watch this space...

**Comment by bfirsh** [comment]
[A LaTeXML paper did the rounds on Twitter recently](https://twitter.com/schrockn/status/940037656494317568) and the only thing broken was this package. @dginev suggested commenting with a +1 for this issue. (Or +3200 retweets. ;)

**Comment by brucemiller** [comment]
Considering I almost lost my draft binding due to fat-fingered git misuse, I probably should do something sooner rather than later. It currently(?) mangles line numbering & blank lines, but would look better than the red blob you got!
