### ISSUE TITLE
Spelling errors in code

### ISSUE THREAD

**Issue by hpreusse** [brucemiller/LaTeXML#2331]
The Debian lintian tool reports spelling errors in the code. Straightforward patch is [here](https://github.com/debian-tex/latexml/blob/master/debian/patches/spelling_errors_new). Sorry for reporting to late.

**Comment by dginev** [comment]
@hpreusse these are fine documentation patches, could you make a PR, or are you not comfortable doing the git branching dance?

**Comment by hpreusse** [comment]
PR number is PR #2332 .
