### ISSUE TITLE
`\braket{}` tex changed by `latexml`

### ISSUE THREAD

**Issue by GregDMeyer** [brucemiller/LaTeXML#2334]
Given the following `main.tex`:

```latex
\documentclass{article}
\usepackage{braket}

\begin{document}
$\braket{a|b}$
\end{document}
```

Running `latexml test.tex --dest=test.xml` yields an XML file including the line

```xml
...
    <p><Math mode="inline" tex="\braket{a}{b}" text="inner-product@(a, b)" xml:id="p1.m1">
...
```

The thing to note here is that the math in the `tex`  attribute does not match the original math in the TeX source. (This is breaking some parsing I am doing).

Thanks in advance!

**Comment by dginev** [comment]
Based on discussions in some previous issues (https://github.com/brucemiller/LaTeXML/issues/2092#issuecomment-1676123213), I don't think you should have the general expectation that the `tex` attribute will always retain the original TeX from the document source.

It's both technically a difficult question to solve in general, as well as a bit out-of-scope for LaTeXML's main purpose, which is conversion to structured formats.

We *could* patch this individual macro you've reported, adding an appropriate `reversion` directive in the binding here:
https://github.com/brucemiller/LaTeXML/blob/de34facab188f18c2181137950ad144b7d1dee90/lib/LaTeXML/Package/braket.sty.ltxml#L77-L79

But this is certainly going to be just one of many possible cases where the `tex` attribute will not match up with the source file.

**Comment by GregDMeyer** [comment]
got it, thanks!

Just to clarify---in this case the math `$\braket{a}{b}$` is not even equivalent to the original math: 

`\braket{a|b}`: $\braket{a|b}$
`\braket{a}{b}`: $\braket{a}{b}$

Should I have an expectation that compiling the `tex` attribute as math should not even match the original output?

**Comment by dginev** [comment]
Right, good point. I think we can safely agree that the reversion is incorrect here - as you show it leads to an incorrect rendering.

So a fix that uses a proper `reversion` attribute on that DefMacro would be one possible healthy upgrade.
