### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by nmatt** [brucemiller/LaTeXML#2366]
[Note: The “Report Issue” form on arxiv.org doesn’t seem to work on iOS Safari (nothing happens when pressing the “Submit in GitHub” button), so I hope this is the right place to submit an issue.]

On a tablet in portrait mode, or in a narrower browser window, the “justified” text alignment of HTML-ized arxiv papers often makes lines of text less readable, due to the shorter line length. It would be nice if there was an option for left-aligned text.

**Comment by dginev** [comment]
Hi @nmatt , this is definitely an arXiv-specific request.

I think it would really help to attach a couple of examples showcasing the need however, as it may be possible to reasonably improve their presentation also while in justified text alignment.

You can also leave a comment on the open issue I remember discussing this at before, it is at:
https://github.com/arXiv/html_feedback/issues/177#issuecomment-1867190189

Closing here as wontfix, as project-specific page design is downstream of latexml itself.
