### ISSUE TITLE
A health check issue

### ISSUE THREAD

**Issue by jvegh** [brucemiller/LaTeXML#2381]
I am trying LaTeXML for the first time.
I installed it with using
 sudo apt-get install latexml
and attempting to use it as
latexmlpost --destination=html Main.tex

where my Main.tex is

\documentclass[12pt,twoside]{memoir}
\begin{document}
		\input{src/Summary}  %
\end{document}

The log is

latexmlpost (LaTeXML version 0.8.6) paginating /home/jvegh/REPO/LaTeX/MyStuff/DynamicNeuron/Main.tex
Fatal:perl:die Perl died
	/home/jvegh/REPO/LaTeX/MyStuff/DynamicNeuron/Main.tex:1: parser error : Start tag expected, '<' not found
	\documentclass[12pt,twoside]{memoir}
	^
LaTeXML died! at /usr/share/perl5/LaTeXML/Common/XML/Parser.pm line 27.
Postprocessing failed 1 fatal error (See /home/jvegh/REPO/LaTeX/MyStuff/DynamicNeuron/Main.latexmlpost.log) (reqd. 0.00s)

It is probably some configuration issue on my system or maybe I do something wrong.
Any ideas or health check?

**Comment by dginev** [comment]
How did you arrive at that use of latexmlpost? There are two typical way of converting a TeX source from the command-line:

1. The classic two step (core + post-processing):
```
 latexml --dest=doc.xml doc ; latexmlpost doc --dest=doc.html 
```

2. Or the newer single command use:
```
 latexmlc doc.tex --dest=doc.html 
```

Both are advertised in the [Using LaTeXML](https://math.nist.gov/~BMiller/LaTeXML/manual/usage/) section of the manual.

**Comment by jvegh** [comment]
Hm, it looks like I am too creative. :-o) 
I have combined the classic 2-step compilation with the name of the single command. Thanks.

Now I have downloaded the .zip file, and I attempted to reproduce the manual.
I think I see some 'virgin install' problems (i.e., something is missing from the installation which is present on systems where it has also developer or manually installed files).
I receive the messages:

./makemanual 

==================================================
Extracting Release, PODS and Schema info
Use of uninitialized value $versions[0] in concatenation (.) or string at ... LaTeXML-master/doc/MakeTools.pm line 211.
Use of uninitialized value $versions[0] in hash element at ... LaTeXML-master/doc/MakeTools.pm line 212.

Writing datafile ... LaTeXML-master/doc/sty/latexmlreleases.tex
Can't locate Pod/LaTeX.pm in @INC (you may need to install the Pod::LaTeX module) ... LaTeXML-master/doc/manual/genpods line 8.
BEGIN failed--compilation aborted at ... LaTeXML-master/doc/manual/genpods line 8.
Failed to generate pods? at ./makemanual line 66.

 ./makesite

No archived releases found in ... LaTeXML-master/doc/LaTeXML/releases at ... LaTeXML-master/doc/MakeTools.pm line 198.

Can't locate Pod/LaTeX.pm ... LaTeXML-master/doc/manual/genpods line 8.

Generating html of manual
--------------------------------------------------
Error:missing_file:pods/latexml_exe Can't find TeX file pods/latexml_exe at manual.tex; line 2171 col 0
and 62 more similar messages

Info:expected:labels Using 'idx' to create page pathname, instead of missing 'labels' at ltx:index
Warning:expected:ids Missing Target for Label: LABEL:latexmlc,LABEL:latexmlpost,LABEL:latexmlmath,LABEL:latexml
Warning:expected:ids Missing Target for Label: LABEL:latexml

**Comment by dginev** [comment]
@jvegh what are you trying to achieve? 

If you want to convert your TeX/LaTeX sources to HTML, you shouldn't need to build the LaTeXML manual or website (`./doc/makemanual` and `./doc/makesite`). As you have seen, they also have dev dependencies that are not listed in the main `Makefile.PL`, as they are not required by most latexml users.

The best way to start playing around with LaTeXML (and thank you for trying it out!) is by applying it to your own documents, assuming they are first successfully building with a classic `pdflatex` or `xelatex` run.

**Comment by jvegh** [comment]
@dginev
Actually, I am looking for a framework to make an e-book size documentation, with sidebar, index, etc., and I wanted to use latexml manual as a template; i.e., not simply convert .tex to .html

**Comment by dginev** [comment]
@jvegh Great, you can get part of the way there with current LaTeXML support. You can use the `.epub` extension for your destination file, as with
```
 latexmlc doc.tex --dest=doc.epub
```

You can reuse some of the options for generating the latexml website in the call to `latexmlc`, but likely not all of them are appropriate in an ePub setting. You'll find them at:

https://github.com/brucemiller/LaTeXML/blob/40e9fa89efbf4006ddf06ecb57da4588aa661b4e/doc/makesite#L70-L78

It is usually better to open a dedicated issue for the kind of document you're trying to produce, and we can try and provide a working recipe - if one exists - or work with you to diagnose what upgrades to LaTeXML will be needed to produce the kind of document you're aiming for.

**Comment by xworld21** [comment]
> latexmlpost (LaTeXML version 0.8.6)

Further unsolicited tip: that version is ancient, relatively speaking. For Debian-based distributions, the latest Ubuntu .deb package can be installed directly and it will work just fine.
