### ISSUE TITLE
Symbols in table don't render

### ISSUE THREAD

**Issue by Anemoonvis** [brucemiller/LaTeXML#2443]
In the the paper [ℛ⁢𝒮⁢𝒱⁢𝒫: Beyond Weisfeiler Lehman Graph Isomorphism Test](https://arxiv.org/html/2409.20157v1) in table I the checkmarkx/crosses are not displayed in the html (instead it shows the 'raw code' for those symbols) while it is displayed correctly in the accompanying pdf. Since this table is central to the experiment, it would be great if this could be fixed!

**Comment by Anemoonvis** [comment]
Previously I tried to submit it via the form which didn't work, but now it does. So I'll close this and (re)submit that.

**Comment by dginev** [comment]
@Anemoonvis yes, please use the web form or submit directly to the arXiv repository here:
https://github.com/arXiv/html_feedback/issues

**Comment by Anemoonvis** [comment]
I did! Not sure why the first time I tried that the submit button just didn't do anything, but now it worked (issue #2754)
