### ISSUE TITLE
latexml silently dies when converting file with eps or pdf graphics (archlinux)

### ISSUE THREAD

**Issue by sergeG** [brucemiller/LaTeXML#2446]
latexml 0.8.8 (as well as the current git version) silently dies when converting LaTeX file with eps or pdf graphics. The OS is archlinux. 

I have both ImageMagick 7.1.1.41 and GraphicsMagick 1.3.45 installed as well as the corresponding perl modules. Moreover, 

gm  convert file.eps file.png 

and

magick convert  file.eps file.png

work as expected. I have no ideas what's wrong in my configuration.  

If png(s) are substituted instead of eps files, then conversion is successful.

**Comment by dginev** [comment]
@sergeG COUld you check if this matches the behavior described in #2239 ?

I think we are still trying to identify the exact cause there, so any additional thoughts are welcome.

**Comment by sergeG** [comment]
Exactly, the error code is 10.

**Comment by dginev** [comment]
Alright, thank you. I will close this issue as a duplicate and hopefully we get to the bottom of the failure before long.
