### ISSUE TITLE
integrate support for minted.sty

### ISSUE THREAD

**Issue by holtzermann17** [brucemiller/LaTeXML#291]
[Originally Ticket 1615]

http://code.google.com/p/minted/ has been making my day all week (running under pdflatex).

This would be lovely to have working within LaTeXML.

**Comment by dginev** [comment]
We have, unsurprisingly, received a request for minted at Authorea. And it turns out even pandoc "supports" it already by writing out a verbatim code block. Probably something to consider as a stop gap, I'm unsure if a partial implementation is better than no implementation here.

**Comment by brucemiller** [comment]
Writing out a code block probably works in many cases, but will fail if there are user defined macros inside; likewise it isn't really correct to attempt to "partially" expand only those user defined macros, although it might work occasionally.

Anyway, I guess it's time to admit that this binding isn't going to happen any time in the near future.  Sorry.l

**Comment by dginev** [comment]
cross-referencing an author's comment for [2109.04981](https://github.com/dginev/ar5iv/issues/4#)](https://github.com/dginev/ar5iv/issues/4#issuecomment-1056402270) in ar5iv, where minted support was mentioned explicitly.

I won't reopen the issue yet, but maybe we'll revisit it eventually...

**Comment by eric-wieser** [comment]
Is a partial implementation of `minted.sty` possible that just outputs a `Verbatim` block?

>For the record: since it uses an external python program/library,

For the purpose of ar5iv, minted never needs to execute python anyway, and runs on cached latex output from pygments consisting of a handful of style commands.

**Comment by dginev** [comment]
@eric-wieser appropriate that you mention ar5iv - there is a [stub implementation](https://github.com/dginev/arxmliv-bindings/blob/main/bindings/minted.sty.ltxml) for minted.sty already available there, which tries to emulate minted blocks via listings.sty listings.

I'm now nearing [50 additional .ltxml files](https://github.com/dginev/arxmliv-bindings/tree/main/bindings) for ar5iv, which mostly just try to do basic damage mitigation, until the mainline LaTeXML repository can integrate fully fleshed out support.

**Comment by eric-wieser** [comment]
Ah, then perhaps my diagnosis of https://github.com/dginev/ar5iv/issues/143 was incorrect; I assumed it was a lack of support for minted!

**Comment by dginev** [comment]
Another high-profile use of minted (if one day we are looking for real-life tests) can be found recommended in Lean 4's user manual, particularly [Syntax Highlighting Lean in LaTeX](https://leanprover.github.io/lean4/doc/syntax_highlight_in_latex.html) .
