### ISSUE TITLE
pstricks image breaks

### ISSUE THREAD

**Issue by holtzermann17** [brucemiller/LaTeXML#384]
[Originally Ticket 1708]

http://planetmath.org/inflexionpoint

Maybe pstricks isn't supported at all currently?  Anyway, this example doesn't work:

```
\begin{center}
\begin{pspicture}(-5,-2.5)(5,2)
\psaxes[Dx=9,Dy=1]{->}(0,0)(-4.5,-1.5)(5,2)
\rput(5,-0.2){$x$}
\rput(0.2,2){$y$}
\rput(3,-0.2){$\pi$}
\rput(-3.1,-0.2){$-\pi$}
\psplot[linecolor=blue]{-4}{4}{x 60 mul sin}
\psdot[linecolor=red](0,0)
\rput(0.2,-2.3){The origin is an inflexion point of the sinusoid \,$y = \sin{x}$.}
\end{pspicture}
\end{center}
```

**Comment by dginev** [comment]
closing until the day comes to address the `pst-*` ecosystem.

All: definitely reopen / let us know if that is an important toolchain for you, so that we can prioritize better.
