### ISSUE TITLE
Two TeX annotations for Math formulas

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#432]
[Originally Ticket 1756]

We were talking with Howard about the two use cases of copying math sources from formulas:
1. Copy the lowest level of expanded TeX to have 100% guarantee that it will compile in your document (= presentation-oriented copy)
2. Copy the highest level of semantic TeX to have 100% guarantee that it will carry over the semantics to your document (= content-oriented copy)

We refactored the following macro:

```
DefMath('\EulerConstant',"\x{03B3}", role=>'ID',
    meaning=>'Euler-constant'); # GREEK SMALL LETTER GAMMA
```

into:

```
DefMath('\EulerConstant','\gamma', role=>'ID',
    meaning=>'Euler-constant'); # GREEK SMALL LETTER GAMMA
```

Which created the same presentation, but had now changed the annotation from:

```
<annotation encoding="application/x-tex">\left|\EulerConstant\right|</annotation>
```

to:

```
<annotation encoding="application/x-tex">\left|\gamma\right|</annotation>
```

So, it hit us that if we have DefMath statements which have lower-level TeX macros to expand into and at the same time the role and meaning attributes, the conversion could record two-forms of "original TeX", one form stopping at the highest level that has "meaning" (= preserve semantics), the other stopping at the lowest expandable level (= ensure compilable presentation).

**Comment by brucemiller** [comment]
As said, the proper way to store _either_ `@tex` or `@content-tex` in the MathML is with an annotation; If you want _both_, then we'll need some way (a special mime type?) to distinguish them, _and_ likely need another option to choose (currently `--mathtex` adds the `@tex` annotation)

**Comment by dginev** [comment]
Yes, similarly to my "math lexemes" PR. It's kind of strange that math is just a single modality, yet there are all these parallel representations that end up being handy, and similarly strange that each would necessitate its own option.

I still think it would be a useful enhancement, and it's schedule for a very distant milestone as it should be... May be good to keep in mind.

**Comment by dginev** [comment]
I've lost focus on the need for multiple tex attributes, at least for the moment, I think a lot of betterment can be brought along by having great locators instead. And I am itching to close old issues, so this one may be a good first sweep.
