### ISSUE TITLE
Be smarter with \itemsep?

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#502]
I am testing some LaTeX files and find myself grabbing for more spacing between my itemized examples, e.g. via:

```
\begin{itemize}\itemsep4em
...
```

At the moment, LaTeXML simply ignores the vertical queues (to the best of my understanding). It would be a step forward to have that information preserved in the final HTML, maybe rounded to an integer? Then one can define CSS rules for the vertical distance, e.g. for "ltx_itemsep_em4", "ltx_itemsep_em5", or so. 

Not preserving the distance precludes any styling in any case, so I guess doing that is the first step in a more stylized direction.

**Comment by brucemiller** [comment]
Itemsep is now preserved. Thanks for the report!

**Comment by dginev** [comment]
Awesome news! Thanks for the enhancement!
