### ISSUE TITLE
Support postprocessing to bundle FirefoxOS Web app

### ISSUE THREAD

**Issue by fred-wang** [brucemiller/LaTeXML#510]
I've recently been using LaTeXML and bash scripts to generate (packaged) FirefoxOS Web apps. Such apps are essentially:
- Web pages
- a manifest (http://cermat.org/events/MathUI/14/proceedings/FirefoxOS-for-Science/demos/app/manifest.webapp)
- everything zipped in one archive (e.g. http://www.maths-informatique-jeux.com/webapps/mathui-demos/package.zip)
- that's all!

They can be installed on FirefoxOS, Android and Desktop: http://www.maths-informatique-jeux.com/webapps/mathui-demos/ (in general apps are available from https://marketplace.firefox.com/).

So I believe that should be quite easy to use the work done for EPUB to support FirefoxOS Web apps, and that would be helpful for people willing to publish some apps in the "books" category of the FirefoxOS marketplace. Some issues I noticed:
- Links in LaTeXML to the main index have the form "./" (without the page name), which shows the directory content in FirefoxOS web apps (similar to what happens for local files) and is probably not what people want. A solution is to use the form "./index.hml" (or "./index.xhml") instead.
- Web apps don't have a "back" button, so there should not be a page where the user is "blocked" (this is a requirement for the app to pass the MarketPlace review). By default, LaTeXML has good navigation links, so that's not a problem. However, it is a problem for external links (for example the "generated by LaTeXML" link or other links with the href package). A solution proposed by the reviewer is to use target="_blank" on external links, so that they will be opened in the browser.

Other optional things:
- Would be good to be able to bundle Web fonts too (#461)
- Have some kind of "mobile UI". FYI, here is what I use:
  @namespace "http://www.w3.org/1999/xhtml";
  /\* Update LaTeXML css style to get some kind of "mobile UI" _/
  body {
  margin: 0;
  background: linear-gradient(45deg, #b50, #e80);
  }
  .ltx_page_main {
  padding: 0;
  }
  .ltx_page_header, .ltx_page_footer {
  border: 0;
  }
  .ltx_page_header a[rel="up"] {
  font-size: 250%;
  }
  .ltx_page_header a[rel!="up"] {
  font-size: 0.8em;
  }
  .ltx_page_header a {
  color: white !important;
  }
  .ltx_page_footer a {
  color: white !important;
  }
  .ltx_page_logo {
  display: none;
  }
  .ltx_page_content {
  background: #ffc;
  padding: .5em;
  }
  /_ Links */
  a, a:visited {
  color: blue;
  }
  a:hover {
  color: red;
  }
- support receipt verification for paid app (https://developer.mozilla.org/en-US/Marketplace/Monetization/Validating_a_receipt).

**Comment by brucemiller** [comment]
I'll admit that I'm pretty unlikely to work on this myself. However, it sounds like a perfect candidate for a plugin.  And we could claim that once we've sorted out the plugin api, with probably a good example for DOC processing, this might be a simple thing you could assemble yourself. It would probably benefit from a few extra core features, such as what was requested in #524.

**Comment by dginev** [comment]
This has gone stale, and as much as I would like to see the support, I think we should close until we find a volunteer to do the wrench work. As Bruce has mentioned, we need to finalize our plugin framework first so that this can be done in an elegant way, so we can get back to it post 0.8.4.
