### ISSUE TITLE
need a binding for endnotes package

### ISSUE THREAD

**Issue by eshellman** [brucemiller/LaTeXML#520]
The project I'm trying to convert is
http://bzr.savannah.gnu.org/lh/books/files/head:/free-as-in-freedom-v2/

There is a null binding at https://svn.kwarc.info/repos/arXMLiv/trunk/sty/endnotes.sty.ltxml 
but it doesn't define any of the tokens in endnote

Have discussed on the mailing list, entering an issue here to track progress.

**Comment by SepidehAlassi** [comment]
has there been any progress on binding for endnotes? I need it for my current project. Thanks
