### ISSUE TITLE
latexml omits parentheses from tag

### ISSUE THREAD

**Issue by swalter62** [brucemiller/LaTeXML#533]
LaTeX interprets the contents of `\tag{}`, in math mode if requested, and encloses it in parentheses. LaTeXML, on the other hand, interprets the contents in text mode, and omits the parentheses. Not quite a bug, but a surprising difference, and an ugly one, as a tag like `\tag{$2'$}` results not in `(2')`, but in `$2^{\prime}$`.
Here's a MWE:

```
\documentclass{article}
\usepackage{amsmath}
\begin{document}

Here's a numbered equation:
\begin{equation} 
y = mx + b
\end{equation}

Here's a numbered equation with a hand-rolled tag:
\begin{equation} 
z = mx + b\tag{$1'$}
\end{equation}
\end{document}
```

No errors or warnings are thrown by latexml or latexmlpost, but I can post the output if so desired.
The LaTeXML `\tag{}` behavior is not difficult to work around, but it would be handy to be able to use math mode in tags, all the same.

**Comment by brucemiller** [comment]
Finally!! Fixed!!! Thanks for the report!

**Comment by swalter62** [comment]
Thanks a million, Bruce!
