### ISSUE TITLE
\usepackage{svg}

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#539]
As this used a shell escape to inkscape I wonder whether that would work in latexml. IIRC latexml supports .svg images. I do not see how?

**Comment by brucemiller** [comment]
I've implemented this package for the most part (except perhaps creating raster images from the svg). Thanks for the report!

**Comment by bernhard-kleine** [comment]
I can now compile the whole document with a few warnings. latexml and latexmlpost, but the svg are missing. Can we investigate?
