### ISSUE TITLE
Figure not showing

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#544]
I have a figure:

``` latex
\begin{figure*}[hbt]
  \centering \small
  \includegraphics[%
    % draft,%
    width=\figurewidth%
  ]%
  {Chap3/g/HP_Achsen}
           \caption{Endocrine regulation via hypothalamic--pituitary axes}\label{fig:hpaxes}
\end{figure*}
```

which does not show up while there is no error message.
The relevant text in test1.html  formed by

```
latexmlpost test1.xml --destination=test1.html --format=html5 --index
```

remains empty: <img src="" ...

``` html
<figure id="Ch3.F1" class="ltx_figure"><img src="" id="Ch3.F1.g1" class="ltx_graphics ltx_centering" alt="">
<figcaption class="ltx_caption ltx_centering ltx_font_small"><span class="ltx_tag ltx_tag_figure">Figure 3.1: </span>Endocrine regulation via hypothalamic–pituitary axes. </figcaption>
</figure>
```

In Chap3/g/ are both HPAchsen.pdf and HPAchsen.svg and HPAchsen.svg is one candidate mentioned in test1.xml:

``` xml
 <figure frefnum="Figure 3.1" placement="hbt" refnum="3.1" xml:id="Ch3.F1" labels="LABEL:fig:hpaxes">
          <graphics candidates="Chap3\g\HPAchsen.pdf,Chap3\g\HPAchsen.svg,Chap3\g\HPAchsen.pdf,Chap3\g\HPAchsen.svg" graphic="Chap3/g/HPAchsen" options="width=327.206693pt" xml:id="Ch3.F1.g1" class="ltx_centering"/>
```

 The figure as such is there with the caption but the image is lacking. please advise

**Comment by bernhard-kleine** [comment]
I have built a testcase, and it turns out it is a problem of the browser: when you open http://b-kleine.com/test/testverxml.html in Chrome the threeparts of svg are displayed: the labeling of the tree and the two figures  while in Firefox nothing is seen. Very strange!

**Comment by brucemiller** [comment]
I'm seeing height=6 on the foreignObjects.  Isn't that a patch that you had applied to get the labels visible? Perhaps it still is being applied?  I don't think the current LaTeXML does that; should have ```100%```, I think.

**Comment by bernhard-kleine** [comment]
Yes I manipulated the html to make it visible. 6 is the smallest value to see the labels, no that they are visible it turns out that they are wrongly positioned. Any idea where I can change that?

**Comment by bernhard-kleine** [comment]
By the way, I am not familiar with "git pull". I use the zip file.

**Comment by brucemiller** [comment]
I assume you mean a zip file from github? If so, I would assume that it represents the current state of the repository; I've never used it myself.

Regarding you comment about "6".  You have apparently made some changes on your end to get that "6", and maybe some other changes?  You need to remove those changes before we can determine if LaTeXML is doing the right thing.  Using the current LaTeXML labels seem always to be visible. Positioning seems usually close, sometimes slightly high, sometimes slightly low; LaTeXML probably has lost some information about size or baseline somewhere? At any rate, the labeled trees that you've given as examples seem to work pretty well for me.

At any rate, what you're talking about now, is not related to this issue, is it?

**Comment by bernhard-kleine** [comment]
The issue is svg figures not showing. I recognized that firefox has a problem and does not show the svg. Obviously the issue is misguiding.

**Comment by brucemiller** [comment]
Again: short example source & result. The page you've linked to above was *not* created by an unmodified LaTeXML, so there's really nothing I can do to fix it.
