### ISSUE TITLE
Problem handling German floats. 

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#548]
Here is something I stumbled over today and I would like to discuss this with you (@dginev may also find this interesing): 
When I use ```$0.717$``` in LaTeX, I get 
```XML
<Math mode="inline" xml:id="p1.m1" tex="0.717" text="0.717">
  <XMath>
    <XMTok meaning="0.717" role="NUMBER">
      0.717
    </XMTok>
  </XMath>
</Math>
```
which is very nice. But when I am in German, and I use ```$0,717``` I get 
```XML
<Math mode="inline" xml:id="p1.m1" tex="0,717" text="list@(0, 717)">
  <XMath>
    <XMDual>
      <XMApp>
	<XMTok meaning="list"/>
	<XMRef idref="XM1"/>
	<XMRef idref="XM2"/>
      </XMApp>
      <XMWrap>
	<XMTok meaning="0" role="NUMBER" xml:id="XM1">0</XMTok>
	<XMTok role="PUNCT">,</XMTok>
	<XMTok meaning="717" role="NUMBER" xml:id="XM2">717</XMTok>
      </XMWrap>
    </XMDual>
  </XMath>
</Math>
```
not so nice. There is a language discrepancy between the two. I am not sure that we want to parse $0,717$ as a float in English. Especially, since you can use dots as a divider for natural numbers in German e.g. ```1.000.000.000``` for a billion. This is ''not'' a float. 

We have been talking about language-specific markers for hyphenation recently, so becoming more language-aware may have a good side here.

**Comment by dginev** [comment]
We should also consider Brazilian among the languages where commas are used for a decimal separator, as indicated by the now closed #573.

**Comment by kohlhase** [comment]
Has there been any progress on this? 

As much as I appreciate the general complexity of the problem, I do think we can pick some low-hanging fruit here easily. For instance, just make the current number parsing algorithm parametric in the language (which we pick up from babel, if present and otherwise just assume English), and set the separator accordingly. This "making parametric" in the language would probably make subsequent improvements easier.

**Comment by kohlhase** [comment]
I would really like to know about the ETA of the first level of support, otherwise we will have to work around this for the glossary.

**Comment by brucemiller** [comment]
It isn't inherently complex, just very awkward to find the right place to associate the language with it's decimal and thousands separators, and how to effect the control. The numprint package is the only place I've seen in TeX that attempts to recognize the association, but it doesn't seem quite right to only support the feature only with numprint.

Let me see if I can get some initial support built in, this weekend.

**Comment by brucemiller** [comment]
actually, it's a bit of a mess, but there's initial support for this now.  It isn't really customizable, but I've copied the languages for which numprint gives special decimal and thousands separators.  Hopefully that will work for you for the time being.

**Comment by kohlhase** [comment]
cool thanks.

**Comment by fred-wang** [comment]
@brucemiller What was the commit? Did you use https://en.wikipedia.org/wiki/Decimal_mark#Hindu.E2.80.93Arabic_numeral_system ?

**Comment by brucemiller** [comment]
Mainly that was in be42fbdfd1a5497cda3e31c339a1e51fba9d7c05.  It's pretty clumsy.

No, I didn't use that page, but it's a good resource.  The current code keys the switch on the ISO language code (with a short, hand-coded list: en, de, fr, nl, pt).  So I'd have to convert that page's list into country codes. That's kinda tedious and I haven't got time now, but if you did... :>

I guess there are also cases where the region suffix matters, so I'd have to figure out a way to deal with that.

**Comment by fred-wang** [comment]
> I guess there are also cases where the region suffix matters, so I'd have to figure out a way to deal with that.

Apparently there are, since I noticed that Spanish countries are in both lists.

**Comment by fred-wang** [comment]
> Apparently there are, since I noticed that Spanish countries are in both lists.

Spanish-speaking I meant... ;-)

**Comment by brucemiller** [comment]
ok; almost had to send you to diversity training!
