### ISSUE TITLE
latexm does not export with tee

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#561]
I wonder why a command like

```
latexml --dest=test.xml test.tex | tee test.xml.log
```

does not pipe the output of the screen to test.xml.log. Can you please explain? Is it strange BTW?

I found this problem first with windows 7 and thought I might be due to windows. However, the same happens with linux and that I will not accept as a system error since that works well with other programs on the command line, it must have to do with latexml or perl.

On the other hand a logfile as an alternative would be most welcome.

**Comment by bernhard-kleine** [comment]
Finally I sorted this out: latexml --dest=test.xml test.tex 2> test.log works in win7, the |& does not

**Comment by dginev** [comment]
If you use latexmlc, you can avoid any of the ```>``` redirects, you can do for example

```
latexmlc --log=test.log --dest=test.xml
``` 

which is platform-independent and can get you a log file.
