### ISSUE TITLE
Threeparttable not supported

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#564]
This is the only package in latex which supports footnotes in tables and figures. Any support would be gratefully acknowledged.

**Comment by brucemiller** [comment]
I just committed a (nominal) binding of threeparttable.sty. Thanks for the report.

**Comment by bernhard-kleine** [comment]
Thanks a lot

 

Bernhard

 

Von: bruce miller [mailto:notifications@github.com] 
Gesendet: Freitag, 1. Mai 2015 12:56
An: brucemiller/LaTeXML
Cc: Bernhard Kleine
Betreff: Re: [LaTeXML] Threeparttable not supported (#564)

 

Closed #564 <https://github.com/brucemiller/LaTeXML/issues/564> .
