### ISSUE TITLE
Implement optional args for origin in \rotatebox

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#566]
The following example throws an error with the latest and earlier builds:

```tex
\documentclass[12pt,a4paper]{book}
\usepackage{rotating}% für gedrehte Tabelle etc.
\DeclareRobustCommand*{\textvertell}{%
    \hspace{.2ex}\rotatebox[x=-0pt,y=-.25ex]{90}{\textellipsis}%
  }%
\DeclareRobustCommand{\bild}[1]{\textit{#1}} 
\begin{document}
  similar amino acids by {\bild{\footnotesize\textvertell}}\ , cysteines are shown 
\end{document}
```

**Comment by brucemiller** [comment]
I think I finally got this sorted out. Origin arguments should work now. Thanks for the report.

**Comment by dginev** [comment]
The code needed to get this right is somewhat intimidating. Nice fix!

Also, pretty happy that you're closing issues in the 0.8.2 milestone, a new minor release may be on the horizon for mid-fall. Just a cheerleading comment :>
