### ISSUE TITLE
`mathsvg` option not supported in LaTeXML 0.8.0

### ISSUE THREAD

**Issue by ThomasA** [brucemiller/LaTeXML#574]
I have installed LaTeXML 0.8.0 from http://dlmf.nist.gov/LaTeXML/releases/LaTeXML-0.8.0.tar.gz in the hope of using it to convert LaTeX with maths into HTML with maths in SVG using the `--mathsvg` option as documented here: http://dlmf.nist.gov/LaTeXML/manual/commands/latexmlpost.html

I have verified that I am running the correct version:
```bash
$ latexmlmath --VERSION
latexmlmath (LaTeXML version 0.8.0)
```
but attempts to use the option fail:
```bash
$ latexmlpost --format=html5 --mathsvg test.xml 
Unknown option: mathsvg
```
The option is not shown in the help command either:
```bash
$ latexmlpost --help|grep svg
        --svg                   converts picture environments to SVG
        --nosvg                 disables the above (default)
             svg png gif jpg jpeg eps.png ps.png ai.png pdf.png
       "--svg", "--nosvg"
```

**Comment by dginev** [comment]
The option was introduced later than the 0.8.0 release. It will be available to the soon to be issued 0.8.1. You can already use the option if you install LaTeXML from GitHub, as described here:
http://dlmf.nist.gov/LaTeXML/get.html#SS7

**Comment by ThomasA** [comment]
That makes the online documentation quite confusing then. I will try the 
GitHub version, thanks.

**Comment by dginev** [comment]
You are completely right that the online documentation ought to have a reference to LaTeXML version and GitHub revision, in order to avoid confusion.

Sorry you had to install 0.8.0 in vain!
