### ISSUE TITLE
latexmlc: Create subdirectory structure for --log if it does not exist

### ISSUE THREAD

**Issue by tkw1536** [brucemiller/LaTeXML#575]
When I do: 

```
latexmlc file.tex --log=/non/existing/folder/file.ltxlog
```

latexmlc simply dies with: 

```
Fatal:I/O:forbidden Couldn't open log file /non/existing/folder/file.ltxlog : No such file or directory
```

It would be good if latexmlc could create subdirectory structures for the log file if it does not exist. 
/cc @dginev KWARC/localmh#194

**Comment by brucemiller** [comment]
Oh, cool! Deyan has already assigned it to himself :>

We've usually tried to automatically create directory structure where needed when files are written, but sometimes we've overlooked it; there's a handy ```pathname_mkdir``` for this.
