### ISSUE TITLE
Error with \usetikzlibrary{babel}

### ISSUE THREAD

**Issue by fred-wang** [brucemiller/LaTeXML#577]
Reduced testcase:

    \documentclass{book}
    \usepackage[spanish]{babel}
    \usepackage{xunicode}
    \usepackage{fontspec}
    \usepackage{tikz}
    \usepackage{graphicx}
    \usetikzlibrary{babel}

    \begin{document}
    \chapter{Test}

    \begin{tikzpicture}
      \draw[->] (0,0) -- (0,4);
    \end{tikzpicture}

    $$u_{n+1} = u_n + k$$

    \end{document}

If you remove the last equation the conversion succeeds. If you remove \usetikzlibrary{babel}, then the tikzpicture fails (this one is expected, see https://sourceforge.net/p/pgf/bugs/274/).

**Comment by dginev** [comment]
Did we ever even test with the babel tikz library? My gut feeling is that we never have.

**Comment by brucemiller** [comment]
Nope: and the very fact that tikz and babel won't natively cooperate, but need a special tikz library, gives me a *bad* feeling.  A quick test shows that it ends up with a stray ```\endcsname``` and a stray ```\fi```.  So, a fishing expedition!

**Comment by brucemiller** [comment]
I hadn't intended to fix this yet (or thought I could), but.... amusing.

Turns out that the spanish makes "." active, and that messed up the macros for ID's, which were being processed in math mode, but shouldn't have been.

Anyway, fixed; thanks!
