### ISSUE TITLE
Shebangs for bindings

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#578]
This is a tiny discussion issue on an entirely cosmetic feature.

Namely, I find myself linking to concrete lines in ```.ltxml``` binding files on GitHub quite often these days, and I love the ability to do so - it is powerful for conveying precise information.

The one thing that really eats at me though is that GitHub doesn't know how to highlight the ```.ltxml``` extension and leaves it as plain text. I would just love to have the bindings highlighted as Perl. From my digging, it seems GitHub uses(used?) an external library for the highlighting called Pygments, which doesn't easily allow for customizations.

There is only one clearly supported way - to add a shebang at the start of each binding file. We are currently using the following in LaTeXML:
```
#!/usr/bin/perl -w
```

It is an annoyance to add that to all binding files for sure, but it is very simple to automate (it's always prepended at the start of the binding). Here is an example of what I have in mind:

1. Regular binding
https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch/blob/50d4e8d76c8b4d869f7427fcb85f7dcdb0369d97/lib/LaTeXML/Package/mws.sty.ltxml

2. Shebanged binding
https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch/blob/746a5b9d031a3af251b3b22a7b1d6e1fd742cf99/lib/LaTeXML/Package/mws.sty.ltxml

Thoughts? I could offer as a freebie to make a pull request and send the change over at 0 effort for you.

**Comment by dginev** [comment]
Oh and I should add GitHub also enabled highlighting in diffs, so binding diffs can look as good as the ```.pm``` diffs:
https://github.com/brucemiller/LaTeXML/commit/4c0a83617f241a4fd81fb0511c34d7e03acb02eb

**Comment by brucemiller** [comment]
Seems perverse, as if they're executable...

You think there's any chance of recognizing emacs mode-lines....

Oh, wait: I think my google foo wins: They're now using Linguist, and there's an open issue:
https://github.com/github/linguist/issues/1792
which should make syntax highlighting reflect customizations.
I've added a .gitattributes file which asserts that ltxml is Perl (assuming that they hadn't already recognized it from the modeline).

**Comment by dginev** [comment]
Ah yes, they had switched to Linguist, true.

I left a comment on your commit - while the new .gitattributes file will fix the GitHub stats, it won't affect the highlighting for "performance reasons".
https://github.com/brucemiller/LaTeXML/commit/144060be299728e6e9f76e45db5ca1bb55b9533e#commitcomment-9684441

Do I understand correctly that you would rather wait for the CPERL emacs heuristics to be implemented and have that trigger the highlighting? That would work, if it materializes.

**Comment by brucemiller** [comment]
I think the mode-line stuff is done and either in effect now, or will be soon. (But it could be that it doesn't know that CPERL == Perl?).

If there's a chance that the mode-line would work, I'd rather go with that. There's already an incentive to add those lines to all files! :>

**Comment by brucemiller** [comment]
Aha! Thanks to @arfon Linguist already supports language formatting based on the emacs modeline, provided it's in the more restrictive form:
```
# -*- mode: Perl -*-
```
and I really needn't have (maybe *shouldn't* have) been using CPERL in the modeline, since any reasonable emacs has already been configured to use cperl mode for perl language files.

I've updated all the *.ltxml and *.latexml, to get the modeline, including some that hadn't had one yet, so it seems a win-win! :>

Thanks for the prodding!

**Comment by dginev** [comment]
What a feast for sore eyes! The bindings look *beautiful* now, completely loving it!

Thanks for the refactor!
