### ISSUE TITLE
Error with \right. and \usepackage[spanish]{babel}

### ISSUE THREAD

**Issue by fred-wang** [brucemiller/LaTeXML#579]
Reduced testcase:

      \documentclass{book}
      \usepackage[spanish]{babel}

      \usepackage{xunicode}
      \usepackage{fontspec}

      \begin{document}

      $\left\{x\right.$

      \end{document}

**Comment by brucemiller** [comment]
Hmm... turns out it was tricky.  But fixed, I think 895edc95d30852cc8678bff5a372060df401943a  & 837fdc5293c016edef7c81509d13efb19a393f32.  Thanks!

**Comment by fred-wang** [comment]
thanks!
