### ISSUE TITLE
Binding request: siunitx & friends, enumitem, type1cm, listingsutf8, braket

### ISSUE THREAD

**Issue by matteosecli** [brucemiller/LaTeXML#580]
I've just encountered some unsupported packages while converting one of my documents, that prevent my document to be converted. They are:
- siunitx.sty,
- enumitem.sty,
- type1cm.sty,
- listingsutf8.sty, 
- braket.sty.

I think that the most important is "enumitem", because it allows lists in the form a) b) c) d) etc..., that are a daily matter in writing LaTeX documents. Then, the second most important is "braket", because it's widely used if you write quantum mechanical stuff. I don't really have the necessary knowledge to help you (otherwise I would), but I don't think that translating "braket" macros into HTML should be so difficult, since the commands can be rewritten in plain LaTeX.
Thank you for your efforts and for your program; it's AMAZING! So far, it's the best in what it does, and I've seen huge improvements during these years.
Keep on this way! :D

**Comment by brucemiller** [comment]
Thanks for the kind words; it's appreciated!

* I think that type1cm.sty is pretty much ignorable, so I've created an empty binding for that.
* I'm hoping that the encoding issues that make listingsutf8 necessary aren't relevant to latexml, so I've defined listingsutf8 to simply load listings; let me know if that works out.
* The two packages siunitx and braket have some interesting semantics and so really should be done.
* and enumitem is also an interesting and useful package, but will take some time to integrate into latexml.

So, sofar, I've only fixed the least useful parts! Hopefully won't take till 0.9 to get done, but I'll leave that Milestone for now

**Comment by matteosecli** [comment]
Thank you for the quick response!
I've just compiled and tried the new version, and now my document compiles (if you wanna use it as a test for the other packages I've reported, it's in one of my repos: https://github.com/matteosecli/QMC/blob/master/LaTeX/main.tex). It's -- obviously -- full of errors about the "braket" package, but apart from that the result is still nice. The listingsutf8 package works correctly, now; and I agree with you that "type1cm" doesn't matter for a HTML output, it was just for a better PDF.
I've read a little bit the documentation and the code that you used to implement some packages; I've also read about sTeX and the importance of semantic. I hope I will learn enough to eventually give some help, but it will take me quite a long time because I've a lot of stuff to program in other projects and I don't know Perl at all.
In the meantime, I will keep reporting bugs! ;)

**Comment by brucemiller** [comment]
OBTW: braket was actually quite easy, and I did manage to squeak that into the distribution before releasing 0.8.1.  siunitx looks interesting and useful, but it's a bit larger, so it, along with enumitem will come later.

**Comment by matteosecli** [comment]
Thanks again!
I tried to recompile my document with version 0.8.1_rev114e1eb a couple of days ago, and the "braket" parts worked like a charm. The output is as perfect as expected on both Chrome+MathJax and Firefox with native MathML.

**Comment by dginev** [comment]
We ended up needing siunitx, SIunits and hepunits at Authorea immediately, so we ended up writing a mock [stub](44c96706b7b13d26d4b527af36f3c3064605c813) for those files, which is also partial. I'm a bit time constrained w.r.t getting to a full implementation, but at the very least I'll add the Authorea label here, and try to help with making a PR for those packages, together with any other interested parties.

**Comment by SmnWntr** [comment]
I'm not familiar with technical terms such as siunitx, mock stub, PR, etc. But did I get that right: the enumitem package will be implemented soon? Since almost all the papers I convert make use of it, this would be highly appreciated! Best regards, Simon

**Comment by dginev** [comment]
Thanks for giving a :+1: to this issue @SmnWntr ! The enumitem package is certainly part of it.

Bruce mentioned earier that it "will take some time" to integrate it into LaTeXML, but with growing interest we can at least prioritize the issue more. I am yet to look into it myself, but we'll get there.

**Comment by 0-wiz-0** [comment]
I'm also interested in an enumitem binding.

**Comment by brucemiller** [comment]
An update: I ended up committing a bare-bones enumitem; it avoids errors, but doesn't yet respect the options.  Some will ultimately be easy, but there are so many!

Summary so far: braket, type1cm, listingsutf8 supported; enumitem partially; siunitx do be done!

**Comment by brucemiller** [comment]
Oh, cool; overlooked this one! All these packages have at least minimal bindings. Thanks for the request!

**Comment by mspertus** [comment]
Any prospects for \newlist in the enumitem binding? That is a pretty common reason for using enumitem.

**Comment by brucemiller** [comment]
Hmm, yeah. But it doesn't make much sense without proper processing of the key values.  I guess I knew this partial binding wasn't going to be good enough for long! :>  I've openned #1015 to finsih this; hopefully we can do something soon.
