### ISSUE TITLE
no displayed equations in footnotes

### ISSUE THREAD

**Issue by swalter62** [brucemiller/LaTeXML#581]
While inline math mode within a footnote is handled correctly by LaTeXML, displayed math appears in the main text, without so much as a warning. Here's a test case, eqn-in-note.tex:
```
\documentclass{article}
\begin{document}
Let's say we want to put an equation in a footnote.\footnote{Here's
  the equation: \[ F=ma. \]}
\end{document}
```
When I run ```latexml --dest=eqn-in-note.xml eqn-in-note``` I get the following:
```
latexml (LaTeXML version 0.8.0_04; revision 848a45d)
processing started Sat Feb 14 22:35:39 2015

(Digesting TeX eqn-in-note...
(Loading /usr/local/share/perl/5.20.1/LaTeXML/Package/TeX.pool.ltxml...
(Loading /usr/local/share/perl/5.20.1/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /usr/local/share/perl/5.20.1/LaTeXML/Package/pdfTeX.pool.ltxml... 0.00 sec) 0.13 sec)
(Processing content /home/pub/test/eqn-in-note.tex...
(Loading /usr/local/share/perl/5.20.1/LaTeXML/Package/LaTeX.pool.ltxml... 0.15 sec)
(Loading /usr/local/share/perl/5.20.1/LaTeXML/Package/article.cls.ltxml... 0.01 sec) 0.18 sec) 0.31 sec)
(Building...
(Loading compiled schema /usr/local/share/perl/5.20.1/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.04 sec)
(Rewriting... 0.00 sec)
(Math Parsing...1 formulae ...[1]
Math parsing succeeded:
   ltx:XMath: 1/1
Symbols assumed as simple identifiers (with # of occurences):
   'F{italic}' (1), 'a{italic}' (1), 'm{italic}' (1)
 0.01 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.
processing finished Sat Feb 14 22:35:40 2015
```
Here's the output of ```latexmlpost --dest=eqn-in-note.html eqn-in-note.xml```:

```
latexmlpost (LaTeXML version 0.8.0_04; revision 848a45d)
processing started Sat Feb 14 22:38:05 2015
(eqn-in-note.html post-processing...
(Scan eqn-in-note.html processing...
(CrossRef eqn-in-note.html processing...
(MathML::Presentation eqn-in-note.html processing...
(XSLT eqn-in-note.html processing...
(Writer eqn-in-note.html processing... 0.02 sec)
Postprocessing complete: No obvious problems
processing finished Sat Feb 14 22:38:05 2015
```
LaTeX accepts display math in footnotes, so this behavior of LaTeXML is a bit disconcerting. A workaround would be to convert all display math in footnotes to inline, I guess, but recovery of the LaTeX standard in LaTeXML would be far better, by my lights.
Best,
Scott

**Comment by brucemiller** [comment]
Actually, if you inspect the XML & HTML, you'd see that it *has* put the equation in the footnote. Unfortunately, the block-level markup used for the equation isn't allowed within the html span used for the footnote, and the HTML5 parser essentially rewrites the document to conform to its model (HTML4 and XHTML will probably yield what you expect, inspite of the lack of validity).

See #526 and #572 for more discussion.
The fix for #572 needs to be extended further into the tables used for displayed equations, but it is a bit trickier. I'll work on this, but probably not by the 0.8.1 release coming up.

**Comment by swalter62** [comment]
I see the problem -- I'd guessed that this issue was related to #572, and can confirm that XHTML yields the expected output. Thanks for taking this up!

**Comment by brucemiller** [comment]
I've updated the XSLT & CSS to go into span-soup mode when equations appear in a non-block context.  So equations inside footnotes (and other peculiar places) should work now. Hopefully no negative side-effects! :>  Thanks for the report

**Comment by swalter62** [comment]
I tried it out the new code, and can confirm your success: we now have equations displayed in footnotes in HTML5. Thanks a million!

**Comment by dginev** [comment]
I can confirm too, here is a link to a demo:
latexml.mathweb.org/editor?tex=There%20is%20an%20equation%20in%20this%20footnote%5Cfootnote%7BTrue%3A%20%24%5Csqrt%7Bx%7D%5Cgeq0%24%7D

**Comment by swalter62** [comment]
Upon further testing, I notice the following problem with numbered equations in footnotes: the equation number appears on the subsequent line to that of the displayed equation. I will supply a test file if you like, but since automatic numbering is the default in the equation environment, the behavior I describe is easily reproduced. Can this be repaired?

**Comment by dginev** [comment]
Since I am now addicted to linking to TeX snippets on the showcase, here is a fully reproducible example from the last comment by  @swalter62 :

http://latexml.mathweb.org/editor?tex=There%20is%20an%20equation%20in%20this%20footnote%5Cfootnote%7BTrue%3A%20%5Cbegin%7Bequation%7D%5Csqrt%7Bx%7D%5Cgeq0%5Cend%7Bequation%7D%20False%3A%20%5Cbegin%7Bequation%7D%5Csqrt%7Bx%7D%3C0%5Cend%7Bequation%7D%7D

**Comment by brucemiller** [comment]
I think I have a safe fix for the css padding in equations now; works here. I also took the opportunity to make the popups a little prettier.

**Comment by dginev** [comment]
Oh nice, it looks gorgeous! You can click on my [previous link](http://latexml.mathweb.org/editor?tex=There%20is%20an%20equation%20in%20this%20footnote%5Cfootnote%7BTrue%3A%20%5Cbegin%7Bequation%7D%5Csqrt%7Bx%7D%5Cgeq0%5Cend%7Bequation%7D%20False%3A%20%5Cbegin%7Bequation%7D%5Csqrt%7Bx%7D%3C0%5Cend%7Bequation%7D%7D) for a live demo.

**Comment by swalter62** [comment]
I concur with Deyan: it looks great, Bruce, equation numbers and all in HTML5.
