### ISSUE TITLE
\lxRDF parameters mis-documented?

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#582]
So, I am using the ```lxRDFa.sty.ltxml``` delights for smoothly adding RDFa metadata to my blog posts, which works incredibly nicely!

This issue is to report that the documentation of ```\lxRDF``` seems out of date. In particular, see:
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/lxRDFa.sty.ltxml#L155

Which claims:
```
# \lxRDF{keyvals}[content] "Add RDF triple"
```

In fact, the current accepted syntax is with reversed arguments:
```
\lxRDF[content]{keyvals}
```

Would be nice to get the two back in sync, I was scratching my head for a minute here. There also seems to be an undocumented optional argument for ```\lxRDFa``` at: 
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/lxRDFa.sty.ltxml#L134

It ought to be:
```
# \lxRDFa[xpath]{keywordpairs} "RDF attributes"
```

and a note on what the xpath does would be nice too.

All minor and easy to fix documentation bits, actually using the macros works super!

**Comment by dginev** [comment]
I made an issue instead of a pull request, since I was unsure if you want to change the documentation or the code, I am happy either way.

**Comment by brucemiller** [comment]
I wrote the documentation and binding before I wrote the latex side, which reminded me that it's traditional to put the optional args first.  So, the doc was wrong. Thanks!
