### ISSUE TITLE
\mathrm in last argument of \defSpecFun

### ISSUE THREAD

**Issue by HowardCohl** [brucemiller/LaTeXML#587]
We discovered that there is a problem with using \mathrm in the last argument of \defSpecFun if the length of the argument is more than one and there are at least two arguments.

See our test at:

[DRMF Wiki](http://drmf.wmflabs.org/w/index.php?title=User:Admin&oldid=29059)

[LaTeX fails with the following error](https://gist.github.com/HowardCohl/224843ce760bfa39d9e8)

**Comment by brucemiller** [comment]
please supply a self-contained testcase that can be run from the command-line; say a single .tex file

**Comment by HowardCohl** [comment]
[LaTeX file](https://gist.github.com/HowardCohl/832a670433b82bf4edbf)

works with pdflatex but not with latexml.

**Comment by brucemiller** [comment]
no, actually the sample works fine; why don't you post a testfile that you actually tested...

**Comment by brucemiller** [comment]
And by the way; how did you come up with "mathrm" being the problem?

**Comment by physikerwelt** [comment]
If the tex file works for you but not for howard, probably the package ```\usepackage{DLMFdefun}```
point to another version. I can test that on Monday, when I can access the files.

@HowardCohl can you create another macro,to test the influence of mathrm
```
\defSpecFun{MPc}{c}[meaning=test-object]{2}[#2{d}#1] 
```


![screenshot 2015-03-14 22 11 37](https://cloud.githubusercontent.com/assets/2777736/6654407/9e3564ec-ca98-11e4-9c85-77d085cbe185.png)

**Comment by physikerwelt** [comment]
Mh. The [example](http://gw125.iu.xsede.org/test.html) seems to render fine on the server with plain latexml form the commandline.
So I guess one of the various post processor options might cause the trouble
```
'post' => 'format=xhtml&whatsin=math&whatsout=math&pmml&cmml&nodefaultresources&preload=LaTeX.pool&preload=article.cls&preload=amsmath.sty&preload=amsthm.sty&preload=amstext.sty&preload=amssymb.sty&preload=eucal.sty&preload=%5Bdvipsnames%5Dxcolor.sty&preload=url.sty&preload=hyperref.sty&preload=%5Bids%5Dlatexml.sty&preload=DLMFmath.sty&tex=literal:%7B%5Cdisplaystyle%20%5CMPb%40%7Bx%7D%7Bf%28x%29%7D%7D',
'host' => 'http://gw125.iu.xsede.org:8888',
'result' => '{"status":"1 warning; 1 error","status_code":"3","result":null,"log":"ltxpsgi (LaTeXML version 0.8.1; revision 753c8d6)\\nprocessing started Sat Mar 14 17:51:10 2015\\n\\n(Digesting TeX Anonymous String...\\n(Processing content Anonymous String...\\n(Processing content Anonymous String...\\n(Processing content Anonymous String... 0.00 sec) 0.02 sec)\\n(Building..... 0.06 sec)\\n(Rewriting... 0.00 sec)\\n(Math Parsing...1 formulae ...[1]\\nError:expected:p1.1.m1.1.1.4 Cannot find a node with xml:id=\'p1.1.m1.1.1.4\'\\n\\tat Anonymous String; line 0 col 0\\n\\nMath parsing succeeded:\\n ltx:XMath: 1/1\\n ltx:XMWrap: 2/2\\n ltx:XMArg: 3/3\\n 0.07 sec)\\n(Finalizing...\\nWarning:expected:node No node found with id=p1.1.m1.1.1.4 (referred to from ltx:XMRef)\\n\\tat Anonymous String; line 0 col 0\\n\\tIn Core::Document[@0x7f9c51d69418] at Anonymous String; line 0 col 0\\n 0.01 sec)\\nConversion complete: 1 warning; 1 error.\\n\\n(post-processing...\\n(Scan processing...\\n(CrossRef processing...\\n(MathML::Presentation processing...Fatal:post:generic Post-processor crashed! \\nFatal:perl:die Perl died\\n\\tPostprocessing LaTeXML::Post::MathML::Presentation\\n\\tCan\'t call method \\"getAttribute\\" on an undefined value at /usr/local/share/perl/5.18.2/LaTeXML/Post.pm line 1010.\\n\\nStatus:conversion:3 \\n"}',
```
You can run 
```
curl -d 'format=xhtml&whatsin=math&whatsout=math&pmml&cmml&nodefaultresources&preload=LaTeX.pool&preload=article.cls&preload=amsmath.sty&preload=amsthm.sty&preload=amstext.sty&preload=amssymb.sty&preload=eucal.sty&preload=%5Bdvipsnames%5Dxcolor.sty&preload=url.sty&preload=hyperref.sty&preload=%5Bids%5Dlatexml.sty&preload=DLMFmath.sty&tex=literal:%7B%5Cdisplaystyle%20%5CMPb%40%7Bx%7D%7Bf%28x%29%7D%7D'  http://gw125.iu.xsede.org:8888
```
to reproduce what MediaWiki is doing.

**Comment by physikerwelt** [comment]
or a shorter version with the same effect (that perl dies)
```
curl -d 'whatsin=math&pmml&preload=DLMFmath.sty&tex=literal:%5CMPb%40%7Bx%7D%7Bf%28x%29%7D'  http://gw125.iu.xsede.org:8888
```

**Comment by brucemiller** [comment]
The key thing is that ```\usepackage{DLMFmath}``` causes the error (and gives (or tries to) semantic markup), whereas ```\usepackage{DLMFdefun}``` doesn't have an error.

Anyway, it's fixed now.

**Comment by brucemiller** [comment]
And as a reminder: the request for a test case is to allow us to focus on fixing the problem.  Having a test case that actually causes the error keeps us from having to guess what you actually did. So, please supply test cases, but please actually test them using ```latexml``` and/or ```latexmlpost```.
thanks

**Comment by HowardCohl** [comment]
Thanks for the clarification regarding test cases.
We actually did test the test case, but apparently our test wasn't sufficient.
(It was producing fatal errors, but for a different reason I guess.)

@moritz, I uploaded the changes to our LaTeXML server.

See for instance:
http://drmf.wmflabs.org/wiki/Definition:AntiDer
http://drmf.wmflabs.org/wiki/Definition:Int
http://drmf.wmflabs.org/wiki/User:Admin

So the error was in DLMFmath.sty or was it in some Perl source?

Thanks for fixing this!  It's all working now.

--
http://www.nist.gov/itl/math/msg/howard-s-cohl.cfm

________________________________________
