### ISSUE TITLE
footnote inherits textsc style

### ISSUE THREAD

**Issue by swalter62** [brucemiller/LaTeXML#588]
This is a minor issue, but I thought I'd point it out all the same. Inside a flushright environment, when a footnote command follows text marked as smallcaps, the displayed text of the footnote appears in smallcaps. No errors or warnings are thrown. Here's an example:
```
\documentclass{article}
\begin{document}
\begin{flushright}
In a flushright environment, the footnote inherits
  the preceding \textsc{smallcaps style}\footnote{Here's the footnote text.}
\end{flushright}
\end{document}
```
LaTeXML produces the following XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/home/pub/test"?>
<?latexml class="article"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-article.css" type="text/css"/>
  <para xml:id="p1">
    <p align="right">In a flushright environment, the footnote inherits
the preceeding <text font="smallcaps">smallcaps style<note mark="1" role="footnote"><text font="upright">Here’s the footnote text.</text></note></text></p>
  </para>
</document>
```
Can you guess what's going on here, Bruce?

**Comment by brucemiller** [comment]
curious.  It actually isn't affected by the flushright.  But what seems to be the issue is that latex considers small-caps as a "shape" (and latexml correctly resets the shape to upright), but in css, small-caps is a font-variant (which is *not* being reset!).  Have to think about this...

**Comment by swalter62** [comment]
I see now that flushright is indeed a red herring, and that insertion of a period before the footnote command produces the expected output.

**Comment by brucemiller** [comment]
Got the CSS sorted out, now. commited 3de1a4f835c3ff200ceef5cf23d4c39888a2f363 & 163ef9d90d2d1b81c35845ea6d0bc7f9dcf02820.  Thanks for the report

**Comment by swalter62** [comment]
That was quick. This works fine for me -- thanks a million, Bruce!
