### ISSUE TITLE
Infinite loop with tikz/pgfplots and basic trigonometric functions

### ISSUE THREAD

**Issue by fred-wang** [brucemiller/LaTeXML#589]
Follow-up of #498 :-)

Testcase:

      \documentclass{article}
      \usepackage{pgfplots}
      \begin{document}
      \begin{tikzpicture}
        \begin{axis}[axis x line=middle, axis y line=center]
          \addplot[domain=-2*pi:2*pi,smooth](\x,{sin(\x r)});
        \end{axis}
      \end{tikzpicture}
      \end{document}

This ends up with an infinite loop

            warning:expected:<number> Missing number, treated as zero
            	at /home/fred/Bureau/a.tex; line 6 col 55
            	while processing \pgfmath@count
            	next token is \x
            	In Core::Gullet[@0x4288780] at /home/fred/Bureau/a.tex; line 6 col 55

**Comment by dginev** [comment]
More context from this run that may be relevant:
```

Error:latex:\GenericError Package pgfkeys Error: I do not know the key '/pgf/fpu', to which you passed
	at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 6 col 53
	'true', and I am going to ignore it. Perhaps you
	misspelled it
	See the pgfkeys package documentation for explanation.
	In \GenericError {}{}{}{} from LaTeX.pool.ltxml line 4061
	 <= Core::Stomach[@0x4b51930] <= { <= Core::Stomach[@0x4b51930] <= ...

Error:undefined:\pgfmathfloatlessthan The token T_CS[\pgfmathfloatlessthan] is not defined.
	at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 6 col 53
	In Core::Stomach[@0x4b51930] at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 6 col 53
	 <= { <= Core::Stomach[@0x4b51930] <= \lxSVG@hbox BoxSpecification HBoxCont... <= ...

Error:undefined:\pgfmathfloatlessthan@ The token T_CS[\pgfmathfloatlessthan@] is not defined.
	at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 6 col 53
	In Core::Stomach[@0x4b51930] at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 6 col 53
	 <= { <= Core::Stomach[@0x4b51930] <= \lxSVG@hbox BoxSpecification HBoxCont... <= ...

Warning:latex:\GenericWarning Package pgfplots Warning: You have an axis with empty range (in direction y). Replacing it with a default range and clearing all plots.
	at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 7 col 14
	In \GenericWarning {}{} from LaTeX.pool.ltxml line 4062
 [warning \pgfkeyscurrentkey]

Error:undefined:\pgfmathfloatshift@ The token T_CS[\pgfmathfloatshift@] is not defined.
	at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 7 col 14
	In Core::Stomach[@0x4b51930] at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 7 col 14
	 <= { <= Core::Stomach[@0x4b51930] <= \lxSVG@hbox BoxSpecification HBoxCont... <= ...

Error:undefined:\pgfmath@basic@subtract@ The token T_CS[\pgfmath@basic@subtract@] is not defined.
	at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 7 col 14
	In Core::Stomach[@0x4b51930] at /home/dreamweaver/testbed/tikz/wang_loop.tex; line 7 col 14
	 <= { <= Core::Stomach[@0x4b51930] <= \lxSVG@hbox BoxSpecification HBoxCont... <= ...
```
for me the conversion hangs after the last error from this snapshot.

I will schedule this for 0.8.2, with the hopes that either Bruce or I get enough time to find the culprit here. And I would so love to find a way to speedup things, it's painstakingly slow.

**Comment by dginev** [comment]
The smallest example reproducing the loops is:
```tex
  \documentclass{article}
  \usepackage{pgfplots}
  \begin{document}
  \begin{tikzpicture}
    \begin{axis}
      
    \end{axis}
  \end{tikzpicture}
  \end{document}
```

Removing the {axis} environment avoids the loop. So that is a good place to start digging.

**Comment by brucemiller** [comment]
Nice simple sample! I think the core problem was a broken iffileexists sorta test that didn't load some essential code.  I happened to look into this while I was also in the middle of reworking the pgfkeys binding. This example turned out to exercise some interesting key settings!

I think it's working well now, and gives a non-trivial speedup (tho' not an order of magnitude!) Thanks for the report.

**Comment by dginev** [comment]
Nice one! I didn't even know that ```iffileexists`` exists until now :>

**Comment by brucemiller** [comment]
Well, strictly speaking it was ```\pgfplots@iffileexists```, which is a generic form of LaTeX's ```\IfFileExists```, but my early version mangled it... (```\IfFileExists{file}{truestuff}{falsestuff}``` loads file and executes truestuff, if the file exists, else falsestuff. Handy)
