### ISSUE TITLE
deluxetable support

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#590]
Style file at: http://fits.gsfc.nasa.gov/standard30/deluxetable.sty
Example at: http://jessresearch.blogspot.com/2012/07/making-awesome-latex-tables.html

Amazingly, this package is not on CTAN, but it has entered very widespread use among astrophysicists, and I am told would be very warmly received as a LaTeXML-supported package.

I will look into this myself in the short-term, but anyone should feel free to chip in.

**Comment by dginev** [comment]
Btw since you mentioned deluxetable in another issue, I have half of the binding ready now, trying to understand better some of the more fancy bits about the exact table setup it requires.

**Comment by brucemiller** [comment]
Hmm... in addressing #591, I first was checking whether classes on alignment elements are being done consistently.  I stumbled onto a deluxetable environment in aas_support (American Astronomical Society); it looks similar to the separate package, although only partly implemented. Probably we should do it Right, as deluxtable.sty.ltxml and include that in aas_support.

Hmm, Hmm... On further thought, it looks like capturing the row/column distinctions, and seeing that there are several style files that do some header handling (longtable, supertabular), it probably makes sense to handle all these, and #591, at once.  How far along are you with deluxetable?  Don't want to steal the fun, but maybe I should pick it up from here and deal with them all? If you agree, send me what you've got...

**Comment by dginev** [comment]
I agree, especially since I feel a little bit rusty with writing bindings and don't at all mind reading your code to freshen up my assortment of TeX tricks. Will send over the basic state I have in a bit, need to get to that laptop.

**Comment by dginev** [comment]
Sent a file bundle via email. 

A related concern about deluxetable, and also an interesting general discussion, is managing the "impedance mismatch" between HTML and PDF. In our web editing setting for instance, we are very curious if LaTeXML could already tell us "hey, here is your table, but be aware this is too wide for an a4 page!" so that we can already report to the authors that their PDF will have the table overflowing. 

Classically, one has always had to run pdflatex and manually inspect the produced rendering, but if LaTeXML could already guess/foresee that there will be spacing issues, that would be awesome. Probably a separate issue altogether, but it is most relevant for tables, as they don't have any auto-breaking mechanisms.

**Comment by brucemiller** [comment]
Done! by extracting an almost complete implementation from aas_support.sty.ltxml. Thanks for the suggestion!

**Comment by dginev** [comment]
Super cool! Thanks, much appreciated.
