### ISSUE TITLE
Preserve information for broken citations in CrossRef

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#592]
For practical (backwards-compatibility) reasons, I am currently developing a setup where LaTeXML is run on fragments without a bibliography, but with the actual ```\cite{}``` commands left in the source.

I find myself needing the actual citation keys in the final HTML output, so that we can post-process them externally to LaTeXML. The keys are already present in the LaTeXML XML but seem to get stripped out during Post::CrossRef. @brucemiller : would you be receptive to keeping the broken bibrefs into the final HTML, maybe with a special CSS class, so that they can be hidden, or made red like the rest of the errors, or turned into he TeX-like question mark, based on the user's preference? I can do the necessary work once we develop a strategy.

Example source:
```tex
\documentclass{article}
\begin{document}
Request: Preserve content of \cite{missing:citations} in post-processing.
\end{document}
```

LaTeXML XML:
```xml
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <para xml:id="p1">
    <p>Request: Preserve content of <cite>[<bibref bibrefs="missing:citations" separator="," show="Refnum" yyseparator=","/>]</cite> in post-processing.</p>
  </para>
</document>
```

XML after CrossRef post-processing (no stylesheet applied):
```xml
<document xmlns="http://dlmf.nist.gov/LaTeXML" xml:id="Document">
  <resource src="LaTeXML.css" type="text/css"/>
  <para xml:id="p1" fragid="p1">
    <p>Request: Preserve content of <cite>[]</cite> in post-processing.</p>
  </para>
</document>
```

**Comment by brucemiller** [comment]
I stole some code snippets from your pull request, but rewrote it to combine the several elses that would have been needed; should achieve the same effect, and maybe even catch another case that would have leaked through.  I also added ```ltx_missing_label``` to ```\ref```'s that have no defined label.  Thanks for the proposed patch!

**Comment by dginev** [comment]
Wonderful! Thanks for the quick adoption!
