### ISSUE TITLE
Global namespace via --documentid not applied to math and tables

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#595]
In the reverse workflow to --split, LaTeXML is used to convert several adjacent fragments (usually sections or paragraphs), the HTML results of which are then put together on the same page.

At the moment, attempting this inevitably results in ID collisions. This is the case even with ids disabled via `--preload=[noids]latexml.sty`, as several elements get IDs unconditionally (those with labels, paras, etc.). And I think having IDs is a great thing in the first place, but without the conflicts (pretty much each fragment has a "p1" id for instance).

At the moment I can add the namespaces via follow-up XPath on the result, so this is a minor problem, but it would be great to have a LaTeXML-native solution in the long run, especially since ID rewriting in a new DOM is runtime-intentsive. 

The simplest idea would be to do `--preload=[gids]latexml.sty`, which would append the document name, or a randomly generated number (akin to ePub) in the case of literal strings, to every ID in the document.

**Comment by brucemiller** [comment]
There's a lot of contrived stuff in the post-processing when things are stuffed into and pulled out of the database (generally by Scan and CrossRef), to try to reassign ID's.  LaTeXML::Post::Document has a method cloneNode that tries to arrange that.  I don't know if that's available to you in the place where you're assembling pieces?

**Comment by dginev** [comment]
I am assembling pieces out and after LaTeXML, and in a different programming language. So I can only specify an option / load a special package as a configuration tactic. But as I said, I have a stopgap solution here, not urgent.

**Comment by brucemiller** [comment]
There's at least part of a "native" solution there. If you assign DOCUMENTID, that will be used as the base ID from which all node ids are derived. So, if you're processing multiple documents that you want to combine pieces from, establishing a unique DOCUMENTID for each, and assigning before processing each, would work.  Not sure if that's solving the exact problem?

**Comment by dginev** [comment]
That is exactly what I need yes. Is there a "best practice" of how to specify the DOCUMENTID on input? I can pretty much incorporate it anywhere, from command-line options to preamble macros.

**Comment by dginev** [comment]
Ha, there is a ```--documentid``` option! Who knew :> Well, if it is there, I guess I can use it. Though I am itching to suggest removing it, just because it seems too rare of a use case. Maybe redo it as ```--preload=[documentid=foo]latexml.sty```? But let's leave it as it is for now.

One thing I noticed was that the documentid prefix was not used everywhere. I am seeing it on logical elements (ltx_para, ltx_section etc.) but not on all inline elements. It is missing for tables and math, but is present for ```p```s.

As my original issue is effectively solved, I will rename the issue to reflect the latest state.

**Comment by brucemiller** [comment]
can you show me how/where ids' are missing the documentid? I'm seeing them.

**Comment by brucemiller** [comment]
Aside: eventually I'll have to sort out handling package options that use keyval, instead of simply csv. latexml.sty would benefit from keyval options, as you suggest (whether preloaded or not).

**Comment by dginev** [comment]
Interesting. Classic invocations of LaTeXML work well:
```
 latexml --preload=article.cls --preload=[ids]latexml.sty --documentid='hello' 'literal:\begin{document}Testing $a+b=c$\end{document}'
```

It also works well with ```latexmlc```. However, if I turn on post-processing, the ID prefixes disappear. Try:
```
latexmlc --format=html5 --preload=article.cls --preload=[ids]latexml.sty --documentid='hello' 'literal:\begin{document}Testing $a+b=c$\end{document}'
```

The only addition is the post-processing to HTML5 (which changes a lot underneath of course). Interestingly, running latexmlpost on the core processed XML also loses the ID prefixes, so I am assuming this is some generic issue with post-processing?

**Comment by dginev** [comment]
Did a little digging, the HTML5 stylesheet is changing the IDs. Will check why next.

**Comment by dginev** [comment]
The fragids don't have the prefix, and they get copied instead of the actual xml:id. We need the documentid to get propagated into the "fragid" attributes.

**Comment by brucemiller** [comment]
Nope, fragids don't have the prefix--- that's really the point: they're id's relative to the document.  If you see any fragids that *do* have the prefix, *that's* a bug!

I guess it didn't quite sink in that you're combining pieces of HTML, rather than XML.  It ought to work relatively straightforwardly to combine fragments of LaTeXML and then XSLT to html. Otherwise, we'd need a new option to disable fragid shortening (for a rather individual use-case).

Alternatively, you'd want to write a function to uniquify ids in imported html fragments (xpath all id's, rewrite them while recording the mapping, then xpath & update all hrefs that use those ids)

**Comment by dginev** [comment]
How is losing the global ID namespace in the final HTML output not a bug? That namespace was explicitly provided on input, there is clear intent for it to be preserved.

**Comment by brucemiller** [comment]
Clearly intended to be preserved in the xml; which it is.

**Comment by dginev** [comment]
Right, but why lose it in the HTML? I am still not understanding how that is a "feature".

**Comment by brucemiller** [comment]
aesthetics, basically; and useful correspondences when ID's are related to visible reference numbers.
To avoid immensely long ids when you have a complex set of large documents that get split into smaller pages.

**Comment by brucemiller** [comment]
Put another way: we're talking about HTML now, not XML. An html id is an identifier *within* a page. In contrast, a URL (possibly with a fragment identifier) is a global identifier.  So shortening the id removes the redundancy.  Yeah, it's still aesthetics.

**Comment by dginev** [comment]
So, correct me if I am wrong, but the only meaningful difference between XML and HTML output, as far as LaTeXML's ID generation is concerned, is whether we have a capacity to split the document into multiple pieces. Which is the main reason why we care about fragid being as small as possible. 

Maybe all that is needed here is an extension for the special case of latexmlc, which has the ```--documentid``` value also in post-processing and can pass it on as a global ID namespace, e.g. for the XSLT stylesheets. One could also add it to latexmlpost, of course.

It becomes a little silly, as LaTeXML will first strip and then re-add the ID, but the behaviour will be closer to expected. If latexmlc is converting to HTML and the ```--documentid``` value is functionally discarded (i.e. the final IDs don't have it in them), then that is a clear usability bug for that option.

**Comment by dginev** [comment]
The key remark I have is that we don't "need a new option", we just want to evolve ```--documentid``` to usefully be observed in post-processing.

That should sound less controversial and more useful, right?

**Comment by dginev** [comment]
In the case of using both ```--documentid``` and ```--split```, the ID namespace will have to be copied over to every single split piece, i.e. it is acting as a global namespace to the entire document. Clearly it's main use will be together with ```--whatsout=fragment``` in the HTML use case, but I think we can have an intuitive behavior here.

**Comment by brucemiller** [comment]
In terms of intuitive & expected, I don't really see how "documentid" is a meaningful concept for postprocessing. At least it isn't intuitive to me what it should mean. After all, in postprocessing, you're given an XML document which already has ids.  So documentid would suggest that you want to *change* the id, not *preserve* it.

If the collapsing of ids in the html is something worth controlling, it seems that the control should be something a bit more explicit, rather than mysteriously implied :>

**Comment by dginev** [comment]
Well, the option is described as:
```
 --documentid=id    assign an id to the document root.
```

So when I run:
```
latexmlc --format=html5 --documentid='helllo' ...
```

Why is the ID not on my document root? That's already expected.

**Comment by brucemiller** [comment]
Not my fault! That's the description copied from latexml, where it means what I say it means.  When it's copied, unchanged, to latexmlc, I agree that it has different implications.  Obviously not the implications that I had in mind.

And supposing you did avoid a new option to preserve the id all the way through by piggybacking --documentid.  Then *I* would need a new option to specify --documentid for the xml, but *not* preserving it through to the html!

**Comment by brucemiller** [comment]
(the latter comment in the context of eventually wanting a single latexml command)

**Comment by brucemiller** [comment]
If anything, I think that fragment output is the only place it makes sense to piggyback; it's the only context where it makes sense to imagine synthesizing a full html out of isolated pieces, and you would want those pieces not to clash.

**Comment by dginev** [comment]
Agreed, it's my fault! But I am using that as leverage :>

Well, it's good we caught this behaviour question early on, so that we can discuss it early. I didn't even know ```--documentid``` existed two days ago!

Also, you can't prove a negative - maybe there are no other use cases, maybe there aren't. The fragment one is one case that we know is out there, and if I we are keeping this option in latexmlc it ought to do what it says it does.

Could you describe your workflow where you want an ID namespace in the XML, you don't want it in the HTML, and you are running all of that under a single call to latexmlc?

**Comment by brucemiller** [comment]
I assume converting to mathml is a fragment case? that should also cause problems if you put multiple maths on a page if they have ids. If you take a full html page apart & reassemble, you deserve what you get.  So, you're arguing for a separate option instead of leveraging fragment? :>

Obviously I don't use mega-latexml in that workflow yet, and it wouldn't be a single call, since it's processing multiple docs w/ separate passes for scanning & crossreffing. But I'll leave it to you to prove that there can't exist a single-call workflow where you'd want the xml w/ids and html w/o.

**Comment by dginev** [comment]
Well played.

The math conversion are a ```--whatsout=math``` case, which is even tinier than fragment and, as you indicate, would immediately bring you clashing ids, if you have any. All math will come back with an ```m1.``` id prefix, and boom goes uniqueness.

So ```--documentid``` can conceivably be used there as well.

In any case, I certainly am not arguing in favour of a new option, we have too many of those. I'd rather drop ```--documentid``` entirely, so that we don't descriminate between core and post processing and we leave LaTeXML users do their own ID management externally.

**Comment by brucemiller** [comment]
i dunno. you need unique ids for math & probably need to specify it, and I can see how --documentid could be reinterpreted to mean that. OTOH, I want the current behaviour as well, an by default.... Have to ponder.

**Comment by dginev** [comment]
I have a pragmatic suggestion. At the moment, this option is only properly utilized in your DLMF workflow, and I am just starting to think of using it. We are the only 2 users, as far as we know.

However, our workflows are dramatically different, and above we already pinpointed a sharp dividing line - the value of the ```--whatsout``` option. In the classic, document output (which is the only thing ```--split``` really works with!) I am 100% happy and satisfied to keep the current behaviour as-is.

On the other hand, for the fancy-web-app fragment outputs (```--whatsout=fragment``` and ```--whatsout=math```) we can realistically assume the ```--documentid``` is important to save the fragment from conflicts with other LaTeXML-generated fragments. So we can switch to my needs for those cases, and those cases only.

Seems diplomatic enough of an approach?

**Comment by brucemiller** [comment]
sounds too diplomatic...

**Comment by dginev** [comment]
The more I think about that interpretation, the more I like it!

**Comment by dginev** [comment]
It has a very nice feeling of "Do What I Mean" to it.

**Comment by dginev** [comment]
Fun fact: setting ```--documentid``` causes the daemon to reload all preloaded packages on every conversion job. Took me forever to debug and I have now completely backed away from using that option, as I need a speedy daemonized conversion. We should think of refactoring in a way that the documentid is passed in as an option to the ```Core::convert``` sub, instead of setting it as a field in the (reusable) LaTeXML object.

**Comment by brucemiller** [comment]
very few options other than preload seem like they ought to affect the choice of a daemon to reuse.

**Comment by dginev** [comment]
Which probably means they shouldn't be fields in the LaTeXML object, but rather arguments for initialization. The way things are now, I need to reinitialize when I make a new LaTeXML object, and I end up making new LaTeXML objects whenever a field is different. Maybe I can improve that code to just set the field value, rather than spawning a new object.

**Comment by brucemiller** [comment]
Yeah, somewhere in my New Scheme of things would be the idea of a large (harumph) class of options that would essentially just set a State variable.  Many of the kinds of things that are wanting to become latexml.sty options.  Of course, it may be preferable to *not* have separate command line options for them, but something like ```--set=variable:value```.  Of course, they'd still need to be documented somewhere.

**Comment by dginev** [comment]
Good discussion, but for now I have resolved things on my end without using `documentid` at all - externally to latexml, so closing here in favor of more pressing issues.
