### ISSUE TITLE
defining \R with \newcommand fails

### ISSUE THREAD

**Issue by petrelharp** [brucemiller/LaTeXML#597]
I (and many others, I think) am in the habit of defining `\R` to give the math blackboard bold symbol, as in the following document:
```
\documentclass{article} \usepackage{amssymb}
\newcommand{\R}{\mathbb{R}}
\begin{document}
This is $\R$, not imaginary.
\end{document}
```

But, this gives the following error:
```
Info:ignore:\R Ignoring redefinition (\newcommand) of 'T_CS[\R]'
	at /home/peter/debug/latexml/test.tex; line 4 col 27

Error:undefined:\R The token T_CS[\R] is not defined.
	at /home/peter/debug/latexml/test.tex; line 9 col 11
	In Core::Stomach[@0x39491f0] at /home/peter/debug/latexml/test.tex; line 9 col 11
	 <= \@@BEGININLINEMATH <= Core::Stomach[@0x39491f0] <= $ <= ...
```
and fails to put in the right thing for the `$\R$`.

Sure enough, if the `\newcommand` is changed to `\renewcommand`, then it works with LaTeXML; but, then, not with `pdflatex`.  (This works for both, though:
```
\def\R{\mathbb{R}}
```

So, it seems like `\R` is defined already... but, if I comment out the definition of `\R` entirely, it tells me:
```
Error:undefined:\R The token T_CS[\R] is not defined.
```

**Comment by dginev** [comment]
Very curious (and embarrassing) error!

Turns out it stems from \endR being defined in eTeX.pool.ltxml, as follows:
```
DefMacroI('\endR',   undef, '');
```

Do we follow the exact algorithm of ```\newcommand``` for checking if a macro is defined? Maybe we ought to. And if we are, we need to figure out what to do with that ```\endR``` in eTeX.

**Comment by dginev** [comment]
Quickest fix is doing the following refactoring in eTeX.pool :
```perl
Let('\beginL', '\relax');
Let('\beginR', '\relax');
Let('\endL',   '\relax');
Let('\endR',   '\relax');
```

**Comment by dginev** [comment]
The larger question is whether this means we should have a stricter style for defining empty/unimplemented/no-op macros, where we always tie them to ```\relax```, just so that we are sure that ```isDefinable``` operates correctly.

**Comment by brucemiller** [comment]
So, I actually quite misunderstood the test dealing with "end" in ```\@ifdefinable```.  Should be good now; thanks for the report.

**Comment by petrelharp** [comment]
right. on. thanks!
