### ISSUE TITLE
make postprocessor more verbose

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#599]
I am experimenting with the postprocessor a bit, and it would be very helpful, if it could be more chatty. Currently, it gives log like 
```
(tost.xml post-processing...
(Scan tost.xml processing...
(CrossRef tost.xml processing...
(XMath tost.xml processing...
(XSLT tost.xml processing...
(Writer tost.xml processing... 0.01 sec)
Post-processing complete: No obvious problems
processing finished Mon Apr 20 10:40:47 2015
Status:conversion:0 
```
It would be great if the XSLT processing would show what stylesheets are loaded, best with full path. 
And while you are at it, I have a curious preference for balanced parentheses.

**Comment by brucemiller** [comment]
Easy enough, and helpful. Done!

**Comment by dginev** [comment]
Now also merged into the KWARC fork.
