### ISSUE TITLE
Secure IO in LaTeXML

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#606]
This issue is a followup from the discussion on my failure to offer a temporary solution at https://github.com/dginev/LaTeXML/commit/0a6a1ec2d0102752c0814cd65a4771ef40bf7f53

Here is a small specification of what I'm trying to achieve:
- Recognize "untrusted" (user-specified) from "trusted" (system) sources
- Disallow any IO operations from any TeX input coming from an "untrusted" source
- Only do so on demand, as we want to be "paranoid" for third-party TeX but "friendly" for classic LaTeXML use.

So far, we have scenarios where the untrusted sources are passed in as literal strings, or alternatively sandboxed ZIP archives, for which we know a sandbox directory.

A solution is then to connect:
- The information whether the input is trusted with the tokens of that input
- Consult that information in IO-enabling components, most notably FileMouth

There is a related refactoring need for the "REMOTE_REQUEST" global state value, which was a first "temporary" solution in this direction from a few years ago.

**Comment by dginev** [comment]
Oh, you opened a duplicate #607 right after I opened #606. You can choose the one you like more and close the other, up to you.

**Comment by brucemiller** [comment]
A reminder to implement some sort of restrictions on files that can be read (let alone written!) for server applications. This should basically only allow files to be read that sit underneath directories given in a whitelist. The whitelist would perhaps consist of @INC, whatever kpathsearch allows, and anything added by the ---paths option? .see some additional discussion in #605. I guess when processing a zip file in the server, the whitelist would include the path where the zip was unzipped. Command line invocation (assuming it even enforced the whitelist), would presumably explicitly include ".", but a server would not.

**Comment by dginev** [comment]
Here is how my temporary workaround "evolved":
https://github.com/dginev/LaTeXML-Plugin-secureio

It was a bit annoying to setup, but it's there. If anything comes to mind that can be added to that "blacklist" for input macros, let me know. It's off-topic to this issue, but relevant if someone needs a temporary patch.

**Comment by dginev** [comment]
Also, @brucemiller , whenever you have the feeling I am rushing a pull request without a strong enough reason for LaTeXML-core, please advise me to make a plugin, it's really the right solution for these cases.

**Comment by brucemiller** [comment]
I'm thinking the above whitelist is probably safe & sane. Provided pathnames are properly canonicallized, it should be easy to test: just match that the path starts with one of the whitelist paths?
There was an issue (or maybe just in email) about canonicalization not dealing with symlinks correctly; can't find it now...

**Comment by dginev** [comment]
I still think this should eventually land in master, but am happy to stay with a plugin for now. Closing here.

**Comment by brucemiller** [comment]
It seems ironic to use `\usepackage{secureio}` to disable other `\input`, but short of a better config system, I guess it works. It does restrict the user to a single .tex source file.  I think a better solution in the long term is to whitelist the directories that can be read (and the searchpaths), but that's considerably more work to do reliably & efficiently.
