### ISSUE TITLE
Support for nameref.sty (needed by hyperref.sty)

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#611]
As Authorea has now entered beta testing of LaTeXML, we have started receiving helpful user reports of various issues and missing features. I will be opening LaTeXML issues for those, and will introduce a new "Authorea" label for them, so that I can keep track myself (and give them priority).

This one is quite straightforward: hyperref supports a range of extended referencing macros, ```\nameref``` being one of the most notable ones. Support for those is missing in LaTeXML (I think we only have the "core" of hyperref implemented?) so we should think of adding the missing bits.

Assigning this issue to myself for now, but please feel free to steal it from me if it seems fun.

**Comment by brucemiller** [comment]
That's actually in nameref.sty but I can't tell if that's always loaded or only with certain options.

**Comment by dginev** [comment]
This works out of the box in pdflatex:
```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}

\section{First}\label{sec:first}
  \nameref{sec:second}

\section{Second}\label{sec:second}
  \nameref{sec:third}

\section{Third}\label{sec:third}
  \nameref{sec:first}

\end{document}
```

Hyperref auto-loads nameref.sty, and a few others, as can be seen from the log:
```
/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2013/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2013/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(./test.aux) (/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(./test.out) (./test.out) [1{/usr/local/texlive/2013/texmf-var/fonts/map/pdftex
/updmap/pdftex.map}] (./test.aux) )</usr/local/texlive/2013/texmf-dist/fonts/ty
pe1/public/amsfonts/cm/cmbx12.pfb></usr/local/texlive/2013/texmf-dist/fonts/typ
e1/public/amsfonts/cm/cmr10.pfb>
```

**Comment by brucemiller** [comment]
well, yeah: that was my point: we need bindings of nameref, etc, so that those can be loaded by hyperref.

**Comment by dginev** [comment]
Fair enough.

**Comment by dginev** [comment]
Documentation: http://www.tex.ac.uk/tex-archive/macros/latex/contrib/hyperref/nameref.pdf

Taking a stab at it now.

**Comment by brucemiller** [comment]
Not having looked deeply, you might want to be leveraging the stuff hidden away in Post::CrossRef.  The "show" attribute is a mysteriously undocumented encoding of how a reference should be filled-in.  I think there's ways to have it say, eg. "Section 1.1.1" instead of "1.1.1" and so on...

**Comment by dginev** [comment]
Works like a charm! I was already snooping there since ```\autoref``` gave me hints and I had just recently been poking around CrossRef (you remember the "weird" PRs).

The only interesting bit before I send you a basic PR (with a test!) is why the "title" field in CrossRef includes the number of the table of contents. For example it gives me "1 Introduction" and "2 Motivation", where I was expecting just "Introduction" and "Motivation".

I don't particularly care about that difference, but the pdflatex result doesn't have the numbers, so I am not 100% compatible with the spec at the moment. Maybe I introduce a "rawtitle" field in CrossRef, specially for my purpose ?

**Comment by dginev** [comment]
Btw autoref seems to be broken too, I applied a fix, but the "type refnum" specification for the show attribute of ltx:ref seems to only produce a number in my tests. Will check if frefnum is set properly...

**Comment by dginev** [comment]
Right, so here is the actual ObjectDB::Entry for the citation entry I am looking at:
```
$VAR1 = bless( {
                 'fragid' => 'S3',
                 'pageid' => 'Document',
                 'key' => 'ID:S3',
                 'children' => [
                                 'S3.SS1',
                                 'S3.SS2'
                               ],
                 'title' => 'XML::<title xmlns="http://dlmf.nist.gov/LaTeXML"><tag close=" ">3</tag>Conclusion</title>',
                 'location' => 'nameref_test.html',
                 'id' => 'S3',
                 'parent' => 'Document',
                 'type' => 'ltx:section',
                 'refnum' => '3',
                 'labels' => [
                               'LABEL:sec:conclusion'
                             ],
                 'primary' => 1
               }, 'LaTeXML::Util::ObjectDB::Entry' );
```

Note that the title field also includes the numbered tag. Which is great, it's useful information. But it's also redundant with the "refnum" and would require me to have a new field for the "show" attribute, e.g. "rawtitle" or "plaintitle", where I can specify that I don't want the tag copied in the filled in HTML reference.

What is your recommendation here? I would like to solve this quickly, since nameref was super simple and is essentially ready for merge once this is settled.

**Comment by dginev** [comment]
Also, the reason that nameref was simple is that all the infrastructure was already in place with hyperref and CrossRef properly implemented. Really nice setup, made the binding work very easy. Thanks a bunch!!

**Comment by brucemiller** [comment]
Thanks for the complement! But conversely, the problem you're having is that this cool "show" feature was & is kinda adhoc, and always treated with expediency in mind, and less good planning.

I think your first intuition, that "title" should just be title is probably more correct than latter.  I'd have to dig into the code, but I suspect that just saying title was an attempt at brevity, or an attempt to deal with corner cases where you've got a refnum but no title, or the other way around.

Maybe rather than add another layer of adhocness (no offence), it might be best to just do it moderately close for now (but with comments to the effect of what it really should do). Then followup with a grep of all usages of show and recode them into something a bit more predicable.

**Comment by dginev** [comment]
Ok, I think that is a good take on affairs, since LaTeX is also not including the tag numbers when you ask it for title. I will do a bit of hunting for existing cases where the title is leveraged.

I'm also a little confused by the use of "typerefnum" without a space. Let me see if I can adequately clean this up, then I will send a PR.

One should probably start with this line in CrossRef:
```perl
  $show =~ s/typerefnum\s*title/title/;    # Same thing NOW!!!
```

**Comment by dginev** [comment]
Huh, actually grepping for "show=" doesn't find any instance of "title" except the one I just added via nameref. Was this never used, or am I going blind?

**Comment by dginev** [comment]
So, jotting down notes as I go along:
 * The ObjectDB entry is the actual <title> element corresponding to the labeled structure. I think that is good behaviour that should stay as-is.
 * The CrossRef module has an expectation for the title to be an XML element, which currently gets cloned into an array of ```@stuff``` to show for each citation entry.
 * It is common to observe comments of the shape ``` # !!!``` around title-handling bits, which makes me a bit uneasy with modifying them. Since I don't necessarily realize what I should be ```!!!``` about :> 
 * In CrossRef, each show component calls ```prepRefText``` to prepare its reference text. In turn that sub calls ```fillInTitle``` which seems to have the purpose of recursing into nested refs inside titles. That's pretty cool.

All that being said, my current feeling is that the best place to remove the "tag" from the (potentially complex XML tree) title is whenever we take the title element out of its ObjectDB::Entry carrier:
```
      my $title    = $entry->getValue('title');
```
However, that method is called in 5 different places in CrossRef.pm, so it's a bit hard to fix it in a simple manner. On the other hand, there are only 2 places where it is called in a "show" attribute context:
```
elsif ($show =~ s/^title//i) {
```

I can add an unbinding of the first ```ltx:tag``` child in the body of that conditional. But I am unsure if you would still consider this ad-hoc. It seems like the "right" localized behaviour right now, but I do admit that I don't properly understand the other 3 uses of the title field from the ObjectDB entry.

**Comment by dginev** [comment]
There is also "Post::Scan::cleanNode", where we could check if we are looking at a "title" node and pluck out the tag before we store it in the DB. That would be a change in a single routine that would propagate to any use of "title" in CrossRef and beyond.

I think I like this idea most for now.

**Comment by brucemiller** [comment]
Actually, there's a ```$doc->trimChildNodes($node)``` that does what I think you're looking for.

**Comment by dginev** [comment]
Perfect, that's the one. Polishing a few bits and will file a PR in a bit.

**Comment by dginev** [comment]
PR is here: #621

**Comment by brucemiller** [comment]
Looks good. I think I should do some comparisons, cause "title" seems to be used in a sneaky way: it ends up as a fallback if the requested pattern can't be filled. There also seem to be "toctitle" and "fulltitle" patterns recognized, if not used.

Wonder if you might be willing to add a few more macros, while you're in the groove.  texscan tells me that ```\Nameref, \Ref, \vnameref``` (and a couple other probably not relevant) are also defined.

**Comment by dginev** [comment]
Will do

**Comment by dginev** [comment]
Almost done here, but ```\Nameref``` is using ```\pageref``` to say stuff like ```on page 3```. Since LaTeXML's ```\pageref``` returns the label of the current block instead (from what I can tell), wondering if that won't get confusing.

**Comment by brucemiller** [comment]
On 06/11/2015 06:09 PM, Deyan Ginev wrote:
> Almost done here, but |\Nameref| is using |\pageref| to say stuff like
> |on page 3|. Since LaTeXML's |\pageref| returns the label of the current
> block instead (from what I can tell), wondering if that won't get
> confusing.

Returns the label?  ```\pageref``` is defined to be identical to ```\ref```,
so there wont be any reference to "page" or the label, unless it isn't 
defined,
but it will be a link to the thing that was labeled (typically using the 
reference number).  What would you want
it to do? Maybe the reference number of the containing html page (after 
split)?

**Comment by dginev** [comment]
Maybe? But what if we don't split? I was thinking of using ```\autoref``` as in ``` on \autoref{#1}``` which would be a sensible HTML-equivalent of "page X"

**Comment by brucemiller** [comment]
On 06/11/2015 06:22 PM, Deyan Ginev wrote:
> Maybe? But what if we don't split?

Then you get the top-level page.

>  I was thinking of using |\autoref| as
> in |on \autoref{#1}| which would be a sensible HTML-equivalent of "page X"

sure, if you think some other show="..." is more appropriate, go for it.

**Comment by dginev** [comment]
Except that I got stuck with a ```show="type refnum"``` only showing me the refnum. Pretty sure it's a CrossRef bug, fishing now.

**Comment by dginev** [comment]
This guy keeps erasing my ```type```. Kind of annoying:
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Post/CrossRef.pm#L331

Any recommendation of how you'd like me to circumvent that?

**Comment by brucemiller** [comment]
On 06/11/2015 06:37 PM, Deyan Ginev wrote:
> This guy keeps erasing my |type|. Kind of annoying:
> https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Post/CrossRef.pm#L331
>
> Any recommendation of how you'd like me to circumvent that?

Probably by removing it.

Maybe that's a leftover from some defaults?

**Comment by dginev** [comment]
Well, the author who put it in there left a comment:
```
 # Since author may have put explicit \S\ref... in!
```

If that makes no sense any longer, it's probably safe to get rid of it.

**Comment by brucemiller** [comment]
On 06/11/2015 06:43 PM, Deyan Ginev wrote:
> Well, the author who put it in there left a comment:
>
> |  # Since author may have put explicit \S\ref... in!
> |
>
> If that makes no sense any longer, it's probably safe to get rid of it.

That's what's trickier to tell. The default show (ref_show) says either
typerefnum or title.  So, maybe it should be just refnum instead of 
typerefnum?
Since you wanted to be able to get title without refnum, we need to sort 
through
all these uses to see where they're used explicitly, which ones default, 
whether
the default is sane, etc.

**Comment by dginev** [comment]
So, removing that bit of code got the right show, but the clause that deals with "type refnum" just tries to copy the "frefnum" attribute, falling back to "refnum". In the example I have, there is no frefnum set on the entry, which looks like:
```
$VAR1 = bless( {
                 'id' => 'S3.SS2',
                 'primary' => 1,
                 'type' => 'ltx:subsection',
                 'refnum' => '3.2',
                 'pageid' => 'Document',
                 'title' => 'XML::<title xmlns="http://dlmf.nist.gov/LaTeXML"><tag close=" ">3.2</tag>autoref</title>',
                 'location' => 'test.html',
                 'parent' => 'S3',
                 'children' => [
                                 'S3.SS2.p1',
                                 'S3.SS2.p2',
                                 'S3.SS2.p3'
                               ],
                 'fragid' => 'S3.SS2',
                 'labels' => [
                               'LABEL:subsec:autoref'
                             ],
                 'key' => 'ID:S3.SS2'
               }, 'LaTeXML::Util::ObjectDB::Entry' );
```

Wondering how come the ```frefnum``` wasn't set.

**Comment by dginev** [comment]
Actually, none of the entries have a ```frefnum``` set.

**Comment by dginev** [comment]
Apparently there is no ```\fnum@type``` equivalent for sections, subsections, etc. which is why this fails. I have to run now, but this is definitely close to figuring out why section-level headings don't have frefnums.

**Comment by brucemiller** [comment]
On 06/11/2015 07:01 PM, Deyan Ginev wrote:
> Apparently there is no |\fnum@type| equivalent for sections,
> subsections, etc. which is why this fails. I have to run now, but this
> is definitely close to figuring out why section-level headings don't
> have frefnums.

Well, frefnum is supposed to mean "formatted refnum", and is quite
possibly obsolete.  I have a long-standing wish to get rid of a bunch
of those refnum attributes and use <ltx:tag> exclusively.

Of course, with your request for "title" meaning "title", you've opened
a can of worms; probably one that needed opening, but still. I think the
path we're on is that all show values should be more explicit, and less
"do what I mean" shorthands.  But, as said, that means digging around for
the places where they are used *and* where they are implied!

**Comment by dginev** [comment]
Sounds like we need a slew of new tests that deal entirely with 1) ref-related and 2) CrossRef post-processing sanity.

Since I can not really guess on my own where the implications will be, as we discussed a bit earlier in this thread, there are some custom considerations already in the code that are a bit puzzling to understand. 

If you can write down TeX examples that come to mind, we can collect them here (I'll add my own) and take it from there. How does that sound?

**Comment by brucemiller** [comment]
I'm bumping into some troubles, and maybe you were right initially in suggesting that "rawtitle" could be the title w/o number, rather than messing with title. In the current arrangement, ltx:title ends up containing the ltx:tag containing possibly the type, and refnum; ltx:toctitle is similar but ends up containing shorter forms of type & refnum.  That stuff can be filled in by macros in certain styles.  And in both cases it's the "natural" form of the title or the title as it should appear in the TOC.  It turns out to be rather awkward to recover that same form for a TOC by using a pattern like "type refnum toctitle"; you'd need "toctype tocrefnum toctitle", assuming you could find what "toctype" should actually be.  So, maybe we should have left title and toctitle alone and leave the tag inside, as it is expected.

OTOH, your request for the title w/o the number is also reasonable. So, I'm thinking "rawtitle" was cleaner (and maybe "rawtoctitle"? Or should rawtitle be the toctitle w/o number, if available?).  Maybe backtrack abit & refactor?

**Comment by dginev** [comment]
I certainly agree with having each individual component as its own field, we can always build up the compounds.

What is "rawtoctitle"? I am aware of the heading text, which I was thinking of as "rawtitle", the type of heading in "type" and the number in the document, which is in "refnum". That's all I understand so far.

**Comment by brucemiller** [comment]
Maybe misunderstood: It isn't actually that easy to re-construct the table of contents form from the components, since the way the number was formatted, and possibly a type prepended, was done by macros, and is different in the regular title and the "toctitle"  If you write "refnum toctitle", you don't necessarily get what latex would have put in the TOC!  In LaTeX all this junk gets generated by a variety of macros, and actually can be language specific too, so for "type" you may get "Chapter", "Chap.", "Ch." or "Kapital", or "Kap", or...?

By "rawtoctitle" I mean the ltx:toctitle with the ltx:tag removed. toctitle, in case you forgot, is the alternative short-form of the title, given as optional argument to ```\section```, eg.  It's a shorter form typically used in a table of contents. If it wasn't explicitly supplied, it defaults to the regular title (but potentially also with a shorter form of the type & refnum!)  It's *probably* the form you'd most likely want to use in links, but presumably the coder ought to be able to choose which form, so that "title" and "toctitle" should both be recognized.  And if raw forms, w/o the number are desired, then you'd likely want "rawtitle" and "rawtoctitle".

**Comment by dginev** [comment]
I get it now! Yes, we clearly want both rawtitle and rawtoctitle then. Thanks a lot for the tutorial.

**Comment by brucemiller** [comment]
Just pushed a commit that fixed up title, etc to be more predictable (I hope), but also added rawtitle and rawtoctitle; so you'll need to update your nameref binding.

**Comment by dginev** [comment]
Thanks! How about adding some tests for the cases you just covered? I will build more tests for the nameref-related ones.

**Comment by dginev** [comment]
(I say this since I fear regressions)

**Comment by brucemiller** [comment]
Good point. I definitely want that. But since "unit" tests are slowish, I wanted to add a single ref test that would probably exercise regular latex, hyperref, nameref, possibly even latexml variations on this theme.  And, since the effect only shows up in postprocessing, it'd want to be a daemon test, I suppose.  (Which is just an additional hurdle for me to set one up).  At any rate, I was kinda waiting for a nameref binding :>

**Comment by dginev** [comment]
Suddenly I find myself holding a hot potato. What a curious burning sensation :> I'll get to it soon.

**Comment by fred-wang** [comment]
I recently fall on this issue (IIRC, hyperref used to not generate any error for missing nameref)

**Comment by dginev** [comment]
Can we close here for now?

**Comment by brucemiller** [comment]
seems like... Thanks!!
