### ISSUE TITLE
Document all allowed options in LaTeXML::Common::Config

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#612]
To my shock, several options are still undocumented, such as ```--dbfile``` and ```--graphicimages``` in the ```Config.pm``` POD. 

I think the reason is that I removed the documentation for any options I had not yet added support for in the joined latexmlc executable. But as I improved on the added support, I forgot to re-add the documentation.

So I should get around to cleaning up the docs soon.

**Comment by brucemiller** [comment]
Undocumented options!?!?! Tell me it isn't so!!

Of course you know that that's the only way some people can sneak new options in---- by not documenting them! :>

**Comment by dginev** [comment]
Hahaha :> Well, they are "classic" options from latexml and latexmlpost, just not "yet" documented in latexmlc / Config.pm. I think I documented my newfangled options early (whatsin, whatsout, etc) since I was using them a lot.

**Comment by brucemiller** [comment]
Hmmm...an 0.8.2 issue...and not even assigned to me :>

**Comment by brucemiller** [comment]
On 06/06/2016 04:24 PM, Deyan Ginev wrote:
> Assigned #612 <https://github.com/brucemiller/LaTeXML/issues/612> to
> @brucemiller <https://github.com/brucemiller>.

??? github even *allows* that????

**Comment by dginev** [comment]
This is new!!! I actually discovered it just now by accident! More reasons to party :tada: :tada: 

It will be super helpful in the future, I'm sure

**Comment by dginev** [comment]
Multiple assignees are a really cool feature.

**Comment by brucemiller** [comment]
On 06/06/2016 04:26 PM, Deyan Ginev wrote:
> Multiple assignees are a really cool feature.

not if you were hoping somebody else'd do it!

**Comment by dginev** [comment]
Oh, this issue is actually truly mine ... Oops :> I'll take care of it tonight!
