### ISSUE TITLE
Bib-file not included

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#617]
I wonder while the bib file is not found by the following command

>latexmlpost --format=html5 --scan --bibliography=f:\EigeneDateien\BuchprojektSpringer\XMLtestordner\literatur/EndokrinologieKundeNourl.bib --dest=engverxml.html engverxml.xml

**Comment by dginev** [comment]
The latexmlpost --bibliography option expects an ```.xml``` file, that was the result of:

```
 latexml file.bib --dest=file.xml
```

For this to work seemleesly, I recommend using ```latexmlc``` instead of the separate ```latexml``` and ```latexmlpost``` executables. Then you can do the conversion in a single step.

**Comment by bernhard-kleine** [comment]
I have in the meantime compiled an entire bibliography.
