### ISSUE TITLE
Missing imageprocesser

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#620]
>Error:imageprocessing:imageclass No image processing module found to convert types
>       Postprocessing LaTeXML::Post::Graphics engverxml.html
>        Skipping F:/EigeneDateien/BuchprojektSpringer/XMLtestordner/Xymtexstrukturen/Neurosteroide-crop.pdf=>png.
>        Please install one of: Graphics::Magick,Image::Magick

What do I have do add?

**Comment by brucemiller** [comment]
It's right there in the error message: 
Please install one of: Graphics::Magick,Image::Magick
