### ISSUE TITLE
Optional parameter of caption is shown. 

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#624]
Caption as well as section etc. have an optional parameter to be used for lists and table of contents. This parameter is shown in the html after latexml and latexmlpost.

**Comment by dginev** [comment]
Providing minimal examples of your problem always helps the developer team reproduce the issue quicker.

**Comment by brucemiller** [comment]
Yes, an example would help greatly, particularly since I can't understand what you're saying is wrong.

**Comment by brucemiller** [comment]
I'm going to assume that this is related to your pfigure macro.

**Comment by bernhard-kleine** [comment]
its obviously gone, thank you!
