### ISSUE TITLE
Caption does not show the figure number

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#625]
Using caption a figure number is generated. The figure number is obviouly referenced correctly, but not shown. A testcase is shown in http://b-kleine.com/test/testverxml.html.

**Comment by dginev** [comment]
In this case, it would also help to attach the exact TeX source you are converting.

**Comment by bernhard-kleine** [comment]
I have to analyse that, since a minimal example shows the number.

**Comment by dginev** [comment]
Wonderful! It is exactly the case that you are in a better position to understand when and where things break, so that we can be much quicker in figuring out how they break and apply a fix.

**Comment by brucemiller** [comment]
Again: short example showing the problem is the only way to fix it, since I can't tell from the page you linked to what you *expected* to see.

**Comment by bernhard-kleine** [comment]
The problem is in the following macro which formalizes the \begin{figure}:
\DeclareRobustCommand{\pfigure}[4]%
  {%
    \def\pfigure@graphic{g/#1}% graphic in the directory ./g named #4-crop.pdf
    \def\pfigure@coopt{#2}%        short form of the caption, optional argument
    \def\pfigure@caption{#3}%      caption text
    \def\pfigure@label{fig:#4}%    \label
    \centering\small%
    \includegraphics[width=\figurewidth]{\pfigure@graphic}\\[1mm]%
    \captionof{figure}[\pfigure@coopt]{\pfigure@caption}%
    \label{\pfigure@label}%
I have quite a number of them.

**Comment by brucemiller** [comment]
What you're calling "formalize" merely manages to completely hide the fact that it has anything to do with a "figure". Since there's no ```graphics``` environment in there, LaTeXML has no way of knowing that you intended it to be a figure.

**Comment by bernhard-kleine** [comment]
It uses \includegraphics.

**Comment by dginev** [comment]
I guess the slightly longer answer is that LaTeXML is a bit different than pure TeX in the way it deals with numbering figures, so you may not get the expected numbering with very low-level macros.

I don't understand your pfigure macro fully, e.g. I don't see how it hooks into the {figure} numbering scheme, maybe \captionof is something to look into on the LaTeXML side of affairs? Not sure.

**Comment by brucemiller** [comment]
Indeed, \captionof (from package caption) imitates \caption for a particular type of float. However, it's a bodge that doesn't actually require there to be a figure, table or whatever.  I've fixed up \captionof a little bit so it shows the number, but it still isn't going to show up in list-of-figures or similar.

**Comment by dginev** [comment]
yuck. But nice to have some support for it!

**Comment by bernhard-kleine** [comment]
Thank you very much!
