### ISSUE TITLE
`\include{}` does not seem to work in preamble

### ISSUE THREAD

**Issue by rplantz** [brucemiller/LaTeXML#626]
My book is written in LaTeX. I produce three versions: PDF, paperback, online (`bob.cs.sonoma.edu`). I used `tex4ht` to create the online version and am now trying to do the same thing with `LaTeXML`. Preliminary results are very encouraging.

The first problem is the way I distinguish between the three versions in my source code. At the beginning of my top-level file in the preamble I have:

    \def\web{0}
    \def\pdf{1}
    \def\paper{2}
    \include{bookType}
    \ifx\doctype\paper
       \documentclass[openany]{book}
    \else
       \documentclass[openany,oneside]{book}
    \fi
    \usepackage[latin9]{inputenc}
    \usepackage[T1]{fontenc}
    ...

Then in my `Makefile` I have (for the web version):

    web: book.tex
        [ ! -f bookType.tex ] || rm -f bookType.tex
        echo "\\\\let\doctype=\web" > bookType.tex
        latexmlc --destination book.xml --format=XML --log=book.xml.log book.tex
        latexmlpost --destination=book.html book.xml

This produces the error:

    (Digesting TeX book...
    (Processing content /home/bob/my_book_working/book.tex...
    Error:undefined:\include The token T_CS[\include] is not defined.
    at /home/bob/my_book_working/book.tex; line 4 col 8
    The token T_CS[\include] is not defined.
    In Core::Stomach[@0x41c7a68] at /home/bob/my_book_working/book.tex; line 4 col 8

`\include{}` works fine in the `document`. Should `\include{}` work in the preamble? Do I need to use another method to select the appropriate code for each of the three versions?

--Bob

**Comment by brucemiller** [comment]
You're being bitten by LaTeXML trying to be all-things-to-all-people; namely it starts out pretending to be TeX, until it detects something "obviously" LaTeX (or AmSTeX); then it loads LaTeX.pool and tries again.   When you run the real latex (or pdflatex) program, the "pool" is preloaded, so it already knows all those commands.

Maybe ```\include``` should be in that list as well? I didn't add it, thinking that it was a strange thing to have before ```\documentclass```; don't you get a blank page or something?  I'd have expected a plain ```\input``` would work better in either case.

In either case, the workaround for such situations is to tell latexml to load LaTeX in advance: ```--preload=LaTeX.pool```

**Comment by dginev** [comment]
Also, it is awesome that you are trying to get your book workflow operational with LaTeXML, keep us in the loop with problems you hit, we really appreciate feedback that helps us make LaTeXML better!

**Comment by brucemiller** [comment]
Aside: there can be plenty of reasons to conditionalize your source depending on which processor is being used. But LaTeXML ignores the oneside option; I'm surprised if tex4ht lays things out differently with the oneside option (why?).

At some point you may want to look at latexml.sty which provides (among other things) an ```\iflatexml```.

**Comment by rplantz** [comment]
Bruce, thank you, the --preload=LaTeX.pool worked. And you're right, \input
is more appropriate than \include in this case.

Deyan, I'm very happy to keep you in the loop. Although I got tex4ht to do
the job for me, so far it looks like LaTeXML will do better. And I have to
confess that the design philosophy of LaTeXML is much more appealing to me.
I probably would have used LaTeXML to begin with, but I did not know about
it. I got stuck at latex2html, which has sort of ended. Oh well, I have to
have something to keep me busy in my retirement. Actually, there's so much
to do in life, I don't know how I ever found enough time to work! :-)

I got stuck on my graphics, most of which is created with Dwight Aplevich's
Circuits_macros. His latest version will create svg files. I followed
http://comp-phys.net/2014/03/22/including-vector-graphics-in-latex-using-includesvg/
to include svg graphics that pdflatex understands. (So far, I have found
one place where I have to tweak the svg pictures with inkscape; the bar
over a letter (as in complement) gets lost. I will tell Dwight about this.)

LaTeXML treats svg and the path to the svg file a little differently. I
have to use:

\begin{figure}[!ht] \centering
\ifx\doctype\web
      \includesvg[width = \textwidth]{book_figs/subsystems}
\else
      \includesvg[width = \textwidth]{subsystems}
\fi
\caption[Subsystems of a computer.]{Subsystems of a computer. The CPU,
Memory, and I/O subsystems communicate with one another via the three
buses.}
\label{fg:subsystems}
\end{figure}

I have my Preface and Chapter 1 working quite well in LaTeXML now. Chapters
2 and 3 have lots of math, and chapters 4 and 5 have lots of circuits. I'm
having lots of fun.

--Bob

**Comment by dginev** [comment]
So, in the interest of order, I suggest you open new issues for the other problems you encounter. We can either close here with "worksforme" or ensure that ```\include``` triggers LaTeX mode in LaTeXML. I will let Bruce decide.

**Comment by brucemiller** [comment]
Yeah, the more I think about it include isn't really a normal thing to expect before the documenttype; I'm surprised it even works.  I think that using ```\input``` would probably work without the ```--preload```.

And yes: please file a separate issue on the svg.  I suspect you're using svgpath, and it hasn't been implemented.
