### ISSUE TITLE
General list environment is incomplete

### ISSUE THREAD

**Issue by rplantz** [brucemiller/LaTeXML#629]
The `list` environment is incomplete. The following (from my source file `general_list.tex`) produces only a bulleted list, not a numbered (using the counter) one:

    %% ~$ latexmlc --destination=general_list.xml --format=XML general_list.tex
    %% ~$ latexmlpost --destination=general_list.html general_list.xml
    
    \documentclass{book}
    \newcounter{exer}
    
    \begin{document}
    
    \begin{list}{\textbf{\thechapter \ - \theexer}}{\usecounter{exer}}
       \item First item.
       \item Second.
       \item And the third.
    \end{list}
    
    \end{document}

**Comment by brucemiller** [comment]
I think it should work now; Thanks for the report!
