### ISSUE TITLE
Extra space in equation split environment

### ISSUE THREAD

**Issue by rplantz** [brucemiller/LaTeXML#631]
Two minor issues:

1. The ``split`` environment inserts too much space to the left of the ``=`` sign.
2. Using ``\texttt{}`` for a subscripted number inserts space between the number and the subscript.

The second issue may fall outside the goals of LaTeXML. My book is about assembly language programming, and I like to use a monospaced font for binary, octal, and hex numbers. This is more of a display issue, not semantics.

My example:

    %% latexmlc --destination=split_eqn.xml --format=XML --preload=LaTeX.pool split_eqn.tex
    %% latexmlpost --destination=split_eqn.html split_eqn.xml
    \documentclass{article}
    \usepackage{amsmath}
    \usepackage{amsfonts}
    
    \begin{document}
    
      \begin{equation*}
        5678_{16} = 5 \times 4096 + 6 \times 256 + 7 \times 16 + 8 \times 1\\
      \end{equation*}
    
      \begin{equation*}
      \begin{split}
        5678_{16}
         &= 5 \times 4096 + 6 \times 256 + 7 \times 16 + 8 \times 1\\
         &= 20480 + 1536 + 112 + 8 \\
         &= +22136_{10}
      \end{split}
      \end{equation*}
    
      \begin{equation*}
      \begin{split}
        \texttt{5678}_{16}
         &= 5 \times 4096 + 6 \times 256 + 7 \times 16 + 8 \times 1\\
         &= 20480 + 1536 + 112 + 8 \\
         &= +22136_{10}
      \end{split}
      \end{equation*}
    
    \end{document}

**Comment by brucemiller** [comment]
Ouch, these both are areas that have given me trouble in the past, so I'll have to be careful to fix 'this' without breaking 'that'.

Your styling is up to you, of course, but I assume you know that the usual fonts are fixed-width for numbers. Still, it would be normal to use ```\mathtt``` in math, rather than ```\texttt```.

**Comment by brucemiller** [comment]
I think I've gotten both of these issues taken care of.  Thanks for the report.
