### ISSUE TITLE
picture environment supported?

### ISSUE THREAD

**Issue by ghost** [brucemiller/LaTeXML#632]
Is the `picture` environment supported? In the following code the text is not aligned properly with the graphics. Furthermore, changing the font size in my browser affects this alignment.

```
%% latexmlc --destination=picture.xml --format=XML --preload=LaTeX.pool picture.tex
%% latexmlpost --destination=picture.html picture.xml

\documentclass{article}
\usepackage{graphicx}

\begin{document}
Figure \ref{fg:kmap2} shows how all four minterms for two variables are mapped onto a four-cell Karnaugh map.
\begin{figure}[!ht] \centering
\begin{picture}(70,65)
\put(12,57){\makebox(0,0){$F(x,y)$}}

\put(30,40){\line(1,0){40}}
\put(30,20){\line(1,0){40}}
\put(30,0){\line(1,0){40}}

\put(30,0){\line(0,1){40}}
\put(50,0){\line(0,1){40}}
\put(70,0){\line(0,1){40}}

\put(50,57){\makebox(0,0){$y$}}
\put(40,47){\makebox(0,0){\footnotesize $0$}}
\put(60,47){\makebox(0,0){\footnotesize $1$}}

\put(14,20){\makebox(0,0){$x$}}
\put(22,30){\makebox(0,0){\footnotesize $0$}}
\put(22,10){\makebox(0,0){\footnotesize $1$}}

\put(40,30){\makebox(0,0){$m_0$}}
\put(60,30){\makebox(0,0){$m_1$}}
\put(40,10){\makebox(0,0){$m_2$}}
\put(60,10){\makebox(0,0){$m_3$}}
\end{picture}
\caption{Mapping of two-variable minterms on a Karnaugh map.}
\label{fg:kmap2}
\end{figure}

\end{document}
```

I'm finding that `png` graphics work best for my application. Most of my figures are circuit diagrams, where the alignment of text relative to the drawing is crucial. I wanted to use `svg`, but then the text in the drawing can be changed independently from the art work.

I think that I still have lots to learn about graphics for electronic viewing!

**Comment by dginev** [comment]
Seems to mostly work when I try it in the editor [here](latexml.mathweb.org/editor?tex=%25%25%20latexmlc%20--destination%3Dpicture.xml%20--format%3DXML%20--preload%3DLaTeX.pool%20picture.tex%0A%25%25%20latexmlpost%20--destination%3Dpicture.html%20picture.xml%0A%0A%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bgraphicx%7D%0A%0A%5Cbegin%7Bdocument%7D%0AFigure%20%5Cref%7Bfg%3Akmap2%7D%20shows%20how%20all%20four%20minterms%20for%20two%20variables%20are%20mapped%20onto%20a%20four-cell%20Karnaugh%20map.%0A%5Cbegin%7Bfigure%7D%5B!ht%5D%20%5Ccentering%0A%5Cbegin%7Bpicture%7D(70%2C65)%0A%5Cput(12%2C57)%7B%5Cmakebox(0%2C0)%7B%24F(x%2Cy)%24%7D%7D%0A%0A%5Cput(30%2C40)%7B%5Cline(1%2C0)%7B40%7D%7D%0A%5Cput(30%2C20)%7B%5Cline(1%2C0)%7B40%7D%7D%0A%5Cput(30%2C0)%7B%5Cline(1%2C0)%7B40%7D%7D%0A%0A%5Cput(30%2C0)%7B%5Cline(0%2C1)%7B40%7D%7D%0A%5Cput(50%2C0)%7B%5Cline(0%2C1)%7B40%7D%7D%0A%5Cput(70%2C0)%7B%5Cline(0%2C1)%7B40%7D%7D%0A%0A%5Cput(50%2C57)%7B%5Cmakebox(0%2C0)%7B%24y%24%7D%7D%0A%5Cput(40%2C47)%7B%5Cmakebox(0%2C0)%7B%5Cfootnotesize%20%240%24%7D%7D%0A%5Cput(60%2C47)%7B%5Cmakebox(0%2C0)%7B%5Cfootnotesize%20%241%24%7D%7D%0A%0A%5Cput(14%2C20)%7B%5Cmakebox(0%2C0)%7B%24x%24%7D%7D%0A%5Cput(22%2C30)%7B%5Cmakebox(0%2C0)%7B%5Cfootnotesize%20%240%24%7D%7D%0A%5Cput(22%2C10)%7B%5Cmakebox(0%2C0)%7B%5Cfootnotesize%20%241%24%7D%7D%0A%0A%5Cput(40%2C30)%7B%5Cmakebox(0%2C0)%7B%24m_0%24%7D%7D%0A%5Cput(60%2C30)%7B%5Cmakebox(0%2C0)%7B%24m_1%24%7D%7D%0A%5Cput(40%2C10)%7B%5Cmakebox(0%2C0)%7B%24m_2%24%7D%7D%0A%5Cput(60%2C10)%7B%5Cmakebox(0%2C0)%7B%24m_3%24%7D%7D%0A%5Cend%7Bpicture%7D%0A%5Ccaption%7BMapping%20of%20two-variable%20minterms%20on%20a%20Karnaugh%20map.%7D%0A%5Clabel%7Bfg%3Akmap2%7D%0A%5Cend%7Bfigure%7D%0A%0A%5Cend%7Bdocument%7D)

**Comment by rplantz** [comment]
The 2x2 grid is shifted one square to the left relative to the text. I've
attached a pdf showing what it's supposed to look like.

--Bob

**Comment by dginev** [comment]
If you attach a PDF to an email it won't upload to GitHub, however. But thanks for pointing out the discrepancies!

**Comment by rplantz** [comment]
Here's a png picture of what it's supposed to look like:
![picture](https://cloud.githubusercontent.com/assets/4309069/8365731/0ed1d3e2-1b44-11e5-89f4-d786ffae6eb2.png)

**Comment by dginev** [comment]
Awesome, we'll check it out!

**Comment by brucemiller** [comment]
nominally supported yes, but apparently not so well in this case.  Will have to look into it.

**Comment by dginev** [comment]
Moving to next milestone (0.8.4), so that we roll out 0.8.3 asap. Apologies this issue didn't make the cut.

**Comment by bfirsh** [comment]
I was thinking of opening another issue about this, but this seems to be a reasonably good place to file it: the `t/graphics/picture.tex` test case is pretty broken, too. Compare the output of that with the PDF in the same directory to see the issues.

**Comment by dginev** [comment]
For reference, here is the current Firefox rendering of the reported snippet in the issue description.
![pic](https://user-images.githubusercontent.com/348975/55812648-58656380-5ab9-11e9-95b9-454b2edb41a5.png)

**Comment by brucemiller** [comment]
Yep, pretty silly. For further reference sake: I've partly debugged this (at least once) in the past, but couldn't quite figure out the fix. It comes down to some structure getting width=0, which (as I recall) svg sometimes requires and sometimes does something like the current situation. Sigh.  Hate to leave something "almost fixed" dangling for so long.
