### ISSUE TITLE
Make svg for equations slightly larger

### ISSUE THREAD

**Issue by HansOlsson** [brucemiller/LaTeXML#635]
The current svgs generated from equations seem to cause clipping at the boundary for browsers (such as Chrome, Internet Explorer) - there was previously a similar issue for svg generated from pictures.

```svg
<?xml version='1.0'?>
<!-- This file was generated by dvisvgm 1.8.1 -->
<svg height='12.183pt' version='1.1' viewBox='65.1067 54.9629 9.20126 12.183' width='9.20126pt' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>
<defs>
<font horiz-adv-x='0' id='cmmi7'>
<font-face ascent='750' descent='-250' font-family='cmmi7' units-per-em='1000'/>
<glyph d='M525 338C511 396 466 456 372 456C232 456 116 351 80 261C74 244 60 203 60 163C60 94 114 -20 270 -20C529 -20 634 303 634 445C634 616 522 714 388 714C225 714 180 584 180 553C180 545 185 517 220 517S276 548 276 572C276 599 256 608 237 610C287 685 369 685 386 685C461 685 550 638 550 496C550 453 545 418 526 338H525ZM272 12C159 12 146 97 146 128C146 167 173 265 183 290C201 336 263 428 376 428C473 428 505 352 505 292C505 225 440 12 272 12Z' glyph-name='partialdiff' horiz-adv-x='610' unicode='∂' vert-adv-y='610'/>
<glyph d='M246 395H348C367 395 380 395 380 417C380 431 367 431 350 431H255L292 579C293 584 295 589 295 593C295 611 281 625 261 625C236 625 221 608 214 582C207 557 220 605 176 431H74C55 431 42 431 42 409C42 395 54 395 72 395H167L108 159C102 134 93 98 93 85C93 26 143 -10 200 -10C311 -10 374 130 374 143S361 156 358 156C346 156 345 154 337 137C309 74 258 18 203 18C182 18 168 31 168 67C168 77 172 98 174 108L246 395Z' glyph-name='t' horiz-adv-x='431' unicode='t' vert-adv-y='431'/>
<glyph d='M249 106C239 72 206 18 155 18C152 18 122 18 101 32C142 45 145 81 145 87C145 109 128 124 105 124C77 124 48 100 48 63C48 13 104 -10 153 -10C199 -10 240 19 265 61C289 8 344 -10 384 -10C499 -10 560 115 560 143C560 156 547 156 544 156C530 156 529 151 525 139C504 70 444 18 388 18C348 18 327 45 327 83C327 109 351 200 379 311C399 388 444 413 477 413C479 413 510 413 531 399C499 390 487 362 487 344C487 322 504 307 527 307S583 326 583 368C583 424 519 441 479 441C429 441 389 408 367 370C349 411 303 441 247 441C135 441 71 318 71 288C71 275 85 275 88 275C101 275 102 279 107 292C132 370 195 413 244 413C277 413 304 395 304 347C304 327 292 277 283 243L249 106Z' glyph-name='x' horiz-adv-x='647' unicode='x' vert-adv-y='647'/>
</font>
</defs>
<style type='text/css'><![CDATA[
text.f1 {font-family:cmmi7;font-size:6.97385px}
]]>
</style>
<g id='page2'>
<text class='f1' x='65.1067' y='59.7878'>∂<tspan x='69.7743'>x</tspan>
<tspan x='65.8609' y='67.1459'>∂</tspan>
<tspan x='70.5284'>t</tspan>
</text>
<rect height='0.398484' width='9.20126' x='65.1067' y='61.0205'/>
</g>
</svg>
```

It seems it is generated from dvisvgm and you can then use something like --bbox=1pt to enlarge the clipping box.

**Comment by brucemiller** [comment]
I'm not seeing the clipping (yet), but my simple test case showed chinese instead of greek!! Maybe there's more to getting dvisvgm to work than I though! :<

But your patch sounds sensible and I'll include that when I get the greek sorted out! Thanks.

**Comment by dginev** [comment]
```my simple test case showed chinese instead of greek```

Well Greece is potentially about to default very soon, so I guess tools are adapting to more stable output formats.

**Comment by brucemiller** [comment]
On 07/09/2015 10:49 AM, Deyan Ginev wrote:
> |my simple test case showed chinese instead of greek|
>
> Well Greece is potentially about to default very soon, so I guess tools
> are adapting to more stable output formats.

Right you are: It's a feature, not a bug!

**Comment by brucemiller** [comment]
I suspect most of our SVG sizing problems are due to LaTeXML's bad font metrics, but conceivably dvipsvgm could have similar issues. I've changed the ```-box=min``` to ```-box=1pt``` as you suggested, just to give a little more margin for error.

I also "fixed" the chinese greek problem by adding the ```--no-fonts``` option, which keeps it from trying to create SVG fonts(?) which don't seem well supported, but also dvisvgm guesses wrong about which unicode codepoint the glyph is (it seems Firefox & Chrome use that codepoint instead of the font).  A future version of dvisvgm apparently will include a better lookup of those glyphs, so we may be able to undo this later.  But for now, it works better.

I'm hoping the 1pt is enough; if not, please reopen the issue and we can try more.  Thanks for the report.

**Comment by HansOlsson** [comment]
Excellent, and quickly done. Thanks a lot.
