### ISSUE TITLE
use package mhchem to convert chemical formulae

### ISSUE THREAD

**Issue by ywcdiao** [brucemiller/LaTeXML#641]
When I use option '--includestyles' to include package "mhchem.sty" and other required packages to convert chemical formulae. It occurs a fatal problem "Fatal:misdefined:# The token T_PARAM[#] should never reach Stomach!" in the package "expl3.sty"(which is required in the package "mhchem.sty") line 105 col 53. I suppose if there is any way to solve it?

**Comment by dginev** [comment]
I'll cross-reference #706 here, and close here as the newer issue.

I'm now also getting requests for support from the new arXiv preview, so there is higher likelihood we'll implement a binding soon.
