### ISSUE TITLE
Add support for the \prescript command (mathtools package)

### ISSUE THREAD

**Issue by fred-wang** [brucemiller/LaTeXML#643]
Testcase from http://ctan.org/pkg/mathtools:

      \documentclass{article}
      \usepackage{amsmath,mathtools}
      \begin{document}
      \[
        {}^{4}_{12}\mathbf{C}^{5+}_{2} \quad
        \prescript{14}{2}{\mathbf{C}}^{5+}_{2} \quad
        \prescript{4}{12}{\mathbf{C}}^{5+}_{2} \quad
        \prescript{14}{}{\mathbf{C}}^{5+}_{2} \quad
        \prescript{}{2}{\mathbf{C}}^{5+}_{2}
      \]
      \end{document}

Result:

          Error:missing_file:mathtools Can't find binding for package mathtools
    	at /home/fred/Bureau/prescripts.tex; line 3 col 6
    	Can't find binding for package mathtools
    	search paths are /home/fred/Bureau
    	Next token is T_CS[\begin]
    	In \usepackage OptionalSemiverbatim Semi... from LaTeX.pool.ltxml line 575
    	 <= Core::Stomach[@0xb426b0] <= ...
    
    Error:undefined:\prescript The token T_CS[\prescript] is not defined.
    	at /home/fred/Bureau/prescripts.tex; line 6 col 12
    	The token T_CS[\prescript] is not defined.
    	In Core::Stomach[@0xb426b0] at /home/fred/Bureau/prescripts.tex; line 6 col 12
    	 <= \[ <= Core::Stomach[@0xb426b0] <= \begin{document} <= ...
     0.23 sec) 0.24 sec)

Note that LaTeXML is clever enough to convert `{}^{4}_{12}\mathbf{C}^{5+}_{2}` into a mmultiscripts but it would be nice to support the `\prescript` syntax too!

**Comment by kpj** [comment]
An unfinished binding for mathtools is currently available [here](https://github.com/kpj/LaTeXML_Bindings_WIP/blob/master/bindings/mathtools.sty.ltxml).

`\prescript` should be supported already.

**Comment by brucemiller** [comment]
Finally finished up and included in the distribution. Thanks @kpj for the code and thanks for the request.
