### ISSUE TITLE
Support for \@curtab

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#644]
@brucemiller are you familiar with ```\@curtab``` and how hard would you think it is to add to LaTeXML?

I have a very cool example to motivate this issue with, ideal for interns that want to do something "exciting" and small:

This is a prime number generator in LaTeX I found on [StackOverflow](http://tex.stackexchange.com/questions/134305/how-to-produce-a-list-of-prime-numbers-in-latex). It seems that if we get ```\@curtab``` implemented, LaTeXML may just be able to get it done. But I don't dare say I fully understand the code, there may be more trickery in there. Great for our native TeX support though!

```latex
\documentclass{article}

\makeatletter
\def\primes#1#2{{%
  \def\comma{\def\comma{, }}%
  \count@\@ne\@tempcntb#2\relax\@curtab#1\relax
  \@primes}}
\def\@primes{\loop\advance\count@\@ne
\expandafter\ifx\csname p-\the\count@\endcsname\relax
\ifnum\@tempcntb<\count@\else
  \ifnum\count@<\@curtab\else\comma\the\count@\fi\fi\else\repeat
\@tempcnta\count@\loop\advance\@tempcnta\count@
\expandafter\let\csname p-\the\@tempcnta\endcsname\@ne
\ifnum\@tempcnta<\@tempcntb\repeat
\ifnum\@tempcntb>\count@\expandafter\@primes\fi}
\makeatother   
%
\begin{document}

\primes{1}{10}

\primes{1}{100}

\primes{1}{1000}

\primes{900}{1000}


\end{document}
```

**Comment by brucemiller** [comment]
On 07/27/2015 06:17 PM, Deyan Ginev wrote:
> @brucemiller <https://github.com/brucemiller> are you familiar with
> |\@curtab| and how hard would you think it is to add to LaTeXML?

\@curtab is just a counter; the mystery is how it gets set in latex.
I think in your code below, it's just used by \primes as an upper limit(?)

> I have a very cool example to motivate this issue with, ideal for
> interns that want to do something "exciting" and small:

Actually, it runs, but needs \@curtab, \count@ defined as counters,
and the \loop macro (that's in TeX.pool) doesn't seem correct...
at least it's not quite the same as latex.ltx's \loop.

**Comment by dginev** [comment]
@brucemiller thanks for the explanation! Sounds like with a little work we can have the example fully working, right?

@kpj and @lkohlhase if you feel like having fun - feel free to take a look.

**Comment by brucemiller** [comment]
On 07/28/2015 09:53 AM, Deyan Ginev wrote:
> @brucemiller <https://github.com/brucemiller> thanks for the
> explanation! Sounds like with a little work we can have the example
> fully working, right?

The TeX & LaTeX definitions are subtly different and in fact
the TeX one fails in pdflatex with \next undefined just as latexml does!
I hate to admit that on a cursory look, I can't figure out why!!!

> @kpj <https://github.com/kpj> and @lkohlhase
> <https://github.com/lkohlhase> if you feel like having fun - feel free
> to take a look.

The trivial, and apparently correct, solution would be to copy
LaTeX's \loop defn into LaTeX.pool.  And probably useful would
be to use tools/texscan to find additional stuff to define.
There are seemingly no (significant) exported symbols, but
   tools/texscan LaTeX.pool --internal
shows lots of internal ones.

Probably the most useful would be to find all the registers
(counts, dimensions, skips, tokens) and define those to cover
the odd uses that crop up from time to time.

**Comment by dginev** [comment]
With Lukas' newest PR this is working like a charm!

Have a look:
latexml.mathweb.org/editor?tex=%5Cdocumentclass%7Barticle%7D%0A%0A%5Cmakeatletter%0A%5Cdef%5Cprimes%231%232%7B%7B%25%0A%20%20%5Cdef%5Ccomma%7B%5Cdef%5Ccomma%7B%2C%20%7D%7D%25%0A%20%20%5Ccount%40%5C%40ne%5C%40tempcntb%232%5Crelax%5C%40curtab%231%5Crelax%0A%20%20%5C%40primes%7D%7D%0A%5Cdef%5C%40primes%7B%5Cloop%5Cadvance%5Ccount%40%5C%40ne%0A%5Cexpandafter%5Cifx%5Ccsname%20p-%5Cthe%5Ccount%40%5Cendcsname%5Crelax%0A%5Cifnum%5C%40tempcntb%3C%5Ccount%40%5Celse%0A%20%20%5Cifnum%5Ccount%40%3C%5C%40curtab%5Celse%5Ccomma%5Cthe%5Ccount%40%5Cfi%5Cfi%5Celse%5Crepeat%0A%5C%40tempcnta%5Ccount%40%5Cloop%5Cadvance%5C%40tempcnta%5Ccount%40%0A%5Cexpandafter%5Clet%5Ccsname%20p-%5Cthe%5C%40tempcnta%5Cendcsname%5C%40ne%0A%5Cifnum%5C%40tempcnta%3C%5C%40tempcntb%5Crepeat%0A%5Cifnum%5C%40tempcntb%3E%5Ccount%40%5Cexpandafter%5C%40primes%5Cfi%7D%0A%5Cmakeatother%20%20%20%0A%25%0A%5Cbegin%7Bdocument%7D%0A%0A%5Cprimes%7B1%7D%7B10%7D%0A%0A%5Cprimes%7B1%7D%7B100%7D%0A%0A%5Cprimes%7B1%7D%7B1000%7D%0A%0A%5Cprimes%7B900%7D%7B1000%7D%0A%0A%0A%5Cend%7Bdocument%7D

Closing here, thanks @lkohlhase !

**Comment by dginev** [comment]
P.S. I am still amazed this TeX program works!
