### ISSUE TITLE
mathsvg problem still exists with latest github distribution

### ISSUE THREAD

**Issue by gpetty** [brucemiller/LaTeXML#650]
Since Bruce closed the issue I opened earlier today, I wasn't sure whether my followup comment in that thread would get read, so I'm reopening as a new issue here (apologies if that wasn't necessary).  See https://github.com/brucemiller/LaTeXML/issues/649 for the details.  Bottom line: even with the latest distribution from github, the mathsvg option isn't working for me.  Diagnostic output is here

https://dl.dropboxusercontent.com/u/1653737/latexml_log.txt
https://dl.dropboxusercontent.com/u/1653737/latexmlpost_log.txt
https://dl.dropboxusercontent.com/u/1653737/ltxmlimg.log

**Comment by dginev** [comment]
There are 2 identical error messages remaining, Bruce probably knows more details about them:
```
! Undefined control sequence.
l.1633 ...{u_{i}^{n+1}-u_{i}^{n}}{\Delta t}+\inner
                                                  @par c\frac{u_{i+1}^{n}-u_...
```

**Comment by gpetty** [comment]
Could a localized macro error in just two equations prevent SVG output for the hundreds of other equations in the document?

**Comment by dginev** [comment]
I think if the shell call to latex fails, as it does:
```
Error:shell:latex LaTeX command 'latex ltxmlimg > ltxmlimg.ltxoutput' failed
	Postprocessing LaTeXML::Post::MathML::Presentation book.xhtml
	returned code 256 (!= 0): 
	See /tmp/LaTeXML27WmYz/ltxmlimg.log
```

It short-circuits the image extraction logic, so 0 images get extracted. Of course, this is more of an educated guess than a definitive statement. I would expect fixing the last error will get all images up and running.

**Comment by gpetty** [comment]
I'd be happy to provide the full document source if it would be useful in debugging.  It's a published textbook with considerable math,  http://www.amazon.com/First-Course-Atmospheric-Numerical-Modeling/dp/0972903348/

**Comment by dginev** [comment]
Well, this is probably simple enough to get right. To me it naively looks as if we need to add a ```\makeatletter``` in the right place, but I really want to understand what that ```\inner@par``` is doing in the middle of that equation.

We should wait for Bruce to take a look.

**Comment by gpetty** [comment]
I apparently spoke too soon.  I just found a directory 'mi/' full of .svg files, and I see now that they're apparently linked in as altimg objects for the MathML codes that I saw when I browsed one of the files.

Apologies for overlooking this!

**Comment by brucemiller** [comment]
I'm puzzled: the log you posted should have indicate that no images were produced (or at least not all). Unless you're mixing two different runs of latexmlpost?

At any rate, the ```\inner@par``` shouldn't have ended up in the TeX, but I'm not sure what should have. It would appear to come from a ```\\`` inside the math which is inside of an environment doing centering or framing or something.  It  would be worth seeing what the markup was that produced that.  It would have looked something like, but not exactly this:
```
\frac{u_{i}^{n+1}-u_{i}^{n}}{\Delta t}+\\ c\frac{u_{i+1}^{n}-u_{i}^{n}}{\Delta x}=0
```
and appeared inside of something interesting (some environment?)

If you could find that document fragment, it would help keep this from happening in the future. Thanks;

**Comment by gpetty** [comment]
I can't be certain that either of these is the right fragment, because similar expressions show up in numerous places, but the following have equations like the above inside of tables:

https://dl.dropboxusercontent.com/u/1653737/Table4-1.tex
https://dl.dropboxusercontent.com/u/1653737/Table4-2.tex

Is there anyway to related the line number given in the error message to a specific line in the original LaTeX source or in some intermediate file?

**Comment by dginev** [comment]
You could make new empty documents, each containing just one of the expressions, and convert them with the same commands. Ideally you hit the message we are hunting for on one of the first tries.

**Comment by brucemiller** [comment]
I don't see any problems running your two examples.  But then, since you'd closed the issue, perhaps the problem isn't actually occurring any more? Maybe it was accidentally fixed or covered up by some other change?  If you make a clean build from scratch, removing whatever stray generated files, logs & caches, do you still get an error when creating images from math?  If not, then we'll probably have to wait for the problem to reveal itself again.

If it does occur, then (with --verbose) the ltximg log should show you what latex did while processing the math; the TeX for the math unfortunately isn't exactly the same as your input, so it's takes a bit of matching up to figure out what original math caused the problem, but it's possible. Then you'd want to create a small document with just that formula and see if it produces the same error. And then we've got something to go on to fix it!

**Comment by brucemiller** [comment]
As I said, ```\inner@par``` shouldn't end up in the TeX strings, but I'm not clear how it got there, and how it should be prevented, without a sample case.  I'll close, for now, given the possibility that this is already fixed, but if it shows up again, please reopen.  Thanks;
