### ISSUE TITLE
Ability to customize the id of sections, figures etc

### ISSUE THREAD

**Issue by fred-wang** [brucemiller/LaTeXML#668]
LaTeXML generates ids like "SS3.SSS3" that are neither "user-friendly" nor stable. Consider for example for sections: 1) it might be better to use the header text or the attached label 2) adding removing or reordering the sections of a LaTeX files may change the URL of sections. It would be great to have the ability to customize these ids.

See the thread on the LaTeXML mailing list for details:
http://lists.jacobs-university.de/pipermail/project-latexml/2015-October/002105.html

**Comment by dginev** [comment]
Moving to next milestone (0.8.4), so that we roll out 0.8.3 asap. Apologies this issue didn't make the cut.

**Comment by brucemiller** [comment]
I've made a fix to #895, that probably applies here.  It leverages the option for split naming based on labels (so only works for split documents), but seems to work pretty well (could probably set up a separate option if really needed).  But I'm going to close this for now.  Thanks for the report!
