### ISSUE TITLE
listings.sty C highlighting bug

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#670]
A minimal example:
```latex
\documentclass{article}
\usepackage{listings}
\lstset{language=C}
\begin{document}

Test: \lstinline{#define EXAMPLE} 

\end{document}
```

LaTeXML seems to eat the ```#``` sign, and possibly get the highlighting wrong?

Current LaTeXML output: [here](http://latexml.mathweb.org/editor?tex=%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Blistings%7D%0A%5Clstset%7Blanguage%3DC%7D%0A%5Cbegin%7Bdocument%7D%0A%0ATest%3A%20%5Clstinline%7B%23define%20EXAMPLE%7D%20%0A%0A%5Cend%7Bdocument%7D)
Expected PDF output: [inline.pdf](https://github.com/brucemiller/LaTeXML/files/14510/inline.pdf)

**Comment by brucemiller** [comment]
THis should be fixed now.
