### ISSUE TITLE
wasysym.sty.ltxml

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#671]
It seems like we can almost fully process the ```wasysym.sty``` LaTeX package natively, but LaTeXML seems to need an extra hind about the font file definitions. See bellow a run with ```--includestyles``` enabled, on the minimal example:

```latex
\documentclass{article}
\usepackage{wasysym}
\begin{document}
test \fullmoon
\end{document}
```
There is probably a minimal binding that succeeds in loading the CTAN wasysym.sty together with the font. Or would we need a special mapping to unicode?

> $ latexmlc wasy.tex --dest=wasy.html --includestyles
>
>(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.13 sec)
>
>latexmlc (LaTeXML version 0.8.1; revision 9dc7900)
processing started Thu Oct 15 17:18:09 2015
>
>(Digesting TeX wasy...
(Processing content /tmp/wasy.tex...
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.16 sec)
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/article.cls.ltxml... 0.02 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/wasysym/wasysym.sty... 0.06 sec)
Error:missing_file:u Can't find definitions u
	at /tmp/wasy.tex; line 4 col 15
	Can't find definitions u
	search paths are /tmp
	Next token is T_CS[\fontfamily]
	```In Core::Definition::Primitive[\@@@fonte... from TeX.pool.ltxml line 1277```
	 <= Core::Stomach[@0x2f9a770] <= Core::Gullet[@0x2fa1ce8] <= Core::Stomach[@0x2f9a770] <= ...
>
>Info:unexpected:wasy Unrecognized font family 'wasy'.
	at /tmp/wasy.tex; line 4 col 15
	Unrecognized font family 'wasy'.
 0.43 sec) 0.43 sec)
(Building...
(Loading compiled schema /home/dreamweaver/perl5/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.05 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: 1 error; 1 missing file[u.fontmap].
>
>(post-processing...
(Scan wasy.html processing... 0.00 sec)
(CrossRef wasy.html processing... 0.00 sec)
(XSLT[using LaTeXML-html5.xsl] wasy.html processing... 0.02 sec)
(Writer wasy.html processing... 0.00 sec) 0.03 sec)
Post-processing complete: No obvious problems
processing finished Thu Oct 15 17:18:10 2015
Status:conversion:2 
1 error
Wrote wasy.html

**Comment by brucemiller** [comment]
On 10/15/2015 05:28 PM, Deyan Ginev wrote:
> It seems like we can almost fully process the |wasysym.sty| LaTeX
> package natively, but LaTeXML seems to need an extra hind about the font
> file definitions.

Not sure I'd even thought to try that, but of course the fonts
it uses are very special purpose; ultimately the glyphs have
to be mapped specifically to unicode (or some other concoction).

> There is probably a minimal binding that succeeds in loading the CTAN
> wasysym.sty together with the font. Or would we need a special mapping
> to unicode?

Actually, I already have a draft binding from @kpj with most
symbols mapped to unicode.  He was doing some experiments to
see if he could extract SVG to handle the others.

Some might be amenable to a simpler approach (that I'm neck-deep in ATM);
getting LaTeXML, and math particularly, to deal better with
TeX's spacing magic (\rlap,\llap, \hss, etc).  Right now I'm trying
to polish up the loose ends of mathtools, but next is looking at
completing wasysym and stmaryd.

**Comment by brucemiller** [comment]
I've just committed the binding after polishing some of the glyphs that can't be found in Unicode. A few could be synthesized by overlapping symbols in a way that seems to work with Firefox & MathJax.  The others, I've adopted a strategy of warning that the have no Unicode equivalent, you get a red ```\foo```, but no error. Seems a gentler approach.

Thanks @kpj for the binding!
