### ISSUE TITLE
latexml should be able to log to console and log file (both)

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#672]
It seems that currently LaTeXML only logs to either the console or the log file. For running LaTeXML in MMT/MathHub.info it would be useful to allow both at the same time. Is this difficiult to do? cc:@cmaeder

**Comment by dginev** [comment]
Yes it is, since we log once and then decide which stream to use. If you had the log in a file it is trivial to ```cat``` the file into STDERR at any point.

**Comment by brucemiller** [comment]
On 10/16/2015 05:16 AM, Michael Kohlhase wrote:
> It seems that currently LaTeXML only logs to either the console or the
> log file. For running LaTeXML in MMT/MathHub.info it would be useful to
> allow both at the same time. Is this difficiult to do? cc:@cmaeder
> <https://github.com/cmaeder>

definitely would be a useful feature, particularly if the
STDERR output were severely shortened and the log file were
more detailed.  Probably not so easy in the short term,
but likely will be once we start integrating things better
(under common config, etc).

[Oh! I see that Deyan thinks it's easier than I did.
That's always a good sign! :> ]

**Comment by cmaeder** [comment]
I could surely `cat` the created log-file to the console, but this is not the "worker-output". latexml also outputs post-processing information to the console, i.e. finally:

```
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/mv/latexml/approxeq.de.omdoc
```

**Comment by dginev** [comment]
I think the final status message is something that was printed out to STDERR specifically after an sTeX request by Michael, as he wanted to monitor the details in the console, while the actual logs were saved to disk. All of that is reasonable, but in batch settings you always have a parent process that orchestrates the latexml run, and that process can look at the log file contents and inform STDERR of the details you need. That's something I do for CorTeX as well, although quite sparingly.

**Comment by dginev** [comment]
I think I feel comfortable with closing here, since it is a use case that has viable workarounds and isn't critical in severity.

**Comment by brucemiller** [comment]
Actually, I think I'd like to keep this one open, as I'd really like a better solution for practical reasons; a bit more TeX like in the sense of a detailed log file, but a *much* briefer console output.

**Comment by dginev** [comment]
@brucemiller maybe the latest logging upgrades close this issue?
