### ISSUE TITLE
listings.sty.ltxml problem: \lstinline in macros 

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#674]
When I use 
```
\usepackage{listings}
...
\def\foo#1{#1}
\foo{\lstinline|is_prime|}
```
then I get the error
```
error: unexpected:_ Script _ can only appear in math mode
```
but LaTeX accepts it without blushing.

**Comment by dginev** [comment]
Possibly related to #670 which is also about lstinline

**Comment by brucemiller** [comment]
Strange... almost like ```\verb|...|```,  but not quite.  Should be fixed now.
