### ISSUE TITLE
Problems with longtable captions and labels

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#675]
I am not sure if this is the right place to post my question, but I would be grateful of help with the problems I am experiencing while trying to convert LaTeX document containing multiple longtables into html. I am using LaTeXML 0.8.0 running under MacOS X 10 with TeXLive. During the conversion LaTeXML does not handle labels and captions correctly: all captions are replaced with the last long table caption and labels are undefined. I attach images of a simple test LaTeX file, and the XML and html outputs.
Thanks

![lngtab-html](https://cloud.githubusercontent.com/assets/4363602/10605292/2e20994c-7722-11e5-9032-03f64fac265e.jpg)
![lngtab-tex](https://cloud.githubusercontent.com/assets/4363602/10605298/302e5a80-7722-11e5-91e3-c3c40d5e115c.jpg)
![lngtab-xml](https://cloud.githubusercontent.com/assets/4363602/10605300/32a7be78-7722-11e5-9049-3bdb8ffd96d1.jpg)

**Comment by brucemiller** [comment]
It's the perfect place to post the question!  Although it would generally be more useful to post the TeX source (or paste in a fragment), rather than attaching images of it.

And while it's generally safer to include ```\label``` within the ```\caption``` of tables, what you had should have worked.  I've fixed it in the current repository; you can check it out from here, and it will be included in 0.8.2 sometime soon.

**Comment by goska** [comment]
Thank you. I tried attaching the files, but lacked permissions to do so. I'll try pasting in fragments of source code next time.

**Comment by dginev** [comment]
GitHub won't allow you to actually attach file formats it doesn't expect. But if the snippet is small enough you could do:

> \`\`\`latex
a snippet
> \`\`\`

In the comment you post, and it will get nicely highlighted. You can use "html" for highlighting HTML. For example:
```latex
\documentclass{article}
\begin{document}
hello latex world!
\end{document}
```

and 
```html
<html>
 <head></head>
 <body> the body </body>
</html>
```

**Comment by goska** [comment]
Thank you, dginev.
Placement of \label was just one of the causes of my problems with \longtable. The main reason appears to the presentce of more than one instance of \longtable in the same document - moving the labels inside captions has made very little difference to the outcomes (still using LaTeXML 0.8.0). (I am trying to convert a document, too long for posting here, which contains several \lontables - they lose captions and labels during transformation, and horizontal lines, which follow captions and labels in tex source (captions and labels are at the bottom of the tables)). 
Thanks.
TeX source:
```latex
\documentclass{article}
\usepackage{longtable}
%\usepackage{latexml}
\usepackage{hyperref}

\begin{document}

\section{First}
\subsection{Verbatim highlights from Table}

Link to Table~\ref{two}.

\begin{longtable}{l}
a\\
b\\

\caption{Table caption 1\label{one}}

\end{longtable}
\section{Second}

\begin{longtable}{l}

c\\
d\\

\caption{Table caption 2\label{two}}

\end{longtable}

Link to Table~\ref{one}.

\end{document}
```
XML output:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/Users/goska/CU9/tests/Doc-tests2"?>
<?latexml class="article"?>
<?latexml package="longtable"?>
<?latexml package="hyperref"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-article.css" type="text/css"/>
  <section refnum="1" xml:id="S1">
    <title><tag close=" ">1</tag>First</title>
    <subsection refnum="1.1" xml:id="S1.SS1">
      <title><tag close=" ">1.1</tag>Verbatim highlights from Table</title>
      <para xml:id="S1.SS1.p1">
        <p>Link to Table <ref labelref="LABEL:two"/>.</p>
      </para>
      <table frefnum="Table 2" refnum="2" xml:id="S2.T2" labels="LABEL:two">
        <caption><tag close=": ">Table 2</tag>Table caption 2</caption>
        <toccaption><tag close=" ">2</tag>Table caption 2</toccaption>
        <tabular>
          <tr>
            <td align="left">a</td>
          </tr>
          <tr>
            <td align="left">b</td>
          </tr>
        </tabular>
      </table>
    </subsection>
  </section>
  <section refnum="2" xml:id="S2">
    <title><tag close=" ">2</tag>Second</title>
    <table frefnum="Table 2" refnum="2" xml:id="S2.T2a" labels="LABEL:two">
      <caption><tag close=": ">Table 2</tag>Table caption 2</caption>
      <toccaption><tag close=" ">2</tag>Table caption 2</toccaption>
      <tabular>
        <tr>
          <td align="left">c</td>
        </tr>
        <tr>
          <td align="left">d</td>
        </tr>
      </tabular>
    </table>
    <para xml:id="S2.p1">
      <p>Link to Table <ref labelref="LABEL:one"/>.</p>
    </para>
  </section>
</document>
```
HTML output:
```html
<div class="ltx_page_main">
<div class="ltx_page_content">
<section class="ltx_document">
<section id="S1" class="ltx_section">
<h1 class="ltx_title ltx_title_section">
<span class="ltx_tag ltx_tag_section">1 </span>First</h1>

<section id="S1.SS1" class="ltx_subsection">
<h1 class="ltx_title ltx_title_subsection">
<span class="ltx_tag ltx_tag_subsection">1.1 </span>Verbatim highlights from Table</h1>

<div id="S1.SS1.p1" class="ltx_para">
<p class="ltx_p">Link to Table <a href="#S2.T2a" title="Table 2 ‣ 2 Second" class="ltx_ref"><span class="ltx_text ltx_ref_tag">2</span></a>.</p>
</div>
<figure id="S2.T2" class="ltx_table">
<figcaption class="ltx_caption"><span class="ltx_tag ltx_tag_table">Table 2: </span>Table caption 2</figcaption>
<table class="ltx_tabular">
<tr class="ltx_tr">
<td class="ltx_td ltx_align_left">a</td>
</tr>
<tr class="ltx_tr">
<td class="ltx_td ltx_align_left">b</td>
</tr>
</table>
</figure>
</section>
</section>
<section id="S2" class="ltx_section">
<h1 class="ltx_title ltx_title_section">
<span class="ltx_tag ltx_tag_section">2 </span>Second</h1>

<figure id="S2.T2a" class="ltx_table">
<figcaption class="ltx_caption"><span class="ltx_tag ltx_tag_table">Table 2: </span>Table caption 2</figcaption>
<table class="ltx_tabular">
<tr class="ltx_tr">
<td class="ltx_td ltx_align_left">c</td>
</tr>
<tr class="ltx_tr">
<td class="ltx_td ltx_align_left">d</td>
</tr>
</table>
</figure>
<div id="S2.p1" class="ltx_para">
<p class="ltx_p">Link to Table <span class="ltx_ref ltx_ref_self">LABEL:one</span>.</p>
</div>
</section>
</section>
</div>
```

**Comment by brucemiller** [comment]
Version 0.8.0 didn't seem to handle multiple longtables correctly, but 0.8.1 does. It doesn't handle the oddly placed ```\label```s, however.  The current version available from github seems to work correctly.  (version 0.8.1 should be available under MacPorts)

**Comment by goska** [comment]
Thank you - I have updated to 0.8.1, which handles multiple long tables correctly (horizontal lines at the bottom of the tables are still missing after conversion (in the complex document I am working on)).

**Comment by dginev** [comment]
Does that mean we can close this issue?

**Comment by brucemiller** [comment]
On 10/25/2015 03:50 PM, goska wrote:
> Thank you - I have updated to 0.8.1, which handles multiple long tables
> correctly (horizontal lines at the bottom of the tables are still
> missing after conversion (in the complex document I am working on)).

You might want to open a separate issue regarding the horizontal lines.
(I don't think there's anything done more correctly in the current code)

**Comment by goska** [comment]
Posted a new issue concerning missing ```\hline```s. Thanks
