### ISSUE TITLE
hyperref's \hyperref command

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#677]
I encountered some problems converting \hyperref[]{} and tried to adapt the respective DefConstructor. Could you please check if the following changes might help?
```
diff --git a/lib/LaTeXML/Package/hyperref.sty.ltxml b/lib/LaTeXML/Package/hyperref.sty.ltxml
index 31a5cf3..5005a1c 100644
--- a/lib/LaTeXML/Package/hyperref.sty.ltxml
+++ b/lib/LaTeXML/Package/hyperref.sty.ltxml
@@ -163,10 +163,8 @@ DefConstructor('\hyperdef Semiverbatim Semiverbatim Semiverbatim',
   "<ltx:anchor xml:id='#id'>#3</ltx:anchor>",
   properties => sub { (id => CleanID(ToString($_[1]) . '.' . ToString($_[2]))); });

-DefConstructor('\hyperref Semiverbatim Semiverbatim Semiverbatim Semiverbatim',
-  "<ltx:ref href='#href'>#4</ltx:ref>",
-  properties => sub { (href => CleanURL(LookupValue('BASE_URL') . ToString($_[1])
-          . '#' . CleanID(ToString($_[2]) . '.' . ToString($_[3])))); });
+DefConstructor('\hyperref OptionalSemiverbatim {}', "<ltx:ref labelref='#label'>#2</ltx:ref>",
+  properties => sub { (label => CleanLabel($_[1])); });

 DefConstructor('\htmlref Semiverbatim  Semiverbatim',
   "<ltx:ref labelref='#label'>#1</ltx:ref>",
```

**Comment by brucemiller** [comment]
On 10/21/2015 08:42 AM, giovanni111 wrote:
> I encountered some problems converting \hyperref[]{} and tried to adapt
> the respective DefConstructor. Could you please check if the following
> changes might help?

I'll take a look; (you go from 4 arguments to 2 ?)
It would help if you had a TeX snippet showing
the use case and the problems it was causing.

**Comment by dginev** [comment]
Hm, looking at the [hyperref manual, page 15](http://mirror.jmu.edu/pub/CTAN/macros/latex/contrib/hyperref/doc/manual.pdf) it seems that it indeed ```\hyperref```` takes 4 arguments.

**Comment by giovanni111** [comment]
Your're right: some people also use \hyperref{}{}{}{}.
```
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\section{text}\label{id}
\hyperref[id]{reftext}
\section{text}
\hyperref{}{section}{2}{reftext}
\end{document}
```
Do you have an idea how to combine the two DefConstructions?

**Comment by dginev** [comment]
So to sum up, there are 2 argument signatures for ```\hyperref```. TeX-emulated polymorphism (ewww)

The big difference is that there are either 4 mandatory args, or 1 optional and 1 mandatory, and latexml only supports the 4-arg variant.

**Comment by brucemiller** [comment]
To combine, you'd use the standard TeX trick of a macro expanding into ```\ifnextchar[```.  I've done that, and merged in your 2-arg definition.  Thanks!!
