### ISSUE TITLE
Latexml fails on math in snugshade

### ISSUE THREAD

**Issue by neos21** [brucemiller/LaTeXML#683]
Whenever there are mathematics in the snugshade environment, the mathematics are erroneously rendered in white background.

Minimal working example:
```latex
\documentclass[12pt,a4paper]{book}

\usepackage{framed}
\usepackage{color}
\definecolor{shadecolor}{gray}{0.85}

\begin{document}
\begin{snugshade}
This is a paragraph that includes some math, e.g. the Pythagorean theorem: $a^2+b^2=c^2$.
\end{snugshade}
\end{document}
```

**Comment by brucemiller** [comment]
yes, needed to accommodate background as well as color when switching modes. Done now in git. Thanks for the report!
