### ISSUE TITLE
Index fails on Greek keywords (non-latin characters).

### ISSUE THREAD

**Issue by neos21** [brucemiller/LaTeXML#684]
I am trying to use the index feature of latexml, but it fails when the indexed keywords are non plain latin. In particular, consider the following file saved with UTF8 encoding that contains keywords to be indexed that contain greek characters:

File: index.tex
```latex
\documentclass[12pt,a4paper]{book}
\usepackage{makeidx}

\begin{document}
\chapter{Pythagoras}
This is the first chapter about Pythagoras \index{Pythagoras} or Πυθαγόρας in greek \index{Πυθαγόρας}.

\chapter{Euclid}
This is the second chapter about Euclid \index{Euclid} or Ευκλείδης in greek \index{Ευκλείδης}.

\printindex
\end{document}
```
Of course, I use the --inputencoding=utf8 at latexml to convert to xml.

The resulting html contains only three indexed keywords - the last, Ευκλείδης, does not appear. Moreover, the keyword Πυθαγόρας is erroneously listed as appearing in both chapters - it seems that latexml equates the two keywords in Greek.

In plain text the resulting html looks as follows:

>
>Chapter 1 Pythagoras
This is the first chapter about Pythagoras or Πυθαγόρας in greek .
>
>Chapter 2 Euclid
This is the second chapter about Euclid or Ευκλείδης in greek .
>
>Index
    Πυθαγόρας Chapter 1, Chapter 2
    Euclid Chapter 2
    Pythagoras Chapter 1

**Comment by brucemiller** [comment]
I assume you're using 0.8.1? It seems to run fine on the git version, but since 0.8.1 I switched to using Unicode::Collate to do the sorting, which should handle such things more correctly.  OTOH, since we're trying to create ID's out of pure greek, after stripping them, we end up with duplicate ID's!  Should fix that, but still it "works".

**Comment by neos21** [comment]
Thanks for the reply. 

Yes I am using 0.81 and I got as an index what I have posted. I am not sure what you mean with your reply. Did you manage to reproduce the problem wiyh the above minimal example? Has it been corrected now or I should wait? If I update/reinstall Latexml via github, I will get a correct index or not?

**Comment by dginev** [comment]
Hi @neos21 ! I just updated the online showcase to the latest revision of LaTeXML's git repository, and you can see how your example looks [by clicking here](latexml.mathweb.org/editor?tex=%5Cdocumentclass%5B12pt%2Ca4paper%5D%7Bbook%7D%0A%5Cusepackage%7Bmakeidx%7D%0A%0A%5Cbegin%7Bdocument%7D%0A%5Cchapter%7BPythagoras%7D%0AThis%20is%20the%20first%20chapter%20about%20Pythagoras%20%5Cindex%7BPythagoras%7D%20or%20%CE%A0%CF%85%CE%B8%CE%B1%CE%B3%CF%8C%CF%81%CE%B1%CF%82%20in%20greek%20%5Cindex%7B%CE%A0%CF%85%CE%B8%CE%B1%CE%B3%CF%8C%CF%81%CE%B1%CF%82%7D.%0A%0A%5Cchapter%7BEuclid%7D%0AThis%20is%20the%20second%20chapter%20about%20Euclid%20%5Cindex%7BEuclid%7D%20or%20%CE%95%CF%85%CE%BA%CE%BB%CE%B5%CE%AF%CE%B4%CE%B7%CF%82%20in%20greek%20%5Cindex%7B%CE%95%CF%85%CE%BA%CE%BB%CE%B5%CE%AF%CE%B4%CE%B7%CF%82%7D.%0A%0A%5Cprintindex%0A%5Cend%7Bdocument%7D).

Does that seem OK?

**Comment by dginev** [comment]
Ooops, the initial link was broken, see github for the updated one.

**Comment by neos21** [comment]
Yes, perfect! Thanks :)

**Comment by dginev** [comment]
Which reminds me I should style that showcase better, it's way too rigid... oh well. Can we close this issue then?

**Comment by brucemiller** [comment]
On 11/11/2015 11:30 AM, Deyan Ginev wrote:
> Which reminds me I should style that showcase better, it's way too
> rigid... oh well. Can we close this issue then?

not just yet: when index entries are completely non-ascii,
they generate an id that is just "idx." (missing the keyword),
which typically gives conflicts. I'd like to figure out a
way to give useful valid ids first. (suggestions welcome).

**Comment by dginev** [comment]
Suggestion: if ids are explicitly ASCII, then [unidecode](http://search.cpan.org/~sburke/Text-Unidecode-1.27/lib/Text/Unidecode.pm) the full entry.

I use unidecode in NNexus, which is ASII-only for now, works wonders. It helps tons for NLP where people just can't decide on consistently using e or é when writing Poincaré, among many other similar examples.

**Comment by brucemiller** [comment]
On 11/11/2015 12:35 PM, Deyan Ginev wrote:
> Suggestion: if ids are explicitly ASCII, then unidecode
> <http://search.cpan.org/%7Esburke/Text-Unidecode-1.27/lib/Text/Unidecode.pm>
> the full entry.

Id's end up in urls as fragment identifiers, so it may not be
strictly forbidden to have unicode, it's not yet(?) very safe.

> I use unidecode in NNexus, which is ASII-only for now, works wonders. It
> helps tons for NLP where people just can't decide on consistently using
> e or é when writing Poincaré, among many other similar examples.

Cool! That's the sorta thing I've thought: such a thing ought to exist!!
Have to check into the dependency implications. Maybe can use it optionally.
Last resort is convert to hex ! :>

**Comment by dginev** [comment]
Using hex for text may dangerously approach its "curse" meaning :>

**Comment by brucemiller** [comment]
Finally decided that Text::Unidecode was an easy, obvious decision; it works pretty cool!  Thanks for the report!
