### ISSUE TITLE
Latexmlpost fails with some complex math

### ISSUE THREAD

**Issue by neos21** [brucemiller/LaTeXML#685]
Trying to compile the following minimal example, latexmlpost fails:
```latex
\documentclass[12pt,a4paper]{book}
\usepackage{amssymb,amsmath}

\begin{document}
Latexmlpost fails on this math expression:
\begin{multline*}
|\sin x-\sin x_0|=2\left|\cos \left(\frac{x+x_0}{2} \right)\sin \left(\frac{x-x_0}{2} \right)\right| \leq 2\left|\mathrm{\sin} \left(\frac{x-x_0}{2} \right)\right| \leq |x-x_0| \\
\Rightarrow  -|x-x_0| \leq \sin x-\sin x_0 \leq |x-x_0|
\end{multline*}
\end{document}
```

The output of latexml is as follows:

>latexmlpost (LaTeXML version 0.8.1)
processing started Fri Nov  6 21:57:24 2015
(sin_fail.html post-processing...
(Scan sin_fail.html processing...
(CrossRef sin_fail.html processing...
(MathML::Presentation sin_fail.html processing...
(XSLT sin_fail.html processing...
(Writer sin_fail.html processing... 0.12 sec)
Postprocessing complete: No obvious problems
processing finished Fri Nov  6 21:57:25 2015
>
>H:\Documents\ebook>latexml --dest=sin_fail.xml sin_fail.tex
latexml (LaTeXML version 0.8.1)
processing started Fri Nov  6 21:57:27 2015
>
>(Digesting TeX sin_fail...
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/TeX.pool.ltxml...
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/eTeX.pool.ltxml... 0.01 sec)
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0
.18 sec)
(Processing content H:/Documents/ebook/sin_fail.tex...
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/LaTeX.pool.ltxml... 0.20 sec)
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/book.cls.ltxml... 0.02 sec)
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/amssymb.sty.ltxml...
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/amsfonts.sty.ltxml... 0.00 sec)
0.03 sec)
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/amsmath.sty.ltxml...
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/amsbsy.sty.ltxml... 0.00 sec)
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/amstext.sty.ltxml... 0.01 sec)
(Loading C:/epub/Strawberry/perl/site/lib\LaTeXML/Package/amsopn.sty.ltxml... 0.01 sec) 0.06 sec) 0.37 sec) 0.56 sec)
(Building...
(Loading compiled schema C:/epub/Strawberry/perl/site/lib\LaTeXML/resources/RelaxNG/LaTeXM
L.model... 0.02 sec)..... 0.27 sec)
(Rewriting... 0.01 sec)
(Math Parsing...1 formulae ...[1]
Math parsing succeeded:
   ltx:XMath: 1/1
   ltx:XMArg: 16/16
   ltx:XMWrap: 1/1
Symbols assumed as simple identifiers (with # of occurences):
   'x{italic}' (16)
 0.44 sec)
(Finalizing... 0.07 sec)
Conversion complete: No obvious problems.
processing finished Fri Nov  6 21:57:28 2015

The output of latexmlpost is then:

>latexmlpost (LaTeXML version 0.8.1)
processing started Fri Nov  6 21:57:31 2015
Error:malformed:document Document fails RelaxNG validation (LaTeXML)
        Validation reports: sin_fail.xml:0: validity error : IDREF attribute idref referen
ces an unknown ID "XM60"
>
>(sin_fail.html post-processing...
(Scan sin_fail.html processing...
(CrossRef sin_fail.html processing...
(MathML::Presentation sin_fail.html processing...
Fatal:perl:die Perl died
        Postprocessing LaTeXML::Post::MathML::Presentation sin_fail.html
        Can't call method "getAttribute" on an undefined value at C:/epub/Strawberry/perl/
site/bin/../lib/LaTeXML/Post.pm line 950.

**Comment by brucemiller** [comment]
Interestingly forgot the case where we're pruning XMDuals that may have an id and be referred to.  Is fixed now.  Thanks for the report!
