### ISSUE TITLE
kill switch for latexmls

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#686]
In many debugging situations it would be good if we had a "kill message" for ```latexmls``` that I could just send the server instead of having to wait for it to terminate by itself. I am thinking of just calling 
```
latexmlc --killserver
```
and that sends the kill message to ```latexmls```.

**Comment by dginev** [comment]
I am using something like that for production in Authorea, just send a job to it with a one second expire and it will auto-reboot. 

```
latexmlc --expire=1 --port=...  'literal:restarting'
```

A new option is overkill in my opinion. You could always ```killall latexmls``` instead.

**Comment by kohlhase** [comment]
> You could always killall latexmls instead.

Actually, in the setting in MathHub, where we have latexmls (and latexmlc for this matter) running in a docker container and using the ```lmh``` utility to send commands into the docker this is quite inconvenient. In particular, we would have to open a docker shell in the right docker and then do a ```pkill ???``` (```killall``` is not installed on the docker; and you are never quite sure whether you have to do a ```pkill perl```... ). This is why I would like to have the kill switch. 

But I guess in this situation we will just use your trick and integrate it into ```lmh```. Just thought that other people might run into the same problem.
