### ISSUE TITLE
\Big clashes with \mathop

### ISSUE THREAD

**Issue by neos21** [brucemiller/LaTeXML#688]
Minimal example:
        
        \documentclass[12pt,a4paper]{book}
        \usepackage{amssymb,amsmath}
        \renewcommand{\diff}{\ensuremath{\mathop{d}\!\!\!}} 
        
        \begin{document}
        Second BIG is ignored:
        \begin{equation}
        a=\int_0^1\log\Big(\frac{1}{1-t}\Big) \diff t,\\
        \end{equation}
        \end{document}

In the above, I have defined \diff using \mathop to correctly render the differential operator, i.e., dt (off-topic: let me know if you have a more appropriate definition for latexml). The result is that the second \Big is ignored and thus the left parenthesis is rendered as big, but the right one is rendered as a normal-size parenthesis.

The same happens with the alternative definition of

        \renewcommand{\diff}{\ensuremath{\operatorname{d}\!\!\!}}

The second one produces an upright d (which is supposedly  more appropriate as a differential operator than the italic d produced by the first operator).

The problem is resolved if I use \left( and \right) instead of \Big (which by the way is the correct way), however it is still a bug to my understanding.

Last, I am using the version 0.81 downloaded from Git two weeks ago.

**Comment by brucemiller** [comment]
Yep, a bug; basically a one-off bug applying some font tweaking to the token in front of the one that needed it, which erased the size info from the close parenthesis.  Should work correctly now; Thanks for the report.
