### ISSUE TITLE
html code of equation number tag

### ISSUE THREAD

**Issue by neos21** [brucemiller/LaTeXML#689]
This is a bug that to my understanding came up in the developer's copy in git when I upgraded about two weeks ago. Before, I was using the cpan version, and there was not such problem. It seems that the formatting of the equation number is broken.

In particular, the current latexml produces
 
        
        <div id="p2" class="ltx_para">
        <table id="Ch0.E1" class="ltx_equation ltx_eqn_table">

        <tr class="ltx_equation ltx_eqn_row ltx_align_baseline">
        <td class="ltx_eqn_cell ltx_eqn_center_padleft"></td>
        <td class="ltx_eqn_cell ltx_align_center"><math id="Ch0.E1.m1" class="ltx_Math" alttext="E=mc^{2}" display="block"><mrow><mi>E</mi><mo>=</mo><mrow><mi>m</mi><mo>⁢</mo><msup><mi>c</mi><mn>2</mn></msup></mrow></mrow></math></td>
        <td class="ltx_eqn_cell ltx_eqn_center_padright"></td>
        <td rowspan="1" class="ltx_eqn_cell ltx_eqn_eqno ltx_align_middle ltx_align_right"><span class="ltx_tag ltx_tag_equation
              ltx_eqn_eqno ltx_align_middle
              ltx_align_right">(0.1)</span></td>
        </tr>
        </table>
        
The last span class that includes ltx_tag, ltx_tag_equation,  ltx_eqn_eqno, ltx_align_middle and ltx_align_right seems to be broken, as, e.g.,  ltx_align_middle and ltx_align_right appear to be contradictory and the class string is broken in multiple lines. Before, the cpan 0.81 version seemed to produce html that has only ltx_tag and ltx_tag_equation in the span class.

Although in a simple text this is barely noticeable, the new span class places the equation numbers not properly aligned, i.e., the numbers extended beyond the right margin where text is justified. This is clear if you compile the following minimal example:

.tex

        \documentclass[12pt,a4paper]{book}
        \usepackage{amssymb,amsmath}
        \renewcommand{\diff}{\ensuremath{\mathop{d}\!\!\!}} 
        
        \begin{document}
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vulputate libero auctor metus vulputate, vel rutrum diam accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus rutrum posuere varius. Vestibulum non neque eget nibh blandit consectetur. Donec placerat turpis in eleifend cursus. Aliquam molestie velit sit amet risus tristique ullamcorper. Maecenas vulputate dapibus dolor at auctor. 

        \begin{equation}
        E= mc^2
        \end{equation}

        Proin mollis felis eu nisi maximus interdum. Nunc pellentesque nunc in lacus hendrerit, ut tristique est ullamcorper. Quisque id massa id est venenatis imperdiet sed nec risus. Phasellus sed ultricies risus. Donec laoreet mi et elit ultrices tempus. Donec ante lorem, faucibus nec viverra vel, pellentesque eu tellus. Quisque non rutrum diam, et pharetra sem. Nam quis suscipit velit, in dapibus nibh. Nulla dignissim scelerisque massa sed laoreet. Nunc malesuada facilisis ipsum, quis consectetur sapien semper et. Aenean vestibulum lacus et lobortis semper.
        \end{document}

and a simple css

        div { text-align: justify;}

**Comment by brucemiller** [comment]
Ooh, that's silly: I'd duplicated a couple of classes on the ```span``` containing the equation number as well as the```td``` containing it; they seem to negate each other.  Should work better now; thanks for the report!
