### ISSUE TITLE
Timeout and fatal reporting are broken again

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#695]
I was looking at the new CorTeX errors and realized the timeout messages disappeared and are now hidden under "die" again. The number of fatals is also off again. I used the official master repo from GitHub.

Maybe this is a regression you can quickly fix, as you worked on these bits most recently? I am just unsure why it regressed.

Here is a minimal example to reproduce:
```bash
$ latexmlc --timeout=1 --whatsin=fragment 'literal:\def\foo{\foo}\foo'

(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.13 sec)

latexmlc (LaTeXML version 0.8.1; revision 51540ed)
processing started Thu Dec  3 19:49:26 2015

(Digesting TeX Anonymous String...
(Processing content Literal String \end{docum...
(Processing content Literal String \def\foo{\...
(Processing content Literal String \documentc...
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.16 sec)
(Loading /home/dreamweaver/perl5/lib/perl5/LaTeXML/Package/article.cls.ltxml... 0.02 sec) 0.19 sec)
Fatal:perl:die Perl died
	at Literal String \def\foo{\; line 1 col 19
	Fatal:timeout:timedout Conversion timed out
		at Literal String \def\foo{\; line 1 col 19
		ALRM
		In Core::Gullet[@0x4d727b0] at Literal String \def\foo{\; line 1 col 19
		 <= Core::Stomach[@0x4d7d6b8] <= Core::Definition::Constructor[\begin{... <= Core::Stomach[@0x4d7d6b8]
	1 fatal error
	In Core::Gullet[@0x4d727b0] at Literal String \def\foo{\; line 1 col 19
	 <= Core::Stomach[@0x4d7d6b8] <= Core::Definition::Constructor[\begin{... <= Core::Stomach[@0x4d7d6b8]
2 fatal errors


Conversion complete: 3 fatal errors.
Status:conversion:3
```

**Comment by brucemiller** [comment]
OK, I *think* I've fixed this --- will it *stay* fixed???

There was 2 issues: it seems that you can't use local to clear ```$SIG{__DIE__}``` when handling timeouts, terms,,, it still sees the previously bound handler!?! (I'm getting rather annoyed with Perl)  So, we do it without ```local``` and hope that the calling structure will set up the handlers again, if needed (in a server context?).

The second problem was your over-caution in LaTeXML.pm, where you're invoking noteStatus; Generally those errors should already have been counted, so they get counted twice. But you're worried about errors leaking through that don't get handled by ```LaTeXML::Common::Error```.  Can understand the caution, and in fact, I've only commented out those noteStatus where conversion and post processing are done, but not (yet) the one creating the initial latexml object. You might want to take a look at that. (and there's a rather big set of bookkeeping that's almost the same after each of those 3 evals that would be easier to "get right" if they were abstracted into a sub).

Hopefully this gets us forward? (I'll pretend this works).
