### ISSUE TITLE
numbering of chemical pictures

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#698]
Hi,

Bruce has told me that there is already a request to support of mhchem. That however, is not what I need. 
```tex
\newcommand*{\mevalonate}{%
  \changeunitlength{0.01mm}%
  \mbox{\begin{XyMcompd}(0,1200)(1500,0){Mevalonat}{}
      \includegraphics[width=3000\unitlength]{bkchem/mevalonate}
%      \pentamethylenei{}{%
%        {1}W==HO;{3}Sb==\null;{3}Sa==OH;{1}D==\kern-.4exO;{5}W==OH}
    \end{XyMcompd}%
  }%
}
\newcommand*{\mevalonatenocmpd}{%
  \changeunitlength{0.01mm}%
  \mbox{\begin{picture}(0,1200)(1500,0)%
      \put(-220,-100){(\cref{Mevalonat})}{}%
          \includegraphics[width=3000\unitlength]{bkchem/mevalonate}
          \end{picture}%
  }%
}
```
\begin{XyMcompd}(xsize,ysize)(x-offset,y-offset){name}
...
\end{XyMcomp}

provides \cref{name} as the number of the structure "name" that can be used anywhere in the text to reference that structure. A command like that what I need. 
I know that reference will only work with latex in the second latex-run. But other label/reference pairs are working in latexml which has only one run.  

The question is: Can anybody construct a environment that could be used to provide that \cref macro that will work not only in latex, but in latexml as well?
Then one could get rid of XyMTeX and it sophisticated drawings (which also generate many warnings in recent Komascript).

Bernhard

**Comment by bernhard-kleine** [comment]
What about support for the chemnum package?

**Comment by dginev** [comment]
You mean [chemnum.sty](https://www.ctan.org/tex-archive/macros/latex/contrib/chemnum?lang=en) ? It's a reasonable request, the only question is when it will arrive. We welcome external contributions too!

**Comment by bernhard-kleine** [comment]
actually I was thinking about something much smaller. I had a look Chemnum.sty, it is in a way complete and takes care of all variations, but most of it is not necessary.

**Comment by bernhard-kleine** [comment]
Would this be supported in latexml?
```tex
\newcounter{compound}
\newcommand*\defcompound[1]{\refstepcounter{compound}\label{cpd:#1}} 
\newcommand*\refcompound[1]{\textbf{\ref{cpd:#1}}}. 
```

This defines \defcompound{bla} to set a label and \refcompound{bla} to reference it. This is from Clemens Niederberger, author of chemnum.sty.

**Comment by brucemiller** [comment]
That'd be part of the solution, at least internally, and should work as far as it goes. But you'll need to put the ```\defcompound``` calls inside of something that accepts and records the label and displays the reference number.  Things like sections, figures, etc.  Provided you wanted to display the compound, ```\newfloat``` would probably be a perfect solution, for example.

**Comment by bernhard-kleine** [comment]
So far I have experienced with
```tex
\documentclass[12pt,a4paper]{book}
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
\setlength{\unitlength}{0.01mm}
\usepackage{graphicx}
\newcounter{compound}%
\DeclareRobustCommand*{\defcmpd}[1]{\refstepcounter{compound}\label{cpd:#1}}
\newcommand*{\mevalonate}{%
	\defcmpd{mevalonate}
	\mbox{\begin{picture}(0,1200)(1500,0)
		\put(0,1200){\textbf{Mevalonat}\protect\refcmpd{mevalonate}}
		\includegraphics[width=3000\unitlength]{bkchem/mevalonate}
		\end{picture}%
	}%
}

\newcommand*{\mevalonatenocmpd}{%
%	\changeunitlength{0.01mm}%
	\mbox{\begin{picture}(0,1200)(1500,0)%
		\put(-220,-100){(\refcmpd{mevalonate})}{}%
		\includegraphics[width=3000\unitlength]{bkchem/mevalonate}
		\end{picture}%
	}%
}

\begin{document}
\DeclareRobustCommand*{\refcmpd}[1]{\textbf{\ref{cpd:#1}}}. 

\mevalonate

\mevalonatenocmpd

\end{document}
```
That however does not work the images are there but the numbers are not.
![screennumbering_pdf](https://cloud.githubusercontent.com/assets/9216487/11782673/aa000694-a272-11e5-9e42-7de30b3003ba.png) ![screennumbering_html](https://cloud.githubusercontent.com/assets/9216487/11782665/962ccd32-a272-11e5-8ba3-a6467e283eee.png)

**Comment by brucemiller** [comment]
That's why I suggested using ```\newfloat```.

**Comment by bernhard-kleine** [comment]
Do you want to say that \newcounter outside a float is not yet supported in latexml? 
References to labels outside of figure tables are equally beyond latexml?

**Comment by brucemiller** [comment]
No, not at all. I'm saying that ```refstepcounter``` and ```\label``` look to the nearest containing object that can accept reference numbers and labels, be it ```\section```, figure, floats, and such things.  You can use label whereever you want, but it may not refer to the thing you intended to refer to.

**Comment by bernhard-kleine** [comment]
This still does not work:
```tex
\documentclass[12pt,a4paper]{book}
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
\setlength{\unitlength}{0.01mm}
\usepackage{graphicx,float,hyperref,calc}
\makeatletter
\newfloat{Mycomp}{hbtp}{log}[chapter] % programmed figures
\floatname{Mycomp}{}
\let\ftype@Mycomp\ftype@figure % figure and factsheet are in same float class (ftype)
\let\theHMycomp\theMycomp % make safe for hyperref
\makeatother
\newcounter{compound}%
\DeclareRobustCommand*{\defcmpd}[1]{\refstepcounter{compound}\label{cpd:#1}}
\newcommand*{\mevalonate}{%
	\begin{Mycomp}
	\defcmpd{mevalonate}
	\mbox{\begin{picture}(0,1200)(1500,0)
		\put(0,1200){\textbf{Mevalonat}\protect\refcmpd{mevalonate}}
		\includegraphics[width=3000\unitlength]{testsvg}
		\end{picture}%
	}%
	\end{Mycomp}
}
\newcommand*{\mevalonatep}{%
	\begin{Mycomp}
		\defcmpd{mevalonatep}
		{\begin{picture}(0,1200)(1500,0)
			\put(0,1200){\textbf{Mevalonatp}\protect\refcmpd{mevalonatep}}
			\includegraphics[width=3000\unitlength]{testsvg}
			\end{picture}%
		}%
	\end{Mycomp}
}

\newcommand*{\mevalonatenocmpd}{%
%	\changeunitlength{0.01mm}%
	{\begin{picture}(0,1200)(1500,0)%
		\put(-220,-100){(\refcmpd{mevalonate})}{}%
		\includegraphics[width=3000\unitlength]{testsvg}
		\end{picture}%
	}%
}

\begin{document}
\DeclareRobustCommand*{\refcmpd}[1]{\textbf{\ref{cpd:#1}}}. 

\mevalonate \quad\quad \mevalonatenocmpd

\mevalonatep

\end{document}
```
What is wrong? The numbering in pdflatex seems ok. The svgtest is included as zip. 
[testsvg.zip](https://github.com/brucemiller/LaTeXML/files/62251/testsvg.zip)
Sorry the last time it was named zip but was 7z-format.

**Comment by bernhard-kleine** [comment]
closing this was not intended.

**Comment by brucemiller** [comment]
What I had in mind was to let the float do the work for you and have it use the compound counter.
Something like
```\newfloat{compound}{hbpt}{compound}```
and then
```\begin{compound}\label{cpd:mevalonate}...```

**Comment by bernhard-kleine** [comment]
I got steps further: However while everything is well displayed in pdf the html using the firefox indicator tells me that the svg is there and the caption as well but they are obviously so small that one can not see them. 

```tex
\documentclass[12pt,a4paper]{book}
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
\usepackage{graphicx,float,hyperref,calc,caption}
\newcounter{compound}%
\newfloat{Mycomp}{hbtp}{cmp}[chapter] % programmed figures
\floatname{Mycomp}{}
\makeatletter\let\ftype@Mycomp\ftype@figure % figure and compound are in same float class (ftype)
\let\theHMycomp\theMycomp % make safe for hyperref
\setlength{\unitlength}{0.1mm}
\newenvironment{Cmpd}[5]%compond
	{%begindef
		\setlength{\unitlength}{0.1mm}%
		\refstepcounter{compound}\caption*{\hspace*{2em}}\label{cpd:#1} %
			\begin{center}
				\begin{picture}(#2,#3)(#4,#5)
					\put(0,#3){\textbf{#1}\ \refcmpd{#1}}
					\put(0,0){\includegraphics[width=#4\unitlength]{#1}}
	}%begindef
	{\end{picture}\end{center}%enddef
}%enddef
\makeatother
\begin{document}
	\DeclareRobustCommand*{\refcmpd}[1]{\textbf{\ref{cpd:#1}}}. 
\begin{Mycomp}[!hbt]
		\centering
		\begin{Cmpd}{testsvg}%#1
				{0}{300}{600}{3}
		\end{Cmpd}
\end{Mycomp}

der Text sucht \refcmpd{testsvg} in irgendwo.
\end{document}
```
There is already an issue scaling of svg.

By the way, the \caption* command in the caption package which in pdflatex blocks the number of the caption to show up, is not supported. I can rise a separatre issue, if you agree.

**Comment by brucemiller** [comment]
I'd rather not sort out that complex code; why don't you try what I suggested?

**Comment by bernhard-kleine** [comment]
This has been solved. Sample code will be in an other issue.
