### ISSUE TITLE
binding for stmaryrd.sty

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#700]
I have been looking through Deyan's new run over the arXiv corpus (see http://cortex.mathweb.org/corpus/arXMLiv/tex_to_html/error/missing_file), and one of the packages used often is ```stmaryrd.sty```, which only introduces some new symbols. This should be relatively easy to do.

**Comment by dginev** [comment]
Google suggests @kpj has already worked on this one: https://github.com/kpj/LaTeXML_Bindings_WIP/blob/master/bindings/stmaryrd.sty.ltxml

**Comment by kohlhase** [comment]
What excellent news. 

BTW, if you look at your list of "missing files" there are quite a few interesting candidates (including soul.sty.ltxml, which Bruce just adeed to the distribution).

**Comment by brucemiller** [comment]
github also suggests that it has been worked on https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/stmaryrd.sty.ltxml.

**Comment by dginev** [comment]
Oops! Thanks for pointing that out. We can move the arXiv discussion to the mailing list if there if @kohlhase wants to offer more suggestions.

**Comment by brucemiller** [comment]
No problem. There's also a wiki list previously copied from CorTeX https://github.com/brucemiller/LaTeXML/wiki/Porting-LaTeX-packages-for-LaTeXML where I've been marking as I go.  The main things that remain are various drawing packages (xy, psstuff) and algorithm packages; the rest have minimal usage.

**Comment by kohlhase** [comment]
I am happy to look at the wiki.
