### ISSUE TITLE
\picture environment does not show included graphics

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#702]
I am somewhat surprised to have in includedgraphics rendered invisible
The testcase:
```tex
\documentclass[12pt,a4paper]{book}
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
\usepackage{graphicx,float,hyperref,calc,caption}
\setlength{\unitlength}{0.1mm}
\begin{document}
\begin{figure}
	\includegraphics[width=6cm]{testsvg}
\end{figure}
\begin{figure}[!hbt]
	\centering
	\begin{picture}(600,300)(600,3)
	\put(0,0){\includegraphics[width=600\unitlength]{testsvg}}%#1
	\end{picture}
\end{figure}

\end{document}
```
The pdf versus htlm are added as screenshots, the files are in the zip-file
![screenpictureenvironment_pdf](https://cloud.githubusercontent.com/assets/9216487/11890973/53c10874-a55a-11e5-94e5-fdc3bc5236a3.png)
![screenpictureenvironment_html](https://cloud.githubusercontent.com/assets/9216487/11890974/53c451b4-a55a-11e5-8d8c-a580e86629f4.png)
[testsvg.zip](https://github.com/brucemiller/LaTeXML/files/66274/testsvg.zip)

**Comment by brucemiller** [comment]
Ah, another tricky bit with size of foreignObject; should work now.

**Comment by bernhard-kleine** [comment]
I will not be able to check for several days since proof reading will take all my time. Maybe i will only will do this after christmas. Sorry.

**Comment by bernhard-kleine** [comment]
Am 18.12.2015 um 17:51 schrieb bruce miller:
> Ah, another tricky bit with size of foreignObject; should work now.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brucemiller/LaTeXML/issues/702#issuecomment-165835760>.
> 
I downloaded the zip file of today, it did not work.
