### ISSUE TITLE
\fbox-ed includegraphics produce errors in tikz nodes

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#703]
While the following code in pdflatex works flawlessly, it gives errors in latexml. The obvious reason seems to be a float in a float. As I had the chemical numbering using a float working (remove the "%" from the line 

``` tex
% \mevalonate    \mevalonatePP
```

and add comments to the figure, it still becomes gets the numbers correcty when place in a figure environment, but the refs are wrong, since they point not to the Mycomp environment but to the figure environment. 

``` tex
\documentclass[12pt,a4paper]{book}
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
\usepackage{graphicx,float,hyperref,calc,caption,tikz}
\newfloat{Mycomp}{hbtp}{cmp}[chapter] % programmed strucures
\floatname{Mycomp}{}
\makeatletter\let\ftype@Mycomp\ftype@figure % figure and compound are the same type
\setlength{\unitlength}{0.1mm}
%in analogy to chemist.sty from the XyMTex package by Clemens Niederberger
\newcounter{compound}
\newcommand*\compoundformat[1]{\textbf{\large#1}}
\newcommand*\compound{\leavevmode\refstepcounter{compound}\compoundformat{\thecompound}}
\newcommand*\nocompound{\refstepcounter{compound}}
\newcommand*\compoundlabel[1]{\compound\label{#1}}
\newcommand*\nocompoundlabel[1]{\nocompound\label{#1}}
\newcommand*\compoundref[1]{\compoundformat{\ref{#1}}}
\DeclareRobustCommand{\mevalonate}{%
  \begin{Mycomp}[H]
    \fbox{
      \parbox[c]{450\unitlength}{%
    \centering\compoundlabel{mevalonate}
    \includegraphics[width=400\unitlength]{bkchem/mevalonate}
      }%
    }
  \end{Mycomp}
}
\DeclareRobustCommand{\mevalonatePP}{%
    \begin{Mycomp}[H]
        \fbox{
        \parbox[c]{450\unitlength}{%
            \centering\compoundlabel{mevalonatePP}
            \includegraphics[width=400\unitlength]{bkchem/mevalonatePP}
            }%
        }
    \end{Mycomp}
}
\DeclareRobustCommand{\mevalonateP}{%
  \begin{Mycomp}[H]
    \fbox{
      \parbox[c]{450\unitlength}{%
     \centering\compoundlabel{mevalonateP}
     \includegraphics[width=400\unitlength]{bkchem/mevalonate}
      }
    }
  \end{Mycomp}
}
\begin{document}
%   \mevalonate     \mevalonatePP
In the text you will refer to the structures by \compoundref{mevalonatePP} and \compoundref{mevalonate}.

  \begin{figure*}[hbt]
    \tikzstyle{mevPP}= [rectangle,minimum size=2.4cm,text width=4.8cm,text centered,inner sep=.05cm,fill=black!12]
   \begin{tikzpicture}
    \node [mevPP]   (mev)          at (0,8) {\mevalonate};      %defines a structure at node mev
    \node [mevPP]   (mevP)        at (8,8) {\mevalonatePP};    %dito                         at node mevP
   \end{tikzpicture}
    \caption{Bildung von Isopentenyl"~ und Dimethylallyl"=Pyrophosphat}
    \label{fig:isopentenylpp}
  \end{figure*}
\end{document}
```

**Comment by bernhard-kleine** [comment]
I wonder when this will be acknowledged and dealt with

**Comment by dginev** [comment]
Hi @bernhard-kleine , just wanted to let you know we've seen the issue (I am sure Bruce is following as well), and we'll try to issue a fix as time permits. Thanks for the patience and the report!

**Comment by brucemiller** [comment]
Actually, you can put a float inside a float, to some extent, as long as you're using one of the subfig type of packages.  But a float inside of a tikz picture doesn't make much sense.  I'm not really all that clear what it is you're trying to accomplish, and your example has a lot of complexity that gets in the way of understanding.  If you're just wanting to add a bit of label to a part of the figure and refer to it somewhere else, you'll probably be best by doing it a big more manually: place the desired text where you want, and have a macro expand into a copy of that text when you want to refer to it.  It's probably the case that LaTeXML can't automatically do what you're trying to do, without a bit of customization.

**Comment by dginev** [comment]
I updated the title of the issue to reflect the exact technical issue.

Indeed, LaTeXML's tikz support may not yet be sophisticated enough t properly embed an \fbox-ed includegraphics sub-image. I wouldn't call that a "subfloat" btw, since it doesn't, well, float :>

**Comment by dginev** [comment]
Btw, let me take a moment to celebrate the fact that such advanced acrobatics are not only considered viable, but are  matter-of-factly expected by LaTeXML users. That speaks volumes of how far LaTeXML has come in its LaTeX emulation!

**Comment by dginev** [comment]
There is still an error here, namely:
```
Error:malformed:ltx:float <ltx:float> isn't allowed in <ltx:inline-block>
```

I am attaching a screenshot of the results produced by pdflatex (left) and the current master of latexml (right).

![fboxed](https://user-images.githubusercontent.com/348975/39019780-2469bf24-4433-11e8-8dac-17f2c138d61f.png)

I think what remains to be solved is adjusting the schema to allow for this type of content, as well as to enhance the label/reference logic.

**Comment by dginev** [comment]
Moving to next milestone (0.8.4), so that we roll out 0.8.3 asap. Apologies this issue didn't make the cut.

**Comment by brucemiller** [comment]
The core error for this issue was fixed long ago; what remained was a problem with the numbers in the ```\ref``` were off.  It seems to me that you've worked with the compound numbering to skirt LaTeX's mechanisms, and go just under LaTeXML's radar, that there's no effective handle for LaTeXML to reference the "compound": within a figure or float, you need some sort of caption to provide that handle.  A simple fix would be to replace the definition of ```\compoundlabel``` with
```
\newcommand*\compoundlabel[1]{\caption{\compound\label{#1}}}
```
That gets on the right track, although you'll likely want to play with formatting, ```\thecompound```, etc.
Hope that helps; thanks for the report.
