### ISSUE TITLE
Using the "framed" package

### ISSUE THREAD

**Issue by prandoni** [brucemiller/LaTeXML#704]
When using the "framed" package, for which I believe a binding is provided, latexml crashes with the message

    Fatal:perl:die Perl died
        at /home/pp/test.tex; line 10 col 14
        Can't locate object method "toAttribute" via package "LaTeXML::Common::Color::rgb" at /usr/local/share/perl/5.18.2/LaTeXML/Core/Document.pm line 1166.
        In Core::Document[@0x4f42e00] at /home/pp/test.tex; line 10 col 14
         <= Core::Definition::Constructor[\begin{... <= Whatsit[\begin{framed},Core::List[Box... <= Core::Document[@0x4f42e00] <= Core::Definition::Constructor[\begin{... <= Whatsit[\begin{document},Core::List[C... <= Core::Document[@0x4f42e00]

Minimal example:

    \documentclass{article}
    \usepackage{framed}

    \begin{document}
    Testing the framed binding
    \begin{framed}
        test
    \end{framed}
    \end{document}

Any hint would be much appreciated!

Also, I put this here because convention demands that posts go directly to the issue, but it was meant to be my opening: Thank you so much for this wonderful application! It is nothing short of spectacular especially when compared to the alternatives!

**Comment by brucemiller** [comment]
Hmm... perl seems not only to allow, but encourage, broken code!  Thanks for the report, should be fixed now.

**Comment by prandoni** [comment]
thanks!!
