### ISSUE TITLE
Should LaTeXML pretend to be pdftex, or xelatex?

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#709]
Here is an interesting preamble (originally from Pandoc's latex writer) for detecting the latex processor. LaTeXML currently throws errors on it, chiefly because of missing packages (ifxetex and ifluatex), but it's an interesting question what the desired result should be:

```latex
\documentclass[]{article}
 \usepackage{ifxetex,ifluatex}
 \ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
   \def\who{pdftex}
 \else % if luatex or xelatex
   \ifxetex
     \def\who{xelatex}
   \else
     \def\who{luatex}
   \fi
 \fi

\begin{document}
  \who
\end{document}
```

Running with pdflatex returns "pdftex", running with xelatex returns "xelatex". Running with latexml returns luatex, and a bunch of erros, which is understandable.

Who is latexml ?

**Comment by dginev** [comment]
Maybe what we need are two trivial packages, defining ifxelatex and ifluatex to false, and letting latexml pretend to be pdftex? Should be super simple to add. The ifnum conditional actually looks a bit advanced, wondering if we can handle it if the macros were defined.

**Comment by brucemiller** [comment]
On 01/21/2016 04:09 PM, Deyan Ginev wrote:
> Who is latexml ?

Interesting question that I've wondered about.
To the extent that it can (and it should) emulate
the things that pdflatex does (hyperrefs, metadata,...)
it could pretend to be pdflatex.

To the extent that it can deal with unicode (which it should)
and some of the exotic xetex packages (which it likely can't yet),
it ought to pretend to be xelatex.

luatex is more iffy; at some level (besides yet more exotic
packages) it will be expected to do something sensible
with snippets of lua code.  That's not in the near term! :>

**Comment by brucemiller** [comment]
Incidentally, there is already an ifxetex.sty.ltxml (and it says we're *not* xetex).  Curiously, on my system there's no ifluatex.sty (but it's centos, here).

**Comment by dginev** [comment]
Well it is on CTAN: https://www.ctan.org/pkg/ifluatex?lang=en

So do you think you could clone the ifxetex binding and just switch it to luatex? Saying we're neither of those, and pretending to be pdflatex sounds great to me.

**Comment by brucemiller** [comment]
OK, easy enough. Done!

**Comment by dginev** [comment]
Thanks!

**Comment by laughedelic** [comment]
> @brucemiller: To the extent that it can deal with unicode (which it should) and some of the exotic xetex packages (which it likely can't yet), it ought to pretend to be xelatex.

> @dginev: Saying we're neither of those, and pretending to be pdflatex sounds great to me.

I am not sure what this means regarding Unicode support. Or is it just about the `\ifxetex` checks?

**Comment by dginev** [comment]
Hey @laughedelic , the conversation in  this issue has been entirely about the conditional checks. LaTeXML is unicode native and unicode input should always succeed under it, even in cases where pdflatex traditionally has issues without inputenc and friends.

**Comment by laughedelic** [comment]
@dginev thanks for clarification! 

> LaTeXML is unicode native and unicode input should always succeed under it

This is great to know. I was kind of concerned about it in some [other context](https://www.authorea.com/users/110613/articles/142632) (~~misguided by support~~), but not anymore 👌
