### ISSUE TITLE
\protected@write in LaTeXML.pool.ltxml

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#716]
In ```LaTeXML.pool.ltxml``` I see 
```
#**********************************************************************
# Since \write does nothing... ?
DefMacro('\protected@write{}{}{}', '');
#**********************************************************************
```
and I am confused, since ```\write``` apparently writes to a file.

**Comment by brucemiller** [comment]
On 02/12/2016 11:02 AM, Michael Kohlhase wrote:
> In |LaTeXML.pool.ltxml| I see
>
> |#**********************************************************************
> # Since \write does nothing... ? DefMacro('\protected@write{}{}{}', '');
> #********************************************************************** |
>
> and I am confused, since |\write| apparently writes to a file.

Ugh! When that comment was written, LaTeXML's \write didn't do anything!
Now it does...  Are you finding \protected@write to be needed?

**Comment by kohlhase** [comment]
not currently. But we are moving much closer to being able to reading ***.sty natively, it would be good to have it, since it does occur in many packages.

**Comment by brucemiller** [comment]
On 02/12/2016 11:11 AM, Michael Kohlhase wrote:
> not currently. But we are moving much closer to being able to reading
> ***.sty natively, it would be good to have it, since it does occur in
> many packages.

It'd be nice if someone had the time to characterize (better
yet code) exactly what "protected" means here and what needs
to be done to the argument before "writing" it.

**Comment by kohlhase** [comment]
I find that http://tex.stackexchange.com/questions/115932/on-the-basics-of-writing-to-reading-from-auxiliary-files-aux-toc-etc has a good introduction. If I understand correctly, ```\protect```ion is not an issue in LaTeXML, so I guess a simple 
```
\DefMacro('\protected@write {}{}{}','\write{#1}{#1{#3}}');
``` 
would be a good start.

**Comment by kohlhase** [comment]
This is essentially what ```latex.ltx``` does (plus some protection handling).

**Comment by dginev** [comment]
Cross-referencing #606 and the stopgap [securio plugin](https://github.com/dginev/LaTeXML-Plugin-secureio) here.

**Comment by brucemiller** [comment]
I think I've got protected write working correctly now. Thanks for the request!
