### ISSUE TITLE
Request for LaTeXML::Util::Test Documentation 

### ISSUE THREAD

**Issue by angerhang** [brucemiller/LaTeXML#722]
Currently we are setting up the `LaTeXML-Plugin-sTeX` test cases. 

It would be nice to have this documented so that it is easier to know what exactly is `make test` doing.

**Comment by dginev** [comment]
Btw, @angerhang , a bit of a pragmatic reply from me - the best way to get the documentation added is to start adding it yourself and ask us questions about bits that seem unclear in this issue.

Then you can make a PR and Bruce should be extremely happy to merge it in :+1:

**Comment by dginev** [comment]
Closing with worksforme, but we'll keep adding docs any chance we get!
