### ISSUE TITLE
chain of equalities

### ISSUE THREAD

**Issue by physikerwelt** [brucemiller/LaTeXML#724]
LaTeXML curretnly encodes
$a=b=c$
as @(and,=(a,b),=(b,c)), more technically latexml.mathweb.org outputs
```
      <apply id="p1.1.m1.1.6.cmml" xref="p1.1.m1.1.6">
        <and id="p1.1.m1.1.6a.cmml" xref="p1.1.m1.1.6"/>
        <apply id="p1.1.m1.1.6b.cmml" xref="p1.1.m1.1.6">
          <eq id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2"/>
          <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑎</ci>
          <ci id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">𝑏</ci>
        </apply>
        <apply id="p1.1.m1.1.6c.cmml" xref="p1.1.m1.1.6">
          <eq id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4"/>
          <share href="#p1.1.m1.1.3.cmml" id="p1.1.m1.1.6d.cmml" xref="p1.1.m1.1.6"/>
          <ci id="p1.1.m1.1.5.cmml" xref="p1.1.m1.1.5">𝑐</ci>
        </apply>
      </apply>
```
According to https://www.w3.org/TR/MathML3/chapter4.html#id.4.4.3 it is possible to chain equalites and thus simplify the expression to
```
        <apply>
          <eq/>
          <ci>𝑎</ci>
          <ci>𝑏</ci>
          <ci>c</ci>
        </apply>
```
This would also be more compatible with the handing of + for example.

**Comment by dginev** [comment]
I recall having this discussion with Bruce a couple of years ago about this very subject, but I fail to remember the exact reasoning behind it. I think the conjunction treatment is more general, and you can apply it to any chain of relations.

Then again if they are n-ary operators maybe there isn't that much harm in using the n-ary form, which is also shorter?

**Comment by brucemiller** [comment]
The thing is the comparison to + is a bit of an illusion.  You can treat +/- as left recursive, and fold together adjacent operators that are the same. The remaining operations, if they're different, apply to the composed left & right parts. OTOH, relations are "chained" and always operate pairwise. It would only make sense to combine them if all operators in a "multi-relation" are the same.

It could conceivably be worth checking for identical operators and collapsing them in those cases; and also make the assumption that all the corresponding MathML operators would accept more than 2 arguments; but it really is a different situation than +.  Is there a reason that this representation would be better, other than aesthetics?

**Comment by dginev** [comment]
```
 Is there a reason that this representation would be better, other than aesthetics?
```

That's a good question, and I don't have a good answer to it personally.

**Comment by dginev** [comment]
Closing for now, if Moritz has a good reason why the multi-relation is superior, he's welcome to reopen. Btw this distinction is something that content math search engines will need to take into account, so CC-ing @kohlhase as a FYI.

**Comment by physikerwelt** [comment]
@dginev I think this is not an issue for MathSearch using https://github.com/michal-ruzicka/MathMLCan created by @michal-ruzicka
@michal-ruzicka am I right?

**Comment by dginev** [comment]
Isn't MathMLCan targeting presentation MathML?

I was mostly thinking of MathWebSearch when I wrote my comment, since it tends to use the content tree without a canonicalization step for now (unless that changed in the last year). Having a meaningful canonical form for Content MathML is a very wise addition to any content search engine.

**Comment by michal-ruzicka** [comment]
@physikerwelt In theory, yes. In practise are MathML Canonicalizer capability still limited, especially on Content MathML code. The main focus of MathML Canonicalizer was and still is Presentation MathML. I just tested MathML Canonicalizer v1.3.1 on the above mentioned Content MathML snippets and the result is not equivalent, i.e. not directly useable for 1:1 search engine matching. I am very sorry our tool is still far from perfect. :-/

**Comment by kohlhase** [comment]
Even though this is closed now, let me add my two cents. I think what we really should have is a higher-order operator for (inequality) chains that encodes the overt structure (no ands) and is general enough to hangle $a=b<c=:d$ and friends. The example above would be ```@(chain,a,=,b,=,c)``` and my example here would be ```@(chain,a,=,b,<,c,=:,d)```. This is what we use in SMGloM.

**Comment by dginev** [comment]
As an aside, it seems Mortiz' suggestion for N-ary relation syntax is not the official recommendation by the spec, which suggests instead using a special csymbol called "predicate_on_list" on the operator, and wrapping its arguments in a list.

https://www.w3.org/TR/MathML3/chapter4.html#contm.nary.reln

Which is arguably even less pleasant than Bruce's solution.

**Comment by physikerwelt** [comment]
The spec says
"While equality is a binary relation, eq may be used with more than two arguments, denoting a chain of equalities, as described in Section 4.3.4.3 N-ary Relations (classes nary-reln, nary-set-reln)."

So I think there is a option to read the spec either way. 

When I was looking at the content MathML generated in comparision to content MathML generated by a human I asked myself: Why does LaTeXML use `@(and,=(a,b),=(b,c))` and the human `=(a,b,c)`, compared to `+(a,b,c)` where both use the same notation? What are the fundamental difference and commonalities between relations (4.3.4) operators (4.3.2)?

Especially, if one rewrite to strict-cmml the common properties of nary-arith and nary-reln one needs to evaluate the tag content to rewrite one fne form to the other.

I like `+(a,b,c)` better than `+(a,+(b,c))` or permutations. But I see that it's much harder to rewrite the more complex expression `@(and,=(a,b),=(b,c)) to =(a,b,c).`

`+(a,b,c)` in strict content MathML
```
         <apply id="p1.1.m1.1.6.cmml" xref="p1.1.m1.1.6">
            <csymbol cd="arith1">plus</csymbol>
            <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑎</ci>
            <ci id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">𝑏</ci>
            <ci id="p1.1.m1.1.5.cmml" xref="p1.1.m1.1.5">𝑐</ci>
         </apply>
```

`=(a,b,c)` in strict content MathML
```
         <apply id="p1.1.m1.1.6.cmml" xref="p1.1.m1.1.6">
            <csymbol cd="logic1">and</csymbol>
            <apply id="p1.1.m1.1.6b.cmml" xref="p1.1.m1.1.6">
               <csymbol cd="relation1">eq</csymbol>
               <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑎</ci>
               <ci id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">𝑏</ci>
            </apply>
            <apply id="p1.1.m1.1.6c.cmml" xref="p1.1.m1.1.6">
               <csymbol cd="relation1">eq</csymbol>
               <share href="#p1.1.m1.1.3.cmml" id="p1.1.m1.1.6d.cmml" xref="p1.1.m1.1.6"/>
               <ci id="p1.1.m1.1.5.cmml" xref="p1.1.m1.1.5">𝑐</ci>
            </apply>
         </apply>
```
or the manually rewritten example
```
            <apply>
               <csymbol cd="fns2">predicate_on_list</csymbol>
               <csymbol cd="relation1">eq</csymbol>
               <apply>
                  <csymbol cd="list1">list</csymbol>
                  <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑎</ci>
                  <ci id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">𝑏</ci>
                  <ci id="p1.1.m1.1.5.cmml" xref="p1.1.m1.1.5">𝑐</ci>
               </apply>
            </apply>
         </apply>
```

**Comment by dginev** [comment]
Right, for a human writer the obvious answer is "the shortest form wins", in order to minimize effort. I think if I were to write strict cmml myself, I would also have a bias towards that, but for a machine it could be trickier, as you simply need to know more to do the compact rewrite.

For example, I can imagine a reading of
> Take $x<y<z=0$

that is read out loud as:
> Take x, smaller than y, smaller than z, where z is equal to zero.

In which case Bruce's suggestion of conjoining each pair of infix applications is the simplest way to capture all of the structural information.

In fact, if we had an n-ary "and" it could be even more convenient than Michael's suggestion of introducing a new symbol:

> @(nary-and, @<(x,y), @<(y,z), @=(z,0))

As opposed to:

> @chain(x,<,y,<,z,=,0)

This may be immediately apparent, but because we pass the relation symbols in their narrative order, this "chain" operator is actually dependent on the used notation, i.e. on the fact that the relations here are used as infix operators. So this is really an "infix-application-chain" symbol, and it becomes too specific to be useful (in my mind). The n-ary and approach looks most versatile to me from a "natural language math" perspective.

**Comment by brucemiller** [comment]
Trying to catch up after some travel...

@kohlhase: Yep, that's essentially the form used in LaTeXML's internal form for non-collapsed equality chains, except that it's called "multirelation".  Perhaps that concept should be elevated to a content dictionary at some point.

Yuck on the notion that cMML's relational operators are usually n-ary, but the OpenMath ones needed for strict cMML are often binary.  OTOH, if there were truly an advantage to having the list of related things "flat", then perhaps the chunk
``` 
 <apply>
      <csymbol cd="fns2">predicate_on_list</csymbol>
      <csymbol cd="relation1">eq</csymbol>
      <apply>
```
can be thought of as an n-ary eq ?  In any case, that's yet-another legal form that such relations can take, and that search engines ought to be able to recognize (by normalization or however).

The current latexml formulation has the "advantage" that both "a=b" and "b=c" are presumably easy to find in the result.  Writing "a+b+c" to "@(+,a,b,c)", on the other hand, while compelling makes finding "b+c" require some normalization games.  You can carry on this game to the next level, asking to find "a=b=c" within "a=b=c=d" or "a=b=c<d" or whatever; not sure what (if any) kind of normalizations would make that easy; likely it would be some similar reduction to a conjunction.

@dginev: aren't pragmatic cMML's "and" and OpenMath's logic1 "and" both n-ary?

**Comment by dginev** [comment]
@brucemiller I just checked, and indeed they are. So I stand by my last comment, that is already quite convenient.

If a search engine was to be interested in being able to exhaustively detect any implied relation from a relation chain, it would need to flatten out the formula into several formula entries which are indexed separately, which with large chains may be quite expensive and could require some innovative indexing techniques.
