### ISSUE TITLE
libxml validity errors for duplicate xml:id in math parsing

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#726]
This seems to be a relative to the validity errors we fixed some time back at #547 .

I have tried to find a minimal example which produces the validity error, they seem to be connected to newer libxml2 installations.

The machine I am reproducing on has libxml v20902:

```
$ xmllint --version
xmllint: using libxml version 20902
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib
```

and XML::LibXML version 2.0122 for the perl wrapper. 

Luckily, a single test file exhibits the validity problems, so there is an easy minimal example:

> t/90_latexmlpost.t ..... 
> 1..1
> \# Running under perl version 5.020002 for linux
> \# Current time local: Sun Mar  6 10:03:39 2016
> \# Current time GMT:   Sun Mar  6 15:03:39 2016
> \# Using Test.pm version 1.26
> t/post/simplemath.xml:0: element XMTok: validity error : ID S1.Ex6.m1.1 already defined
> t/post/simplemath.xml:0: element XMTok: validity error : ID S1.Ex6.m1.2 already defined
> t/post/simplemath.xml:0: element XMTok: validity error : ID S1.Ex6.m1.3 already defined
> t/post/simplemath.xml:0: element XMTok: validity error : ID S1.Ex6.m1.4 already defined
> t/post/simplemath.xml:0: element XMApp: validity error : ID S0.Ex4.m1.1 already defined
> t/post/simplemath.xml:0: element XMTok: validity error : ID S0.Ex3.m1.1 already defined
> t/post/simplemath.xml:0: element XMApp: validity error : ID S0.Ex3.m1.2 already defined
> t/post/simplemath.xml:0: element XMTok: validity error : ID S0.Ex2.m1.1 already defined
> t/post/simplemath.xml:0: element XMTok: validity error : ID S0.Ex2.m1.2 already defined
> ok 1

It seems related to the XMDual and XMRef interplay, as I see it. @brucemiller let me know if you can reproduce.

Motivation for the issue: the validity errors are seen quite often when doing CorTeX runs over arXiv, when monitoring the workers, and even though they don't lead to any fatal breakage, they're quite annoying.

**Comment by dginev** [comment]
Btw, the command to reproduce the test errors requires the right verbosity, so I am pasting it here:

```
make test TEST_VERBOSE=1 TEST_FILES=t/90*
```

**Comment by brucemiller** [comment]
Hmm, can't reproduce, but I have libxml2 20903, fwiw.

**Comment by dginev** [comment]
Can you reproduce now? These errors are so annoying, yet feel completely harmless. But they pollute my logs extensively.

**Comment by dginev** [comment]
Rediscovered the libxml2 thread: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766884

**Comment by brucemiller** [comment]
On 05/26/2016 06:20 PM, Deyan Ginev wrote:
> Rediscovered the libxml2 thread:
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766884

Not sure if that's relevant, since I have a newer version
of libxml2.  Unfortunately, I have an older version of
XML::LibXML, 2.0121; presumably a difference there is
the reason?

If it's anything like the previous bug, it'd be extremely
difficult to track down w/o being able to reproduce it.

**Comment by dginev** [comment]
```
perl -MXML::LibXML -e 'print $XML::LibXML::VERSION,"\n";'
2.0124
```

```
$ xmllint --version
xmllint: using libxml version 20902
```

To reproduce the errors:
```
make test TEST_VERBOSE=1 TEST_FILES=t/9*
```

You are of course right that some of the very old installations don't have the issue (most of our KWARC servers, that are ooooldies are fine).

**Comment by dginev** [comment]
A more explicit way to reproduce:
```
$ bin/latexmlc t/math/simplemath.tex --keepXMath --pmml --noscan --nocrossref > /dev/null
```

Post-processing looks like:
```
(post-processing...
element XMTok: validity error : ID S1.Ex6.m1.1 already defined
element XMTok: validity error : ID S1.Ex6.m1.2 already defined
element XMTok: validity error : ID S1.Ex6.m1.3 already defined
element XMTok: validity error : ID S1.Ex6.m1.4 already defined
element XMApp: validity error : ID S0.Ex4.m1.1 already defined
element XMTok: validity error : ID S0.Ex3.m1.1 already defined
element XMApp: validity error : ID S0.Ex3.m1.2 already defined
element XMTok: validity error : ID S0.Ex2.m1.1 already defined
element XMTok: validity error : ID S0.Ex2.m1.2 already defined
(XMath[w/MathML::Presentation]  7 to process... 0.02 sec)
(XSLT[using LaTeXML-xhtml.xsl]  processing... 0.04 sec) 0.06 sec)
Post-processing complete: No obvious problems
```

I seem to be using:
```
$ apt-show-versions -a libxml2
libxml2:amd64 2.9.4+dfsg1-2 install ok installed
libxml2:amd64 2.9.4+dfsg1-2 yakkety us.archive.ubuntu.com
libxml2:amd64/yakkety 2.9.4+dfsg1-2 uptodate
libxml2:i386 2.9.4+dfsg1-2 install ok installed
libxml2:i386 2.9.4+dfsg1-2 yakkety us.archive.ubuntu.com
libxml2:i386/yakkety 2.9.4+dfsg1-2 uptodate

$ perl -MXML::LibXML -e 'print $XML::LibXML::VERSION,"\n";'
2.0128
```

I am now suspecting this class of issues to be at least a partial cause of 1.89% of Fatals over arXiv, so I'll dig some more.

**Comment by dginev** [comment]
Hm, I take it back, Perl seems to be using an older libxml2 version:
```
$ perl -MXML::LibXML -e 'print XML::LibXML::LIBXML_VERSION,"\n";'
20902
$ perl -MXML::LibXML -e 'print XML::LibXML::LIBXML_RUNTIME_VERSION,"\n";'
20902
$ perl -MXML::LibXML -e 'print XML::LibXML::LIBXML_DOTTED_VERSION,"\n";'
2.9.2
```

Let me see if I can move it to 2.9.4 and retest

**Comment by dginev** [comment]
I had to delete some old libxml2.so files from `/usr/local/lib`, then:
```
$ perl -MXML::LibXML -e 'print XML::LibXML::LIBXML_RUNTIME_VERSION,"\n";'
20904
```

And after running the previously mentioned command, the error is gone entirely! Hurrah. More importantly, running over an example "expected:id" Fatal file from arXiv seems to still experience the Fatal, without any of the validation errors, so it was unrelated.

**Resolution proposal**: ```wontfix``` with a suggestion to upgrade libxml to 2.9.4 or newer, if the error is encountered.
