### ISSUE TITLE
Wrongly balanced big parantheses

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#727]
Source equation:
```tex
\begin{align}
 \big{(}\mathbf{d}_{obs} - g(\mathbf{m})\big{)}^T \mathbf{C}^{-1}_D \big{(}
\mathbf{d}_{obs} - g(\mathbf{m})\big{)}
\end{align}
```

LaTeXML "application/x-tex" encoding:
```tex
\big{(}\mathbf{d}_{obs}-g(\mathbf{m})\big{){}^{T}\mathbf{C}^{-1}_{D}\big{(}
\mathbf{d}_{obs}-g(\mathbf{m})\big{)}}
```

The part to pay attention to is the T superscript on the big closing parantheses, which gets misintepreted as ```\big{){}^{T}...}``` 

I haven't checked if the MathML tree is also wrong, but given the annotation, it ought to be. An Authorea user hit this while writing their document, as those equations broke in rendering with mathjax.

**Comment by brucemiller** [comment]
That's just weird. I guess \big is fighting with ^ over tokens? Hmm....

**Comment by brucemiller** [comment]
Oh, forgot to close. should be fixed now. Thanks.

**Comment by dginev** [comment]
Cool!
