### ISSUE TITLE
Let backtick have an active catcode to be used in DefMacro

### ISSUE THREAD

**Issue by angerhang** [brucemiller/LaTeXML#728]
In LaTeX we can have 
```tex
\catcode``=13
\def`#1`{\ensuremath{\mmt{#1}}}
```
so that ``  `#1` `` will be escaped into `\mmt{#1}`. Currently I have 
```perl
AssignCatcode('`', CC_ACTIVE);
DefMacro(' `{}` ', '\mmt{#1}');
```
but this doesn't seem to work and give me the following error:

```log`
Warning:perl:warn Odd number of elements in hash assignment
	/Users/Hang/perl5/lib/perl5/LaTeXML/Package/mmt.sty.ltxml line 33
	at /Users/Hang/perl5/lib/perl5/LaTeXML/Package.pm line 899
	In Core::Gullet[@0x7fe178a9e0e0] /Users/Hang/perl5/lib/perl5/LaTeXML/Package/mmt.sty.ltxml line 33

Error:misdefined:DefMacro (`{}`) DefMacro (`{}`) does not accept options:CODE(0x7fe17a82ff18)
	/Users/Hang/perl5/lib/perl5/LaTeXML/Package/mmt.sty.ltxml line 33
	In Core::Gullet[@0x7fe178a9e0e0] /Users/Hang/perl5/lib/perl5/LaTeXML/Package/mmt.sty.ltxml line 33
```

I also tried to use ``DefMacro('\`{}\` ', '\mmt{#1}');`` or ``DefMacro(' `{} ', '\mmt{#1}')`` but none of them seems to work. 

Can someone point out the parts that I might be missing or can this be done at all in LaTeXML?

**Comment by dginev** [comment]
Probably the binding parser falls short for this character.

You can use an internal definition approach, e.g. via DefMacroI, here are some example for standard TeX:
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/TeX.pool.ltxml#L5942

Alternatively, why not just RawTeX the working tex directly? That could work and be simplest.

**Comment by angerhang** [comment]
Yes RawTeX works perfectly. Totally forgot about that. 

Thanks for the help.
