### ISSUE TITLE
Math not displayed correctly in some browses due to LaTeXML-maybeMathjax.js failing to load MathJax - reopening #725

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#729]
Thank you for your suggestion. MathJax is still not loading when using the version of LaTeXML-maybeMathjax.js available from GitHub (https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/resources/javascript/LaTeXML-maybeMathjax.js ).

**Comment by brucemiller** [comment]
Could you post (or email to me bruce.miller at nist.gov) the user-agent strings of any browsers that aren't loading MathJax?  A site like http://www.useragentstring.com/ ought to be able to tell.
Thanks

**Comment by goska** [comment]
Thank you.
The user-agent reported for the Internet Explorer is: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
I have asked my colleague to send the ones for the Chrome under CentOS.
We have also experienced problems with math display under Kubuntu (in Firefox 44), causing wrong line height to be applied to math expressions (which gives the impression of double-spacing when math expressions are embedded within normal text). The problem appears to be due to the fonts installed locally (used by FF to display MathML rendered natively), possibly as reported in  http://askubuntu.com/questions/716016/firefox-wikipedia-mathml-equations-have-too-much-space-above-and-below.  As before, the problem is cured by loading MathJax directly form CDN.

**Comment by brucemiller** [comment]
There's some confusion about whether the script is *failing* to load MathJax, or not even *trying*.  From the user agent string, it should be trying.  I've heard of issues with recent IE's having security settings that cause them not to load external javascript; I don't know if there's a console or log where you can determine if IE is refusing to load the script; alternatively you could look into its settings.  I haven't heard of any problems with Chrome, however (till now).

Do you have a url to the page(s) in question? Maybe I can figure something out...

As far as Firefox; the whole point of *maybe*-MathJax is to *not* load MathJax for Firefox.  Of course, Firefox tends to suffer more when it doesn't have adequate fonts.  Or perhaps the MathML that LaTeXML generates could be improved? For that, would need a TeX sample.

**Comment by goska** [comment]
Yes, I thought of the possibility of the IE/Chrome security settings preventing loading of an external script. I could not find anything in my IE settings and no warning or dialogue was displayed when browsing pages using either version LaTeXML-maybeMathjax.js - and it did not matter whether the HTML documents were read from the local file system or a remote URL over HTTP. 
To further check if the IE was preventing loading scripts via scripts from external URL, I modified LaTeXML-maybeMathjax.js by taking out the test:
```
//======================================================================
// Load MathJax, IFF the current browser can't handle MathML natively.

var LTX_mathjax_url = "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=MML_HTMLorMML";

function LTX_refreshMath(){
    // Maybe unnecessary, or overkill, but...
    if(typeof MathJax != "undefined"){
	MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
    }}

var LTX_agent = navigator.userAgent;
// Add script element loading MathJax unless we can handle MathML

    var script = document.createElement('script');
    var head = document.getElementsByTagName("head")[0];
    if(head != null){
        script.type = "text/javascript";
        script.src = LTX_mathjax_url;

        script.onreadystatechange = LTX_refreshMath;
        script.onload = LTX_refreshMath;

        head.appendChild(script); 
}
```
When using modified version, MathJax.js was loaded in both (local and remote HTML documents) cases. I'll double-check with my colleague what is exactly happening in Chrome on CentOS.
Unfortunately, I cannot post the files, or URLs to the files in question, as they contain material which hasn't yet been published (and the files on test server are password-protected).

**Comment by goska** [comment]
I have just used a simple JavaScript to check the outcomes of the tests carried out in LaTeXML-maybeMathjax.js, and it appears the test detects the presence of Mathplayer. I have an old version Mathplayer installed on my system (used it in the past), but it is never loaded in IE 11.

**Comment by brucemiller** [comment]
Now I'm more confused! :> Your check showed that has_mathplayer came out true; but I don't quite see how since "MathPlayer" isn't present in the agent string you posted above. (and surprising that it would end up in the agent string if IE isn't executing it).  Since you're mucking around with the javascript, maybe you could post what the agent string is from there? Gotta be a clue...

**Comment by goska** [comment]
I have used the following html/javascript, which includes user agent tests from LaTeXMl-majbeMathjax.js and prints the outcomes as well as the user-agent in a page:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Title of the document</title>
 
</head>

<body>
<p id="message"></p>
<p id="user-agent"></p>
<script>
 var agent = navigator.userAgent;
var message = "";
    var is_gecko = (agent.indexOf("Gecko") > -1 &&
                    agent.indexOf("KHTML") === -1 &&
                    agent.indexOf("Trident") === -1);
    if (is_gecko) {message=message+"is gecko";}
    var has_mathplayer = agent.match(/MathPlayer/);
    if (has_mathplayer) {message=message+ " has mathplayer";}
document.getElementById("message").innerHTML = "message: " + message;
document.getElementById("user-agent").innerHTML = "user agent: " + agent;
</script>
</body>

</html> 
```
User agent reported for IE on my system is: 
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; MathPlayer 3.00 beta 1; McAfee; .NET4.0E; GWX:DOWNLOADED; rv:11.0) like Gecko

My colleague hasn't been able to reproduce the problems in Chrome on CentOS 7. He reported the following user-string (using online tool t http://www.useragentstring.com/ ): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36

**Comment by brucemiller** [comment]
Hmm... I actually fixed this (well, I hope), but forgot to comment & close.  The script should ignore MathPlayer if IE is 10 or greater.  If that doesn't work out, or if you can clarify the problem with Chrome (if any), please reopen/refile.  Thanks for the report!
