### ISSUE TITLE
<om: OMATTR> not conforming schema?

### ISSUE THREAD

**Issue by angerhang** [brucemiller/LaTeXML#730]
In 
https://github.com/brucemiller/LaTeXML/blob/6ad30b7203be2dcc9d7d19d2c05537ffb6cf6edd/lib/LaTeXML/Post/OpenMath.pm#L143-L149, we generate the `om:OMATTR` element i.e.
```xml
	<om:OMATTR>
	  <om:OMATP>
	  <om:OMS cd="OMDoc" name="verbalizes">
	    <om:FOREIGN encoding="mtext">
	      <a href="2" title="" class="ltx_ref mmtRef" content="a"/>
	    </om:FOREIGN>
	  </om:OMS>
	  <om:OMS cd="OMDoc" name="infObj"/>
      </om:OMATP>
	</om:OMATTR>
```
however according to the openmath [schema](http://www.openmath.org/standard/om20-2004-06-30/omstd20html-3.xml#rncssec_xmlomel), we should have an `omel` after `OMATP` is closed.
```
# attribution constructor and attribute pair constructor
OMATTR = element OMATTR { compound.attributes, OMATP, omel }
```

Is the `omel` being omitted here on purpose? Or the second `om:OMS` element should be placed after `om:OMATP`?
```xml
	<om:OMATTR>
	  <om:OMATP>
	  <om:OMS cd="OMDoc" name="verbalizes">
	    <om:FOREIGN encoding="mtext">
	      <a href="2" title="" class="ltx_ref mmtRef" content="a"/>
	    </om:FOREIGN>
	  </om:OMS>
      </om:OMATP>
	 <om:OMS cd="OMDoc" name="infObj"/>
	</om:OMATTR>
```

**Comment by brucemiller** [comment]
Hmm, I'm pretty sure this came about from an old discussion about a random chunk of text within a math formula in sTeX, but it's pretty clear that at least one of us wasn't thinking it through clearly. :>

I think you're partly right, but there's still a problem. An OMATTR should look like:
```
<om:OMATTR>
   <om:OMATP>
       <om:OMS symbol that describes the property/>
       <om:OMsomething an expression representing the value of the property/>
   </om:OMATP>
  <om:OMsomething the expression which receives the property/>
</om:OMATTR>
```
Probably @dginev or @kohlhase remembers what ```infObj``` is supposed to signifiy (an anonymous informational object?)  I suspect the intended result is
```
  <om:OMATTR>
      <om:OMATP>
      <om:OMS cd="OMDoc" name="verbalizes"/>
      <om:FOREIGN encoding="mtext">
          <a href="2" title="" class="ltx_ref mmtRef" content="a"/>
      </om:FOREIGN>
      </om:OMATP>
     <om:OMS cd="OMDoc" name="infObj"/>
    </om:OMATTR>
```
which would mean that infObj is annotated with "a" as it's "verbalization".

Does that sound right? (easily fixed, if so)

**Comment by brucemiller** [comment]
I went ahead & committed it as I proposed. Let me know if that seems right.

**Comment by kohlhase** [comment]
@brucemiller that looks correct. Thanks.
