### ISSUE TITLE
\phantomsection support?

### ISSUE THREAD

**Issue by sbecuwe** [brucemiller/LaTeXML#744]
Is there a way to get following construction working in LaTeXML?
I have a chapter with exercises and another chapter with solutions. In the pdf version, I'm able to jump to the solution using the \phantomsection construction. In LaTeXML, all those \phantomsection labels seem to refer the section they're in, not to the specific solution. In the example below, no matter how many exercises there are, it would always jump to the beginning of the section instead of going to the solution directly. How could I deal with this kind of references?

`
\chapter{Solutions}
\section{First section}
\phantomsection\label{sol:ex1}
Solution exercise 1: ...
...
\phantomsection\label{sol:ex2}
Solution exercise 2: ...
...
`

**Comment by brucemiller** [comment]
Reminder to see a proposed solution in #746

**Comment by dominique-unruh** [comment]
The following is a quick workaround to get labels tied to arbitrary places in the document:

```
DefConstructorI('\labelhere','{}', '<ltx:inline-itemize><ltx:inline-item labels="LABEL:#1"><ltx:tag/></ltx:inline-item></ltx:inline-itemize>');
```

This Perl code defines a command \labelhere that works like \label, but produces an empty inline itemization that one can link to. Just use \labelhere{labelname}, and later \hyperref[labelname]{Text} or \ref{labelname} to link to it.

Possibly the following definition works, too, if you prefer not to use Perl code, but I haven't tried:

```
\newcommand\labelhere[1]{\begin{inparaitem}\item[]\label{#1}\end{inparaitem}}
```

One warning: \labelhere{label} produces an extra space. However, if you use it only adjacent to a space (e.g., `text\labelhere{label} text`) then the extra space should not show up in the final document.

**Comment by dginev** [comment]
Has this question been answered @sbecuwe ? Is t here an additional deliverable to consider here, or are the workarounds sufficient? I will resolve the issue for now, feel free to reopen or follow-up if this isn't viable.
