### ISSUE TITLE
Respect \newtheoremstyle arguments (Was: RefStepCounter reference update)

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#746]
I’m having trouble using `\refstepcounter{customCounter}`, and it seems my problems are stemming from `refstepcounter`.  Consider the following:

```tex
\documentclass{article}
\begin{document}
\refstepcounter{figure}\label{label}
The counter is \ref{label}.
\end{document}
```
In LaTeX, the output is “The counter is 1.”

In LaTeXML, the output is “The counter is id1.”

It appears that the label hasn’t attached to the reference, but has instead floated up to the root document tag.

Playing around, it seems that `refstepcounter` increments the counter, but it never updates the reference, so that the subsequent label refers to the most recent occurrence of a default counter.  Indeed, (tex)`\refstepcounter` simply calls (perl)`RefStepCounter`, and the documentation for the latter doesn’t mention updating the reference, only that you get a reference hash in return.

Does this mean that if I want to use (tex)`\refstepcounter` to update the reference, I’ll need to take the output of (perl)`RefStepCounter` and build my own label?  What would be the appropriate xml tag to hold the label?  Or would I need to hijack a counter related command like `\subsubsection` in order to have a reference for my label?

**Comment by dginev** [comment]
Thanks @teepeemm , this is an excellently reported issue! I'll leave it to Bruce to give advice / issue a patch, but just wanted to thank you for reporting this!

**Comment by brucemiller** [comment]
This isan awkward problem that really stems from the different models of LaTeX and LaTeXML. In particular that LaTeXML tries to follow the model that (imho) LaTeX is trying to simulate. All  that ```\refstepcounter``` does is step counters and record ```\@currentlabel``` (which isn't actually a label in the ```\label```  sense, but a reference number); it doesn't actully update any references. ```\label```,  otoh, merely records the association between the given label and whatever ```\@currentlabel``` happens to be, at that moment.

My interpretation is that ```\label``` wants to record a label on the current *object* (section, figure,...). Then ```\ref`` not only gets filled in with the number associated with the object, but also provide a hyperlink to the object.  In this approach, ```\refstepcounter``` is semi-internal macro one would use to increment the counter *within* some object.

In your example, LaTeX is happy giving you the "figure" reference number, but there's no figure (or anything) for LaTeXML to link to.  I don't quite know how to get the effect you're after, w/o breaking the. more expected behaviour.  It would make more sense if you had some kind of labellable object (section, float, something) to attach the label to.

**Comment by teepeemm** [comment]
The something I’m trying to label is an example.  So let’s try these:

```
\documentclass{article}
\newcounter{exampleCounter}
\usepackage{examples}
\begin{document}
\begin{example}\label{label}
Example text.
\end{example}

That was example \ref{label}.
\end{document}
```
examples.sty:
```
\newenvironment{example}{%
\refstepcounter{exampleCounter}\textbf{Example \arabic{exampleCounter}}%
}{}
```
That could easily be done without LaTeXML (i.e., not in a package), but there’s no reason to expect it to behave any differently because we’ve not given LaTeXML anything to label.  So let’s give it something to label:

examples.sty.ltxml:
```
# -*- mode: Perl -*-
use strict;
use warnings;
use LaTeXML::Package;
DefEnvironment('{example}',
  '<ltx:para class="example" xml:id="#id"><ltx:text class="exampleTitle">Example #exampleCounter</ltx:text> #body</ltx:para>',
  properties=>sub{
    my %rsc = RefStepCounter('exampleCounter');
    return (
      exampleCounter => $rsc{refnum},
      id => $rsc{id}
    );
  }
);
1;
```
My reading of the schema is that because I’m not using one of the somethings listed at [http://dlmf.nist.gov/LaTeXML/manual/schema/schema.module.LaTeXML-common.html#schema.pattern.Labelled.attributes](http://dlmf.nist.gov/LaTeXML/manual/schema/schema.module.LaTeXML-common.html#schema.pattern.Labelled.attributes), the label defaults back to labeling the document root.  But none of those somethings are appropriate to my custom div.

So maybe my question isn’t “how can I make refstepcounter update the reference?”, but is actually “how can I create something that can be a label target?”

**Comment by brucemiller** [comment]
First let me link to issue #744, and call out to @sbecuwe, since the issue there is almost the same.

You're definitely on the right track with your proposed solution, with the caveat that ltx:para also isn't quite a labellable element. For the record:
 * ltx:p are low level "physical" paragraphs, essentially a block; 
 * ltx:para are logical paragraphs, which might contain a single ltx:p, or several with displayed equations interspersed; and 
 * ltx:paragraph is for a structural paragraph, with title and possibly numbered. 
The last one would be labellable and you could use it as you did above and things should work.

However, what may be a more appropriate way to setup a target would be to define some new environments for examples, problems, etc, that would get numbered and are labellable using the amsthm package.  It also gives you a handle on some styling.  Something like:
```
\documentclass{article}
\usepackage{amsthm}
\newtheorem{example}{Example}
\begin{document}
\begin{example}\label{anexample}
An Example
\end{example}

The example was \ref{anexample}.
\end{document}
```

Do you think that could work out for your application?

**Comment by dginev** [comment]
Side thought to @brucemiller : 

In the original example given:
```tex
\documentclass{article}
\begin{document}
\refstepcounter{figure}\label{label}
The counter is \ref{label}.
\end{document}
```

The main "user experience" issue is that instead of the expected ```1```, the ```\ref``` created ```id1```. That, in itself, should be simple to fix, shouldn't it? I believe the values of the plain ```\ref``` macro are always numeric for a particular depth? E.g. ```1.2.3.1```. Why make an exception to that for the top level?

**Comment by teepeemm** [comment]
It appears that amsthm will allow me to reference everything appropriately.  But that does lead me to one last (slightly) related question.  I currently have

```
\documentclass{amsart}

\newtheoremstyle{mystyle}% name
  {}% Space above, empty = `usual value'
  {}% Space below
  {}% Body font
  {}% Indent amount (empty = no indent, \parindent = para indent)
  {\bfseries}% Thm head font
  {}% Punctuation after thm head
  {\newline}% Space after thm head: " " = normal interword space; \newline = linebreak
  {\thmname{\textbf{#1}}\thmnumber{ \textbf{#2}}\thmnote{ \textbf{#3}}}% Thm head spec

\theoremstyle{mystyle}
\newtheorem{exercise}{Exercise}

\begin{document}

\begin{exercise}[thmnote]
Content.
\end{exercise}

\end{document}
```

But it appears newtheoremstyle completely ignores the theorem head specification in the last argument.  I can use css to style most of the environment the way I’d like, but the default puts the theorem note in parentheses, which isn’t what I want.  Is there a way to get rid of the parentheses?

**Comment by dginev** [comment]
Adding ``` \`\`\`tex ``` in the header of code blocks, makes latex snippets a lot prettier, went ahead and beautified here.

**Comment by brucemiller** [comment]
Ah, so everybody wants things pretty; comments, theorems, ...!

Best would be to respect all the newtheoremstyle arguments.  I've made it extra complicated by trying to find the commonality between the newtheorems of latex, amsthm, ntheorem.  I'll see what I can do.

FWIW, latex itself also provides a newtheorem, just less customizable.

**Comment by dginev** [comment]
Updated title to reflect new topic. Beautiful snippets are super  :+1:

**Comment by brucemiller** [comment]
I've got amsthm using the "headspec", so it should be a bit more useful for you.  Thanks for raising that point!
