### ISSUE TITLE
A bug in mathtools.sty.ltxml?

### ISSUE THREAD

**Issue by SmnWntr** [brucemiller/LaTeXML#747]
If I compile the below code via
`latexmlc --mathimages --destination=test-out.xml test.tex`
then I get an error: the image of the formula can’t be created. If I delete the (unused) package mathtools, then everything goes fine. (The real problem happens in a larger TEX file where I indeed need mathtools, and where the aligned formula has more lines.)
Thanks for your input! Simon
```
\documentclass{article}
\usepackage{mathtools}
\begin{document}
\begin{equation}
\left\{\begin{aligned}
&x=\sqrt{2},
\end{aligned}\right.
\end{equation}
\end{document}
```

**Comment by dginev** [comment]
Looks like something I should be able to debug and give advice on, will take a look a little later. Thanks for the report!

**Comment by brucemiller** [comment]
Odd... The lack of a space or newline before the ampersand in the recreated TeX (not the original)
```...\begin{aligned}&...``` appears to be the culprit.

**Comment by brucemiller** [comment]
This should be fixed now (probably not a completely generic fix, but...)  Thanks for the report!
