### ISSUE TITLE
href no longer working?

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#751]
Consider the following:

```tex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\section{Label target}\label{mylabel}
\href{http://dlmf.nist.gov/LaTeXML/}{two mandatory arguments} \\
\hyperref{http://dlmf.nist.gov/LaTeXML/manual/customization/customization.latexml.html}{SS1}{name}{four mandatory arguments} \\
\hyperref[mylabel]{optional then mandatory argument}
\end{document}
```

The current release (0.8.1) of hyperref.sty.ltxml package doesn’t work with `\hyperref[]{}`.  The current version of hyperref.sty.ltxml on GitHub has fixed this problem.  But now, every occurrence of `\href{}{}` causes
`Fatal:misdefined:Verbatim Unrecognized parameter type in "Verbatim"`
whereas this was working fine before.

The difference appears to be that hyperref.sty.ltxml used to have
```perl
DefConstructor('\href Semiverbatim  {}',
  "<ltx:ref href='#href'>#2</ltx:ref>",
  properties => sub { (href => CleanURL(LookupValue('BASE_URL') . ToString($_[1]))); });
```
But we now have (at line 125)
```perl
DefConstructor('\href Verbatim  {}',
  "<ltx:ref href='#href'>#2</ltx:ref>",
  properties => sub { (href => CleanURL((LookupValue('BASE_URL') || '') . ToString($_[1]))); });
```
Indeed, changing Verbatim back to Semiverbatim causes the above to work without a problem.

But I’m not entirely sure that I’ve diagnosed this correctly.  I’m also not sure if I’ve identified the correct solution (the Verbatim/Semiverbatim distinction is still mysterious to me).

**Comment by dginev** [comment]
Sounds like something that can get a quick fix by @brucemiller

**Comment by brucemiller** [comment]
It works fine here; is it possible that your system's picking up the old TeX.pool.ltxml from the old 0.8.1 release? (You could see that from the listing of files as they're loaded)

The ```Verbatim``` type was added later (to TeX.pool) probably as part of fixing hyperref, or something similar. With Verbatim and SemiVerbatim, I'm trying to recognize the common sets of characters that get their catcodes set to letter or other in most latex macros.  SemiVerbatim is for most cases, like ```\label```, ```\ref```, etc. I only gradually realized that % does *not* get neutralized in those cases, but stays a comment character.  However, % is often used in URL's, so many of hyperref's arguments need a bit more coaxing.  Verbatim makes %  an other as well.

**Comment by teepeemm** [comment]
The command output begins
```
[directory] $ latexml filename.tex --dest=filename.xml
latexml (LaTeXML version 0.8.1)
processing started Thu May 26 16:36:08 2016

(Digesting TeX filename...
(Loading /opt/local/lib/perl5/vendor_perl/5.22/LaTeXML/Package/TeX.pool.ltxml...
```
It appears that I am indeed using the old TeX.pool.ltxml.  Which would be expected, since I installed via MacPorts and haven’t attempted to execute from my github directory.

I guess this means that hyperref.sty.ltxml and TeX.pool.ltxml were both modified so that the above will work in 0.8.2 (but mixing the ltxml from different versions would of course cause problems).  In that case, that is a satisfactory answer.

**Comment by dginev** [comment]
Cool! Acting as a secretary and closing here.

**Comment by brucemiller** [comment]
In case it's not obvious, you can uninstall from macports (whatever the command is called), but that will leave all the dependencies, so that the github version should work (until we do a new release, patch up the Portfile and then you can install the macports version again).
