### ISSUE TITLE
Integrating LaTeXML into TeX editors

### ISSUE THREAD

**Issue by senthilmm** [brucemiller/LaTeXML#757]
Where do you copy the batch files in Windows platform.

**Comment by dginev** [comment]
Hi @senthilmm 

The windows setup usually depends on the Perl installation you are using. I believe we've last tried to install LaTeXML under Strawberry Perl, which has its own designated directory for the executables. You may need to add that to the path.

Neither I nor @brucemiller are active Windows developers, so we could need some extra information about what you're trying to achieve. And any help figuring out the details is most welcome!

**Comment by senthilmm** [comment]
Hello @dginev 

Tested installing LaTeXML  0.8.1 on Windows 10. Here are the issues I had and how I resolved.

Current Installation Configurations: 
Windows OS: Windows 10 Pro, 32-bit Operating System, x64-based processor
Strawberry Perl: strawberry-perl-5.20.3.3-32bit
TeX-System: TexLive 2015
ImageMagick: ImageMagick-6.8.9-8-Q16-x86-dll
Installed PerlMagick on cpan command prompt with "notest install Image-Magick"
Installed prerequisites "cpan Image::Size Parse::RecDescent UUID::Tiny"
LaTeXML: 0.8.1
Installed LaTeXML using "cpan install LaTeXML" on command prompt.

Issues
Latest build of ImageMagick does not have equivalent PerlMagick build release. Tried with ImageMagick-7.0.1-6-Q16-x86-dll
PerlMagick does not get installed on latest release of Strawberry Perl strawberry-perl-5.24.0.1-32bit.msi had to revert to strawberry-perl-5.20.3.3-32bit.msi

Now for the part of Integrating LaTeXML in TeXWorks, followed instructions as given in https://github.com/brucemiller/LaTeXML/wiki/Integrating-LaTeXML-into-TeX-editors.

Is there any specific location that we store the batch files or simply add them in a folder that is in Path.

Thanks
Senthil

**Comment by dginev** [comment]
That's a great description, thank you!

I think adding them to a folder that is in Path should suffice, as long as the Perl installation is available to TeXWorks. If that doesn't help, I may need to ask around for some windows developers. Let us know!

**Comment by senthilmm** [comment]
Hello @dginev

Thanks for the input. Included a common folder and added to the Path in TexWorks. Had issues with XML::LibXML. Installed the package using ppm XML-LibXML on command prompt.

Everything works like a charm.

**Comment by dginev** [comment]
Oh wow, that's great to hear! You must know what you are doing, since it has been a major pain for me to setup all individual components... There must be an easier way to bundle a windows installation, maybe something like an .msi file? I don't know...

Wish we had/could recruit a Windows enthusiast to help us with at least building installers for the releases, e.g. for the upcoming 0.8.2. Could improve the experience by a lot.

But these are just thoughts ...
