### ISSUE TITLE
attachfile.sty

### ISSUE THREAD

**Issue by matteosecli** [brucemiller/LaTeXML#761]
[attachfile](https://www.ctan.org/pkg/attachfile) is quite an unimportant package, but it's useful to e.g. attach an external PDF file to a LaTeX-made PDF. It would be nice to have support for it! :smiley:

**Comment by brucemiller** [comment]
So you'd want to have a link to the pdf?  There're certainly the necessary bits & pieces around to put this together; making a reference to the thing is easy, but you'd probably want to copy the pdf from whereever it is into the target directory.  There was some ideas & talk about doing that in a nicely generic way that would also work for things like ePub, but never quite finished.

**Comment by matteosecli** [comment]
Yeah, that's the basic idea! :+1:

**Comment by brucemiller** [comment]
I hadn't intended to do this one right away, but by the time I figured out what it was, it was easier to go ahead and finish it!  Thanks for the request!

**Comment by matteosecli** [comment]
Thank you! :smiley:
