### ISSUE TITLE
Generic binding symbols in openmath postprocessor  

### ISSUE THREAD

**Issue by angerhang** [brucemiller/LaTeXML#762]
As sTeX is trying to retire the KWARC fork of LaTeXML and migrate to the upstream, there are various Openmath changes that need to be synced and this is one of them. 

In OpenMath.pm, the KWARC fork has a sketch for generic binding symbols: 

``` perl
#NOTE: Experimental sketch for generic binding symbols
sub findElements_internal {
  my ($type, $name, $attr, @children) = @_;
  my @elements;
  if ($name eq $type) {
    @elements = ([$name, $attr, @children]);
  }
  else {
    @elements = map { findElements_internal($type, @$_) } grep { ref $_ } @children; }
  return @elements; }

DefOpenMath('Apply:BINDER:?', sub {
    my ($ic, $op, $bvars, $expr) = @_;
    if (!defined $expr) {
      Fatal('Apply:BINDER expects 3 arguments')
    }
    my $bvarspost = om_expr($bvars);
    #Recursively fish out all OMV elements:
    my @vars = findElements_internal('om:OMV', @$bvarspost);
    ['om:OMBIND', {},
      om_expr($op),
      ['om:OMBVAR', {}, @vars],    # Presumably, these yield OMV
      om_expr($expr)] });
```

A concrete example of this is being discussed at https://github.com/KWARC/LaTeXML-Plugin-sTeX/issues/108. I will just copy over the exact details below.
Given 

``` tex
$\bsetst{x}x{\text{$\inset{x}{A}$ or $\inset{x}{B}$}}$.
```

Given this code snippet we get the desired version:

``` xml
<om:OMOBJ stex:srcref="smglom/sets/source/union.en.tex#textrange(from=3;47,to=4;59)">
  <om:OMBIND>
    <om:OMA>
      <om:OMS cd="set" name="bsetst"/>
      <om:OMV name="&#x1D465;"/>
    </om:OMA>
    <om:OMBVAR>
      <om:OMV name="&#x1D465;"/>
    </om:OMBVAR>
    <om:OMATTR>
      <om:OMATP>
    <om:OMS cd="OMDoc" name="verbalizes"/>
    <om:OMFOREIGN encoding="mtext">
      <om:OMOBJ stex:srcref="Anonymous String#textrange(from=0;1,to=0;0)">
        <om:OMA>
          <om:OMS cd="set" name="inset"/>
          <om:OMV name="&#x1D465;"/>
          <om:OMV name="&#x1D434;"/>
        </om:OMA>
      </om:OMOBJ>
      or
      <om:OMOBJ stex:srcref="Anonymous String#textrange(from=0;1,to=0;0)">
        <om:OMA>
          <om:OMS cd="set" name="inset"/>
          <om:OMV name="&#x1D465;"/>
          <om:OMV name="&#x1D435;"/>
        </om:OMA>
      </om:OMOBJ>
    </om:OMFOREIGN>
      </om:OMATP>
      <om:OMS cd="OMDoc" name="infObj"/>
    </om:OMATTR>
  </om:OMBIND>
</om:OMOBJ>
```

whereas via the upstream which doesn't include generic binding symbols, we obtain the following

``` xml
<om:OMOBJ>
    <om:OMA>
        <om:OMS cd="arithmetics" name="multiplication" />
        <om:OMSTR>\bsetst</om:OMSTR>
        <om:OMV name="&#x1D465;" />
        <om:OMV name="&#x1D465;" />
        <om:OMATTR>
            <om:OMATP>
                <om:OMS cd="OMDoc" name="verbalizes">
                    <om:FOREIGN encoding="mtext">
                        <om:OMOBJ>
                            <om:OMA>
                                <om:OMS cd="set" name="inset" />
                                <om:OMV name="&#x1D465;" />
                                <om:OMV name="&#x1D434;" /></om:OMA>
                        </om:OMOBJ> or
                        <om:OMOBJ>
                            <om:OMA>
                                <om:OMS cd="set" name="insext" />
                                <om:OMV name="&#x1D465;" />
                                <om:OMV name="&#x1D435;" /></om:OMA>
                        </om:OMOBJ>
                    </om:FOREIGN>
                </om:OMS>
                <om:OMS cd="OMDoc" name="infObj" /></om:OMATP>
        </om:OMATTR>
    </om:OMA>
</om:OMOBJ>
```

We would love to incorporate the generic binding symbols here. How to best do that?

**Comment by brucemiller** [comment]
Actually, there's already a (likely incorrect) stub in OpenMath.pm acknowledging that it has to be handled; so it's perfectly reasonable to adopt this code, or something like it.  We only want to decide a reasonable representation in XMath that will be converted to OpenMath. 

What's possibly not to like about your proposal (& the stub) is that they're using the role attribute.  Obviously it wouldn't use the "meaning" (which ultimately corresponds to a cd:name), so perhaps that's the right thing to do.

Background: the role attribute is the "grammatical role", used in parsing. As LaTeXML evolved it started getting overloaded into a bunch of representational nonsense along with sundry presentational attributes.  Eventually the house of cards fell, and we started using XMDual very heavily to separate presentation from content at a much earlier stage, and most of those cruft attributes are gone. And, the role attribute settled into something much cleaner.

Maybe BINDER is a legitimate special case (I'm sure there are others)...

**Comment by dginev** [comment]
I think @angerhang is no longer responsible for that migration and it may now be @tkw1536 who gets to work on the PR here. In any case making a PR rather than this issue gets a higher chance to resolve, and this has gone sufficiently stale to close.
