### ISSUE TITLE
\nocite seems to generate empty <cite>

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#765]
This came up in the course of #764. I generate documents with lots of ```\nocite``` macros and each one seems to generate 
```xml
<cite class="ltx_cite"></cite>
```
 in the html. I do not think that this is useful.

**Comment by brucemiller** [comment]
On 06/14/2016 09:02 AM, Michael Kohlhase wrote:
> This came up in the course of #764
> <https://github.com/brucemiller/LaTeXML/issues/764>. I generate
> documents with lots of |\nocite| macros and each one seems to generate
>
> |<cite class="ltx_cite"></cite> |
>
> in the html. I do not think that this is useful.

Not sure how you're using it, but with stock LaTeXML, ```\nocite{*}```
generates ```<cite><bibref bibrefs="*" show="nothing"/></cite>```.
That doesn't produce anything particularly useful at that point
in the html, but it does cause the bibliography to be filled in
with all bib entries.

**Comment by kohlhase** [comment]
I was using ```\nocite{foo}``` with (essentially) ```latexmlc --format=html```.

**Comment by dginev** [comment]
I know it doubles the reporting burden, but having self-contained minimal examples really speeds us up with resolving issues. If we can do a trivial copy-paste and reproduce, we can focus on solving the issue rather than trying to reverse-engineer the problem. Everyone's time is valuable, but the reporter is usually in the unique position to quickly prepare a minimal test case.

**Comment by brucemiller** [comment]
On 06/14/2016 10:29 AM, Michael Kohlhase wrote:
> I was using |\nocite{foo}| with (essentially) |latexmlc --format=html|.

which still shouldn't produce anything particular
where the ```\nocite``` was, but should have the
effect of including "foo" in the bibliography.
Does it not do that?

**Comment by kohlhase** [comment]
you are right. will do. 
```
\documentclass{article}
\usepackage{biblatex}
\bibliography{kwarcpubs,kwarccrossrefs,extcrossrefs}
\nocite{foo}
\printbibliography
\end{document}
```
and I run it with 
```
Michaels-MBP:bibs kohlhase$ latexmlc --bibliography=kwarcpubs.bib.xml --bibliography=kwarccrossrefs.bib.xml --bibliography=extcrossrefs.bib.xml --format=xhtml --destination=mkohlhase-article.html --log=mkohlhase-article.tex.ltxlog --log=mkohlhase-article.ltxlog mkohlhase-article.tex
```

**Comment by kohlhase** [comment]
BTW, it also generates ```<p class="ltx_p"><cite class="ltx_cite"/></p>``` if I use the more standard 
```
\documentclass{article}
\nocite{foo}
\bibliographystyle{unsrt}
\bibliography{kwarcpubs,kwarccrossrefs,extcrossrefs}
\end{document}
```

**Comment by brucemiller** [comment]
So, apparently the bibliography contains what it should contain, but has an empty ```<cite>``` that is not useful.  But is it harmful?  (the ltx:cite can contain lots of stuff: phrases, ltx:bibcite, as well as the empty ltx:bibcite, so it's annoying to scan).

**Comment by brucemiller** [comment]
ok, not so hard to remove, so done.
