### ISSUE TITLE
supertabular.sty.ltxml: conceptual problem

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#769]
The supertabular package provides the supertabular environment that allows tabulars across page breaks. Such a supertabular might also have a caption (\tablecaption). Insofar, {supertabular} is an replacement for {table}+{tabular}. In other words: {supertabular} is designed to be placed not inside {table}. It rather beaves like {longtable}. The difference to {longtable} is that the accompanying \tablecaption must be placed before {supertabular}.
The LaTeXML testing file `t/alignment/supertabular.tex` still has {table} around {supertabular}. Without this {table}, the file produces errors.
Could you adapt `supertabular.sty.ltxml` in a way that it respects \tablecaption right before {supertabular}?

**Comment by brucemiller** [comment]
Yeah, I misunderstood that aspect of supertabular!  Thanks for the research and the good explanation.  Should work properly now, I think.
