### ISSUE TITLE
\graphicspath gives errors with mutliple directories

### ISSUE THREAD

**Issue by casio7131** [brucemiller/LaTeXML#773]
\graphicspath (from graphicx package) doesn't seem to handle multiple directories within LaTeXML - see my simple example below.

I get errors about missing closing braces when multiple directories are used - variant 1 works (single directory), but variants 2 and 3 (multiple directories) give an error.

I don't believe I'm doing anything wrong (see UK TEX FAQ example), so I'm reporting a possible bug here.

```
\documentclass{article}
\usepackage{graphicx} % or {graphics}
%\graphicspath{{./fig/}}            % YES-WORKS % http://www.tex.ac.uk/FAQ-graphicspath.html
\graphicspath{{./fig/},{../fig/}} % NO: Error:expected:} A closing } was supposed to be here *** at []/graphicspath.tex; line 4 col 23
%\graphicspath{{./fig/},{./fig2/}} % NO: Error:expected:} A closing } was supposed to be here *** at []/graphicspath.tex; line 5 col 23
\begin{document}
Dummy text.
\end{document}
```

**Comment by casio7131** [comment]
I should say that I'm using LaTeXML version 0.8.1 on Ubuntu 16.04 LTS (inside a Windows 10 VirtualBox) - both are 64bit.

**Comment by brucemiller** [comment]
Ah, I hadn't realized that the paths had to be comma separated! Thanks for the report; fixed now in git.

**Comment by casio7131** [comment]
I will follow up here - or should I start a new ticket instead? - I'm new to github's systems so I'm not sure.

But I just got around to testing with the \graphicspath fix from above.  I'm not sure whether I'm making a mistake?, or whether there is another bug here? So I will post here and see.

See this ZIP for simple example <http://ul.to/c8nb1z9q> (sorry I can't see how to attach to the ticket).

Here is my: `\graphicspath{{../../fig/},{../fig/}}` where my figures are located in the 2nd folder.  When I use these commands:
```
latexml graphicspath.tex --dest=OUT.xml
latexmlpost OUT --dest=OUT.html
```
I get an error about missing graphics file:
```
(Graphics OUT.html processing...
Warning:expected:source No graphic source specified; skipping
	In Post::Graphics[@0x4656748] ->processGraphic
 0.03 sec)
```
But if I manually add the "../fig" folder to the path like this:
```
latexml graphicspath.tex --dest=OUT.xml --path=../fig
latexmlpost OUT --dest=OUT.html
```
then the figure is found.

So I'm wondering whether this extra `--path=../fig' is actually necessary? I would assume it isn't and that the ../fig folder should be picked up from \graphicspath. But maybe I'm wrong?
