### ISSUE TITLE
listings.sty.ltxml behavior differs from LaTeX. 

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#778]
Just wanted to point out (not sure if this is intended): If I use 
```
\begin{lstinline}
(-?)([0-9]+)?("."[0-9]+)?([eE](-?)[0-9]+)?
\end{lstinline}
```
then LaTeX processes this without a hitch but LaTeXML throws a nasty error.

**Comment by brucemiller** [comment]
So "lstinline" can be used as an environment, as well? Who knew!?!  Should be fixed now. Thanks for pointing that out.
