### ISSUE TITLE
Installation under Windows 7 (Unidecode problems)

### ISSUE THREAD

**Issue by SmnWntr** [brucemiller/LaTeXML#780]
Hi Bruce,
today I downloaded the latest LaTeXML-master.zip and tried to install it (under Windows 7) exactly the way I did it three months ago. After 
```
cpan Image::Size Parse::RecDescent UUID::Tiny
```
I run ```perl Makefile.PL``` and got "Warning: prerequisite Text::Unidecode 0 not found" which I didn’t get three months ago. May this be the reason why the installation (dmake / dmake test / dmake install) doesn’t succeed? When I run ```latexml ``` I get the error

```
 "Can't locate Text/Unidecode.pm in @INC"
```

Thanks for help.
Simon

**Comment by dginev** [comment]
Hi Simon,

This is indeed a freshly new dependency that Bruce introduced a couple of days ago. You should be able to easily fetch it by adding ```Text::Unidecode``` to your cpan line.

**Comment by dginev** [comment]
Managing dynamically changing dependencies is something you need to keep an eye on when working with Perl projects, but the ```perl Makefile.PL``` call will always notify you that there is something missing.

**Comment by dginev** [comment]
For my personal workflow I have switched to using the cpanminus installer, which takes care of always fetching any new dependencies for you. You can simply do

```
cpanm .
```

and it will build and install Perl project in the current directory with all its dependencies.  Ideally, enabling ```cpanm``` is as easy as ```cpan App::cpanminus```.
