### ISSUE TITLE
\graphicspath again

### ISSUE THREAD

**Issue by casio7131** [brucemiller/LaTeXML#787]
[I originally followed up in ticket #773 but I making a new ticket since it seems it was missed since that is closed]

But I just got around to testing with the \graphicspath fix from above.  I'm not sure whether I'm making a mistake?, or whether there is another bug here? So I will post here and see.

See this ZIP for simple example http://ul.to/c8nb1z9q (sorry I can't see how to attach to the ticket).

Here is my: `\graphicspath{{../../fig/},{../fig/}}` where my figures are located in the 2nd folder.  When I use these commands:

```
latexml graphicspath.tex --dest=OUT.xml
latexmlpost OUT --dest=OUT.html
```

I get an error about missing graphics file:

```
(Graphics OUT.html processing...
Warning:expected:source No graphic source specified; skipping
    In Post::Graphics[@0x4656748] ->processGraphic
 0.03 sec)
```

But if I manually add the "../fig" folder to the path like this:

```
latexml graphicspath.tex --dest=OUT.xml --path=../fig
latexmlpost OUT --dest=OUT.html
```

then the figure is found.

So I'm wondering whether this extra `--path=../fig' is actually necessary? I would assume it isn't and that the ../fig folder should be picked up from \graphicspath. But maybe I'm wrong?

**Comment by brucemiller** [comment]
Ugh, typo, so paths didn't get carried over into the processing-instructions; fixed now. Thanks for the report!
