### ISSUE TITLE
Tikz "\clip" does not seem to be taken into account

### ISSUE THREAD

**Issue by kaagithub** [brucemiller/LaTeXML#791]
Hi,

I just tested the 0.8.2 version and this still does not seem to work (I waited to post it): the clipping presented in the following example does not seem to appear correctly in the Epub I generated (I tested several viewers this time ;-)

http://www.texample.net/tikz/examples/venn-diagram/

```
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{shapes,backgrounds}
\begin{document}
\pagestyle{empty}
% Suppose we have three circles or ellipses or whatever. Let us define
% commands for their paths since we will need them repeatedly in the
% following:

\def\firstcircle{(0,0) circle (1.5cm)}
\def\secondcircle{(45:2cm) circle (1.5cm)}
\def\thirdcircle{(0:2cm) circle (1.5cm)}

% Now we can draw the sets:
\begin{tikzpicture}
    \draw \firstcircle node[below] {$A$};
    \draw \secondcircle node [above] {$B$};
    \draw \thirdcircle node [below] {$C$};

    % Now we want to highlight the intersection of the first and the
    % second circle:

    \begin{scope}
      \clip \firstcircle;
      \fill[red] \secondcircle;
    \end{scope}

\end{tikzpicture}

\end{document}
```

**Comment by brucemiller** [comment]
I don't know if there's something specific about ePub or ePub viewers here, but when I tested generating html (html5 w/ svg), it looks exactly the same in the browser as the pdf.  The ```\clip``` just causes the red portion to be the intersection of circles A & B, right?  Seems to work in the current code.

**Comment by brucemiller** [comment]
I just tried the Venn diagram example from TeXamples, and it works fine in html.  It's hard to see how conversion to ePub could break it, but if you're convinced that's the case, please reopen.
