### ISSUE TITLE
tikz matrices

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#794]
I'm trying to incorporate tikz matrices into my document (in order to create sign charts for sketching functions).  Unfortunately, it's giving all sorts of errors.

``` tex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \matrix {
    \node {1}; & \node {2}; \\
  }; % line 12
\end{tikzpicture}
\end{document}

```

latexml returns:

```
Driver file for pgf: \pgfsysdriver

HALIGN IN PGF!

Error:unexpected:\@@LTX@noalign Attempt to end mode text
    at /Users/tprescott/Documents/programming/latexml/tikz/minimal.tex; line 12 col 3
    current frame is boxing group due to T_BEGIN[{] at /Users/tprescott/Documents/programming/latexml/tikz/minimal.tex; line 12 col 3
    In Core::Stomach[@0x7fc8c59ca948] at /Users/tprescott/Documents/programming/latexml/tikz/minimal.tex; line 12 col 3
     <= Core::Definition::Constructor[\@@LTX@... <= Core::Stomach[@0x7fc8c59ca948] <= Core::Definition::Primitive[\@@open@i... <= ...

Error:unexpected:\@@close@column Attempt to close boxing group
    at /Users/tprescott/Documents/programming/latexml/tikz/minimal.tex; line 12 col 3
    current frame is mode-switch to text due to T_CS[\@@LTX@noalign] at /Users/tprescott/Documents/programming/latexml/tikz/minimal.tex; line 12 col 3
    In Core::Stomach[@0x7fc8c59ca948] at /Users/tprescott/Documents/programming/latexml/tikz/minimal.tex; line 12 col 3
     <= Core::Definition::Primitive[\@@close@... <= Core::Stomach[@0x7fc8c59ca948] <= Core::Definition::Primitive[\@@open@i... <= ...
```

followed by 12 more ``Error:unexpected:... Attempt to close boxing group'' and then another 9 errors.

``HALIGN IN PGF!'' is mentioned in #760, but I don't think is the problem here.

How can I incorporate a tikz matrix?

**Comment by dginev** [comment]
This continues to be a limitation of the tikz bindings, but your example now even produces a Fatal error. I will send a patch for the worst of it, but still won't allow you to properly use tikz matrices for now.

**Comment by brucemiller** [comment]
Got some ideas, but am going to have to bump this to the next release. Sorry.

**Comment by dginev** [comment]
Organizational comment: getting the basic tikz matrix support likely depends on halign, but is likely easier (and a requirement for) the tikz-cd package requested in #1280 .

**Comment by dginev** [comment]
I should mention that the minimal example mentioned in this issue is now operational with the latest latexml. We ought to try some more complex matrices and see if this is fully resolved.

**Comment by teepeemm** [comment]
All of my examples compile, but the nodes' text doesn't seem to end up in the correct place.  This:
``` latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\noindent before\\
\begin{tikzpicture}
  \matrix {
    & \node (A) {A}; \\
    \node{B};&& \node(C){C}; \\
  };
  \draw (A.south) -- (A|- C.south);
\end{tikzpicture}\\
after
\end{document}
```
Should produce
```
before
  A
B | C
after
```
but instead  the A, B, and C get shifted left and up.  If the entire matrix were shifted, I could account for that and unshift the matrix, but the line is drawn where the nodes were before being shifted out of place.

**Comment by teepeemm** [comment]
The positioning is better, but still not good enough for my tastes.  The document
```tex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\noindent before\\
\begin{tikzpicture}
  \matrix[row sep=3mm,column sep=3mm]{
   \node(left){L}; &&&&&& \node(right){R};\\\\\\\\
   \node(bottom){B};\\
  };
  \draw(left)--(right)(left)--(bottom);
\end{tikzpicture}\\
after
\end{document}
```
Produces the visuals
|pdf|html|
|---|---|
|<img width="152" alt="Screen Shot 2021-11-11 at 2 26 50 PM" src="https://user-images.githubusercontent.com/13021169/141366551-e1df6fd8-b1bf-47fc-9e62-3d5135bc178a.png">|<img width="108" alt="Screen Shot 2021-11-11 at 2 27 05 PM" src="https://user-images.githubusercontent.com/13021169/141366585-edbab02c-a73b-49d5-adf1-bd207e723d2a.png">|

On the other hand, in issue #1196, you say this might boil down to LaTeXML not having access to accurate font size information, and it won't be fixable in the short term.  Which I can work with, if necessary.

**Comment by dginev** [comment]
Thanks @teepeemm for the example! I'll reopen the issue to make sure Bruce and I see it again while discussing an upcoming large changeset motivated by pgf. Maybe we can already make things better, and if not, we can pinpoint which bits remain.

**Comment by brucemiller** [comment]
It seems that LaTeXML has troubles with "empty" columns & rows. It seems desirable to prune them, to end up with sensible html markup, but figuring out what's *really* empty isn't as easy as you'd think.

**Comment by brucemiller** [comment]
Ah, that was exactly the problem, but luckily there was a similar trick used for xy: Thanks for the report. Fix coming...
