### ISSUE TITLE
Typo in the manual

### ISSUE THREAD

**Issue by laszlokv** [brucemiller/LaTeXML#797]
The manual seems to have a typo here:
http://dlmf.nist.gov/LaTeXML/manual/usage/

It says:
The usage of these commands can be as simple as
latexml doc.tex | latexmpost --dest=doc.html

Shouldn't that be latexmlpost instead of latexmpost?

**Comment by brucemiller** [comment]
fixed.

**Comment by brucemiller** [comment]
Oh; and Thanks!
