### ISSUE TITLE
Why don't we use InputDefinitions for more package bindings?

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#807]
This is more of a question than anything else.  I was looking at making a binding for lipsum.  I found that simply using
`InputDefinitions('lipsum', type => 'sty', noltxml => 1);`
would almost work.  The only hitch is that lipsum.sty calls `\AtEndOfPackage{\unpacklipsum}` at (my) line 121, which calls `\@ifstar\@@unpacklipsum\@unpacklipsum` at line 61. This `\@ifstar` (but not the other two) causes:
`Error:misdefined:\@ifstar {}{} Expected a Token in expansion of \@ifstar {}{}`
I think this is related to the tokens being expanded before they can actually become boxes with content (because this is still before `\begin{document}`).  But the macros (even `\unpacklipsum`) seems to work as normal.

So it seems like we could have the binding simply `InputDefinitions`.  There are a few other bindings that do this:
algc, algcompatible, algmatlab, algorithm, algpascal, algpseudocode, babel, circuitikz, ifthen, pgfplots, t1enc, tikz-3dplot

There are some bindings that InputDefinitions and then redefine a few things:
algorithmic, algorithmicx, numprint, pgf, tikz

That seems to be it.  (There are a few others that `InputDefinitions` of something other than the package in the current binding, but that's not related to my point.)

It seems to me that this could be the default approach that we take for every package: start by `InputDefinitions`, and then use Perl to fix the things that don't yet work.  Obviously, we don't generally do this.  This brings me to my main question: why don't we start more of the 200+ bindings with `InputDefinitions`?  We've done this for all 8 of the alg* bindings, but only 9 of the other bindings.

I could see one reason to avoid `InputDefinitions` would be that it would add errors to the log (such as the error caused by lipsum), but it seems like we could adjust the logging to not count those errors (and possibly re-echo them as `Info` or `Warning`). Does there exist some way to do this?

Another difficulty would be that we'd have to double check that a package updating doesn't break anything on our end.  But at the moment, a package updating can also add a feature that then isn't present in our binding, leading to an undefined macro.

Another advantage is that the redefinitions would nicely track everything we need to do in order to directly input all TeX code and automatically load all packages for version 1.0.  If a redefinition is appearing in multiple bindings, then it would warrant further investigation.

This was somewhat discussed in #622 , where dginev pointed out that another downside would be that interpreting the style as TeX via LaTeXML would almost certainly be slower than loading Perl.  But in that case, we could stick with the current approach, and just InputDefinitions when we've found that it doesn't cause too much of a slowdown.  (Which could possibly be based on the length of the package.)

**Comment by dginev** [comment]
Yep, the summary is: 
 - until recent latexml versions, InputDefinitions couldn't handle enough of TeX. Now it largely can, ever since latexml became good enough to parse tikz
 - native definitions are significantly slower than the Perl definitions in loading
 - the dependency on a TeX installation is currently optional, and it is an open question if the concession of making it mandatory is worthwhile.

There is an option ```--includestyles``` which makes native loading of ```.sty``` and ```.cls``` files by LaTeXML the default behavior.

**Comment by dginev** [comment]
On a design level, writing Perl bindings has other advantages too, as it allows us to revisit the various markup being created by a package and make the markup as semantic as possible. Raw interpretation tends to create very low-level markup, which is not always good enough.

**Comment by brucemiller** [comment]
Excellent question!  What Deyan says is spot on,
but for "purely" presentational stuff, it can be
worthwhile, providing LaTeXML can simulate the TeX.
Maybe in your example, something's not quite right
with ```\@ifstar```, or ```\AtEndOfPackage```, or something?
Or maybe, we need to add a few special definitions for lipsum?
I'm not familiar with lipsum, so a test case would help here.

Part of the reason there aren't more simple bindings like
you suggest is that including one in the distribution implies
we've actually tested it :>  Your ````lipsum``` might be a
good candidate (after some tweaking).

And then there's the ```--includestyles``` that Deyan mentioned:
There's always the pipe dream that LaTeXML gets close enough
that we can turn it on by default.

And since you raise the subject, a really awesome contribution to
LaTeXML would be where you find packages that seem to work this
way, to set up a test case or two that exercise it thoroughly
and let us know.  That's the "easy" way to grow its coverage!

**Comment by teepeemm** [comment]
I've attached the file I've been using to experiment with lipsum.  The main point of lipsum is to print the "lorem ipsum" paragraphs, which LaTeXML clearly does.  The other options adjust how individual lipsum paragraphs end: with a space or not, and with a \par or not. It appears that these all match. (I've added "end" to each call to help see how they end.)

As I mentioned, a binding with just
```Perl
InputDefinitions('lipsum', type => 'sty', noltxml => 1);
```
only causes a single error:
`Error:misdefined:\@ifstar {}{} Expected a Token in expansion of \@ifstar {}{}`

It's possible to recreate that error in a shorter style file consisting only of:
```TeX
\let\cool@down=\relax
\newcommand\run@race{%
  \@ifstar\cool@down\cool@down
}
\AtEndOfPackage{\run@race}
```
I've discovered the following:
If the shorter file ends with
```TeX
\AtEndOfPackage{\run@race}
\AtEndOfPackage{\cool@down}
```
the error doesn't occur.
If the shorter file ends with
```TeX
\AtEndOfPackage{\cool@down}
\AtEndOfPackage{\run@race}
```
the error does occur.
If the shorter file ends with
```TeX
\run@race
\cool@down
\AtEndOfPackage{\run@race}
```
the error does occur.
If \run@race is changed to only call commands that are already defined:
```TeX
\newcommand\run@race{%
  \@ifstar{\typeout{star}}{\typeout{no star}}%
}
```
the error still occurs.
I'm not sure what all this means.

lipsum would really benefit from a direct InputDefinitions, since 90% of the file is just typing out 150 paragraphs of the lorem ipsum text.

If we can't figure out how to fix the bug in InputDefinitions, then the next best outcome would be to somehow adjust the logging so that the error doesn't appear (and doesn't count toward the 100 errors).  If all else fails, the binding could simply be:
```Perl
Info('Ignore Error',undef,'lipsum.sty',
     'The upcoming Error:misdefined:\@ifstar is unavoidable. Ignore it.');
InputDefinitions('lipsum', type => 'sty', noltxml => 1);
```
[lipsumTests.zip](https://github.com/brucemiller/LaTeXML/files/572001/lipsumTests.zip)

**Comment by brucemiller** [comment]
Somehow I overlooked that there was an actual bug being reported here --- I was procrastinating on solving the General problem of just reading in all style files.  And indeed, it's just a simple corner case with `\@ifstar`, which should be fixed now; Thanks for the report.

But then, I'm wondering if it's worth keeping this issue open as a discussion point for folks that want to comment, or verify which styles work, or such.  But basically, we're well aware of the general issue.

**Comment by dginev** [comment]
> But then, I'm wondering if it's worth keeping this issue open as a discussion point for folks that want to comment, or verify which styles work, or such. But basically, we're well aware of the general issue.

I think, given it is over a year later, the issue can now be closed and archived - it is still easy to find if people need a reference point, and anyone reading should feel encouraged to open a follow-up issue if needed.
