### ISSUE TITLE
Conditional compilation flag

### ISSUE THREAD

**Issue by ianhbell** [brucemiller/LaTeXML#811]
I have some conditional compilation code in my LaTeX manuscript to deal with pdflatex/xelatex/luatex compilation.  Is there a way to protect these macros from latexml with a macro that latexml defines?  It gets very confused when it hits xelatex stuff that it doesn't understand and it borks math image conversion.  I looked all over the docs, and couldn't find it described somewhere if it exists.  

If this capability doesn't already exist, consider this a feature request.

**Comment by dginev** [comment]
There is ```\iflatexml``` defined in latexml.sty, packaged in the distribution. Feel free to reopen if that doesn't work out.

**Comment by ianhbell** [comment]
Perfect.  Is that documented somewhere?

**Comment by dginev** [comment]
There are mentions of ```\iflatexml``` on the open web, but not in the LaTeXML Manual itself. Although the manual does mention that there are handy convenience utilities in latexml.sty. Can probably be extended further.
