### ISSUE TITLE
Unexpected pgfkeys and parsing a list as a floating point number in pgfplot's axis environment

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#813]
I'm trying to use pgfplots to plot graphs.  Unfortunately, some of the arguments to the axis environment don't seem to parse correctly.  With the following code:
```TeX
\documentclass{article}

\usepackage{pgfplots}
\pgfplotsset{compat=1.13}

\begin{document}

\begin{tikzpicture}
\begin{axis}[xmin=0, xmax=3, ymin=0, ymax=2]
\end{axis} % line 10
\end{tikzpicture}

\begin{tikzpicture}
\begin{axis}[xtick={1,2}, xticklabels={A,B}, xmin=0, xmax=3, ymin=0, ymax=2]
\end{axis} % line 15
\end{tikzpicture}

\begin{tikzpicture}
\begin{axis}[xtick={1}, xticklabels=C, xmin=0, xmax=3, ymin=0, ymax=2]
\end{axis} % line 20
\end{tikzpicture}

\begin{tikzpicture}
\begin{axis}[xtick=\empty, xmin=0, xmax=3, ymin=0, ymax=2]
\end{axis} % line 25
\end{tikzpicture}

\end{document}
```

At lines 10, 15, 20, and 25 (at each `\end{axis}`), I get 4 warnings:
```
Warning:unexpected:pgfkeys In package pgfkeys:
  I do not know the key '{/tikz/ydiscont}{}', to which you passed '',
  and I am going to ignore it. Perhaps you misspelled it
Warning:unexpected:pgfkeys In package pgfkeys:
  I do not know the key '{/tikz/xdiscont}{}', to which you passed '',
  and I am going to ignore it. Perhaps you misspelled it
Warning:unexpected:pgfkeys In package pgfkeys:
  I do not know the key '{/tikz/ydiscont}{}', to which you passed '',
  and I am going to ignore it. Perhaps you misspelled it
Warning:unexpected:pgfkeys In package pgfkeys:
  I do not know the key '{/tikz/xdiscont}{}', to which you passed '',
  and I am going to ignore it. Perhaps you misspelled it
```
What really confuses me is where `xdiscont` and `yxdiscont` come from, since they're not in the previous source and not in LaTeXML.  In addition to the 16 warnings, at line 15, I get
```
Error:latex:\GenericError Package PGF Math Error:
  Could not parse input '{1,2}' as a floating point number, sorry.
  The unreadable part was near the decimal separator ',2'.
  Do you need the option 'read comma as period'?
Warning:expected:<number> Missing number, treated as zero.
```
(xticklabels={A,B} doesn't cause an error, but the tick label is ``A,B'', so it looks like it didn't parse correctly.)  And at line 25, I get
```
Error:latex:\GenericError Package PGF Math Error:
  Could not parse input '' as a floating point number, sorry.
  The unreadable part was near ''.
Warning:expected:<number> Missing number, treated as zero.
```
In both cases, the output is the same as `xtick=0`, which is probably to be expected from "Missing number, treated as zero."

It's possible (but not ideal) to overlook the warnings, but getting an error every time I use axis means that I end up hitting the fatal 100 errors.  What I find strange about all of this is that the errors are coming from the pgf library, not LaTeXML.  So somehow, LaTeXML is misparsing these options before passing it on to pgf.  Can the axis environment handle the options xtick, xticklabels, xmin, xmax, ymin, and ymax?

**Comment by teepeemm** [comment]
I just noticed that the error for parsing `'{1,2}'` is also reported in #771.

**Comment by brucemiller** [comment]
I think I've fixed the issues reported here.  Thanks for the report!
