### ISSUE TITLE
bug in endnote conversion in case of existance of $$ in endnote

### ISSUE THREAD

**Issue by SepidehAlassi** [brucemiller/LaTeXML#819]
when there are inline math formulas in endnote and the formulas are indicated by "$$" instead of "$" the endnote conversion ends by encountering the first $$. 
example:

```tex
\endnote{
the end note text starting
$$ \Big[\frac mn\Big] = \int_0^1 \sqrt[n]{\Big(\ell \,\frac1x\Big)^m}\,dx, \qquad
   \Big(\frac pq\Big) = \int_0^1 \frac{x^{p-1}}{\sqrt[n]{1-x^n}^{n-q}}\ dx $$
some text } %endnote ends here
```

after xml conversion, result is 
```xml
<note mark="1" role="endnote">the end note text starting</note>  
```
The rest of endnote 
```tex
$$ \Big[\frac mn\Big] = \int_0^1 \sqrt[n]{\Big(\ell \,\frac1x\Big)^m}\,dx, \qquad
   \Big(\frac pq\Big) = \int_0^1 \frac{x^{p-1}}{\sqrt[n]{1-x^n}^{n-q}}\ dx $$
some text }
```
is ignored completely.

**Comment by dginev** [comment]
Thanks for the report, I have reformatted the description for readability. We'll take a look.

**Comment by brucemiller** [comment]
We'll need some more details; such as what version of LaTeXML you're running.  And a small, self-contained TeX sample.  For example, I don't know where your ```\endnote``` comes from. The only one in the distribution is part of revtex4, and it seems to work correctly for me. (other than the fact that it isn't put at the end of the document, but is treated the same as footnotes; See #520)
