### ISSUE TITLE
The quotation mark problem

### ISSUE THREAD

**Issue by aimsky** [brucemiller/LaTeXML#821]
the quotation mark in tex file is transformed to single quotation mark(\x{2018}\x{2018} and \x{2019}\x{2019}),but I want double quotation mark(\x{201C} and \x{201D}). What is the problem? and how to fix it?

**Comment by brucemiller** [comment]
Can you give a short TeX sample that shows the problem?  If I write ```A ``Quote.'' ``` using plain ASCII backquote & quote as one normally does in latex, the backquotes and quotes initially get converted into ```\x{2018}``` and ```\x{2019}```, as you say, but then the 2 pairs get combined into ```\x{201C}``` and ```\x{201D}```.

**Comment by aimsky** [comment]
thank you for your reply
For example:
`` local response'' is transformed to 
![qq 20161219102729](https://cloud.githubusercontent.com/assets/13769087/21299364/cccc4c32-c5d5-11e6-82a5-a7738231547f.png)
But the correct should be like this:
![image](https://cloud.githubusercontent.com/assets/13769087/21299395/27421f70-c5d6-11e6-8817-6f217360584f.png)
the 2 pairs are not combine into \x{201C} and \x{201D}
And I review the code in Tex.pool.ltxml:
`
DefLigature(qr{\x{2018}\x{2018}}, "\x{201C}",
  fontTest => sub { ($_[0]->getFamily ne 'typewriter') && (($_[0]->getEncoding || 'OT1') eq 'OT1'); });
DefLigature(qr{\x{2019}\x{2019}}, "\x{201D}",
  fontTest => sub { ($_[0]->getFamily ne 'typewriter') && (($_[0]->getEncoding || 'OT1') eq 'OT1'); });
`
It seems that it's useless.

**Comment by brucemiller** [comment]
You still haven't supplied a complete example, but from the image, it looks like your text is in typewriter font like ```\texttt{``local twitch response''}```. But latex won't combine those quote marks either; that's why latexml doesn't.

**Comment by aimsky** [comment]
Example:
```
\documentclass{article}
\usepackage[T1]{fontenc}
\begin{document}

\section{Testing Accents}
\abstract{\newline
``poor sleep'' is example
}
\end{document}
```
I know that the package fontenc result in the bug.But I need fontenc,,how to fix it?

**Comment by brucemiller** [comment]
Aha, indeed! I know the presence of ligatures depends on fonts, but not sure why the encoding test is there. At any rate, if it's there it should include T1 as well as OT1.  So, fixed in git;  Thanks for the report!
