### ISSUE TITLE
Missing autoref labels

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#822]
Hyperref has the convenient \autoref command, so that instead of `Section \ref{mylabel}`, I can type `\autoref{mylabel}`, and the entire text becomes a link, instead of the individual number.  Using the attached tex file, it seems that:
* LaTeXML autorefs correctly for chapters, figures, tables, and theorems
* LaTeXML doesn't autoref for sections, subsections, equations, items, and footnotes
* LaTeXML doesn't autoref for anything produced by \captionof (although the Info suggests that we shouldn't expect it to work)
* LaTeXML and LaTeX don't autoref for subsubsections (we've passed secnumdepth?)
* LaTeXML would autoref correctly for parts, but when I include parts, my xml has \xA0 characters sprinkled throughout the names, and latexmlpost refuses to run

For section and subsection (which I'm most interested in at the moment), having autoref work correctly appears to require an adjustment to `\@startsection` in LaTeX.pool.ltxml to include the correct frefnum (which would also make index entries display correctly).  Failing that, a hack on the postprocessing end could be something like
```XML
  <xsl:template match="ltx:section[@refnum][not(@frefnum)]">
    <xsl:attribute name="frefnum">
      <xsl:text>Section </xsl:text>
      <xsl:value-of select="@refnum" />
    </xsl:attribute>
    <xsl:apply-templates/>
  </xsl:template>
```
but this crashes with the fatal error `Cannot add attributes to an element if children have been already added to the element.`  (I also don't know xslt well enough to know if that's remotely correct.)

Would we be able to make autoref work for more of these options?
[autoref.tex.zip](https://github.com/brucemiller/LaTeXML/files/675073/autoref.tex.zip)

**Comment by brucemiller** [comment]
'Twould be really helpful if you happened to have a small document that exercised the various ways that autoref should work; that would make it a lot easier to fix (I'm suspecting that if it partly works, it shouldn't be terribly hard to get the rest working?)

**Comment by teepeemm** [comment]
Is there an aspect of autoref missing from the file I attached to the first comment here?  That should have been showing what I was talking about (except for possibly \xA0 showing up).

**Comment by brucemiller** [comment]
Oh, that zip file? It was printed in invisible ink, before! That's my story and I'm sticking to it!!

**Comment by brucemiller** [comment]
Should work now; Thanks for the report!
