### ISSUE TITLE
Errors with algpseudocode

### ISSUE THREAD

**Issue by davpoole** [brucemiller/LaTeXML#825]
We are converting our intro AI book to html using latexml (0.8.2). We have hit a snag with algpseudocode. I have created a small examples that does not work.

test.tex:
````
\documentclass{book} 
\usepackage{algpseudocode} 
%\usepackage[noend]{algpseudocode} 
\begin{document}
\begin{algorithmic}[1]
\Procedure{Proc}{$a,b$}
\State\Return{7}
\EndProcedure
\end{algorithmic}
\end{document}
````

Latex works fine.  The command
    latexml  --destination=dest.xml test.tex
says "Conversion complete: No obvious problems."
Then
    latexmlpost --destination=result.html dest
gives many errors of the form
````
dest.xml:11: validity error : xml:id : attribute value .l2 is not an NCName
      <listingline xml:id=".l2"><tag><text fontsize="80%">2:</text></tag><text f
                               ^
````
and does not produce an output. This is preventing us from converting our book!

-----
Aside: we are converting the second edition of our AI textbook from latex to HTML. The first edition used hyperlatex; see [http://artint.info/html/ArtInt.html](http://artint.info/html/ArtInt.html) but we needed to do much postprocessing by hand. We have decided to use latexml because it supports mathml and many packages. The book is written using high-level semantic commands and we don't mind defining separate macros to render  the latex and the html (which is how we got hyperlatex to work).  Thanks for providing latexml.

**Comment by brucemiller** [comment]
hmm... it seems the binding for algpseudocode is assuming that the algorithm package is loaded, and wants to number the lines from within an algorithm counter, but that's not happening in your case.  I've got to look into how to make it behave in both scenarios...

Nice textbook, btw!

**Comment by brucemiller** [comment]
OK, I think I've got it working right, now; checked in.  Thanks for the report and good luck with your book; let us know how it goes!
