### ISSUE TITLE
Two more problems with algpseudocode

### ISSUE THREAD

**Issue by davpoole** [brucemiller/LaTeXML#826]
Thanks for fixing the fatal errors with algpseudocode! There are two more problems I found, which should be easy to fix.

- noend does not work properly. It correctly doesn't put the "end" in, but incorrecly adds a blank line.
- the lines are supposed to be able to be labels, so that we can refer to lines in the text. We do this often.

I created a small test example. The file
http://artint.info/2e/test/test.tex should look like http://artint.info/2e/test/test.pdf but looks like http://artint.info/2e/test/result.html

To see this in context, see for exanple  http://artint.info/2e/html/ArtInt2e.Ch3.S5.SS3.html

Thanks!
David

**Comment by brucemiller** [comment]
Easy to fix, but a touch subtle. But reallly helpful test case.  Fixed now in git. Thanks for the report!!

**Comment by davpoole** [comment]
Great! It works perfectly now. Thanks!
