### ISSUE TITLE
Problem with conversion. How to include caption2.sty and babel.sty?

### ISSUE THREAD

**Issue by IvanRadiantStd** [brucemiller/LaTeXML#828]
```
Conversion complete: 1 warning; 32 errors; 30 undefined macros[\cyrshch, \cyrb, \cyrishrt, \cyro, \cyrery, \cyrch, \cyrv, \cyrz, \cyrf, \cyrsh, \CYRP, \cyru, \cyrsftsn, \cyrr, \cyrp, \cyrya, \CYRI, \cyri, \cyrd, \CYRV, \cyryu, \cyrl, \CYRN, \cyrs, \cyra, \cyrm, \cyre, \cyrn, \cyrt, \cyrk]; 
1 missing file[caption2.sty].
processing finished Wed Feb  8 06:40:26 2017

```
Please tell me how to solve this problem.

P.S. Sorry for my English

**Comment by dginev** [comment]
Hi @IvanRadiantStd . This issue has completely slipped by me and Bruce, sorry you got no reply in months!

If you are still reading on GitHub, you need a working texlive installation to have support for these advanced bindings, as latexml relies on the native language definition files of babel that come bundled in e.g. texlive. Please let me know if this is sufficient to get you moving further, and reopen/follow-up in a new issue if not. 

Again, sorry this slipped by us and we didn't reply for so long - I just noticed this issue today!
