### ISSUE TITLE
help with eprints in bibliography - a question

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#832]
Any advice on what would be the best approach for getting hyperlinks in HTML bibliography on references to eprints would be greatly appreciated.
I am working with aa style bibliography and using a separate bib style. The bib file is converted to XML separately with aa.cls.ltxml file preloded (`--preload=aa.cls.ltxml`). Several records in the original bib file contain references to eprints in eprint and (optionally) archive prefix fields, e.g.
`archivePrefix = "arXiv",`
`eprint = {1105.0879},`
and, where archive prefix forms part of the eprint string, 
`eprint = {astro-ph/0101235}`
After conversion to XML these fields become
`<bib-data role="archiveprefix">arXiv</bib-data>`
`<bib-links>1408.4668</bib-links>`
and 
`<bib-links>astro-ph/0101235</bib-links>`
and, in HTML
`<span class="ltx_text ltx_bib_external">1408.4668</span>`
`<span class="ltx_text ltx_bib_external">astro-ph/0101235</span>`
I would like to be able to be able to insert hyperlinks to eprint pages during conversion to HTML (I know which URLs correspond to which archive prefixes). I have unsuccessfully attempted to find a way to do it by modifying LaTeXML-bib-xhtml.xsl sheet.
What would be the best approach?
Thanks in advance.

**Comment by brucemiller** [comment]
Hmm. Not so clear if there's any single "best" approach (or even a "good" one!); there's 3 places you might try to customize:
* Packages/BibTeX.pool.ltxml by redefining ```\bib@field@default@eprint```, but that would apply to *all* eprint fields, and wouldn't easily be able to access the prefix.
* Post/MakeBibliography.pm (which is fairly opaque, alas)
* resources/XSLT/LaTeXML-bib-xhtml.xsl, which you were trying.
Actually, I would think that modifying the XSLT would be the easiest approach, but you've got to recognize that by the time the XSLT sees it MakeBibliography has already turned ```ltx:bib-links``` into ```ltx:text``` with ```class="ltx_bib_external"```, you'd want to define a template
```
<xsl:template match="ltx:text[@class='ltx_bib_external']">
````
(whether that was a good design decision or not...)

And while modifying the built-in stylesheet may be expedient for development or testing, in the long run, you'd probably benefit from providing your own top-level stylesheet (modelled on, perhaps, LaTeXML-html5.xsl), and adding/overriding the specific templates you need.  That way you won't get out of sync with the further evolution of the built-in stylesheets.

**Comment by goska** [comment]
Thank you, I'll have another go at modifying XSLT sheet(s).

**Comment by dginev** [comment]
Please reopen if you need more assistance here, will resolve for now! Thanks for reaching out.
