### ISSUE TITLE
Change to new MathJax CDN by April 30

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#834]
We have a script using the mathjax CDN here:
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/resources/javascript/LaTeXML-maybeMathjax.js#L6

As per their announcement, this needs to be migrated away by April 30:
https://www.mathjax.org/cdn-shutting-down/

**Comment by goska** [comment]
Changing Mathjax url in https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/resources/javascript/LaTeXML-maybeMathjax.js#L6 is straightforward. However, the problem mentioned on the announcement page is that one alternative CDN, cdnjs, recommended by the Mathjax team, does not provide automatic switching to the latest version, so the Mathjax URL would have to include reference to a specific Mathjax version, and may have to be updated every now and then. 
Perhaps it's worth waiting to see if another CDN option becomes available. 
Otherwise, a local installation may have to be considered.

**Comment by dginev** [comment]
A different way forward here may also swtich to KaTeX now that I think about it.

The idea of hosting any javascript library in the main LaTeXML repository feels quite unnatural to me.

**Comment by dginev** [comment]
But the simple solution of using a fixed version of MathJax may also be reasonable. Most/all production services would use this javascript file as a starting point template, and if they have an advanced setup for MathJax, they'll adapt the code directly.

**Comment by brucemiller** [comment]
Yes, the original idea was that ```LaTeXML-maybeMathjax.js``` was just an example implementation which folks might adapt to their specific needs. (although at times I was tempted to think it should automatically be applied, I resisted!)   Although the more "turnkey" the better, there are simply too many deployment choices to build them all in; better to provide the hooks (hopefully with examples) for folks to customize.

That is, I certainly have no intention of hosting, and am even rather annoyed at having to make a version choice in the example;   But I guess we have to do that.... (and look for options).

**Comment by brucemiller** [comment]
OK, patched.  I'll call it closed for now, but not sure what the long term solution ought to be.

**Comment by goska** [comment]
By local installation I meant local version of Mathjax installed on individual's server/machine. One issue I had with when trying to use local installation directly (without LaTeXML-maybeMathjax.js) and using LaTeXML 0.8.1 was the difficulty with passing configuration parameters when running latexmlpost, i.e. when I tried using latexmlpost with --javascript set to the reference to the local script, I could not use configuration parameter, as latexmlpost would not accept the query string. Of course, I could link to the script already installed on my server (when I could include the query string in the URL), but this would not work for everyone. Perhaps this has changed - I haven't tried with newer versions of LaTeXML.
