### ISSUE TITLE
\stackrel: behaviour incompatible to LaTeX

### ISSUE THREAD

**Issue by dominique-unruh** [brucemiller/LaTeXML#838]
The command `\stackrel` is supposed to typeset its first argument in smaller over the second argument. However, in combination with a size change in its first argument, it behaves differently than LaTeX's `\stackrel`. Namely, the size change escapes the first argument of `\stackrel`, and if the size change is followed by only one token, it does not affect that token.

(Tested with LaTeXML 0.8.2.)

Example document (expected behavior is that all examples look like the examples marked with "All is OK"):
```
\documentclass{article}
\begin{document}

\verb|\scriptscriptstyle| escapes the argument of \verb|\stackrel|, but does not apply to $z$:

$  x \stackrel{\scriptscriptstyle z}\leftarrow e$ 

\verb|\scriptscriptstyle| escapes the argument of \verb|\stackrel|:

$  x \stackrel{\scriptscriptstyle zz}\leftarrow e$

\verb|\scriptscriptstyle| not apply to $z$:

$  x \stackrel{{\scriptscriptstyle z}}\leftarrow e$

All is OK:

$  x \stackrel{{\scriptscriptstyle zz}}\leftarrow e$

All is OK:

$  x \stackrel{{\scriptscriptstyle {}z}}\leftarrow e$
\end{document}
```

**Comment by brucemiller** [comment]
Hmm, weird that was never noticed (more likely a regression).  Anyway, should be good now in the development version. Thanks for the report!

**Comment by dginev** [comment]
> Hmm, weird that was never noticed (more likely a regression). 

Should we add a unit test?
