### ISSUE TITLE
\textit is not correct when content is inline-formula

### ISSUE THREAD

**Issue by aimsky** [brucemiller/LaTeXML#841]
For example:
**\textit{$\Delta\phi $ }**  is transformed as below:

``<Math mode="inline" tex="\Delta\phi" text="Delta * phi" xml:id="S2.SS2.p2.m1">
<XMath>
       <XMApp>
             <XMTok meaning="times" role="MULOP">⁢</XMTok>
             <XMTok name="Delta" role="UNKNOWN">Δ</XMTok>
             <XMTok font="italic" name="phi" role="UNKNOWN">ϕ</XMTok>
       </XMApp>
</XMath><text font="italic"> </text>``

however, That is false. The expected result should be as below:

`<text font="italic">
<Math mode="inline" tex="\Delta\phi" text="Delta * phi" xml:id="S2.SS2.p2.m1">
<XMath>
       <XMApp>
             <XMTok meaning="times" role="MULOP">⁢</XMTok>
             <XMTok name="Delta" role="UNKNOWN">Δ</XMTok>
             <XMTok font="italic" name="phi" role="UNKNOWN">ϕ</XMTok>
       </XMApp>
</XMath>
</Math>
</text>`

How to fix this problem?

**Comment by brucemiller** [comment]
I disagree; what actually is the problem?  The ```\textit``` doesn't affect the font used in the math, and there is no text that needs to be in italic, so there's no need for the extra ```<text>``` wrapper.
