### ISSUE TITLE
v0.8.2 not in Debian (unstable) apt sources

### ISSUE THREAD

**Issue by blahah** [brucemiller/LaTeXML#846]
https://packages.debian.org/unstable/main/latexml

The latest is 0.8.1-1, which gives `0.8.1` in response to `--VERSION`.

Can `0.8.2` be pushed to the apt source?

**Comment by brucemiller** [comment]
Hmm, we're in transition with debian maintainers; I'll have to check on the status. Thanks for the report.

**Comment by dginev** [comment]
This is important for the upcoming 0.8.3 as well, best to resolve beforehand.

**Comment by brucemiller** [comment]
Just to see what happens, I'm going to assign this to @dginev :>

**Comment by dginev** [comment]
Ok, I have stepped up:
 * Have emailed the current maintainers with Bruce in CC
 * Have sent a reply to the Debian issue for packaging 0.8.2 at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858121

I'm doing this now largely in anticipation of 0.8.3 coming along soon, and wanting us to be in a good position to have it packages very soon after the release.

**Comment by brucemiller** [comment]
On 02/25/2018 11:48 AM, Deyan Ginev wrote:
> I'm doing this now largely in anticipation of 0.8.3 coming along soon, 

Calling my bluff, huh?
Thanks! (and sorry to put you, or anybody, on the spot!)

**Comment by norbusan** [comment]
I will update the packaging and commit a new release during the day.

**Comment by dginev** [comment]
> Calling my bluff, huh?

If you want a game to go faster, raise the stakes :> 

Great thanks to @norbusan for responding so quickly to my email, he has solved this GH issue by uploading a 0.8.2 package to Debian unstable, as can be seen here:
https://tracker.debian.org/pkg/latexml

So I'll go ahead and close, and try to get some more issues resolved for 0.8.3. That milestone passed 100 closed issues recently, so we're getting close to _something_
