### ISSUE TITLE
Invalid XML Using Test Case (Encoding)

### ISSUE THREAD

**Issue by DeathByRegex** [brucemiller/LaTeXML#855]
I get invalid XML (according to the schema in lib/schemas) when running some of the test cases through LaTeXML and then jing (from Jing-Trang). The particular error I am getting from Jing is : 

cp437.xml:17:42: error: value of attribute "thead" is invalid; must be equal to "column", "column row" or "row"

From where : 

>           <tr>
>             <td border="r" thead="true"/>

However, from the schema, it seems that the only allowed values of thead are : 
```

   <attribute name="thead">
        <a:documentation>whether this cell corresponds to a table row or column heading or both
(whether in head or foot).</a:documentation>
        <choice>
          <value>column</value>
          <value>column row</value>
          <value>row</value>
```

Is this a bug? This seems to occur for several dozen test cases (namely all of the encoding/ directory). I've attached the XML output from the cp437 test case.

[cp437.xml.zip](https://github.com/brucemiller/LaTeXML/files/1163370/cp437.xml.zip)

Thanks!

**Comment by brucemiller** [comment]
Looks like you're validating the output of 0.8.1 against the schema of 0.8.2 (or later); there was a change in the definition of that attribute.  LaTeXML should be consistent within each version, but sometimes incompatibilties between them creep in.

**Comment by DeathByRegex** [comment]
Bruce, thanks for the quick reply. I can confirm that I was validating against 0.8.2 schemas but generated the XML files with 0.8.1. All is now well, we can close this/mark as solved. Thanks again!
