### ISSUE TITLE
Issue with \partial command

### ISSUE THREAD

**Issue by SabinSnorlax** [brucemiller/LaTeXML#856]
Hi! I am using Authorea.com to write my research manuscripts, display on the site is based on LaTeXML.
When I use \partial within a math equation, this somehow gets recognized as the \par command + tial, so all I get is a display of "tial" instead of the symbol. I would be very grateful for some help with this. Cheers!

**Comment by dginev** [comment]
Hi @SabinSnorlax , this is an actual Authorea bug rather than a latexml one, so i will close here. You can write to us at Authorea directly at `help@authorea.com`. As it happens I was the one to introduce the weirdness you are reporting, will try to quickly correct it -- should be gone in a day.

**Comment by dginev** [comment]
Oh and I should mention that the root cause is Authorea using custom rules to try and overcome some of the easier limitations in coverage of KaTeX, which we use to render mathematics on the web in the Beta editor.

**Comment by SabinSnorlax** [comment]
Many thanks! I had reported this on Authorea first, but was then told to head over here.

**Comment by dginev** [comment]
Sorry for the roundabout path then! I have added a fix on Authorea, so the next deploy should mend things. We'll let you know when that's prepared.

**Comment by brucemiller** [comment]
On 08/01/2017 08:00 AM, Deyan Ginev wrote:
> this is an actual
> Authorea bug rather than a latexml one,

Ah, I'd suspected as much; local tests showed nothing,
and I couldn't see a way that it could happen.

Thanks for looking into this!
