### ISSUE TITLE
Output format JATS adds linebreak in Author fields

### ISSUE THREAD

**Issue by Thanathan-k** [brucemiller/LaTeXML#864]
While using the --format=jats option the output file of a .tex file will have strange added linebreaks in the authorfield of given-names.

See https://gist.github.com/Thanathan-k/4737da29913e6eeecb177dd2cf1fa651 for a very simple example.

**Comment by tkw1536** [comment]
This originates from an extra ``&#160;`` (non-breakable space) in https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl#L532. I have made a PR to fix it,  but I am not sure why it was there in the first place.
