### ISSUE TITLE
Jats Conversion breaks References

### ISSUE THREAD

**Issue by Thanathan-k** [brucemiller/LaTeXML#870]
After converting a arXiv document with LaTeXML and then with LaTeXMLpost into the Jats format the references are broken.

Example-Document: https://arxiv.org/abs/1708.08473

Problem: The references in the text still reference the old key (<xref ref-type="bibr" rid="BalanTsakmakis">), however the key is deleted from the bibliography and only the xml:id is set as id.

**Comment by dginev** [comment]
Thanks for the report!

Can you share with us the exact commands you ran, just so that we have a clear path to reproduce? Also feel free to attach the JATS document to this issue.

**Comment by Thanathan-k** [comment]
The commands I ran were:

latexml --destination=ManuscroptShutov_arXiv.xml ManuscroptShutov_arXiv.tex
latexmlpost --destination=ManuscroptShutov_arXiv_jats.nxml --format=jats ManuscroptShutov_arXiv.xml

The produced JATS document is:
https://gist.github.com/Thanathan-k/977d19f79a7f1e70d214dfb2632f8b14

**Comment by brucemiller** [comment]
Hmm... I just ran the document through the current LaTeXML, and I'm getting, eg
```<xref ref-type="bibr" rid="bib.bib39">[39]</xref>''' for ```\cite{Reiner}```, and with the corresponding bibitem starting ```<ref id="bib.bib39"><mixed-citation>Reiner M......```.  I don't know if that's actually correct, but it's consistent, and different from what you got.

What version of LaTeXML are you running?

**Comment by dginev** [comment]
[Syntax aside] Markdown reminder: using single ticks for inline `code` and triple-ticks for display style 
```
code
```

works best.

**Comment by brucemiller** [comment]
ok, but why does triple ticks not actually give display, unless it's on newlines?

**Comment by dginev** [comment]
Markdown is a limited thing.

**Comment by brucemiller** [comment]
Not sure if there is a bug here or not; what is the markup that is expected?

**Comment by brucemiller** [comment]
apparently it's ok, now.
