### ISSUE TITLE
Nested emph

### ISSUE THREAD

**Issue by HansOlsson** [brucemiller/LaTeXML#874]
As far as I can tell the following works correctly in pdflatex but not in LaTeXML (tested in 0.8.2):

`\emph{Nest \emph{me}}`

In pdflatex "me" is in normal font, in LaTeXML the entire text is italized.

**Comment by dginev** [comment]
Wow, applying emph twice _does_ reset the normal font, I had no idea myself. Marking as a bug, and thanks for the report!

**Comment by brucemiller** [comment]
Well, I knew that emph toggled, but I mistakenly assumed that the HTML folks knew that as well! :>.  I'd handled emph sorta semantically with just an ```emph``` element.  Now I was rethinking whether it should be better handled by CSS rules for emph, but that would be awkward to handle arbitrary depths, so let's just handle it by font switches.  Done! Thanks for the report!!
