### ISSUE TITLE
Enhancement for LaTeX.pool.ltxml

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#876]
When processing
```
\documentclass{article}
\includeonly{ a }
\begin{document}
\include{a}
\end{document}
```
the file a.tex is not included. I propose the following change:
```
diff --git a/lib/LaTeXML/Package/LaTeX.pool.ltxml b/lib/LaTeXML/Package/LaTeX.pool.ltxml
index 7cffe68..035f70d 100644
--- a/lib/LaTeXML/Package/LaTeX.pool.ltxml
+++ b/lib/LaTeXML/Package/LaTeX.pool.ltxml
@@ -3006,6 +3006,8 @@ DefPrimitive('\include{}', sub {
 DefPrimitive('\includeonly{}', sub {
     my ($stomach, $paths) = @_;
     $paths = ToString($paths);
+    $paths =~ s/^\s+//;
+    $paths =~ s/\s+$//;
     my $table = LookupValue('including@only');
     AssignValue('including@only', $table = {}, 'global') unless $table;
     map { $$table{$_} = 1 } split(/,\s*/, $paths);
```

**Comment by dginev** [comment]
Sounds quite reasonable to me! I'm sure it'll be a quick merge when @brucemiller gets a minute. Also feel free to make pull requests if you prefer @giovanni111 , it may be easier than having to paste the diff in by hand.

Thanks for another nice find!

**Comment by brucemiller** [comment]
Pretty reasonable, but have to also guard against spaces around the commas.  Should work better now.  Thanks for the report & suggested patch!
