### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by nthiery** [brucemiller/LaTeXML#878]
Dear LaTeXML devs,

Running 
```
latexmlc Cours.tex --dest latexml/cours.html
```
on the following `Cours.tex` file:
```
\documentclass{article}
\makeatletter
\AtBeginPart{\advance\beamer@tempcount by 1}
\makeatother
\begin{document}
  COUCOU
\end{document}
```
Triggers the following error:
```Fatal:misdefined:LaTeXML::Package::Pool::__ANON__ Can't locate method 'valueOf' via 'missing'
	at /usr/local/share/perl/5.24.1/LaTeXML/Package/TeX.pool.ltxml line 1220, <$IN> line 3.
	In Core::Definition::Primitive[\advance ... from TeX.pool.ltxml line 1220
	 <= Core::Stomach[@0x5579eb02b750] <= Core::Definition::Primitive[Begin] <= Core::Stomach[@0x5579eb02b750]
3 errors; 1 fatal error; 1 undefined macro[\AtBeginPart]

Conversion complete: 3 errors; 1 fatal error; 1 undefined macro[\AtBeginPart].
Status:conversion:3
3 errors; 1 fatal error; 1 undefined macro[\AtBeginPart]
Error! Did not write file latexml/cours.html
```

I am running the latest latexml installed by cloning this repo.

That's just for info. I can workaround this by redefining AtBeginPart to do nothing when running under latexmjl.

**Comment by dginev** [comment]
Thanks for the report! It looks to me that there is still sufficient reason to produce a regular error message (or more), but definitely no reason for a Fatal failure. Since this is a very nice minimal example, could be a nice and easy robustness patch.

May give it a stab this weekend.
