### ISSUE TITLE
latexmlmath breaks at "%"

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#884]
Calling
```
latexmlmath --mathimage=f.png \\begin{array}{l}1\\%\\\\0.01\\end{array}
```
fails with the messge
```
Couldn't find image for 'DirectMathImages:png:\beginDISPLAY \begin{array}[]{l}1\0.01\end{array}\endDISPLAY'
```
I presume that some re-formatting of the LaTeX code does not handle the \% adequately.

**Comment by brucemiller** [comment]
Yikes, indeed a % preceded by a single slash shouldn't get stripped out, but 2 slashes? Actually only when preceded by an even number of slashes; Regexp Funtime!! I think I got it though; Thanks for the report!!
