### ISSUE TITLE
Test Failure: t/81_babel.t

### ISSUE THREAD

**Issue by skellat** [brucemiller/LaTeXML#891]
I was attempting to install from scratch on Xubuntu 17.10 with Perl 5.26 using a current checkout since nobody upstream in Debian has packaged the latest version to flow downstream to Ubuntu and its community editions.

Test Summary Report
-------------------
t/81_babel.t         (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=25, Tests=292, 186 wallclock secs ( 0.10 usr  0.02 sys + 168.40 cusr 13.59 csys = 182.11 CPU)
Result: FAIL
Failed 1/25 test programs. 1/292 subtests failed.
Makefile:1654: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255

I ran `script` while running `make test` and have attached the output of that file hereto.

[typescript.txt](https://github.com/brucemiller/LaTeXML/files/1503326/typescript.txt)

**Comment by dginev** [comment]
```
t/81_babel.t ........... 2/6 
#   Failed test 't/babel/french'
#   at /home/skellat/Desktop/GGG/LaTeXML/blib/lib/LaTeXML/Util/Test.pm line 93.
Wide character in print at /usr/share/perl/5.26/Test2/Formatter/TAP.pm line 105.
# Difference at line 36 for t/babel/french
#       got : '      <p>ÆæŒœ@^~\o</p>'
#  expected : '      <p>ÆæŒœ@^~\°</p>'
```

Thanks for the report @skellat ! I was going to report this myself after I ensured my setup was correct - I have texlive 2017 on Ubuntu 17.10 and can reproduce.

**Comment by dginev** [comment]
The good news is that this is likely minor and localized specifically to the french babel bindings.

**Comment by brucemiller** [comment]
Yep, I've seen it as well; I'll have to find the offending system so I can test (& fix!)
FWIW, it's probably only an issue if you're using babel french.

**Comment by brucemiller** [comment]
Curious; the latest babel loads `french.ldb` when you ask for french instead of `frenchb.ldb` (so it missed my "fixes"). I've added a binding for `french.ldb` as well.  Should work now; Thanks for the report!

**Comment by dginev** [comment]
```
All tests successful.
Files=25, Tests=292, 560 wallclock secs ( 0.18 usr  0.06 sys + 520.45 cusr 37.28 csys = 557.97 CPU)
Result: PASS
```

Perfect, thanks!
