### ISSUE TITLE
Make "latexml --help" do something helpful

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#892]
It seems to just print the source code of the script. Ideally it'd display the usage for the command, along with stuff like this: http://dlmf.nist.gov/LaTeXML/manual/usage/usage.conversion.html

**Comment by brucemiller** [comment]
My documentation could be improved, but it's usually better than source code! :>

It sounds like the proper POD documentation isn't getting printed for some reason. What platform are you using?

**Comment by bfirsh** [comment]
Ah, I see! Probably something I haven't installed on my part then. To re-report this bug, perhaps it should print an error telling me what to install instead of just printing source code. ;)

Platform is Linux inside Docker. Here's the environment: https://github.com/arxiv-vanity/engrafo/blob/6c995a99dbfa5305b9709bdb1633694b2158dd08/Dockerfile

**Comment by brucemiller** [comment]
I don't know docker, but the code looks like it should be doing the right thing.  The usage display should only depend on `Pod::Usage`, which ought to be a core module, so I don't think you've missed a dependence. I'll have to see if I can google something up; It Shouldn't Happen!

In the meantime, hopefully `perldoc latexml` would give you useful info? (or just more source code!)

**Comment by bfirsh** [comment]
Yeah, Docker's doing nothing, it's just plain Debian with the commands listed in `Dockerfile` run on it.

```
root@8e0d3208d5b1:/app# perldoc latexml
You need to install the perl-doc package to use this program.
```

That explains it. :)

**Comment by dginev** [comment]
I managed to reproduce on Ubuntu 17.10. Interestingly latexmlc is not affected, but latexml and latexmlpost --help both print the source. Reason:

```
$ latexml --help
latexml (LaTeXML version 0.8.2; revision e97a0e37)
You need to install the perl-doc package to use this program.
```

I will reopen until we update the docs for Debain installs :+1: Thanks for the report!

**Comment by dginev** [comment]
P.S. Hope I am not spotting a trend of Perl getting gradually phased out of the default ubuntu packages...

**Comment by dginev** [comment]
We can also reorganize latexml and latexmlpost to use the Config.pm-based machinery for the latexmlc report. It works without the dependency, which is neat.

**Comment by bfirsh** [comment]
It's default Debian, FWIW, it's a very minimal distribution. (debian-minimal or whatever it is, or even less stuff.)

**Comment by dginev** [comment]
Oh, thanks for clarifying. I'm on a mainstream "bloated" distro though, so if Ubuntu is not offering it, we can't be silently expecting it, sadly

**Comment by brucemiller** [comment]
Jeez, why's everything keep changing... and btw, stay off my lawn!

**Comment by brucemiller** [comment]
You could be right, but you could be over-interpreting; there's less installed-by-default programming stuff these days on lots of systems (minimal, ubuntu, etc)... more "user" oriented.

**Comment by brucemiller** [comment]
Well, whatever the reason behind the change, I've updated the installation guide (should appear on the site soon). This detail is probably somewhat lost amongst all the special cases, but it is there.  Thanks for the report!

**Comment by bfirsh** [comment]
Thanks for fixing! 🎉
