### ISSUE TITLE
--graphicsmap option isn't validated

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#893]
The documentation implies that you can provide `--graphicsmap` as a space separated list of formats, but this isn't the case. I originally tried:

```
--graphicsmap="svg png gif jpg jpeg eps.png ps.png ai.png pdf.png"
```

But this just failed to convert any images, until I realised they have to be provided as separate arguments.

A few things:

1) Docs should be clearer, with an example of usage
2) latexmlpost should throw fatal error if options are invalid
3) Perhaps support this space-separated usage. It's much neater, and makes it clearer that you're overriding the default options with a new complete set of options. (I had to read the docs very carefully to realise that providing a single option overrode all the defaults, which is not the behaviour I expected.)

(I'll probably have a go at fixing this, but filing it here in case I don't get round to it!)

**Comment by brucemiller** [comment]
I was just trying to be concise, but I can see how it could be misinterpreted; I've clarified the doc. I also made it give an error when there are extra unrecognized arguments/options, which would have been the case here  (everything after the svg were seen as extra arguments).  Thanks for the report!

**Comment by bfirsh** [comment]
Nice thanks!
