### ISSUE TITLE
--graphicsmap=pdf.svg doesn't seem to work

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#894]
For something like this:

```
\includegraphics[width=0.75\textwidth]{Figs/BadParNet4}
```

It just converts `Figs/BadParNet4.pdf` to png. I'm not sure if I'm using this wrong, or whether this is not supported. If it's the latter, it should throw an error instead of silently not working.

**Comment by brucemiller** [comment]
Are you sure it didn't "convert" it to svg?  On my system, it converts it to a rather pointless svg that just includes a raster image (which is in png format, but supplied by an embedded data url).

**Comment by bfirsh** [comment]
Ah - you're absolutely correct. But I have uncovered an even weirder bug which was causing me to think this behaviour was happening! https://github.com/brucemiller/LaTeXML/issues/901

**Comment by bfirsh** [comment]
Also filed the "conversion" issue. ;) https://github.com/brucemiller/LaTeXML/issues/902
