### ISSUE TITLE
Small formatting issue with captions in float package

### ISSUE THREAD

**Issue by evoludolab** [brucemiller/LaTeXML#898]
In my .tex file I define a new float environment using
```\usepackage{float}
\floatstyle{plain}
\newfloat{simulation}{ht}{los}[chapter]
\floatname{simulation}{\bfseries Interactive lab}
```
This yields the expected output from latex for the caption:
![tex](https://user-images.githubusercontent.com/21139511/33637458-f019187c-d9d5-11e7-8866-95aae66c2948.jpg)
However, when converting to XHTML with lateXML the caption is formatted as
![xml](https://user-images.githubusercontent.com/21139511/33637490-1512be44-d9d6-11e7-9b82-7bb18fa4a112.jpg)
Note that there are two small, related problems: first, the colon is missing after the numbers and second the entire caption is set in bold instead of only `floatname` plus the counters.

It seems like lateXML is dropping a couple of closing characters after the counters and prematurely continues processing the rest of the caption. This should be easy to fix but unfortunately I did not succeed so far.

**Comment by dginev** [comment]
Thanks for the report!

**Comment by brucemiller** [comment]
Well, it *should* have been easy... but in any case is fixed now.  Thanks for the report!
