### ISSUE TITLE
Fatal Parse::RecDescent error

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#903]
An attempted conversion of LateX sources to XML failed with Fatal:misdefined:Parse::RecDescent::AUTOLOAD Not a HASH reference. The conversion was attempted with LaTeXML 0.8.1 installed as a secondary LaTeXML installation (export Path is used to instruct the system to use this installation) under CentOS. Conversion of the same files worked with an earlier version of LaTeXML 0.8.1 used as a single, primary installation. Conversion of the same files on the same machine completed with LaTeXML 0.8.2, and it also worked on a MacPro with 0.8.1. The issue is caused by a math formula.  I usually get warnings concerning maths but they don't cause failure to convert to XML. In case of the failed conversion, I did not get any warnings - just the fatal error. So, it almost looks as though RecDescent and/ or LaTeXML were operating in different modes during compilation with 0.81 and 0.8.2 on CentOS machine. Is there a setting I could change? Is it possible for the two versions of LaTeXML to use different Parse-RecDescent libraries? Form the path given in the error message I can see which where Parse-RecDescent library was loaded by LaTeXML 0.8.1, but I don't know yet which library was used by LaTeXML 0.8.2 as the software was installed for me by sysadmins of the CentOS server. Have you come across a similar error and would you be able to give any suggestions?
Any help would be much appreciated. Thanks.

**Comment by brucemiller** [comment]
Must be really bad math! But seriously... The actual parsing should only cause warnings. It seems to be a problem with having 2 installations and that some part of `Parse::RecDescent` is loaded wrongly in one case.  Generally we've tried to avoid such problems: each latexml executable looks for it's own modules relative to it's installation, and uses other modules relative to the actual perl that's being run.  

Are you using the same perl in each case? How was Parse::RecDescent installed?

**Comment by goska** [comment]
Thanks. I am also suspecting that `Parse::RecDescent` is loaded incorrectly in case of the secondary installation. Now that you have confirmed my suspicions, I am better equipped to ask the administrators (who installed that software) to investigate. Happy New Year!

**Comment by goska** [comment]
It turns out that I was told to export the wrong path to the secondary installation of LaTeXML. When I tried the path similar to the one I had used on my local machine, which resolved the problem.

**Comment by brucemiller** [comment]
Glad to hear this worked out!
