### ISSUE TITLE
Contributing instructions

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#904]
There don't seem to be any instructions for simple things like:

* How to get a development environment set up (seems to be similar to installing, but it's not clear whether installed `latexml` is the same one I'm working on in source directory)
* Running the tests
* Writing a test (and how to run a single test to iterate on it)
* Writing a new binding with a test (presumably the most common contribution you want)

I'm currently doing all of these things, so happy to write down what I am doing! Should I create a new section in the manual, or would you like them somewhere else? `CONTRIBUTING.md` in the root directory is a [pretty common pattern](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

**Comment by dginev** [comment]
We should make the wiki less hidden as a first step, I think @brucemiller came to like that space most - https://github.com/brucemiller/LaTeXML/wiki

We had a very impressive back-and-forth some time ago whether we should use `.md` files as is the github standard, and as you can see we have settled with the more alien `.pod` format, which is the Perl best practice here.

You could add the steps you go through as comments in this issue and we move them to the wiki, or just give you wiki permissions right away, or ... Will let Bruce decide. 

And we should definitely make whichever way we go clear from the readme. Thanks for the issue!

**Comment by brucemiller** [comment]
Wiki? Oh, yeah... we should make it less hidden! :>  Is there a way for the pod/md to be on top, or even omit the "code" from the initial page?  That would make more of the project info visible.  And, yes, we should make the existence of the wiki more visible.  In fact, should invite users to contribute their advice.  If I'm not mistaken, it already is writable by any github user.

**Comment by brucemiller** [comment]
Hmm, interesting: somebody just made a mod to the wiki, noting that the kwarc links to arXMLiv don't work any more!  Doesn't seem that I receive notifications when somebody modifies the wiki, but I think I'd like to.

**Comment by dginev** [comment]
@brucemiller you should star+watch this repository, then you see the notifications - I got one 👍 I also know those links are dead with a high likelihood of them not coming back, so those pages may need to be rewritten and updated... Looking at a mirror.

**Comment by skellat** [comment]
I’ll freely admit I made the change.  I’m still on furlough from Treasury so I want to be constructive.

**Comment by brucemiller** [comment]
@skellat; you did the right thing!  I was only surprised that I didn't get a notification from github.  I obviously watch this repo, but didn't star it; maybe that makes a difference? We'll see.

**Comment by brucemiller** [comment]
I've just done some reorganizing and fleshing out of the wiki pages.  There's now a how to contribute (not sure how to link from here!) It's a start at what you were asking for.  Take a look and feel free to improve it!
