### ISSUE TITLE
Bloated dbfile on macOS High Sierra

### ISSUE THREAD

**Issue by evoludolab** [brucemiller/LaTeXML#910]
I am experiencing a weird issue with bloated database files on macOS High Sierra (10.13)... Using a minimal laTeX file `HelloLaTeXML.tex` containing
```
\documentclass{article}
\begin{document}
Hello LaTeXML!
\end{document}
```
and executing
`latexml --dest=HelloLaTeXML.xml HelloLaTeXML.tex`
followed by
`latexmlpost --prescan --dbfile=HelloLaTeXML.db --dest=HelloLaTeXML.xhtml HelloLaTeXML.xml `
creates a database file `HelloLaTeXML.db` of over 40MB! Adding two more words to the tex-file results in over 70MB... As a consequence, for any reasonable tex-file the database quickly grows to GB's and the scan eventually needs to be aborted.

Everything works as expected on my other machine with macOS Sierra (10.12). In the above example the database amounts to about 16kB and the size does not change by adding two more words.

Just in case, I have installed lateXML 0.8.2 through macports and get the same results with TeXLive installed through macports or a separate installation of MacTeX (with the appropriate variant `port install latexml +mactex`).

This is a mystery to me...

**Comment by dginev** [comment]
Curious... I am seeing a 12kb DB file for your example on my Ubuntu machine. Can you compare the DB file versions on the two machines you are experimenting on?

For example I have 1.84:
```
$ perl -MDB_File -e 'print $DB_File::VERSION, "\n"'
1.84
```

The other obvious question is whether this is happening in a completely fresh directory, where there are no other cache files laying around... Bruce would have other ideas as well.

**Comment by evoludolab** [comment]
Thanks for the quick response!

I just realized that my other machine is running El Capitan (10.11) and not Sierra (10.12) as previously stated. However, I do have access to a third machine with 10.12 in case this becomes relevant.

When executing your perl-command, both machines (10.11 and 10.13) report version 1.835.

The problem is unchanged when starting in a pristine location.

**Comment by dginev** [comment]
Could you by any chance attach the 40 MB file for us to inspect? You would need to use a third-party hosting provider however, GitHub doesn't allow attachments that large. I think neither I nor Bruce have a 10.13 MacOS (or any MacOS on my part), so inspecting the file could be the most reliable path to diagnosing and patching.

Thanks for the report!!

**Comment by evoludolab** [comment]
Thanks! I have just uploaded the results to my owncloud:
[https://owncloud.math.ubc.ca/index.php/s/GjRte0RqfAvpOwD]

It's a folder containing the results for 10.11 as well as 10.13.

**Comment by dginev** [comment]
Thanks for that! As I should have expected, I can't naively access those DB files as they are platform-specific binary encodings (my `db_dump` chokes on them). So I should have asked you for the result of:

```
perl -MDB_File -MData::Dumper -e 'my %db=(); tie %db, "DB_File", "HelloLaTeXML.db"; print Dumper(\%db);'
```

instead

**Comment by dginev** [comment]
Or if you have the utility installed, it is a bit more reliable / easier to also run `db_dump HelloLaTeXML.db`.

**Comment by evoludolab** [comment]
I have added the dump of each database files to the above owncloud directories as `HelloLaTeXML.dump`.

Interestingly, only your perl command worked. `db_dump` reported `unexpected file type or format` for both the 'good' and the 'bad' database.

**Comment by evoludolab** [comment]
I found the culprit - it's macOS High Sierra (10.13)... something about berkeley-db has been changed behind the scenes and causes headaches.

Here are the links that got me on the right track:
- [https://stackoverflow.com/questions/46660971/how-to-install-perl-on-macos-10-13-high-sierra]
- [https://origin-discussions2-us-dr.apple.com/thread/8125401]

Looks like this will need to be addressed by macports (and the good people at macports are already aware of issues with perl and db [https://trac.macports.org/ticket/55207]). After some fiddling around I went with an ugly hack that (for now) seems to have resolved the issue:
1. uninstall perl `port uninstall perl5 perl5.24 perl5.26`
2. create links 
```
ln -s /opt/local/lib/db48/libdb.a /opt/local/lib/libdb.a
ln -s /opt/local/lib/db48/libdb.dylib /opt/local/lib/libdb.dylib
ln -s /opt/local/include/db48/db.h /opt/local/include/db.h
```
3. reinstall perl: `port install perl5 perl5.24 perl5.26`

Since this appears to be a rather deep lying issue with macports, perl and High Sierra, I hope a proper solution will become available in the near future. However, for now things seem to be running fine again.

Thank you very much for your support and Happy New Year!

**Comment by dginev** [comment]
Impressive debugging! This definitely goes into the "why do things keep changing?!" bug category that Bruce invented some time ago, platform-specific issues are quite the headache for us to resolve centrally. Great to see that there is a macports ticket open already!

In the long run, if there is no path forward, one could imagine the dependency being phased out for a more Perl-native solution, but let's hope that won't be needed.
