### ISSUE TITLE
best practices macro creation

### ISSUE THREAD

**Issue by physikerwelt** [brucemiller/LaTeXML#911]
I'm currently trying to use LaTeXML to generate MathML that is linked to the corresponding wikidata ids. Therefore I did create a simple package with two macros:
```LaTeX
\newcommand{\w}[2]{\lxDeclare[role=ID,meaning=#1]{\ensuremath{#2}}#2}
\newcommand{\wf}[2]{\lxDeclare[role=FUNCTION,meaning=#1]{\ensuremath{#2}}#2}
```
This works very well for simple cases. (90% of the cases I have.) However, there are some symbols that have a different presentation. For instance `(X,\Sigma)` which I would like to associate with the Wikidata id for [measurable space](https://www.wikidata.org/wiki/Q3058218). Now I'm searching for a way to define a macro that does not change the presentation, which is currently:
```xml
    <mrow id="p1.1.m1.1.6" xref="p1.1.m1.1.6.1.cmml">
      <mo stretchy="false" id="p1.1.m1.1.1" xref="p1.1.m1.1.6.1.cmml">(</mo>
      <mi id="p1.1.m1.1.2" xref="p1.1.m1.1.2.cmml">X</mi>
      <mo id="p1.1.m1.1.3" xref="p1.1.m1.1.6.1.cmml">,</mo>
      <mi mathvariant="normal" id="p1.1.m1.1.4" xref="p1.1.m1.1.4.cmml">Σ</mi>
      <mo stretchy="false" id="p1.1.m1.1.5" xref="p1.1.m1.1.6.1.cmml">)</mo>
    </mrow>
```
.
However it should change the content MathML to apply,symobl,arg1,arg2 in this case
```xml
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <apply>
        <csymbol cd="wikidata">Q3058218</csymbol>
        <csymbol cd="latexml" id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2">Q36161</csymbol>
        <csymbol cd="latexml" id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">Q739925</csymbol>
      </apply>
    </annotation-xml>
```
rather than
```xml
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <interval closure="open" id="p1.1.m1.1.6.1.cmml" xref="p1.1.m1.1.6">
        <csymbol cd="latexml" id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2">Q36161</csymbol>
        <csymbol cd="latexml" id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">Q739925</csymbol>
      </interval>
    </annotation-xml>
```
.
In this example
* Q3058218 is associated with [measurable space](https://www.wikidata.org/wiki/Q3058218)
* Q36161 is associated with [set](https://www.wikidata.org/wiki/Q36161)
* Q739925 is associated with [family of sets](https://www.wikidata.org/wiki/Q739925)
Any suggestions are highly appreciated.

**Comment by dginev** [comment]
Oh, and btw, this is pretty cool work @physikerwelt ! It came to me as a surprise that wikidate can be used as a content dictionary while reading your description, that could be highly pragmatic to get coverage. Very neat.

**Comment by physikerwelt** [comment]
@dginev since we intend to report on our results on Jan 18 I'm looking for a pragmatic solution. If I need to create 50 or 100 extra macros for each individual case  that is ok. Still better than rewriting the MathML source manually.

I was searching in the LaTeXML source and the documentation for some mechanism to describe presentation and content alongside. I found  http://dlmf.nist.gov/LaTeXML/manual/schema/schema.module.LaTeXML-math.html#schema.element.XMDual but I could not really figure out how to use it for my purposes. I was trying to define a macro \MesurableSpace@{a}{b} using something like DefMacro('\mesurableSpace{}' ... while I could not figure out by myself how to use the tokens in a way to create content mathml as described above, I got the impression that it should be possible with the current version of LaTeXML...

**Comment by dginev** [comment]
Oh, so you are ok with rewriting all instances of `(X,\Sigma)` with something like `\measurableSpace{X}{\Sigma}` or the sort?

If so, there can be a nice use of XMDual here indeed. I somehow misunderstood that you can't change the source formulas, my bad. Can give it a shot in the morning if Bruce isn't around.

**Comment by physikerwelt** [comment]
Yes. I can rewrite the input. Thank you very much for your help.

**Comment by brucemiller** [comment]
Well, this is an interesting morning greeting! Neat idea!

Assuming I'm understanding what you're after, it should be quite simple, but you've currently got to drop into the binding level (there's not yet a LaTeX way to declare this yet). For example:
```
use LaTeXML::Package;
DefMath('\XSet',      'X',      role => 'ID', omcd => 'wikidata', meaning => 'Q36161');
DefMath('\SetFamily', '\Sigma', role => 'ID', omcd => 'wikidata', meaning => 'Q739925');
DefMath('\measurableSpace{}{}', '(#1,#2)', omcd => 'wikidata', meaning => 'Q3058218');
1;
```
Then, you'd markup the expression you wanted as
```
\measurableSpace{\XSet}{\SetFamily}
```
and it should give what you wanted.

Incidentally, `\lxDeclare` is a bit more global than I think you're expecting: it adds a declaration in effect for the whole sectional unit that it appears in rather than just the immediately following expression. You're more likely to confuse LaTeXML by having it repeated everytime you use the symbol; you'd be better moving it outside the macro.

**Comment by brucemiller** [comment]
I should probably add that the upcoming Rethinking that @dginev refers to aims to make some of this cd+name stuff less of an afterthought, and formalize the notion that what you're trying to do is exactly what you *should* be doing.  Namely, at least every known symbol should have a cd+name, maybe even cdbase.  So, then the meaning attribute should be in the form `cd:name` or `cdbase:cd:name`, to encourage this, rather than separate attributes.

**Comment by physikerwelt** [comment]
Thank you very much @brucemiller 

It works like a charm. http://gouldi.wmflabs.org/2


![screenshot from 2018-01-03 21-53-07](https://user-images.githubusercontent.com/2777736/34521416-f9040930-f0d0-11e7-84af-cc2a9997f7d6.png)

**Comment by brucemiller** [comment]
Cool!

**Comment by dginev** [comment]
No need for XMDual?! DefMath is so smart. Closing here after the elegant solution 💯

**Comment by brucemiller** [comment]
On 01/03/2018 09:07 AM, Deyan Ginev wrote:
> No need for XMDual?! DefMath is so smart. 

Yep; DefMath makes one for ya!
