### ISSUE TITLE
Add a linebreak after "Appendix A" in HTML output

### ISSUE THREAD

**Issue by asmaier** [brucemiller/LaTeXML#913]
For document class book when we have in latex

    \chapter{Example}

this will be converted to

    Chapter 1
    Example

in HTML. However if it is a chapter inside the appendix

    \appendix
    \chapter{Example}

the latexml post processing will convert this to

    Appendix A Example

Note the missing linebreak between "Appendix A" and the title of the appendix. To be consistent also with the PDF output of latex, a linebreak should be inserted after "Appendix A" , so that the HTML looks like

    Appendix A
    Example

**Comment by brucemiller** [comment]
Aha, just a simple CSS fix. Done; Thanks for the report!
