### ISSUE TITLE
Add link to references to table of content in HTML output

### ISSUE THREAD

**Issue by asmaier** [brucemiller/LaTeXML#914]
It would be nice to have a link to the References section also in the table of content in the HTML output.

**Comment by brucemiller** [comment]
yeah, but you normally don't get unnumbered sections in the contents

**Comment by asmaier** [comment]
Actually in scientific books it is very common to have an unnumbered entry for bibliography, see eg. 
https://www.amazon.com/Classical-Electrodynamics-Third-David-Jackson/dp/047130932X
https://www.amazon.com/dp/9810241054/ref=sspa_dk_detail_1?psc=1
https://www.amazon.com/Gravitation-Cosmology-Principles-Applications-Relativity/dp/8126517557

**Comment by brucemiller** [comment]
well, yes, and DLMF as well. But I meant that LaTeX doesn't normally add it.
The normal latex tricks of playing around with addtocontents aren't implemented in LaTeXML.  And I'm not sure the hacks I used for DLMF are easily documentable in the short-term.

**Comment by asmaier** [comment]
I also wouldn't mind if the references/bibliography section get's a numbered entry in the table of content, if that is easier to implement. Donald Knuth does that in his book https://www.amazon.com/Art-Computer-Programming-Vol-Fundamental/dp/0201896834 . I just think there should be an easier way to navigate to the references in the HTML than selecting the last chapter and then scrolling down.

**Comment by brucemiller** [comment]
This should be working correctly now, at least if you use the usual LaTeX techniques for getting things into/out of the toc (`\addcontentsline`, etc)  Thanks for the report!
