### ISSUE TITLE
Update mathjax link in documentation

### ISSUE THREAD

**Issue by asmaier** [brucemiller/LaTeXML#922]
The documentation on http://dlmf.nist.gov/LaTeXML/manual/usage/usage.single.html states to use 
```
latexmlpost --format=html5 \
--javascript='http://cdn.mathjax.org/mathjax/latest/MathJax.js \
--destination=somewhere/doc.html doc
```
but this doesn't work anymore since April 2017 (see https://www.mathjax.org/cdn-shutting-down/). The correct call is
```
latexmlpost --format=html5 \
--javascript='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=MML_CHTML' \
--destination=somewhere/doc.html doc
```
The option `config=MML_CHTML` selects the MathML to CommonHTML rendering engine of MathJax (see http://docs.mathjax.org/en/latest/config-files.html#the-mml-chtml-configuration-file), which generated very good results in all browsers I tried (Firefox, Chrome, Safari). 
Maybe it should also be mentioned in the documentation that [a lot of browser don't support MathML](https://caniuse.com/#feat=mathml) and therefore using MathJax is the only option to generate a HTML with math formulas, which works in all browsers.

**Comment by dginev** [comment]
Yep, had a PR for the actual JS link in the code #834 when it was announced, but apparently no one remembered there is a similar link in the documentation. Good catch!

**Comment by brucemiller** [comment]
Actually, for the manual, it'd probably be better to point to the maybeMathjax javascript.

**Comment by brucemiller** [comment]
Fixed; Thanks for the report!
