### ISSUE TITLE
The token T_CS[\@ifpackagelater] is not defined

### ISSUE THREAD

**Issue by Grief** [brucemiller/LaTeXML#925]
1. I have a TeX file which does `\usepackage{tablefootnote}`.
2. I found `tablefootnote.sty` [here](https://svn.vu.nl/repos/article_TCC/tablefootnote.sty). 
3. I tried to transform the document with `--includestyles` flag (and LaTeXML built from the latest commit to master at the moment, because it contains the fix to make `includestyles` work)
4. I see (not only) an error:
`Error:undefined:\@ifpackagelater The token T_CS[\@ifpackagelater] is not defined.`

How can I workaround that?

**Comment by brucemiller** [comment]
Thanks for trying `--includestyles`, but this is an interesting counter-example: footnotes in tables is tricky for LaTeX, and the code is quite complex. But it turns out that footnotes in tables is trivial for LaTeXML; So, I've just provided a binding for `tablefootnote`!  Thanks for the report!
