### ISSUE TITLE
Some issues with the environment thebibliography

### ISSUE THREAD

**Issue by asmaier** [brucemiller/LaTeXML#930]
When using the simple environment for bibliography entries `\begin{thebibliography}...\end{thebibliography}` there are some issues, which don't occur with a bibliography generated by bibtex.To test this consider the following example document testbib.tex:
```
\documentclass[twoside]{report}
\usepackage[utf8]{inputenc}    
	
\begin{document}
\title{Test document}
\tableofcontents
\chapter{Introduction}
Lorem ipsum.\cite{mh}
Boring \cite{wie} test.
       
\begin{thebibliography}{99}
\bibitem{ac} A.Ahmad and L. Cohen. Journal of Computational Physics \textbf{12},
389-402 (1973)
\bibitem{mh} J. Makino and P.Hut. Performance Analysis Of Direct N-Body
Calculations. \textit{ApJS}, 68:833-856, December 1988
\bibitem{wie} R. Wielen, Veröffentlichungen Astr. Rechen-Institut Heidelberg
Nr. \textbf{19} (1967)
\bibitem{ars} J. Makino and S. Aarseth. On a hermite
integrator with ahmad-cohen scheme for gravitational
many-body problems. \textit{PASJ}, 44:141-151, April 1992
\bibitem{ars3} S.Aarseth. NBODY2: A direct N-body integration code. New
Astronomy 6 (2001) 277-291
\bibitem{gang}  E. Gamma, R. Helm, R. Johnson, J. Vlissides. Design Patterns,
Elements of Reusable Object-Oriented Software, Addison-Wesley, 1994
\bibitem{eff2} Scott Meyers. More Effective C++, Addison-Wesley, 1996
\bibitem{stl} Nicolai M. Josuttis. The C++ Standard Library, Addison-Wesley,
1999
\end{thebibliography}
\end{document}
```
After running
```
latexml testbib.tex --dest=testbib.xml
latexmlpost --format=html5 --javascript='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=MML_CHTML' --dest=testbib.html testbib.xml --splitat=chapter
```
the output HTML bib.html looks like
![testbib](https://user-images.githubusercontent.com/3169297/35013996-75a05744-fb0f-11e7-93e1-16451f7935fd.jpeg)

Compared to the PDF output the HTML has the following issues:

1. The title "Bibliography" is too small. It should be of the same size as the other chapter titles. But the fontsize is set to 100% instead of 200% and the fontweight should be bold, not just normal. 
2. The reference numbers should not be bold, but instead be in squared brackets like [1], [2], [3], ... 
3. The backlinks to the place of the citation are missing from the bibliography entries.

**Comment by dginev** [comment]
Thanks for the detailed issue, much appreciated!

**Comment by brucemiller** [comment]
I just fixed (2); I think (1) got fixed by a CSS correction in the meantime; and if you mean the "free" backlinks you get when you use a `.bib` files, they're not so free with a preformatted bibliography (sorry).

Thanks for the report!
