### ISSUE TITLE
Math fonts needs surrounding {-}

### ISSUE THREAD

**Issue by AndreG-P** [brucemiller/LaTeXML#931]
I'm still working with `latexmlc` and it works fine. Here is my input:
```
latexmlc \
  --includestyles\
  --format=xhtml\
  --whatsin=math\
  --whatsout=math\
  --pmml\
  --cmml\
  --nodefaultresources\
  --linelength=90\
  --preload=LaTeX.pool\
  --preload=article.cls\
  --preload=amsmath.sty\
  --preload=amsthm.sty\
  --preload=amstext.sty\
  --preload=amssymb.sty\
  --preload=eucal.sty\
  --preload=[dvipsnames]xcolor.sty\
  --preload=url.sty\
  --preload=hyperref.sty\
  --preload=[ids]latexml.sty\
  --preload=texvc\
  literal:"\frac{a}{b}"
```
However, when I enter `\mathbf{x}` there is a warning about "mathbf" should only appear in math mode and the output is a html fragment. Same for `\mathcal{x}`. When I enter `{\mathbf{x}}` everything works again...

**Comment by dginev** [comment]
Thanks for the report. Looks like the math guards of `--whatsin=math` may need a fresh look
