### ISSUE TITLE
Add a small preprocessor to LaTeXML

### ISSUE THREAD

**Issue by asmaier** [brucemiller/LaTeXML#933]
LaTeXML is not perfect, yet ;-) and some things, which do work nicely with pdflatex don't work with LaTeXML. But to still be able to use a single source file to generate PDF with pdflatex and HTML with LaTeXML it would be nice, if LaTeXML could conditionally include or exclude lines of latex in a preprocessing step. 

To give an example, this is a small latex file (which pdflatex can digest without problems), where I have added some special comments:

```
\documentclass[twoside]{ruthesis}      %<notlatexml>
%<latexml> \documentclass[twoside]{report}

\usepackage{cite,latexsym,amssymb,graphicx,amsmath,epsfig,array}
\usepackage[T1]{fontenc}
\usepackage[latin1]{inputenc}    

\begin{document}
       \include{Title/title}                %<notlatexml>
       \afterpreface                        %<notlatexml>
%<latexml> \tableofcontents
       \include{Chap1/chap1}
       \include{Chap2/chap2}
       \appendix

\end{document}
```

The meaning is simple: When a line starts with `%<latexml>`, this line should be uncommented and included in the latex presented to the LaTeXML parser. If a line ends with the comment
`%<notlatexml>`, this line should be excluded from the latex before it is fed into the parser. 
Here in the example you can see, that the lines, with commands specific to the unknown documentclass `ruthesis` are excluded. Instead for LaTeXML we use the simple document class `report` and manually add a table of content. 

I have written a very small python script `latexmlpre.py` (use it like `python latexmlpre.py in.tex out.tex`) which can already parse the special comments as decribed above:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

tex_out = []
with open(sys.argv[1]) as infile: 
	for line in infile:
		if not line.endswith("%<notlatexml>\n"):
			if line.startswith("%<latexml>"):
				tex_out.append(line[10:])
			else:
				tex_out.append(line)	

with open(sys.argv[2], 'w') as outfile:
    for line in tex_out:
        outfile.write("{}\n".format(line))
```
But although this works quite nicely for me, this has some shortcomings, e.g. the python script cannot follow the links to the include files. So I suggest that such a preprocessing step might be better done by LaTeXML itself.

**Comment by dginev** [comment]
There is a native LaTeX solution for this problem offered by `latexml.sty` that you could use - i have relied on it a lot in the past.

Namely the `\iflatexml` conditional which takes the form:

```
\iflatexml
 % code that will be executed / deposited only in the HTML processing
\else
 % code that will be executed / deposited only in the pdflatex processing
\fi
```

Would that solve your problem and remove the need of an extra preprocessor?

**Comment by dginev** [comment]
P.S. latexml is certainly not perfect, but it keeps surprising you with hidden features ;-)

**Comment by asmaier** [comment]
For my usecase of exchanging the document class when using LaTeXML I cannot use `\usepackage{latexml}`, because that statement can only be inserted after the document class has already been loaded. 
However I [learned](https://tex.stackexchange.com/questions/35855/placing-items-before-documentclass) that I can use \RequirePackage to do what I want :

```
\RequirePackage{latexml}
\iflatexml
    \documentclass[twoside]{report}
\else
    \documentclass[twoside]{ruthesis}
\fi

\usepackage{cite,latexsym,amssymb,graphicx,amsmath,epsfig,array}
\usepackage[T1]{fontenc}
\usepackage[latin1]{inputenc}    

\begin{document}
\iflatexml
    \tableofcontents
\else
    \include{Title/title}           
    \afterpreface                      
\fi
    \include{Chap1/chap1}
    \include{Chap2/chap2}
    \appendix
\end{document}
```

This solution works nicely with pdflatex and latexml. Thank you for this nice hidden feature.

P.S.: Unfortunately I couldn't install the latexml package via the usual `sudo tlmgr install latexml`. I needed to copy the `latexml.sty` file out of the LaTeXML directory `/usr/local/Cellar/latexml/0.8.2/libexec/lib/perl5/LaTeXML/texmf/latexml.sty` directly and in addition install the `comment` package as dependency via `sudo tlmgr install comment` to make it work. Maybe it would be a good idea to offer `latexml.sty` on CTAN, so it could be installed via the standard mechanisms?

**Comment by dginev** [comment]
Whether latexml.sty should be on CTAN, small as it is, is definitely a good question - would leave answering that to @brucemiller , personally I'm all for hosting it on CTAN _and_ keeping the current install steps in the latexml Make file.

**Comment by brucemiller** [comment]
Well, yes latexml.sty should be hosted on CTAN but really needs more consistent naming/calling conventions before doing that. But installing LaTeXML *should* install latexml.sty into the usual texmf directories where tex/latex should find it; did that not happen?

**Comment by asmaier** [comment]
No , it did not happen. But this may be due to my setup. I installed LaTeXML and BasicTex via Homebrew on Mac OS X. The homebrew package of LaTeXML has some issues (https://github.com/Homebrew/homebrew-core/issues/22903) and is probably also not installing the latexml.sty file correctly.

**Comment by brucemiller** [comment]
I think this has evolved into a question of publishing `latexml.sty` to CTAN (after getting it publishable) which is essentially a dup of #844, so I'm closing here.  Thanks for the report!
