### ISSUE TITLE
Length of List of tables and List of figures entries

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#936]
Where in LaTeXML 0.8.2 is the code which controls the length of List of tables and List of figures entries in HTML? Despite the use of LaTeX short captions (in square brackets) many entries get truncated (with ellipses added). In LaTeXML 0.8.1 short captions were fully displayed in lists of tables/figures.
Thanks,
Goska

**Comment by goska** [comment]
I have checked XML version of my document  - it contains untruncated toccaptions. 
I have found a statement in Post::Scan.pm which appears to be responsible for the truncation of toccaptions in the HTML:
``toccaption => orNull($self->truncateNode($doc, $self->cleanNode($doc,
$doc->findnode('descendant::ltx:toccaption', $node)))));``
Does this mean that I cannot stop the entriesgetting truncated without modifying the core LaTeXML itself?

**Comment by dginev** [comment]
Hi @goska , I am not personally familiar with this feature but the code of `truncateNode` is indeed using a constant value for the maximum length at the moment. So you would need to change that file directly, or have a refactor that exposes the parameter to the user, to make a change. At least from a glance reading.

**Comment by dginev** [comment]
Hm, so the max length is a class variable, so you may be able to try to redefine it from a binding, which may work if you are lucky - there still needs to be a refactor exposing it better, but maybe this can be a good stopgap?

In a custom `.ltxml` binding file of your choice (which you would need to load via a `\usepackage` in the source, maybe you already have one?) you can add:

```perl
$LaTeXML::Post::Scan::TOCTEXT_MAX_LENGTH = 100;
```

Can't be sure it will work without testing, but worth a shot if you're in a hurry.

**Comment by goska** [comment]
Thanks @dginev , I'll try.

**Comment by brucemiller** [comment]
Actually, this really was a bug with some experimental code that shouldn't have ended up committed as enabled.  Sorry for the runaraound.

**Comment by goska** [comment]
I tried added the code in a binding of one of the packages I use, but to no avail. I am using route: LaTeX -> (latexml) XML  -> (latexmlpost) HTML and I am not sure how the new value of TOCTEXT_MAX_LENGTH could survive this transformation.

**Comment by brucemiller** [comment]
perhaps I wasn't clear: I've fixed `LaTeXML::Post::Scan` so that it doesn't truncate (by default).

But you're also right: setting that variable in a binding won't carry through across `latexml+latexmlpost` (but presumably would in `latexmlc`). Such things will need a better config system, which is on the back burner atm.

**Comment by goska** [comment]
You were clear :-), but it is too late for me to start experimenting with a new version, and I cannot make changes in the currently installed one, so I was keen to see if  @dginev's suggestion would work.

**Comment by dginev** [comment]
In that case, you would need to switch to using `latexmlc` for my suggestion to work, as Bruce indicated. Sorry, should have made that clearer.
