### ISSUE TITLE
[bug] Inconsistent chapter numbering in 'book'

### ISSUE THREAD

**Issue by matteosecli** [brucemiller/LaTeXML#941]
Take a typical 'book.cls' document structure, as the following `MWE.tex`:
```latex
\documentclass{book}
\usepackage[english]{babel}


\begin{document}


\frontmatter
\chapter{Preface}

\mainmatter
\chapter{First Chapter}

\appendix
\chapter{First Appendix}

\backmatter
% References


\end{document}
```

The result is that the chapters in the the `frontmatter` are _not_ numbered, while the actual numbering starts in the `mainmatter`:
```
Preface
Chapter 1 - First Chapter
Appendix A - First Appendix
```

It seems that LaTeXML does not get it right. A simple conversion
```bash
latexmlc MWE.tex --verbose --format=html5 --destination=MWE.html
```
gives the following document structure:
```
Chapter 1 - Preface
Chapter 2 - First Chapter
Appendix A - First Appendix
```

**Comment by brucemiller** [comment]
Indeed; fixed now; thanks for the report!
