### ISSUE TITLE
[binding-request] subcaption.sty

### ISSUE THREAD

**Issue by matteosecli** [brucemiller/LaTeXML#943]
I currently disable the package and redefine
```latex
\renewenvironment{subfigure}[2][#1]{\begin{figure}}{\end{figure}}
```
which avoids the errors. However, the figure numbering and the `\textwidth` inside the subfigure are not correct.

**Comment by dginev** [comment]
Is this a bug with the existing [subfigure.sty.ltxml](https://github.com/brucemiller/LaTeXML/blob/dbc9b8833f45c7f41adc5517bc38a5ca785e4d3f/lib/LaTeXML/Package/subfigure.sty.ltxml) binding?

**Comment by matteosecli** [comment]
@dginev I'm sorry, my fault. The `subfigure` environment comes with the package `subcaption`, not from `subfigure` (indeed, they are incompatible). I changed the title accordingly.

**Comment by dginev** [comment]
Cool, thanks for clarifying!

**Comment by brucemiller** [comment]
I've just checked in a fairly preliminary version of subcaption. it's missing all the styling, but I'll come back to that later.  I'm going to go ahead & close, but if the lack of styling or other errors arise, please open a new issue (or reopen).  Thanks!
