### ISSUE TITLE
Errors thrown by latexml when URLs defined in baseurl contain unescaped underscores

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#950]
LaTeXML 0.8.2
I am experiencing another problem with underscores in URLs when attempting to convert LaTeX document to XML, this time when they are used in baseurl definitions, e.g.
`\hypersetup{baseurl=https://example.com/tests_converted}`
causes in error:
`Error:unexpected:_ Script _ can only appear in math mode
        at /somelocation/mydoc.tex; line 404 col 79
        In Core::Definition::Primitive[Subscript] from TeX.pool.ltxml line 3583
         <= Core::Stomach[@0x29d60c8] <= Core::Gullet[@0x298b9a8] <= Core::Stomach[@0x29d60c8] <= ...
`

**Comment by dginev** [comment]
The definition may need to be switched to Semiverbatim, it's an easy one-line fix. You should be cautioned that latexml ignores hypersetup entirely, from what I see in the binding:

```perl
# \hypersetup{keyvals} configures various parameters,
# I think none matter much to latexml, but we do need to at least ignore it.
DefMacro('\hypersetup{}', '');
```

CC @brucemiller here

**Comment by dginev** [comment]
That said, your `baseurl` parameter may just be meaningful enough that we may want to support it in latexml? Then it goes from a one-line fix to a small enhancement project.

**Comment by goska** [comment]
I use `baseurl` in the following scenario:
In text we have hyperlinks to large (very large) hi-resolution versions of some images, which need to work in the published version as well as in the private test version available at a different URL before publication. These images cannot be made publicly visible before the publication and, as there are a lot of them, we would like to use relative URLs in the links, so only `baseurl` needs changing when documents are published at a different destination URL.
We generate PDF and HTML versions from the same LaTeX source.
Do you know of a different, not involving `baseurl`, way of achieving our objective?

**Comment by brucemiller** [comment]
Interestingly, most of the code for this was in place, just perhaps not in the right place.  It should work now; Thanks for the report!
