### ISSUE TITLE
svmult.sty: version update + dual heading numbering

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#955]
Reported on an arXiv paper at https://github.com/arxiv-vanity/engrafo/issues/231

On some reading of [svmult.cls](http://www.eso.org/~rfosbury/research/Chile-AGN/lnp-agn_Mar06/svmult.cls) it comes down to that package supporting **both** the numart and book numbering schemes, i.e. starting with section or starting with chapter.

They need to be explicitly toggled by using `\title` or `\title*`. This is in fact recognized in the latexml binding:

```
# Oddly, they allow * on \title to affect numbering (* => numart, none => book)
```

The .cls file uses the usual heavy handed counter redefinitions based on this switch, which is gnarly to reimplement, but doable?

Another idea is to do something I've implemented in the past as a post-processing step after latexml, but this time as possibly a part of the crossref machinery in post-processing? Namely, to do a loop over all heading numbers and if they **all** have a leading zero, to trim that zero away. I recall there were some discussions that having a 0 chapter makes sense in some rare cases, but if the entire document is situated in the zero chapter, probably less so?

**Comment by dginev** [comment]
Another tiny peculiarity that turns this paper into an `error` category instead of a `warning` category is that it is using a more recent version of svmult `version 5.4 (25-Jun-07)` which also natively defines `\url` (the cause of error).

Link to the up-to-date version:
https://raw.githubusercontent.com/Microsoft/AirSim/master/docs/paper/svmult.cls

**Comment by brucemiller** [comment]
This one should basically be fixed, at least as regards svmult.  The given document does give a validation error, due to the authors not using an `\appendix` command; Perhaps we'll have to revisit how the schema represents appendices in the future.  For now, I'll call this one fixed! Thanks for the report!!
