### ISSUE TITLE
Infix \vert produces wrong math output

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#958]
I have distilled a minimal example from the [arxiv-vanity 1603.00788](https://github.com/arxiv-vanity/engrafo-issues/issues/102), which (besides some missing package issues, notably glossaries.sty) has some broken equations.

The core problem comes from a redefinition of `\mid` as:

```tex
\documentclass{article}

\usepackage{amsmath}
\DeclareRobustCommand{\mb}[1]{\mathbf{\boldsymbol{#1}}}
\renewcommand{\mid}{~\vert~}
\newcommand{\mbx}{\mb{x}}
\newcommand{\mbtheta}{\mb{\theta}}

\begin{document}

$p (\mbx\mid\mbtheta)$

\end{document}
```

The problems are two-fold:
 * First, firefox renders the MathML with the vertical bar as prefix, as opposed to the regular probability syntax in the PDF:
    - Firefox: ![ffmath](https://user-images.githubusercontent.com/348975/37333360-d875c016-26b1-11e8-9067-869cf8f908b3.png)
    - PDF: ![pdftest](https://user-images.githubusercontent.com/348975/37333368-db666a14-26b1-11e8-884b-b011aa57ec01.png)

    - I haven't checked the mathjax rendering, but there comes part 2 of the issue.

 * Second, the tex attribute is very low-level and out of scope for renderers like MathJax, because of commands such as `\leavevmode` and `\nobreak`. This may not be latexml's problem to solve, and could indeed be better addressed by solving #432 , which suggests adding a "high-level macro" math annotation attribute. My minimal example produces a slightly different string, but on arxiv-vanity it is:

   ```tex
   p(\mathbf{\boldsymbol{x}}\leavevmode\nobreak\ |\leavevmode\nobreak\ \mathbf{%
   \boldsymbol{\theta}})
   ```

**Comment by dginev** [comment]
I should also attach the presentation MathML that I made a FF screenshot for:
```xml
<mrow>
   <mi>p</mi>
   <mo>⁢</mo>
   <mrow>
      <mo stretchy="false">(</mo>
      <mrow>
         <mo rspace="5.8pt" stretchy="false">|</mo>
         <mo>⁡</mo>
         <mpadded width="+3.3pt">
            <mi>&#x1d431;</mi>
         </mpadded>
         <mi>&#x1d73d;</mi>
      </mrow>
      <mo stretchy="false">)</mo>
   </mrow>
</mrow>
```

**Comment by brucemiller** [comment]
Ah, simple problem; when I tweaked the grammar to recognize various forms of VERTBAR as infix, I forgot to update the grammatical role so postprocessing would treat it as infix.  Fixed now! Thanks for the report.
