### ISSUE TITLE
HTML subfigures via flexbox rather than tables?

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#979]
I was inspecting an arXiv document (1802.06832) which has 4 subfigures a)-d) in its Results section and noticed they don't reflow in the HTML.

They are currently marked as 4 `td` table cells with class `ltx_subfigure` in the same `tr` row. 

The fixed single-row display looks quite bad even on large displays, as it is significantly wider than the main article width. And on small displays you end up with a huge horizontal scroll, which is just as bad. 

As I recently did some flexbox work with the moderncv binding, I'm wondering if @brucemiller would see that as a better mechanism for presenting the subfigures. That would give us decent reflow, and we can contain the max-width to a reasonable responsive width.

**Comment by dginev** [comment]
Here is a screenshot from the arXiv PDF, as viewed in my 27'' screen:
![pdf](https://user-images.githubusercontent.com/348975/39405334-50097950-4bac-11e8-9261-56f178deb883.png)

and the Firefox rendering of the subfigure table by the current latexml master (with the etoolbox PR):
![firefox](https://user-images.githubusercontent.com/348975/39405346-738cfd8e-4bac-11e8-8bbd-0ddaa34e56ae.png)

They manage to overflow even my 27'' screen :wilted_flower:

**Comment by dginev** [comment]
TeX snippet:
```tex
\begin{figure*}[t!]
	\centering
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{bps_word_error}
    \caption{Word error as bits per sentence changes for 0.05 bit erasure probability. \label{fig:bps_error}}
    \end{subfigure}%
    ~
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{bdr_word_error}
    \caption{Word error as erasure or bit-drop rate increases for 400 bit encoding. \label{fig:bdr_error}}
    \end{subfigure}%
    
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{len_sentence_word_error}
    \caption{Effect of sentences of different sizes with 400 bit encoding, 0.05 drop rate. \label{fig:sen_len_error}}
    \end{subfigure}%
    ~
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{example_embedding}
    \caption{Sample embeddings mapped to two dimensions using manifold dimensions with hamming distances between codes. \label{fig:example_embedding}}
    \end{subfigure}
    \caption{Performance plots.}
    \spaceup
\end{figure*}
```

**Comment by dginev** [comment]
Cool, then I'll take a stab at the subfigure case as a first MVP, and I invite you to give me details on what other latex paths end up depositing such blocks. For now I'm thinking that you may mean to auto-wrap any `\includegraphics` macro in a flex container?

**Comment by brucemiller** [comment]
Indeed; I think what you're going to find is that it's all done in `LaTeXML-para-xhtml.xsl`, and it creates a table wrapper if there are more than one figure, table, graphics, .... So the trick will be to wrap it in something simpler, probably just a div, and applying the appropriate CSS.

**Comment by bfirsh** [comment]
We actually do this in the current version of Engrafo - we rewrite the tables to be divs arranged with flexbox. Tables are much harder to make responsive.

**Comment by bfirsh** [comment]
This is a great example of a paper that would benefit from using flexbox:

https://www.arxiv-vanity.com/papers/1602.07188/

Ideally the images would be laid out automatically across several rows, because they can't all fit side-by-side.

**Comment by dginev** [comment]
Bookkeeping comment: We also need #1322 fixed before this issue can be properly made to work. Figure 1.3 in arXiv:2105.04026 is another good test (2 rows, 4 subgraphics on each, in the PDF) to test with here.

**Comment by dginev** [comment]
This was fixed some time back, but the issue remained open. Closing now.

**Comment by goska** [comment]
Do I understand correctly that there are plans to implement automatic arrangement of individual images within figures (not subfigures) in a responsive grid (i.e. number of images per row corresponding to the number images per line in LaTeX, individual images being sized responsively)?

**Comment by dginev** [comment]
@goska some care has already been put in place to keep TeX-authored line breaks as hard breaks in the final HTML figures. So authors that e.g. rely on `\\` ought to get the same grid rows in a wide HTML display as they would in a PDF. 

Naturally, on a horizontally narrow display there will always be a single column of 1 image per row, so the `(top)` and `(bottom)` annotations from a caption would have to be reverse-engineered by readers using say a handheld mobile device, where a 2x2 figure becomes a 1x4 figure and e.g. "top-right" now means "row 2".

As to the example paper, it uses a somewhat implicit technique to lay out the subfigures. Take for example:
```tex
\begin{figure}
  \begin{center}
    \includegraphics[width=0.5\textwidth]{./FluxLossS9R1T2nomotion_new.pdf}
   \includegraphics[width=0.5\textwidth]{./FluxLossS9R1T2fullmotion_new.pdf}
  \end{center}  
	\caption{\small{The fraction of measured flux in the CCD for strip 9, row 1 and FoV 2 in AF is plotted
	as a function of the centering offset with no AC motion
(top) and maximal AC motion (bottom). For assumed maximal centering offsets of about one pixel the dependence on the 
colour $V-I$ of the 
source is the dominating effect for AC flux loss with variations up to 1.1 percent.}
\label{fig:loss}    
}
\end{figure}
```

Had that been written with just a single space less, pdflatex would have fit the figures together on the same line, as in:
```tex
    \includegraphics[width=0.5\textwidth]{./FluxLossS9R1T2nomotion_new.pdf}%
   \includegraphics[width=0.5\textwidth]{./FluxLossS9R1T2fullmotion_new.pdf}
```

We could try to detect such cases, but latexml has to be very accurate in tracking sizing, as the intention to use multiple rows is not directly available from the source markup. Compare to the explicit break:

```tex
    \includegraphics[width=0.5\textwidth]{./FluxLossS9R1T2nomotion_new.pdf}\\
   \includegraphics[width=0.5\textwidth]{./FluxLossS9R1T2fullmotion_new.pdf}
```

which should already be getting preserved. Feel free to open a new ar5iv issue for the article in question, I could at least keep this upgrade in mind when we feel extremely confident that subfigure sizing is a solved problem in latexml.

**Comment by goska** [comment]
@dginev, thank you. Handling responsive figures can be challenging, I know (this includes the use of large numbers of individual image files per figure). Unfortunately some scientists are used to fixed print layouts and use grid references extensively. I'll raise an ar5iv issue, if only for reference.
