### ISSUE TITLE
Section embedded within other section in sample2e.tex

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#984]
Looks like https://github.com/brucemiller/LaTeXML/issues/959 is now fixed, but I'm seeing another regression when trying to bump LaTeXML. I _think_ it's in d18cdad..fd566f13477a2c5807ebd22e5d52f7bbd27c4d75 somewhere.

It's a problem with [sample2e.tex](https://github.com/arxiv-vanity/engrafo/blob/9730fa1038637034dbc679bdf10cf0d902008e90/tests/documents/sample2e.tex), a test document that is bundled with LaTeX. It's quite hard to explain, but quite obvious if you just render it and view the DOM. Basically, Section 2 is embedded inside the last paragraph of section 1. Some of the stuff in that last paragraph is also messed up (like the footnote, which should be in its own paragraph), which I think it is causing it to mess up everything following that.

Here is a screenshot of the DOM which shows the problem more clearly:

<img width="493" alt="screenshot 2018-05-02 19 01 35" src="https://user-images.githubusercontent.com/40906/39534878-44dc297e-4e3b-11e8-9fb2-e46ae9717f17.png">

Ref https://github.com/arxiv-vanity/engrafo/pull/292 (As an aside: our tests have HTML snapshotting. I have committed the broken output so you can see the diff of the HTML if you expand the large diff in the github UI.)

**Comment by dginev** [comment]
Thanks for the report! We'll take a look. And it would also be great for us to ensure conformance with your test harness before we release 0.8.3, which should be coming up soon.

**Comment by dginev** [comment]
First issue I can spot here is a couple of nested `ltx:text` elements (debugging on the XML, rather than the HTML), for the latex:
```tex
\mbox{\emph{itemnum}}
```

creating:
```xml
<text><text class="ltx_emph" font="italic">itemnum</text>
that...
```

note that the outer text was not closed, and the reason seems clear from the binding:
```perl
DefConstructor('\mbox {}',
  "<ltx:text _noautoclose='1'>#1</ltx:text>", mode => 'text', bounded => 1,
  sizer => '#1',
  beforeDigest => sub { reenterTextMode(); });
```

I wonder if this is a bug with the implementation of `_noautoclose` ?

**Comment by dginev** [comment]
It is indeed a bug because that outer `<text>` has _no_ closing tag at all.

**Comment by dginev** [comment]
I can now also confirm removing the `\mbox` returns the document to correct markup (including the HTML), so that should be the main and only issue.

**Comment by brucemiller** [comment]
ok, I think I've got it fixed this time (Really!)  Thanks again!

**Comment by bfirsh** [comment]
Nice! Thanks!
