### ISSUE TITLE
\the\value expansion

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#989]
This is a question related to my etoolbox testing (#978 ). I decided to test the math in the etoolbox counter machinery via:

```tex
\newcounter{countfour}
\defcounter{countfour}{2+2}
\the\value{countfour}
```

which works in pdflatex and prints 4, as expected. In latexml there is an error of the kind:
```
Error:expected:<register> A <register> was supposed to be here
	at /home/dreamweaver/git/my-LaTeXML/t/expansion/etoolbox.tex; line 30 col 21
	Got T_OTHER[4]
	Next token is T_SPACE[U+000a/LF]
	In Core::Definition::Expandable[\the Reg... from TeX.pool.ltxml line 921
	 <= Core::Gullet[@0x55cada3f8718] <= Core::Stomach[@0x55cada3fbfe0] <= ...
```

but it seems, according to the TeXbook, `\the` accepts a wider variety of arguments than just a register. I still don't have the book but found: 

https://tex.stackexchange.com/a/38676/78008

So, question to Bruce - should I test the counter differently for the moment, or should I take a detour and expand on the `\the` definition? I expect this may have consequences for a wider array of packages, in raw interpretation mode.

**Comment by brucemiller** [comment]
The various "exceptions" are all(?) treated as registers by LaTeXML (some of them should be marked read-only).  I think the problem here is `\value`, which in latex.ltx simply expands to the TeX counter (`\c@ctr`), rather than the value of....

**Comment by dginev** [comment]
Thank you for straightening my understanding up! 

And you're spot on as usual - this rephrasing of `\value` is fully operational in my example:

```perl
DefMacro('\value{}', sub {
    my ($gullet, $arg) = @_;
    T_CS("\\c@".ToString(Expand($_[1]))) });
```

Do you think this is worth the change? The current version is:

```perl
DefMacro('\value{}', sub {
    ExplodeText(CounterValue(ToString(Expand($_[1])))->valueOf); });
```

which I think will always throw an error with `\the`

**Comment by brucemiller** [comment]
Yea, should be fixed; can't imagine that it ever worked in legit latex code!

**Comment by dginev** [comment]
Cool, I will add it to the etoolbox pull request then, commit incoming. Closing here, thanks again for the guidance!
