### ISSUE TITLE
pdgfmath regression

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#991]
The sine plot has funnily enough turned into a flatline in the tikz showcase example:

```tex
\documentclass{article}
\usepackage{tikz}
\begin{document}

\section{Plot of $\sin(x)$}
\begin{tikzpicture}
\draw plot (\x,{sin(\x r)});
\end{tikzpicture}

\end{document}
```

latexml produces 48 errors of the kind:
```
Error:pgfparse:pgfparse Parse of 'sin(-5r)' failed
	at /tmp/test.tex; line 7 col 27
	LTX: '0'
	Left: sin(-5r)
	Next token is T_CS[\let]
	In Core::Definition::Expandable[\lx@pgfm... from pgfmath.code.tex.ltxml line 320
	 <= Core::Gullet[@0x559065c97ab8] <= Core::Stomach[@0x559065c9f738] <= Core::Definition::Primitive[Begin] <= ...
```

which may be easy to fix

**Comment by brucemiller** [comment]
Did that actually work correctly before? Not sure when/where it broke, but it should be good now. Thanks for the report!

**Comment by dginev** [comment]
Just as a note - yes, it worked correctly years ago, when i made the showcase examples. Thanks for reviving it!
