### ISSUE TITLE
hyperref.sty.ltxml throws error for \url containing underscores in \footnote

### ISSUE THREAD

**Issue by siegfriedzoetzsche** [brucemiller/LaTeXML#992]
LaTeXML throws an

    Error:unexpected:_ Script _ can only appear in math mode

for

```tex
    \documentclass{article}
    \usepackage{hyperref}
    \begin{document}
    \footnote{\url{url.with.under_score}}
    \end{document}
```

but does not complain about

```tex
    \documentclass{article}
    \usepackage{hyperref}
    \begin{document}
    \url{url.with.under_score}
    \footnote{\url{url.without.underscore}}
    \end{document}
```

or

```tex
    \documentclass{article}
    \usepackage{url}
    \begin{document}
    \footnote{\url{url.with.under_score}}
    \end{document}
```

Despite the error message, LaTeXML seems to produce correct output.

**Comment by dginev** [comment]
Indeed, it seems that the hyperref binding keeps underscores as is? @brucemiller may know more, the relevant line is:

```perl

my @toks = map { (((($cc = $_->getCatcode) == CC_CS) || ($cc == CC_SUB)) ? $_ : T_OTHER(ToString($_))) } $url->unlist;
```

Thanks for the report and the pointed examples!

**Comment by dginev** [comment]
I have recently seen an increase with these
```
Error:unexpected:_ Script _ can only appear in math mode
```

errors while testing over recent batches of papers from arXiv, so a fix here may be an easy win for improving the statistics there.

**Comment by brucemiller** [comment]
Curious... that's part of it, but url.sty and hyperref.sty differ slightly, and the above doesn't quite capture the difference.  I'll have to create some good tests (and testcases!)

**Comment by brucemiller** [comment]
Boy, once I started digging and comparing url & hyperref, and trying out tests, it got a bit messier. hyperref expands, url doesn't, which carries with it a few peculiarities.  I think I've got it sorted out and added a couple of more thorough test cases.  Thanks for the report!

(and hopefully it'll help arXiv as well :> )
