### ISSUE TITLE
\noindent and list environments: class="ltx_noindent" in wrong <para> in some cases

### ISSUE THREAD

**Issue by siegfriedzoetzsche** [brucemiller/LaTeXML#994]
Sometimes, the `\noindent` information seems to get lost in `\item`s such as

    \item A\par\noindent a

This seems to depend on whether such an `\item` is followed by a blank line or not.
I have seen this behaviour with `{trivlist}`, `{itemize}` and `{enumerate}`.

Examples:
No blank lines after `\item` (two `class="ltx_noindent"` missing one in the wrong `<para>`) :

    \documentclass{article}
    \begin{document}
    \begin{trivlist}
    \item A\par\noindent a
    \item B\par b
    \item C\par\noindent c
    \end{trivlist}
    \end{document}

Converted to:

    [...]
    <para xml:id="p1">
      <itemize>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p1">
            <p>A</p>
          </para>
          <para xml:id="p1.p2">
            <p>a</p>
          </para>
        </item>
        <item>
          <tags>
            <tag/>
          </tags>
          <para class="ltx_noindent" xml:id="p1.p3">
            <p>B</p>
          </para>
          <para xml:id="p1.p4">
            <p>b</p>
          </para>
        </item>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p5">
            <p>C</p>
          </para>
          <para xml:id="p1.p6">
            <p>c</p>
          </para>
        </item>
      </itemize>
    </para>
    [...]

Blank lines between `\item`s but not before `\end{trivlist}` (one `class="ltx_noindent"` missing one in the correct `<para>`) :

    \documentclass{article}
    \begin{document}
    \begin{trivlist}
    \item D\par\noindent d
    
    \item E\par e
    
    \item F\par\noindent f
    \end{trivlist}
    \end{document}

Converted to:

    [...]
    <para xml:id="p1">
      <itemize>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p1">
            <p>D</p>
          </para>
          <para class="ltx_noindent" xml:id="p1.p2">
            <p>d</p>
          </para>
        </item>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p3">
            <p>E</p>
          </para>
          <para xml:id="p1.p4">
            <p>e</p>
          </para>
        </item>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p5">
            <p>F</p>
          </para>
          <para xml:id="p1.p6">
            <p>f</p>
          </para>
        </item>
      </itemize>
    </para>
    [...]

Blank lines after every `\item` (looks good):

    \documentclass{article}
    \begin{document}
    \begin{trivlist}
    \item G\par\noindent g
    
    \item H\par h
    
    \item I\par\noindent i
    
    \end{trivlist}
    \end{document}

Converted to:

    [...]
    <para xml:id="p1">
      <itemize>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p1">
            <p>G</p>
          </para>
          <para class="ltx_noindent" xml:id="p1.p2">
            <p>g</p>
          </para>
        </item>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p3">
            <p>H</p>
          </para>
          <para xml:id="p1.p4">
            <p>h</p>
          </para>
        </item>
        <item>
          <tags>
            <tag/>
          </tags>
          <para xml:id="p1.p5">
            <p>I</p>
          </para>
          <para class="ltx_noindent" xml:id="p1.p6">
            <p>i</p>
          </para>
        </item>
      </itemize>
    </para>
    [...]

**Comment by brucemiller** [comment]
Ah, indeed, there's a bunch of implied `\par` in there. I think I've got it right, now. Thanks for the report.
