### ISSUE TITLE
Nesting - question

### ISSUE THREAD

**Issue by Grief** [brucemiller/LaTeXML#995]
This time I've double-checked but not sure is it an expected behaviour.
Input:
```tex
\documentclass{article}
\usepackage{xcolor}
\begin{document}
    \title{Some title}
    \author{{\color{red}Author1}\newline{}Author2}
    \maketitle
\end{document}
```
Output:
```xml
  <creator role="author">
    <personname><text color="#FF0000">Author1<break/></text>Author2</personname>
  </creator>
```
Shouldn't `<break/>` be outside of `<text></text>` block?

**Comment by Grief** [comment]
So it's an expected behavior, right? A bit strange that break is put inside of the previous block.
`\author{{\color{red}Author1\newline{}}Author2}`
produces exactly the same output.

**Comment by brucemiller** [comment]
Not exactly intentional, but I guess you could call it expected. Inserting character data in various fonts & colors is what usually triggers the opening & closing of `ltx:text', rather than grouping. So, it isn't until "Author2" appears in a different font or color that the `ltx:text` element is closed. (`ltx:break` has no chars).  The trigger could probably be tweaked to generate somewhat more logical xml, but would be messier & more error prone.

Is there a situation where this arrangement is a problem, or is it just a curiosity?

**Comment by Grief** [comment]
@brucemiller my goal is to be able to find separate authors in the document and it seems that the situation when different authors are separated from each other by a simple new line break inside of the single `\authors` block is pretty common for documents we have. I wanted to do some xslt transformation to split the parent block by this break into two blocks, and the specifics of break insertion I have described here made the xslt transformation non-trivial. However, after some inquiry it appears that such hack would break too many working cases and after discussion with my team we decided to left it as is. So please feel free to close this issue or process it somehow else as you like.

**Comment by dginev** [comment]
@Grief you have my full sympathy on the topic of data-mining arbitrary LaTeX, this is in fact a mild case of  an irregularity that makes author segmentation difficult.

I would completely agree that having a clean & pure XSLT rule for segmentation will not work with "latex in the wild" and you may need to resort to a different strategies. I have had success with two different approaches, depending on your circumstances:

1. Change the LaTeX authoring syntax to a "more semantic" one, e.g. use a style where each author is specified by an individual `\author` macro. One example already supported by latexml is the authblk.sty package.

2. In your example, first map the resulting XML down to plain text (replacing breaks with a newline character for instance) and then use a standard named entity recognition toolkit to segment person names out. 

I am quite happy to see more organization undertaking these regularization tasks over the output of LaTeXML, so definitely keep us in touch if any other difficulties arise! Will close this issue for now, as the pragmatic answer seems to be a "worksforme".
